export const LICAO_LA_2 = {
  titulo: "Lição 2 - Porta Fechada e Livros Abertos (3 a 9 de outubro)",
  semana: "2026-W40",
  trimestre: "Livro Aberto",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-10-03",
      titulo: "TEASER",
      conteudo: "A lição desta semana mostra a solene realidade sobre o julgamento. Na verdade, o julgamento está ocorrendo hoje. Os adventistas do sétimo dia se referem a essa fase como o julgamento investigativo, o período que precede a volta de Cristo, quando a vida de todos os que se dizem cristãos está sendo avaliada por Deus. Ellen White escreveu o seguinte a respeito do julgamento: 'Quando os livros de registro são abertos no juízo, a vida de todos aqueles que creram em Jesus passa em revista diante de Deus' (Os Resgatados, p. 246).\n\nEm toda a Bíblia, o tema da responsabilidade de prestar contas continua a aparecer em termos diretos e claros. Até mesmo a imagem do livro aberto transmite a atmosfera da sala de tribunal do julgamento investigativo.\n\nO profeta Malaquias escreveu: 'Foi escrito um livro como memorial na Sua presença acerca dos que temiam o Senhor e honravam o Seu nome' (Ml 3:16). O mundo hoje está relutante em ouvir essa verdade. Mesmo assim, ao redor do mundo, as três mensagens angélicas advertem que devemos temer a Deus e glorificá-Lo, porque chegou a hora do Seu juízo (Ap 14:7).\n\nUma das tarefas desta lição será lembrar que Deus declarará 'inocente' todo aquele que confessar seus pecados e reivindicar o sangue de Cristo. Perdoado. Redimido. Restaurado. Justo aos olhos do Céu. Precisamos entender esta verdade, de que o julgamento está ocorrendo hoje, e devemos tomar a decisão de seguir a Cristo e refletir Seu caráter.",
      versiculoChave: { texto: "Deus exterminou todos os seres vivos que havia na terra: os seres humanos, os animais domésticos, os animais que rastejavam pelo chão e as aves do céu. Todos foram destruídos. Apenas Noé e os que estavam com ele na arca sobreviveram.", referencia: "Gênesis 7:23" },
      perguntas: [
        { id: "d1q1", pergunta: "Como os adventistas do sétimo dia chamam a fase do julgamento que precede a volta de Cristo?", opcoes: ["Juízo final","Julgamento investigativo","Julgamento eterno das nações","Tribunal celestial"], correta: 1, explicacao: "Essa fase é chamada de julgamento investigativo: enquanto Cristo não volta, a vida dos que se dizem cristãos está sendo avaliada por Deus." },
        { id: "d1q2", pergunta: "Segundo Ellen White (Os Resgatados, p. 246), o que acontece 'quando os livros de registro são abertos no juízo'?", opcoes: ["A vida dos que creram passa em revista","Todos os anjos descem à Terra","O tempo de graça se estende por mais um ano","Satanás é imediatamente destruído"], correta: 0, explicacao: "'A vida de todos aqueles que creram em Jesus passa em revista diante de Deus.'" },
        { id: "d1q3", pergunta: "Julgue: segundo o texto, o profeta Malaquias escreveu que foi escrito um livro como memorial acerca dos que temiam o Senhor e honravam o Seu nome.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "Malaquias 3:16 é citado exatamente com esse conteúdo no texto de hoje." },
        { id: "d1q4", pergunta: "Segundo o texto, o que Deus declarará sobre todo aquele que confessar seus pecados e reivindicar o sangue de Cristo?", opcoes: ["'Culpado'", "'Em dúvida'", "'Inocente'", "'Esquecido'"], correta: 2, explicacao: "Deus declarará 'inocente' todo aquele que confessar seus pecados e reivindicar o sangue de Cristo." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-10-04",
      titulo: "ROTEIRO ORIGINAL",
      conteudo: "A história de Noé é bastante conhecida e normalmente pensamos nela como o exemplo de obediência de um homem fiel em atender a uma ordem estranha da parte de Deus. Mas há algo mais nessa história. Jesus fez questão de mencioná-la quando viveu na Terra, mostrando sua importância. Que tal relembrá-la? Leia em sua Bíblia Gênesis 7:6-24 e depois responda às seguintes perguntas:\n\nO que você percebe na narrativa do dilúvio que se relaciona com as pessoas que vivem no tempo do fim?\n\nLeia Mateus 24:39 e observe se a história do dilúvio é parecida com a cena do juízo do tempo do fim. Como essa história é a ilustração perfeita para a cena do juízo final? Como pode ser diferente?\n\nLeia Daniel 7:1-10 e observe especialmente as cenas do juízo nos versos 9 e 10. Qual a ligação entre o julgamento que sobreveio nos tempos de Noé e o julgamento que estamos atualmente vivenciando?\n\nCom base em que os crentes hoje podem estar seguros de que Deus está declarando-os 'inocentes'? Que outras histórias ou eventos se lembram de cenas do juízo final como as citadas nesta lição?",
      versiculoChave: { texto: "Estava vendo isso, até que foram postos tronos, e um Ancião de Dias se assentou; a sua veste era branca como a neve, e o cabelo da sua cabeça, como a limpa lã; o seu trono, chamas de fogo... Assentou-se o tribunal, e abriram-se os livros.", referencia: "Daniel 7:9-10" },
      perguntas: [
        { id: "d2q1", pergunta: "Qual passagem o Roteiro Original de hoje pede para você ler primeiro, sobre a história do dilúvio?", opcoes: ["Gênesis 7:6-24", "Êxodo 14:1-15", "1 Samuel 17:1-10", "Apocalipse 20:1-6"], correta: 0, explicacao: "O texto pede a leitura de Gênesis 7:6-24." },
        { id: "d2q2", tipo: "ordenar", pergunta: "Coloque em ordem as leituras do Roteiro Original de hoje:", itens: ["Gênesis 7:6-24 (o dilúvio)","Mateus 24:39 (palavras de Jesus)","Daniel 7:1-10 (a cena do juízo)"], explicacao: "O roteiro começa pela história do dilúvio (Gn 7), passa pelo que Jesus disse sobre ela (Mt 24:39) e termina na cena do tribunal celestial (Dn 7:9, 10), ligando o juízo dos dias de Noé ao juízo de hoje." },
        { id: "d2q3", pergunta: "Em Daniel 7:1-10, quais versos tratam especificamente das cenas do juízo, segundo o texto?", opcoes: ["Os versos 1 e 2","Os versos 9 e 10","Os versos 11 e 12","Os versos 7 e 8"], correta: 1, explicacao: "O texto destaca 'especialmente as cenas do juízo nos versos 9 e 10' de Daniel 7: tronos, o Ancião de Dias e os livros abertos." },
        { id: "d2q4", pergunta: "Julgue: o texto de hoje afirma que a história do dilúvio não tem nenhuma relação com o julgamento que vivenciamos atualmente.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "É falso: o texto pergunta justamente qual a ligação entre o julgamento dos tempos de Noé e o julgamento atual, pressupondo uma ligação entre eles." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-10-05",
      titulo: "ZOOM",
      conteudo: "Leia o Texto-Chave desta semana, que se encontra em Gênesis 7:23. A história de Noé é perfeita para ilustrar o tema do julgamento, pois os antediluvianos precisavam tomar a decisão de entrar ou não na arca antes de a chuva começar a cair. Essa ideia é muito difundida e tão antiga quanto o mundo, mas é totalmente insensata.\n\nNo momento em que a porta da arca se fechou e o dilúvio veio, cada um tinha decidido como se apresentaria perante Deus - sozinhos em seus próprios méritos, ou como Noé, que 'encontrou graça aos olhos do Senhor'.\n\nSó de pensar em julgamento as pessoas costumam ficar com medo. No entanto, não é esse o sentimento que o evento deveria produzir naqueles que confiam no Senhor.\n\nEm Daniel 7:22, em algumas versões bíblicas, diz que 'o julgamento foi entregue aos santos do Altíssimo'. Essa frase pode ser mal interpretada por pessoas que pensam que os santos são os que estão julgando. Qualquer advogado pode afirmar que quando 'o julgamento foi entregue' para alguém, na verdade quer dizer que o julgamento é passado a favor dos santos. Se você procurar, vai descobrir que a maioria das traduções descreve a cena em que os santos 'em Cristo' são declarados 'inocentes'.\n\nQue o 'julgamento' lhe traga a expectativa de que o tempo para o acerto de contas está chegando e o Justo Juiz colocará cada coisa em seu devido lugar, beneficiando os inocentes.",
      versiculoChave: { texto: "Deus exterminou todos os seres vivos que havia na terra: os seres humanos, os animais domésticos, os animais que rastejavam pelo chão e as aves do céu. Todos foram destruídos. Apenas Noé e os que estavam com ele na arca sobreviveram.", referencia: "Gênesis 7:23" },
      perguntas: [
        { id: "d3q1", pergunta: "Segundo o texto, qual foi a decisão que cada antediluviano teve de tomar antes de a chuva começar a cair?", opcoes: ["Que animais levaria para dentro da arca","Como se apresentaria diante de Deus","Em qual cidade construiria sua nova casa","Quantos dias duraria a viagem"], correta: 1, explicacao: "Cada um decidiu como se apresentaria perante Deus - sozinho em seus próprios méritos, ou como Noé, que 'encontrou graça aos olhos do Senhor'." },
        { id: "d3q2", pergunta: "Segundo o texto, o que Noé encontrou 'aos olhos do Senhor'?", opcoes: ["Ouro","Fama entre o povo","Graça","Longevidade"], correta: 2, explicacao: "Noé é descrito como alguém que 'encontrou graça aos olhos do Senhor'. Ele não se salvou pelos próprios méritos." },
        { id: "d3q3", pergunta: "Julgue: segundo o texto, a frase de Daniel 7:22 sobre 'o julgamento ser entregue aos santos' significa que os santos são quem está julgando.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "O texto explica que essa é uma interpretação equivocada: 'quando o julgamento foi entregue para alguém, na verdade quer dizer que o julgamento é passado a favor dos santos'." },
        { id: "d3q4", pergunta: "Segundo o texto, a maioria das traduções bíblicas descreve os santos 'em Cristo' como sendo declarados o quê?", opcoes: ["'Perdidos'", "'Inocentes'", "'Testemunhas'", "'Anjos'"], correta: 1, explicacao: "A maioria das traduções descreve a cena em que os santos 'em Cristo' são declarados 'inocentes'." }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-10-06",
      titulo: "MAKING OF",
      conteudo: "Daniel viu e descreveu o julgamento. Ele fala de tronos e de um ancião assentado em um trono envolto em fogo. As rodas do trono estavam em chamas. Era uma ocasião solene. Quando o tribunal deu início ao julgamento, os livros foram abertos (Dn 7:9,10).\n\nO Ancião de Dias, mencionado na Bíblia, é Deus Pai. Ele é descrito usando uma veste branca como a neve e tendo o cabelo branco como a lã.\n\nDesde 1844, Jesus participa ativamente do julgamento como nosso grande Sumo Sacerdote, que entrou no lugar santíssimo a fim de realizar Sua última obra sacerdotal em favor do ser humano. Esse é o momento para julgar os que professam ser o povo de Deus. O julgamento dos ímpios é uma obra separada que acontecerá em um momento posterior.\n\nHá também um relatório dos pecados dos homens. 'Ao lado de cada nome nos livros do Céu, estão escritos toda má palavra, todo ato egoísta, todo dever não cumprido, todo pecado secreto. Advertências enviadas pelo Céu ou reprovações negligenciadas, momentos desperdiçados, a influência exercida para o bem ou para o mal, assim como seus resultados de vasto alcance, tudo é historiado pelo anjo relator' (p. 245).\n\nSão os livros de registro no Céu que determinarão os vereditos do julgamento. O livro da vida se encontra entre eles. É nele que estão os nomes de todos que algum dia ingressaram no serviço de Deus. No livro memorial estão registrados todos os bons atos daqueles que temeram o Senhor e honraram Seu nome.\n\nA lei de Deus é o padrão de juízo. Quando o trabalho de Cristo como mediador terminar no Céu, Ele virá para buscar os salvos (Hb 9:28).",
      versiculoChave: { texto: "Assim também Cristo, oferecendo-se uma vez para tirar os pecados de muitos, aparecerá segunda vez, sem pecado, aos que O esperam, para a salvação.", referencia: "Hebreus 9:28" },
      perguntas: [
        { id: "d4q1", pergunta: "Segundo o texto, quem é o 'Ancião de Dias' mencionado na Bíblia?", opcoes: ["Deus Pai","O anjo Gabriel","Jesus","O arcanjo Miguel"], correta: 0, explicacao: "O Ancião de Dias, mencionado na Bíblia, é Deus Pai, descrito com veste branca como a neve e cabelo branco como a lã." },
        { id: "d4q2", pergunta: "Desde que ano Jesus participa ativamente do julgamento como nosso Sumo Sacerdote, segundo o texto?", opcoes: ["Desde o ano 31 d.C.", "Desde 1844", "Desde 1798", "Desde o dilúvio"], correta: 1, explicacao: "Desde 1844, Jesus participa ativamente do julgamento como nosso grande Sumo Sacerdote." },
        { id: "d4q3", pergunta: "Julgue: segundo o texto, o julgamento dos ímpios acontece no mesmo momento do julgamento dos que professam ser povo de Deus.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "É falso: o texto diz que 'o julgamento dos ímpios é uma obra separada que acontecerá em um momento posterior'." },
        { id: "d4q4", tipo: "pares", pergunta: "Ligue cada item do julgamento ao que ele contém ou representa:", pares: [["Livro da vida","Nomes de quem serviu a Deus"],["Livro memorial","Bons atos de quem temeu a Deus"],["Relatório dos pecados","Toda má palavra e ato egoísta"],["Padrão do juízo","A lei de Deus"]], explicacao: "Os livros do Céu determinam os vereditos: o livro da vida guarda os nomes, o memorial guarda os bons atos e o relatório guarda os pecados. A lei de Deus é a régua usada no juízo." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-10-07",
      titulo: "EXTRAS",
      conteudo: "Leia e marque em sua Bíblia os textos adicionais desta semana. Algum deles o surpreendeu? Qual? Por quê?\n\nVocê percebeu que todos os versos mencionam livros? É muito legal saber que a ideia de ter livros surgiu na mente de Deus! Para conhecer um pouco da dinâmica do julgamento investigativo e entender o papel dos livros, leia este texto:\n\n'Quando os livros de registro são abertos no juízo, a vida de todos aqueles que creram em Jesus passa em revista diante de Deus. Começando com aqueles que viveram primeiro na Terra, nosso Advogado [Jesus] apresenta o caso de uma geração após a outra. Cada nome é mencionado; cada caso, investigado. Alguns nomes são aceitos, outros rejeitados. Quando alguém tem pecados que permanecem nos livros de registro sem arrependimento e sem perdão, seu nome é apagado do livro da vida' (Os Resgatados, p. 246).\n\nUau! Que triste! Foi por isso que Deus disse a Moisés que riscaria de Seu livro todo aquele que pecasse contra Ele (Êx 32:33). Mas o plano de Deus não é que essa história termine assim. Ele providenciou uma solução!\n\nTextos adicionais desta semana: Daniel 7:9,10; Malaquias 3:16; Apocalipse 22:10-11.",
      versiculoChave: { texto: "E disse o Senhor a Moisés: Aquele que pecar contra mim, a este riscarei do meu livro.", referencia: "Êxodo 32:33" },
      perguntas: [
        { id: "d5q1", tipo: "digitar", pergunta: "Complete: \"Aquele que pecar contra mim, a este riscarei do meu ___.\" (Êxodo 32:33)", resposta: "livro", explicacao: "Todos os textos desta semana falam de livros. Em Êxodo 32:33, Deus diz que riscaria do Seu livro quem pecasse contra Ele — mas Ele providenciou uma solução: o perdão em Cristo." },
        { id: "d5q2", pergunta: "Segundo a citação de Os Resgatados (p. 246), o que acontece com o nome de alguém que tem pecados sem arrependimento e sem perdão nos livros de registro?", opcoes: ["É destacado em dourado", "É apagado do livro da vida", "É transferido para outro livro", "Permanece inalterado para sempre"], correta: 1, explicacao: "'Quando alguém tem pecados que permanecem nos livros de registro sem arrependimento e sem perdão, seu nome é apagado do livro da vida.'" },
        { id: "d5q3", pergunta: "Julgue: segundo o texto, Deus disse a Moisés que riscaria de Seu livro todo aquele que pecasse contra Ele.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto cita Êxodo 32:33: Deus disse a Moisés que riscaria do Seu livro quem pecasse contra Ele." },
        { id: "d5q4", pergunta: "Segundo o texto, o plano de Deus termina com a história do pecado apagando nomes do livro da vida, sem alternativa?", opcoes: ["Sim, essa é a conclusão final e definitiva", "Não, Deus providenciou uma solução", "Sim, pois não há mais esperança", "Não, pois os livros deixam de existir"], correta: 1, explicacao: "O texto afirma: 'o plano de Deus não é que essa história termine assim. Ele providenciou uma solução!'" }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-10-08",
      titulo: "PANORÂMICA",
      conteudo: "O capítulo 28 do livro Os Resgatados (O Grande Conflito na linguagem de hoje) contém, sem dúvida, um dos conteúdos mais importantes para você compreender o assunto do julgamento investigativo. Como acontece em qualquer tribunal, conhecer o processo faz toda a diferença.\n\nÉ bom lembrar que nunca houve um momento na Terra em que tanta coisa estivesse em jogo. Mas em vez de causar medo e culpa, o julgamento investigativo deve trazer alívio para os inocentes, especialmente porque existe a certeza de que a justiça divina é perfeita. Ela não é 'cega'.\n\nA noção de que esse julgamento está acontecendo agora deve nos levar à reflexão quanto à maneira como vivemos.\n\nHoje é o tempo de enxergar e aceitar a misericórdia divina que está sendo derramada sobre o ser humano. Os livros ainda estão abertos - estrategicamente colocados para serem um lembrete de que o juízo de Deus está acontecendo hoje. Para aqueles que têm confiado em Cristo, isso é algo muito bom!\n\n'Todos os que se arrependeram de verdade e, pela fé, reivindicaram o sangue de Cristo como seu sacrifício expiatório receberão perdão, o qual foi registrado nos livros do Céu. Como se tornaram participantes da justiça de Cristo e seu caráter foi achado em harmonia com a lei de Deus, seus pecados serão apagados, e eles serão considerados dignos da vida eterna' (Os Resgatados, p. 246).",
      versiculoChave: { texto: "Todos os que se arrependeram de verdade e, pela fé, reivindicaram o sangue de Cristo como seu sacrifício expiatório receberão perdão, o qual foi registrado nos livros do Céu. Seus pecados serão apagados, e eles serão considerados dignos da vida eterna.", referencia: "Os Resgatados, p. 246" },
      perguntas: [
        { id: "d6q1", tipo: "multipla", pergunta: "Quais destas afirmações o texto faz sobre o julgamento investigativo? (marque todas)", opcoes: ["Deve trazer alívio aos inocentes","Está acontecendo agora mesmo","Seus livros já foram fechados","Deve causar medo e culpa nos fiéis"], corretas: [0,1], explicacao: "O juízo está acontecendo hoje, e os livros ainda estão abertos. Para quem confia em Cristo, ele não traz medo nem culpa, e sim alívio." },
        { id: "d6q2", pergunta: "Segundo o texto, por que a justiça divina traz alívio aos inocentes?", opcoes: ["Porque ela é imprevisível e mutável","Porque ela é perfeita e não é 'cega'","Porque ela sempre favorece a maioria","Porque ela pode ser apelada depois no Céu"], correta: 1, explicacao: "'Existe a certeza de que a justiça divina é perfeita. Ela não é cega.'" },
        { id: "d6q3", pergunta: "Julgue: segundo o texto, os livros do julgamento já foram fechados e não é mais possível examiná-los.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "É falso: o texto diz que 'os livros ainda estão abertos', como lembrete de que o juízo de Deus está acontecendo hoje." },
        { id: "d6q4", pergunta: "De qual capítulo do livro Os Resgatados vem o conteúdo estudado hoje, segundo o texto?", opcoes: ["Capítulo 27", "Capítulo 28", "Capítulo 30", "Capítulo 16"], correta: 1, explicacao: "O texto se refere ao 'capítulo 28 do livro Os Resgatados'." }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-10-09",
      titulo: "OFF",
      conteudo: "A lição desta semana transmite uma mensagem clara e urgente. Estamos vivendo no período do julgamento de Deus. Por meio da plena confiança no ministério intercessor de Cristo no santuário celestial, se nos arrependermos sinceramente e buscarmos o Seu poder para abandonarmos o pecado, poderemos enfrentar corajosamente cada dia, sabendo que, ao olhar Deus para a nossa lista de ações, encontrará a palavra 'PERDOADO'.\n\nTodo ano no deserto, até a época de Cristo, o Dia da Expiação promovia um senso de reverência e solenidade em Israel. Era o momento de encarar o pecado de frente e abandoná-lo. Não importava se estivesse ocupado, muitos compromissos marcados, coisas para estudar ou fazer. Nada era mais importante do que o arrependimento. Essa é uma palavra que não é muito usada hoje, mas ela significa 'mudar a mente de tal forma que as suas ações também serão transformadas'.\n\nTodos nós precisamos escolher a Deus, confessar os pecados, aceitar o perdão e reconhecer a Cristo como nosso Salvador. É assim que nosso nome entra para o Livro da Vida. É uma questão de escolha mesmo!\n\nAnalise sua vida e observe para onde suas escolhas o têm levado. Há algo que está afastando você dos caminhos do Senhor?\n\n'Muitos que planejam buscar a Deus na décima hora, morrem às 10:30.' - Desconhecido\n\n'Meu maior pensamento é minha responsabilidade para com Deus.' - Daniel Webster",
      versiculoChave: { texto: "Deus exterminou todos os seres vivos que havia na terra: os seres humanos, os animais domésticos, os animais que rastejavam pelo chão e as aves do céu. Todos foram destruídos. Apenas Noé e os que estavam com ele na arca sobreviveram.", referencia: "Gênesis 7:23" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo o texto, qual palavra Deus encontrará ao olhar para nossa lista de ações, se nos arrependermos e buscarmos Seu poder?", opcoes: ["'Esquecido'", "'Perdoado'", "'Condenado'", "'Adiado'"], correta: 1, explicacao: "Deus encontrará a palavra 'PERDOADO' ao olhar para nossa lista de ações." },
        { id: "d7q2", pergunta: "Segundo o texto, o que o Dia da Expiação promovia anualmente em Israel?", opcoes: ["Um senso de reverência e solenidade","Uma grande festa comemorativa","Uma peregrinação ao Egito","Um período de jejum de um mês inteiro"], correta: 0, explicacao: "O Dia da Expiação promovia um senso de reverência e solenidade em Israel: era a hora de encarar o pecado de frente e abandoná-lo." },
        { id: "d7q3", tipo: "relampago", pergunta: "Rodada relâmpago: revise a semana!", itens: [{"texto":"O julgamento investigativo acontece antes da volta de Cristo.","verdadeiro":true},{"texto":"O Ancião de Dias, em Daniel 7, é o anjo Gabriel.","verdadeiro":false},{"texto":"Desde 1844, Jesus atua no julgamento como nosso Sumo Sacerdote.","verdadeiro":true},{"texto":"O padrão do juízo de Deus é a opinião da maioria.","verdadeiro":false},{"texto":"Arrepender-se é mudar a mente de modo que as ações também mudem.","verdadeiro":true}], explicacao: "O Ancião de Dias é Deus Pai, e o padrão do juízo é a lei de Deus. O resto é verdade: o juízo já começou, Jesus intercede por nós desde 1844, e o arrependimento verdadeiro muda o jeito de viver." },
        { id: "d7q4", pergunta: "Segundo a frase citada no texto, atribuída a Daniel Webster, qual é seu maior pensamento?", opcoes: ["Sua carreira profissional e política","Sua responsabilidade para com Deus","Sua família","Sua saúde"], correta: 1, explicacao: "'Meu maior pensamento é minha responsabilidade para com Deus' - Daniel Webster." }
      ]
    }
  ]
};

export const LICAO_LA_3 = {
  titulo: "Lição 3 - A Origem do Mal (10 a 16 de outubro)",
  semana: "2026-W41",
  trimestre: "Livro Aberto",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-10-10",
      titulo: "TEASER",
      conteudo: "Um dos grandes mistérios da história humana tem que ver com a compreensão da origem do mal. Esse é um assunto bastante complexo. Entendemos que Deus concedeu à Sua criação o poder de escolha. Apesar de isso ser verdade, a presença do pecado abre a porta a sofrimento e destruição, e é difícil compreender o valor de tal liberdade. Deus, porém, não desejava governar o Universo de outra forma. Ellen White afirmou que foi necessário que o mal amadurecesse para que pudesse ser eliminado.\n\nÉ esse assunto que descreve a visão geral da história da salvação, e essa mesma história é o ponto principal do propósito mais elevado do Universo: salvar os filhos de Deus e reivindicar Seu caráter diante de todos os seres criados - caídos e não caídos.\n\nO problema humano com o pecado vai muito além de Adão e Eva, atingindo toda criatura que aguarda a resposta de Deus às acusações feitas por Lúcifer. Em Gênesis 3, Satanás levou Adão e Eva a desobedecerem a Deus e a seguirem seu mesmo objetivo. A essência da mentira de Lúcifer lançou dúvidas na forma de pensar das pessoas e dos anjos em relação ao Criador. Por fim, aquilo que as pessoas pensam sobre Deus é o que determinará de que lado ficarão.",
      versiculoChave: { texto: "Houve guerra no Céu. Miguel e Seus anjos lutaram contra o dragão e seus anjos. O dragão perdeu a batalha, e ele e seus anjos foram expulsos do Céu. Esse enorme dragão, a antiga serpente chamada diabo ou Satanás.", referencia: "Apocalipse 12:7-9" },
      perguntas: [
        { id: "d1q1", pergunta: "Segundo o texto, o que Deus concedeu à Sua criação, mesmo sabendo que isso abriria espaço ao sofrimento?", opcoes: ["Riqueza ilimitada", "O poder de escolha", "Imortalidade garantida", "Conhecimento total do futuro"], correta: 1, explicacao: "'Entendemos que Deus concedeu à Sua criação o poder de escolha.'" },
        { id: "d1q2", pergunta: "Segundo o texto, qual é o ponto principal do propósito mais elevado do Universo?", opcoes: ["Salvar os filhos de Deus e reivindicar Seu caráter","Expandir o número de planetas habitados","Multiplicar o conhecimento científico de todos os anjos","Eliminar imediatamente todo ser que pecou"], correta: 0, explicacao: "O ponto principal é 'salvar os filhos de Deus e reivindicar Seu caráter diante de todos os seres criados - caídos e não caídos'." },
        { id: "d1q3", pergunta: "Julgue: segundo o texto, o problema humano com o pecado afeta apenas Adão e Eva, sem atingir outras criaturas do Universo.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "É falso: o texto diz que o problema 'vai muito além de Adão e Eva, atingindo toda criatura que aguarda a resposta de Deus às acusações feitas por Lúcifer'." },
        { id: "d1q4", pergunta: "Segundo o texto, em qual capítulo de Gênesis Satanás levou Adão e Eva a desobedecerem a Deus?", opcoes: ["Gênesis 1", "Gênesis 2", "Gênesis 3", "Gênesis 6"], correta: 2, explicacao: "O texto cita: 'Em Gênesis 3, Satanás levou Adão e Eva a desobedecerem a Deus'." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-10-11",
      titulo: "ROTEIRO ORIGINAL",
      conteudo: "Comparado a outros temas bíblicos, há muito pouco revelado a respeito da origem do pecado e quais elementos nutriram essa doença no coração de Lúcifer. As três passagens que revelam esses fatos são encontradas em Isaías 14 (v. 12-14); Ezequiel 28 (v. 11-17); Apocalipse 12 (v. 7-9). Leia os textos em sua Bíblia e depois responda às seguintes perguntas:\n\nQue verso você considera mais importante na história? Por quê?\n\nQue palavras e frases são usadas para descrever a natureza de Lúcifer antes de sua queda?\n\nO que a Bíblia diz que fez com que Lúcifer se corrompesse?\n\nNa história da queda de Lúcifer, como você explicaria a aparente inatividade de Deus?\n\nQue avisos ou exemplos você pode extrair ao observar a maneira como o pecado começou em Lúcifer? Como o fato de conhecer a história da rebelião de Lúcifer o ajuda a viver de forma diferente?\n\nDe que maneira essa história aprofunda sua visão do amor de Deus e aumenta sua aversão ao pecado?",
      versiculoChave: { texto: "Perfeito eras em todos os teus caminhos, desde o dia em que foste criado, até que se achou iniquidade em ti.", referencia: "Ezequiel 28:15" },
      perguntas: [
        { id: "d2q1", pergunta: "Segundo o texto, quais são as três passagens bíblicas que revelam fatos sobre a origem do pecado no coração de Lúcifer?", opcoes: ["Salmos 23; João 3; Romanos 8","Isaías 14; Ezequiel 28; Apocalipse 12","Gênesis 3; Deuteronômio 30; Mateus 4","Daniel 2; Daniel 7; Daniel 9"], correta: 1, explicacao: "As três passagens são Isaías 14 (v. 12-14), Ezequiel 28 (v. 11-17) e Apocalipse 12 (v. 7-9)." },
        { id: "d2q2", pergunta: "Quais versos de Ezequiel 28 são indicados na leitura de hoje?", opcoes: ["Versos 1-5", "Versos 11-17", "Versos 20-26", "Versos 8-10"], correta: 1, explicacao: "O texto indica 'Ezequiel 28 (v. 11-17)'." },
        { id: "d2q3", pergunta: "Julgue: o texto afirma que há muito pouco revelado na Bíblia sobre a origem do pecado no coração de Lúcifer.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto diz: 'há muito pouco revelado a respeito da origem do pecado e quais elementos nutriram essa doença no coração de Lúcifer'." },
        { id: "d2q4", pergunta: "Segundo as perguntas do dia, sobre o que se pede para refletir a respeito da 'aparente inatividade de Deus'?", opcoes: ["Por que Deus não criou mais anjos leais","Se Deus dorme durante a noite","Como explicá-la na queda de Lúcifer","Se Deus conhece todo o futuro do Universo"], correta: 2, explicacao: "Uma das perguntas é: 'Na história da queda de Lúcifer, como você explicaria a aparente inatividade de Deus?'" }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-10-12",
      titulo: "ZOOM",
      conteudo: "Leia o Texto-Chave desta semana, que se encontra em Apocalipse 12:7-9. Esse texto faz parte de um rápido resumo do grande conflito. Veja o que o Comentário Bíblico Adventista (vol. 7, p. 895-897) diz a respeito dele:\n\n'Embora a visão [de João] se concentre, em primeiro lugar, no ponto central do conflito que ocorreu na cruz, é correto entender que as palavras Houve peleja no Céu também se referem a um período anterior à criação da Terra, quando começou a hostilidade de Lúcifer. Nessa ocasião, ele e os anjos que simpatizaram com sua causa foram expulsos do Céu. Na época, os anjos leais não entendiam por completo todas as questões envolvidas. Entretanto, quando Satanás chegou ao ponto de derramar o sangue de Cristo, tudo ficou exposto de forma plena e eterna diante das hostes celestiais. Desde então, suas atividades foram restringidas.'\n\nVocê sabe quem são os principais personagens mencionados nessa batalha? Acompanhe a explicação:\n\nMiguel: Significa 'quem é como Deus?'. Uma análise das passagens bíblicas sobre Miguel leva à conclusão de que Ele é o próprio Senhor e Salvador Jesus Cristo.\n\nDragão: É autoexplicativo. Refere-se à serpente que enganou Eva. Diabo (difamador) e Satanás (adversário) são os mesmos nomes para ele. 'Quando conseguiu provocar a queda de Adão e Eva, reivindicou a Terra como seu domínio. Todavia, ele não restringiu seus esforços a este planeta, e tentou também os habitantes de outros mundos.'",
      versiculoChave: { texto: "Houve guerra no Céu. Miguel e Seus anjos lutaram contra o dragão e seus anjos. O dragão perdeu a batalha, e ele e seus anjos foram expulsos do Céu. Esse enorme dragão, a antiga serpente chamada diabo ou Satanás.", referencia: "Apocalipse 12:7-9" },
      perguntas: [
        { id: "d3q1", tipo: "pares", pergunta: "Ligue cada nome ao seu significado, segundo o texto:", pares: [["Miguel","Quem é como Deus?"],["Diabo","Difamador"],["Satanás","Adversário"],["Dragão","A serpente que enganou Eva"]], explicacao: "Miguel ('quem é como Deus?') é o próprio Jesus Cristo. Já o dragão, a antiga serpente, recebe os nomes de diabo (difamador) e Satanás (adversário)." },
        { id: "d3q2", pergunta: "Segundo o texto, quem é Miguel, à luz da análise das passagens bíblicas?", opcoes: ["Um simples anjo mensageiro do Céu","O próprio Senhor Jesus Cristo","O arcanjo Gabriel","Um dos 24 anciãos"], correta: 1, explicacao: "'Uma análise das passagens bíblicas sobre Miguel leva à conclusão de que Ele é o próprio Senhor e Salvador Jesus Cristo.'" },
        { id: "d3q3", pergunta: "Julgue: segundo o texto, Satanás restringiu seus esforços de tentação apenas ao planeta Terra.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "É falso: o texto diz que 'ele não restringiu seus esforços a este planeta, e tentou também os habitantes de outros mundos'." },
        { id: "d3q4", pergunta: "Segundo o Comentário Bíblico Adventista citado no texto, quando as atividades de Satanás foram plenamente restringidas?", opcoes: ["Quando derramou o sangue de Cristo","Quando Adão e Eva foram criados no Éden","Quando o dilúvio ocorreu","Quando o templo foi destruído"], correta: 0, explicacao: "'Quando Satanás chegou ao ponto de derramar o sangue de Cristo, tudo ficou exposto de forma plena e eterna... Desde então, suas atividades foram restringidas.'" }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-10-13",
      titulo: "MAKING OF",
      conteudo: "Abaixo de Cristo, Lúcifer tinha sido o ser a quem Deus mais havia honrado no Céu. Antes de sua queda, ele era o chefe dos querubins cobridores. No entanto, isso não foi suficiente para ele. Mesmo sendo criatura, ele quis o lugar que pertencia ao Criador. E ainda culpou a Deus pela discórdia que suas próprias ações causaram no Céu.\n\nO Dicionário de Símbolos apresenta o dragão como uma fusão de serpente e pássaro. Essa definição está de acordo com o que a Bíblia afirma ao atribuir esse símbolo ao diabo. Lembre-se de que Satanás usou a serpente como disfarce para enganar Eva. Antes do pecado, essa serpente era uma das criaturas mais belas e inteligentes. Seu corpo brilhava como ouro polido e ela voava!\n\nQuando a expulsão de Lúcifer do Céu foi anunciada, ele se colocou em aberta rebelião contra a lei de Deus e declarou sua intenção de aboli-la. Ele tem acusado Deus de tirar a liberdade do ser humano e de exercer um governo opressor e tirano.\n\nA morte de Jesus na cruz foi a maior evidência do amor divino pela humanidade e a prova incontestável do verdadeiro caráter de Deus. Cristo não veio apenas para salvar o ser humano. Sua vinda mostrou para todos os mundos que a lei de Deus é imutável e permanente.\n\nTodo o Céu viu a justiça de Deus revelada. Os mundos não caídos enxergaram o verdadeiro caráter de Lúcifer. E no juízo final ficará claro que não existe nenhuma justificativa para o pecado.",
      versiculoChave: { texto: "Tu eras querubim da guarda, ungido, e te estabeleci; estavas no monte santo de Deus; passeavas no meio das pedras afogueadas.", referencia: "Ezequiel 28:14" },
      perguntas: [
        { id: "d4q1", tipo: "ordenar", pergunta: "Coloque em ordem a história de Lúcifer:", itens: ["Era o chefe dos querubins cobridores","Quis o lugar que pertencia ao Criador","Sua expulsão do Céu é anunciada","Rebela-se abertamente contra a lei"], explicacao: "Lúcifer era o ser mais honrado abaixo de Cristo, mas quis o lugar do Criador. Quando sua expulsão foi anunciada, entrou em rebelião aberta e declarou que queria abolir a lei de Deus." },
        { id: "d4q2", pergunta: "Segundo o Dicionário de Símbolos citado no texto, como é apresentado o dragão?", opcoes: ["Como uma fusão de leão, touro e águia","Como uma fusão de serpente e pássaro","Como um monstro marinho","Como um touro alado"], correta: 1, explicacao: "'O Dicionário de Símbolos apresenta o dragão como uma fusão de serpente e pássaro' — e, antes do pecado, a serpente usada por Satanás voava." },
        { id: "d4q3", pergunta: "Julgue: segundo o texto, antes do pecado a serpente usada por Satanás para enganar Eva era uma criatura bela e inteligente, capaz de voar.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto afirma: 'Antes do pecado, essa serpente era uma das criaturas mais belas e inteligentes. Seu corpo brilhava como ouro polido e ela voava!'" },
        { id: "d4q4", pergunta: "Segundo o texto, o que a morte de Jesus na cruz mostrou para todos os mundos?", opcoes: ["Que a lei de Deus é imutável e permanente", "Que Deus mudaria Sua lei se necessário", "Que o pecado deixaria de existir imediatamente", "Que Lúcifer seria perdoado sem condições"], correta: 0, explicacao: "'Sua vinda mostrou para todos os mundos que a lei de Deus é imutável e permanente.'" }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-10-14",
      titulo: "EXTRAS",
      conteudo: "Leia e marque em sua Bíblia os textos adicionais desta semana. Qual texto lhe diz mais sobre a posição que você ocupa hoje na guerra travada entre Cristo e Satanás? Por quê?\n\nEsses versos ajudam a responder algumas das dúvidas sobre o caráter de Deus em um mundo que parece estar repleto de maldade. É intenção de Satanás fazer com que as pessoas acreditem que Deus é o culpado por este mundo estar desse jeito.\n\nPara os mundos não caídos, já ficou claro o verdadeiro caráter de Lúcifer - aquele que um dia foi um anjo exaltado no Céu. Quando Jesus, o Filho de Deus, veio como um de nós para salvar o ser humano, todos os argumentos e acusações de Satanás contra o Criador caíram por terra.\n\nVocê sabe como se cumpriu a profecia de Gênesis 3:15? Ao longo de toda a vida de Jesus na Terra, Satanás procurou causar-Lhe o maior sofrimento possível, levando as pessoas até mesmo a crucificarem o Messias. Toda a dor e aflição foram como o ferimento no calcanhar de Jesus. No entanto, na cruz, o Salvador esmagou a cabeça da serpente. Ali o caráter e as intenções do inimigo foram plenamente revelados. A derrota de Satanás se tornou um fato. Agradeça diariamente a Jesus. A vitória Dele também é a sua vitória!\n\nTextos adicionais desta semana: Gênesis 3:15; Romanos 5:18,19; Hebreus 2:14,15.",
      versiculoChave: { texto: "Porei inimizade entre ti e a mulher, entre a tua semente e a sua semente; esta te ferirá a cabeça, e tu lhe ferirás o calcanhar.", referencia: "Gênesis 3:15" },
      perguntas: [
        { id: "d5q1", pergunta: "Segundo o texto, qual é a intenção de Satanás em um mundo que parece repleto de maldade?", opcoes: ["Provar que os anjos não existem","Fazer as pessoas culparem Deus pelo mal do mundo","Convencer as pessoas de que o pecado nunca existiu","Fazer as pessoas amarem mais a Deus"], correta: 1, explicacao: "'É intenção de Satanás fazer com que as pessoas acreditem que Deus é o culpado por este mundo estar desse jeito.'" },
        { id: "d5q2", tipo: "digitar", pergunta: "Complete: \"Esta te ferirá a ___, e tu lhe ferirás o calcanhar.\" (Gênesis 3:15)", resposta: "cabeça", aceitas: ["cabeca"], explicacao: "Satanás feriu o 'calcanhar' de Jesus com todo o sofrimento que Lhe causou, mas na cruz o Salvador esmagou a cabeça da serpente. A derrota de Satanás virou um fato." },
        { id: "d5q3", pergunta: "Julgue: segundo o texto, na cruz o caráter e as intenções de Satanás foram plenamente revelados, tornando sua derrota um fato.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto afirma que 'ali o caráter e as intenções do inimigo foram plenamente revelados. A derrota de Satanás se tornou um fato.'" },
        { id: "d5q4", pergunta: "Segundo o texto, o que já ficou claro para os mundos não caídos a respeito de Lúcifer?", opcoes: ["Que ele nunca existiu","O seu verdadeiro caráter","Que ele retornaria ao Céu em breve","Que ele era mais poderoso que Deus"], correta: 1, explicacao: "'Para os mundos não caídos, já ficou claro o verdadeiro caráter de Lúcifer.'" }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-10-15",
      titulo: "PANORÂMICA",
      conteudo: "Os capítulos 29 e 30 do livro Os Resgatados (O Grande Conflito na linguagem de hoje) apresentam a melhor explicação para Deus ter permitido a entrada do pecado em nosso mundo. Você precisa ler para não ter nenhuma dúvida sobre esse assunto e também para saber responder às pessoas que não entendem o que estava em questão.\n\nEssa batalha cósmica está chegando ao fim. Em breve tudo isso vai ser passado. Alegre-se com a perspectiva de um futuro incrível: 'O mal nunca mais vai se levantar novamente. A lei de Deus será honrada como a lei da liberdade. A criação testada e provada nunca mais vai se afastar da lealdade Àquele que demonstrou que Seu caráter consiste de amor inescrutável e sabedoria infinita' (Os Resgatados, p. 257).\n\n'Se o Senhor apagasse a existência do inimigo de imediato, eles passariam a servi-Lo por medo, não por amor. Deus não destruiria por completo a influência do enganador, nem eliminaria o espírito de rebelião. Pelo bem do Universo ao longo das eras eternas, Satanás precisaria desenvolver seus princípios de maneira completa. Então todos os seres criados seriam capazes de enxergar a realidade por trás de suas acusações contra o governo divino' (Os Resgatados, p. 254, 255).",
      versiculoChave: { texto: "Se o Senhor apagasse a existência do inimigo de imediato, eles passariam a servi-Lo por medo, não por amor. Pelo bem do Universo ao longo das eras eternas, Satanás precisaria desenvolver seus princípios de maneira completa, para que todos os seres criados fossem capazes de enxergar a realidade por trás de suas acusações contra o governo divino.", referencia: "Os Resgatados, p. 254, 255" },
      perguntas: [
        { id: "d6q1", pergunta: "Segundo o texto, quais capítulos do livro Os Resgatados apresentam a melhor explicação para Deus ter permitido a entrada do pecado no mundo?", opcoes: ["Capítulos 29 e 30", "Capítulos 1 e 2", "Capítulos 40 e 41", "Capítulos 15 e 16"], correta: 0, explicacao: "'Os capítulos 29 e 30 do livro Os Resgatados... apresentam a melhor explicação.'" },
        { id: "d6q2", tipo: "multipla", pergunta: "Quais destas coisas a citação de Os Resgatados (p. 257) promete para o futuro? (marque todas)", opcoes: ["O mal nunca mais vai se levantar","A lei de Deus será a lei da liberdade","Satanás terá uma nova chance no Céu","A lei de Deus será trocada por outra"], corretas: [0,1], explicacao: "'O mal nunca mais vai se levantar novamente. A lei de Deus será honrada como a lei da liberdade.' A criação, depois de provada, nunca mais vai se afastar de Deus." },
        { id: "d6q3", pergunta: "Julgue: segundo o texto, se Deus apagasse a existência de Satanás de imediato, os seres criados passariam a servi-Lo por amor, não por medo.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "É falso: o texto diz o contrário - 'eles passariam a servi-Lo por medo, não por amor'." },
        { id: "d6q4", pergunta: "Segundo o texto, por que Satanás precisa desenvolver seus princípios de maneira completa, antes de ser destruído?", opcoes: ["Para que todos enxerguem a verdade sobre suas acusações","Para que ele tenha mais tempo de se arrepender e voltar ao Céu","Para que os anjos caídos aumentem de número","Para que a Terra se torne mais habitável"], correta: 0, explicacao: "'Pelo bem do Universo... todos os seres criados seriam capazes de enxergar a realidade por trás de suas acusações contra o governo divino.'" }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-10-16",
      titulo: "OFF",
      conteudo: "O fato de o pecado ter surgido já é difícil de compreender, mas o fato de Deus ter permitido que o mal reinasse tem levado muitos a questionarem o caráter de Deus. Deus não nos condena por termos perguntas a fazer, mas, ao surgirem dúvidas a respeito do que Deus está fazendo para salvar a humanidade e reivindicar o Seu nome, devemos estudar o assunto com humildade e oração.\n\nAo pressionarmos Deus para explicar-Se em vez de nos submetermos a Ele, impedimos a atuação da fé em nossa vida e nos equivocamos quanto à nossa participação no plano da salvação. Lúcifer caiu porque escolheu o orgulho em vez de devoção - egoísmo em vez de adoração. O pecado entrou no nosso mundo por meio da desobediência de Adão e Eva e, por isso, temos a tendência natural de sermos egoístas sem nem sempre nos percebermos. Quanto mais pensamos nisso, porém, mais compreendemos que há uma saída.\n\nA história da queda de Lúcifer fala de um Deus que anseia que O sirvamos por amor e não por medo - razão pela qual Ele não exterminou de imediato o anjo caído ou os pecadores.\n\nNo fim, o próprio Satanás reconhecerá a soberania de Deus e admitirá suas motivações egoístas. O mal será destruído para sempre e nunca mais voltará a existir. Amém!\n\n'A essência do pecado é revolta contra Deus, recusa em sujeitar-se a Ele e inimizade contra Deus. O transgressor quer ser seu próprio deus - a rebelião completa o ciclo.' - John M. Fowler\n\n'Em nenhuma outra parte da Bíblia o Céu e a Terra se acham tão próximos um do outro como no Apocalipse.' - William G. Johnsson",
      versiculoChave: { texto: "Houve guerra no Céu. Miguel e Seus anjos lutaram contra o dragão e seus anjos. O dragão perdeu a batalha, e ele e seus anjos foram expulsos do Céu. Esse enorme dragão, a antiga serpente chamada diabo ou Satanás.", referencia: "Apocalipse 12:7-9" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo o texto, por que Lúcifer caiu?", opcoes: ["Porque escolheu o orgulho em vez de devoção","Porque foi enganado por outro anjo mais poderoso","Porque Deus o expulsou sem motivo","Porque ele amava demais a humanidade"], correta: 0, explicacao: "'Lúcifer caiu porque escolheu o orgulho em vez de devoção - egoísmo em vez de adoração.'" },
        { id: "d7q2", pergunta: "Segundo a citação de John M. Fowler, o que é a 'essência do pecado'?", opcoes: ["Ignorância sobre a lei de Deus","Revolta contra Deus e recusa em sujeitar-se a Ele","Falta de conhecimento bíblico","Uma simples fraqueza humana, passageira e sem culpa"], correta: 1, explicacao: "'A essência do pecado é revolta contra Deus, recusa em sujeitar-se a Ele e inimizade contra Deus.' - John M. Fowler" },
        { id: "d7q3", tipo: "relampago", pergunta: "Rodada relâmpago: revise a semana!", itens: [{"texto":"Deus concedeu à Sua criação o poder de escolha.","verdadeiro":true},{"texto":"O nome Miguel significa 'príncipe das trevas'.","verdadeiro":false},{"texto":"Deus não destruiu Satanás de imediato para que O sirvamos por amor.","verdadeiro":true},{"texto":"Segundo Gênesis 3:15, a serpente feriria a cabeça do Salvador.","verdadeiro":false},{"texto":"Lúcifer caiu porque escolheu o orgulho em vez da devoção.","verdadeiro":true}], explicacao: "Miguel significa 'quem é como Deus?'. E em Gênesis 3:15 a serpente fere só o calcanhar; é o Salvador quem esmaga a cabeça dela, na cruz." },
        { id: "d7q4", pergunta: "Segundo William G. Johnsson, citado no texto, em qual livro bíblico o Céu e a Terra se acham mais próximos um do outro?", opcoes: ["Gênesis","Salmos","Apocalipse","Deuteronômio"], correta: 2, explicacao: "'Em nenhuma outra parte da Bíblia o Céu e a Terra se acham tão próximos um do outro como no Apocalipse.' - William G. Johnsson" }
      ]
    }
  ]
};

export const LICAO_LA_4 = {
  titulo: "Lição 4 - Anjos e Demônios (17 a 23 de outubro)",
  semana: "2026-W42",
  trimestre: "Livro Aberto",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-10-17",
      titulo: "TEASER",
      conteudo: "A guerra espiritual entre Cristo e Satanás não é um combate isolado entre dois poderes iguais no mundo celestial. Em primeiro lugar, Deus é supremo e todo-poderoso. Satanás já foi sentenciado e seu fim é inevitável. Em segundo, os seres angelicais, criados por Deus, estão ocupados executando as tarefas concernentes ao reino de Deus, e os anjos caídos, que se uniram a Lúcifer, também estão trabalhando desesperadamente para a ruína humana à medida que sua própria sentença se aproxima de seu cumprimento.\n\nObviamente, a humanidade caída sente que algo está acontecendo além daquilo que os olhos podem ver. Os cristãos sabem, por meio da Bíblia, que Deus já declarou vitória sobre o pecado, mas que Satanás ainda está trabalhando para enganar e minar o plano da salvação, procurando 'devorar', 'roubar' e 'matar' aqueles que escolhem reivindicar seu lugar como herdeiros do reino de Deus.\n\nA batalha pela conquista do coração do homem é claramente descrita na história do endemoninhado. A vitória de Jesus é uma realidade na vida de todo aquele que O aceita como Salvador e Libertador.",
      versiculoChave: { texto: "Chegaram até onde Jesus estava e viram o homem que tinha sido possuído pela legião de demônios. Estava sentado ali, vestido e em perfeito juízo, e todos tiveram medo.", referencia: "Marcos 5:15" },
      perguntas: [
        { id: "d1q1", pergunta: "Segundo o texto, qual é o primeiro motivo pelo qual a guerra espiritual entre Cristo e Satanás não é um combate entre dois poderes iguais?", opcoes: ["Deus é supremo e todo-poderoso", "Satanás tem mais anjos do que Deus", "Os humanos são mais fortes que os anjos", "O combate ainda não começou"], correta: 0, explicacao: "'Em primeiro lugar, Deus é supremo e todo-poderoso.'" },
        { id: "d1q2", pergunta: "Segundo o texto, o que os anjos caídos estão fazendo à medida que sua sentença se aproxima do cumprimento?", opcoes: ["Trabalhando pela ruína humana","Pedindo perdão a Deus","Ajudando os seres humanos a se converterem","Descansando, pois já perderam a guerra"], correta: 0, explicacao: "'Os anjos caídos... estão trabalhando desesperadamente para a ruína humana à medida que sua própria sentença se aproxima de seu cumprimento.'" },
        { id: "d1q3", pergunta: "Julgue: segundo o texto, Satanás já foi sentenciado e seu fim é inevitável.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto afirma claramente: 'Satanás já foi sentenciado e seu fim é inevitável.'" },
        { id: "d1q4", pergunta: "Segundo o texto, o que Satanás procura fazer com aqueles que escolhem reivindicar seu lugar como herdeiros do reino de Deus?", opcoes: ["'Devorar', 'roubar' e 'matar'","Recompensá-los com poder e riqueza","Ignorá-los completamente","Transformá-los em anjos"], correta: 0, explicacao: "Satanás 'procura devorar, roubar e matar aqueles que escolhem reivindicar seu lugar como herdeiros do reino de Deus'." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-10-18",
      titulo: "ROTEIRO ORIGINAL",
      conteudo: "A Bíblia apresenta muitas histórias que comprovam a atuação tanto dos anjos de Deus como dos espíritos maus na vida dos seres humanos. A passagem bíblica desta semana, que se encontra em Marcos 5:1-19, revela como Jesus lidou com a situação. Depois de ler em sua Bíblia, responda às perguntas a seguir:\n\nEm sua opinião, por que essa história foi registrada nos evangelhos? Com qual objetivo? Qual a importância da mensagem transmitida por essa história?\n\nDe que forma foi descrito o indivíduo endemoninhado?\n\nDe acordo com o relato bíblico, como os habitantes do vilarejo - e até mesmo os discípulos - se relacionavam com o homem conhecido por ser 'possuído de espírito imundo'?\n\nPor que será que as pessoas reagiram daquela forma? O que as motivou a pedir que Jesus fosse embora?\n\nPor que será que o homem libertado do poder dos demônios não queria se separar de Jesus? Por que será que Jesus ordenou-lhe que permanecesse na região e contasse aos outros o que Deus havia feito em sua vida? De que maneira essa missão ajudaria o homem liberto dos espíritos maus?",
      versiculoChave: { texto: "Jesus, porém, não lho permitiu, mas disse-lhe: Vai para tua casa, para os teus, e anuncia-lhes quantas coisas o Senhor te fez, e como teve misericórdia de ti.", referencia: "Marcos 5:19" },
      perguntas: [
        { id: "d2q1", pergunta: "Em qual passagem bíblica se encontra a história do endemoninhado estudada nesta semana?", opcoes: ["Marcos 5:1-19", "Lucas 15:1-10", "João 11:1-44", "Mateus 8:1-13"], correta: 0, explicacao: "'A passagem bíblica desta semana... se encontra em Marcos 5:1-19.'" },
        { id: "d2q2", pergunta: "Segundo o texto, como os habitantes do vilarejo e até mesmo os discípulos se relacionavam com o endemoninhado?", opcoes: ["Como alguém possuído de espírito imundo","Como um líder religioso muito respeitado","Como um estrangeiro rico","Como um profeta enviado por Deus"], correta: 0, explicacao: "Ele era conhecido 'por ser possuído de espírito imundo' — por isso todos o evitavam." },
        { id: "d2q3", pergunta: "Julgue: segundo o texto, o homem libertado dos demônios pediu para ir embora com Jesus, mas Jesus o instruiu a ficar e contar aos outros o que Deus havia feito por ele.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto pergunta 'por que será que Jesus ordenou-lhe que permanecesse na região e contasse aos outros o que Deus havia feito em sua vida', confirmando essa instrução." },
        { id: "d2q4", tipo: "ordenar", pergunta: "Coloque em ordem a história de Marcos 5:", itens: ["Jesus liberta o endemoninhado","O povo pede que Jesus vá embora","O homem pede para ficar com Jesus","Jesus o manda contar aos seus"], explicacao: "Depois da libertação, o povo pediu que Jesus saísse da região. O homem queria ir com Ele, mas Jesus o enviou para casa como missionário: 'anuncia-lhes quantas coisas o Senhor te fez' (Mc 5:19)." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-10-19",
      titulo: "ZOOM",
      conteudo: "Leia o Texto-Chave desta semana, que se encontra em Marcos 5:15. A experiência em Gerasa aconteceu logo após Jesus ter acalmado a tempestade. Quando viram a terrível cena com o endemoninhado, os discípulos fugiram, com medo. No entanto, Jesus permaneceu ali. Com autoridade, ordenou que os demônios deixassem o pobre homem.\n\nQuem eram aqueles demônios, que se identificaram como 'Legião'? Eram os anjos caídos, aqueles que ficaram do lado de Lúcifer na batalha no Céu. As pessoas podiam não ter reconhecido Jesus como o Filho de Deus, mas aqueles seres sobrenaturais sabiam bem quem era Ele. Eles O chamaram de 'Jesus, Filho do Deus Altíssimo', e não puderam resistir à Sua ordem.\n\nQuando os discípulos se aproximaram, encontraram outro quadro. O homem agora estava calmo, tranquilo. É assim que ficam as pessoas que encontram Jesus. Os habitantes do lugar, no entanto, não quiseram que Jesus permanecesse ali: viram Aquele que havia derrotado o príncipe das trevas diante dos seus olhos como um intruso, e enxotaram de suas portas o Dom do Céu (O Libertador, p. 197).\n\nMuitas pessoas hoje têm agido assim. Mas, para aqueles que aceitam o Senhor e a luz que Ele oferece, a boa notícia é que ainda podem, por meio de Cristo, ser transformadas em mensageiros de justiça e enviadas para contar que 'coisas grandiosas fez o Senhor por nós' (Sl 126:3) (p. 198).",
      versiculoChave: { texto: "Chegaram até onde Jesus estava e viram o homem que tinha sido possuído pela legião de demônios. Estava sentado ali, vestido e em perfeito juízo, e todos tiveram medo.", referencia: "Marcos 5:15" },
      perguntas: [
        { id: "d3q1", pergunta: "Segundo o texto, quem eram os demônios que se identificaram como 'Legião'?", opcoes: ["Anjos caídos, do lado de Lúcifer","Espíritos de pessoas mortas","Anjos ainda leais a Deus, mas confusos","Demônios criados especialmente para aquele homem"], correta: 0, explicacao: "Eram 'os anjos caídos, aqueles que ficaram do lado de Lúcifer na batalha no Céu'." },
        { id: "d3q2", tipo: "digitar", pergunta: "Complete: \"Estava sentado ali, vestido e em perfeito ___, e todos tiveram medo.\" (Marcos 5:15)", resposta: "juízo", aceitas: ["juizo"], explicacao: "O homem que antes vivia dominado pela Legião agora estava calmo, vestido e em perfeito juízo. É assim que ficam as pessoas que encontram Jesus." },
        { id: "d3q3", pergunta: "Julgue: segundo o texto, os discípulos reconheceram Jesus como Filho de Deus antes mesmo dos demônios reconhecerem.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "É falso: o texto diz que 'as pessoas podiam não ter reconhecido Jesus como o Filho de Deus, mas aqueles seres sobrenaturais sabiam bem quem era Ele'." },
        { id: "d3q4", pergunta: "Segundo o texto, como os habitantes do lugar trataram Jesus após a libertação do endemoninhado, de acordo com O Libertador (p. 197)?", opcoes: ["Como um intruso, e o enxotaram de suas portas", "Como um herói, oferecendo-lhe uma festa", "Com total indiferença, sem qualquer reação", "Pedindo que Ele ficasse para sempre na região"], correta: 0, explicacao: "Trataram 'Aquele que havia derrotado o príncipe das trevas... como um intruso, e enxotaram de suas portas o Dom do Céu' (O Libertador, p. 197)." }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-10-20",
      titulo: "MAKING OF",
      conteudo: "Os anjos foram criados antes dos seres humanos e são superiores a eles. Deus os comissionou para 'servir aqueles que hão de herdar a salvação' (Hb 1:14) - ou seja, nós. Eles são identificados como ágeis mensageiros de Deus (Ez 1:14).\n\nDeus envia anjos com força superior para proteger Seus filhos. 'Os maus não podem romper a guarda que Deus posicionou em torno de Seu povo' (p. 264).\n\n'Originalmente, os espíritos maus foram criados sem pecado. Eram iguais em natureza, poder e glória aos seres santos. [...] Agora são caídos por causa do pecado e se uniram não somente para desonrar ao Senhor, mas para destruir a humanidade. Unidos a Satanás em rebelião, cooperam com ele na guerra contra a autoridade divina' (p. 262).\n\nSatanás tem muito interesse que as pessoas não acreditem em sua existência ou que o retratem como alguém ridículo ou desprezível. 'Agrada-se em ser retratado de forma cômica, disforme, metade animal e metade humano. Fica alegre ao ouvir seu nome ser usado em piadas e zombaria' (p. 264). Assim, quando ele aparece em sua verdadeira forma, é confundido com anjo de luz e engana a todos os que não seguem a Cristo.\n\nNa época em que Jesus veio à Terra, a Palestina era a única região que não havia cedido totalmente ao tentador. Por isso, os anjos maus concentraram suas forças ali. Eles entenderam que, se a missão de Cristo tivesse sucesso, seu domínio logo terminaria.\n\nCada seguidor de Cristo tem um anjo da guarda, designado pelo próprio Deus.",
      versiculoChave: { texto: "Não são todos eles espíritos ministradores, enviados para servir a favor daqueles que hão de herdar a salvação?", referencia: "Hebreus 1:14" },
      perguntas: [
        { id: "d4q1", tipo: "pares", pergunta: "Ligue cada ser ao que o texto diz sobre ele:", pares: [["Anjos de Deus","Servem os herdeiros da salvação"],["Espíritos maus","Lutam contra a autoridade divina"],["Anjo da guarda","Acompanha cada seguidor de Cristo"]], explicacao: "Os anjos de Deus foram enviados para nos servir (Hb 1:14), e cada seguidor de Cristo tem um anjo da guarda. Já os espíritos maus cooperam com Satanás na guerra contra Deus." },
        { id: "d4q2", pergunta: "Segundo o texto, o que os espíritos maus eram originalmente, antes de sua queda?", opcoes: ["Criados já corrompidos e inferiores aos humanos","Simples ilusões da mente humana","Sem pecado e iguais aos seres santos","Criaturas criadas depois da queda de Adão"], correta: 2, explicacao: "'Originalmente, os espíritos maus foram criados sem pecado. Eram iguais em natureza, poder e glória aos seres santos.'" },
        { id: "d4q3", pergunta: "Julgue: segundo o texto, Satanás gosta de ser retratado de forma cômica, disforme, metade animal e metade humano.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto confirma: 'Agrada-se em ser retratado de forma cômica, disforme, metade animal e metade humano.'" },
        { id: "d4q4", pergunta: "Segundo o texto, por que os anjos maus concentraram suas forças na Palestina na época de Jesus?", opcoes: ["Porque era a região mais populosa do mundo antigo","Porque só ela não cedera totalmente ao tentador","Porque ali ficava a capital do Império Romano","Porque os anjos bons não atuavam ali"], correta: 1, explicacao: "'A Palestina era a única região que não havia cedido totalmente ao tentador. Por isso, os anjos maus concentraram suas forças ali.'" }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-10-21",
      titulo: "EXTRAS",
      conteudo: "Leia e marque em sua Bíblia os textos adicionais desta semana. Qual deles chamou mais sua atenção? Por quê?\n\nVocê conhecia a história contada por Jesus sobre a volta do espírito imundo (Mt 12:43-45)? Ela é bastante significativa. Preste atenção nos detalhes, porque há uma ligação com a estratégia de Satanás para tomar conta da vida de alguém.\n\nO Comentário Bíblico Adventista (vol. 5, p. 418) dá a seguinte explicação ao texto: 'O infeliz representado pela casa não se colocou do lado de Deus de forma positiva. Suas intenções eram boas. Não imaginava que o espírito imundo voltaria e, portanto, falhou em entregar a casa ao controle de Cristo. [...] Nossa única segurança está na entrega total do coração a Cristo, a fim de que Ele possa entrar e viver vida perfeita em nós. Essa parábola é uma advertência solene contra simples melhorias; não é suficiente evitar o mal, devemos ativamente buscar as coisas lá do alto.'\n\nTextos adicionais desta semana: Mateus 12:43-45; Romanos 7:21-23; Tiago 1:13,14.",
      versiculoChave: { texto: "Então vai, e leva consigo outros sete espíritos piores do que ele e, entrando, habitam ali; e o último estado desse homem torna-se pior do que o primeiro. Assim há de acontecer também a esta geração perversa.", referencia: "Mateus 12:45" },
      perguntas: [
        { id: "d5q1", pergunta: "Qual parábola contada por Jesus é destacada no texto de hoje?", opcoes: ["A parábola da volta do espírito imundo","A parábola do filho pródigo e seu irmão","A parábola do semeador","A parábola das dez virgens"], correta: 0, explicacao: "O texto destaca 'a história contada por Jesus sobre a volta do espírito imundo (Mt 12:43-45)'." },
        { id: "d5q2", pergunta: "Segundo o Comentário Bíblico Adventista citado, onde está nossa única segurança contra o retorno do espírito imundo?", opcoes: ["Na entrega total do coração a Cristo", "Em evitar apenas simples melhorias externas", "Em nunca mais pensar no assunto", "Em confiar somente em rituais religiosos"], correta: 0, explicacao: "'Nossa única segurança está na entrega total do coração a Cristo, a fim de que Ele possa entrar e viver vida perfeita em nós.'" },
        { id: "d5q3", pergunta: "Julgue: segundo o comentário citado, basta evitar o mal, sem necessidade de buscar ativamente 'as coisas lá do alto'.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "É falso: o texto diz que 'não é suficiente evitar o mal, devemos ativamente buscar as coisas lá do alto'." },
        { id: "d5q4", pergunta: "Segundo o texto, por que o homem representado pela 'casa' na parábola falhou?", opcoes: ["Porque odiava a Deus abertamente","Porque não entregou a casa ao controle de Cristo","Porque nunca teve boas intenções","Porque construiu a casa em terreno arenoso e instável"], correta: 1, explicacao: "'Não imaginava que o espírito imundo voltaria e, portanto, falhou em entregar a casa ao controle de Cristo.'" }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-10-22",
      titulo: "PANORÂMICA",
      conteudo: "A leitura complementar desta semana está nos capítulos 31 e 32 do livro Os Resgatados (O Grande Conflito na linguagem de hoje). São textos incríveis, que explicam as estratégias que o inimigo tem usado para desviar as pessoas dos caminhos de Deus. Especialmente no capítulo 32 é apresentada a fórmula para derrotar Satanás. Não deixe de ler. Você vai ficar surpreso!\n\nSó para ter uma ideia do conteúdo, reflita sobre esse importante trecho: 'O grande conflito entre Cristo e Satanás terminará em breve, e o maligno está aumentando seus esforços para derrotar a obra de Jesus em prol da humanidade. Seu objetivo é manter as pessoas em trevas e rebelião até que a ministração do Salvador no santuário termine. Quando as pessoas na igreja estão indiferentes, Satanás não se preocupa. Entretanto, quando os corações indagam: O que devo fazer para ser salvo?, ele aparece para nivelar seu poder contra Cristo e neutralizar a influência do Espírito Santo' (p. 265).\n\nVocê entendeu o que está em jogo? Há uma obra em andamento no Céu exatamente agora e não podemos nos distrair. Precisamos estar atentos e preparados. Está muito perto de Jesus voltar!\n\n'Cristo e Seus apóstolos não realizaram milagres? O mesmo Salvador está tão disposto a ouvir a oração de fé hoje como quando andava visivelmente na Terra. O natural coopera com o sobrenatural. Faz parte do plano de Deus nos conceder, em resposta à oração de fé, aquilo que não nos daria se não pedíssemos com fervor' (Os Resgatados, p. 269).",
      versiculoChave: { texto: "Cristo e Seus apóstolos não realizaram milagres? O mesmo Salvador está tão disposto a ouvir a oração de fé hoje como quando andava visivelmente na Terra. Faz parte do plano de Deus nos conceder, em resposta à oração de fé, aquilo que não nos daria se não pedíssemos com fervor.", referencia: "Os Resgatados, p. 269" },
      perguntas: [
        { id: "d6q1", pergunta: "Segundo o texto, em quais capítulos de Os Resgatados está a leitura complementar desta semana?", opcoes: ["Capítulos 31 e 32", "Capítulos 1 e 2", "Capítulos 20 e 21", "Capítulos 40 e 41"], correta: 0, explicacao: "'A leitura complementar desta semana está nos capítulos 31 e 32 do livro Os Resgatados.'" },
        { id: "d6q2", tipo: "multipla", pergunta: "Quais destas coisas o texto diz sobre Satanás? (marque todas)", opcoes: ["Aumenta seus esforços contra a obra de Jesus","Quer manter as pessoas em trevas e rebelião","Quer que a ministração no santuário dure mais","Já desistiu de enganar a humanidade"], corretas: [0,1], explicacao: "O conflito está terminando, e por isso o maligno aumenta seus esforços: quer manter as pessoas em trevas até que a ministração de Jesus no santuário termine." },
        { id: "d6q3", pergunta: "Julgue: segundo o texto, quando os corações indagam 'o que devo fazer para ser salvo?', Satanás fica indiferente e não se preocupa.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "É falso: o texto diz que Satanás não se preocupa quando as pessoas estão indiferentes, mas quando os corações fazem essa pergunta, 'ele aparece para nivelar seu poder contra Cristo e neutralizar a influência do Espírito Santo'." },
        { id: "d6q4", pergunta: "Segundo a citação de Os Resgatados (p. 269), o que faz parte do plano de Deus em resposta à oração de fé?", opcoes: ["Ignorar pedidos feitos com muita frequência e insistência","Dar o que não daria se não pedíssemos com fervor","Substituir os anjos por respostas diretas","Adiar toda resposta até o juízo final"], correta: 1, explicacao: "'Faz parte do plano de Deus nos conceder, em resposta à oração de fé, aquilo que não nos daria se não pedíssemos com fervor.'" }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-10-23",
      titulo: "OFF",
      conteudo: "Estudos indicam que o veneno das serpentes é constituído basicamente de proteína. Apesar de todos termos a necessidade diária de uma fonte de proteína, não quer dizer que o veneno da serpente seja uma fonte apropriada. Ninguém em sã consciência ingeriria veneno de serpente para obter uma dieta balanceada de proteína.\n\nNo entanto, muitos têm se tornado base de apoio para o inimigo de Deus ao pensar que o mundo invisível não é tão perigoso ou que são espertos o bastante para vencer Satanás. O inimigo trabalha arduamente para iludir, enganar e seduzir as pessoas a fim de escravizá-las. Deus, por outro lado, trabalha incansavelmente para convidar, convencer e conquistar Seus filhos por meio de Seu sacrifício e amor infinito. Deus prometeu enviar Seus anjos para ajudar-nos em nossa jornada espiritual.\n\nOs anjos são enviados diretamente da sala do trono de Deus para assistir, proteger e lutar pelos direitos da humanidade de conhecer seu Criador e receber a salvação provida pelo Céu. É como se todas as forças celestiais estivessem ocupadas em levar a humanidade a decidir onde desejará passar a eternidade.\n\n'Se o homem não está se elevando para ser um anjo, pode estar certo de que ele está se rebaixando para ser um demônio.' - Samuel Taylor Coleridge\n\n'Os anjos não podem pregar o evangelho, somente seres como Paulo, você e eu podemos pregar o evangelho.' - Oswald Chambers",
      versiculoChave: { texto: "Chegaram até onde Jesus estava e viram o homem que tinha sido possuído pela legião de demônios. Estava sentado ali, vestido e em perfeito juízo, e todos tiveram medo.", referencia: "Marcos 5:15" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo o texto, do que é constituído basicamente o veneno das serpentes?", opcoes: ["Proteína", "Açúcar", "Minerais raros", "Água pura"], correta: 0, explicacao: "'Estudos indicam que o veneno das serpentes é constituído basicamente de proteína.'" },
        { id: "d7q2", pergunta: "Segundo o texto, o que o inimigo trabalha arduamente para fazer com as pessoas?", opcoes: ["Iludir, enganar e seduzir para escravizá-las","Enriquecê-las rapidamente","Torná-las mais estudiosas","Uni-las todas em um só governo mundial e pacífico"], correta: 0, explicacao: "'O inimigo trabalha arduamente para iludir, enganar e seduzir as pessoas a fim de escravizá-las.' Deus, ao contrário, trabalha para convidar, convencer e conquistar." },
        { id: "d7q3", tipo: "relampago", pergunta: "Rodada relâmpago: revise a semana!", itens: [{"texto":"Os anjos foram criados antes dos seres humanos.","verdadeiro":true},{"texto":"Os demônios de Gerasa se apresentaram como 'Exército'.","verdadeiro":false},{"texto":"Em Gerasa, os discípulos fugiram com medo do endemoninhado.","verdadeiro":true},{"texto":"Satanás quer que as pessoas acreditem muito em sua existência.","verdadeiro":false},{"texto":"No tempo de Jesus, os anjos maus concentraram forças na Palestina.","verdadeiro":true}], explicacao: "Os demônios se chamaram 'Legião'. E Satanás prefere que as pessoas não acreditem nele ou o vejam como piada: assim, engana mais fácil quem não segue a Cristo." },
        { id: "d7q4", pergunta: "Segundo Oswald Chambers, citado no texto, quem pode pregar o evangelho?", opcoes: ["Somente os anjos", "Somente os profetas do Antigo Testamento", "Seres como Paulo, você e eu", "Apenas os pastores ordenados"], correta: 2, explicacao: "'Os anjos não podem pregar o evangelho, somente seres como Paulo, você e eu podemos pregar o evangelho.' - Oswald Chambers" }
      ]
    }
  ]
};
