export const LICAO_LA_8 = {
  titulo: "Lição 8 - Comunicação é o Segredo (14 a 20 de novembro)",
  semana: "2026-W46",
  trimestre: "Livro Aberto",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-11-14",
      titulo: "TEASER",
      conteudo: "Todos nós desejamos um relacionamento duradouro e significativo com Deus. O desafio, porém, é conseguirmos dedicar o tempo necessário para cultivarmos a amizade com Ele. Muitas vezes, as distrações se disfarçam traiçoeiramente de atividades essenciais. Somos viciados – não em drogas ou em álcool – mas em tarefas, trabalho e assim por diante.\n\nDeus, no entanto, tem a solução para o nosso problema! Ele nos concedeu um meio de enraizar profundamente nossa vida Nele – a comunicação diária e o descanso de sábado. A oração é uma forma de comunicar-nos com Deus. Outras formas de fazer isso incluem a leitura de Sua Palavra, a reflexão sobre o que aprendemos na Bíblia, a lembrança de como Ele tem nos conduzido e assim por diante. A comunicação diária com Deus significa simplesmente dedicar tempo para falar, ouvir e refletir sobre Ele. Com o descanso de sábado, Deus nos convida a pararmos, reduzirmos a velocidade, centralizarmos nossos pensamentos Nele e recebermos a bênção de estar em Sua presença.\n\nA cultura agitada de nosso tempo vai na contramão desse pensamento. Porém, seremos muito abençoados ao separarmos tempo para amar e ser amados. Esses momentos aprofundam nosso relacionamento com Deus e servem como um oásis no tempo para refletirmos e reordenarmos nossa vida.",
      versiculoChave: { texto: "Guardei Tua palavra em meu coração, para não pecar contra Ti. [...] Meditarei em Tuas ordens e refletirei sobre Teus caminhos. Terei prazer em Teus decretos e não me esquecerei de Tua palavra.", referencia: "Salmo 119:11-16" },
      perguntas: [
        { id: "d1q1", pergunta: "Segundo o texto, o que Deus nos concedeu como meio de enraizar profundamente nossa vida Nele?", opcoes: ["Comunicação diária e descanso de sábado", "O estudo aprofundado de teologia acadêmica", "A participação em grandes eventos religiosos", "Um calendário de jejuns anuais"], correta: 0, explicacao: "Deus nos concedeu a comunicação diária e o descanso de sábado como meio de enraizar profundamente nossa vida Nele." },
        { id: "d1q2", pergunta: "Julgue: segundo o texto, somos viciados apenas em drogas ou álcool, nunca em tarefas ou trabalho.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "O texto diz que somos viciados 'não em drogas ou em álcool – mas em tarefas, trabalho e assim por diante'." },
        { id: "d1q3", tipo: "multipla", pergunta: "Quais destas o texto cita como formas de nos comunicarmos com Deus? (marque todas)", opcoes: ["A oração", "A leitura de Sua Palavra", "Fazer longas viagens a templos", "Lembrar como Ele nos conduziu"], corretas: [0, 1, 3], explicacao: "O texto cita a oração, a leitura da Palavra, a reflexão sobre o que aprendemos e a lembrança de como Deus nos conduziu. Viagens a templos não aparecem: comunicar-se com Deus é dedicar tempo para falar, ouvir e refletir sobre Ele." },
        { id: "d1q4", pergunta: "Segundo o texto, o que o descanso de sábado nos convida a fazer?", opcoes: ["Pararmos e centralizarmos os pensamentos Nele", "Planejarmos com calma a semana de trabalho seguinte", "Visitarmos parentes distantes", "Organizarmos nossas finanças pessoais da semana"], correta: 0, explicacao: "O sábado nos convida a pararmos, reduzirmos a velocidade, centralizarmos nossos pensamentos Nele e recebermos a bênção de estar em Sua presença." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-11-15",
      titulo: "ROTEIRO ORIGINAL",
      conteudo: "A Bíblia está repleta de exemplos de pessoas que fizeram da oração uma prioridade na vida. Davi, por exemplo, tinha o hábito de orar três vezes ao dia (Sl 119:164). Depois da ressurreição de Jesus, Seus discípulos continuaram a orar em certos momentos do dia (At 3:1; At 10:9). Leia em sua Bíblia os textos de Daniel 6:3-10 e Êxodo 20:8-11 para relembrar os benefícios da oração e do descanso no sábado. Depois, responda às perguntas a seguir:\n\nQue palavras ou frases chamam sua atenção na experiência de Daniel? Por quê?\n\nQual era o preço de desobedecer ao decreto de Dario?\n\nDaniel habitualmente orava três vezes ao dia (v. 10). Em sua opinião, como essa prática o ajudou a enfrentar a grande pressão?\n\nLeia Êxodo 20:8-11. O sábado está relacionado à confiança em Deus, à diminuição do ritmo para apreciar as dádivas que Ele nos concedeu, ao descanso de nossas atividades escolares e à consciência das bênçãos e promessas que Ele nos dá – durante 24 horas. Como você costuma guardar o sábado?\n\nQue preocupações, dúvidas ou temores você tem que o impedem de fazer da guarda do sábado um hábito semanal?",
      versiculoChave: { texto: "Guardei Tua palavra em meu coração, para não pecar contra Ti. [...] Meditarei em Tuas ordens e refletirei sobre Teus caminhos. Terei prazer em Teus decretos e não me esquecerei de Tua palavra.", referencia: "Salmo 119:11-16" },
      perguntas: [
        { id: "d2q1", pergunta: "Segundo o texto, quantas vezes ao dia Davi tinha o hábito de orar?", opcoes: ["Uma vez", "Duas vezes", "Três vezes", "Cinco vezes"], correta: 2, explicacao: "Davi tinha o hábito de orar três vezes ao dia (Sl 119:164)." },
        { id: "d2q2", pergunta: "Quais textos bíblicos o Roteiro Original de hoje pede para ler sobre a oração e o descanso no sábado?", opcoes: ["Gênesis 1 e Salmo 23", "Daniel 6:3-10 e Êxodo 20:8-11", "Mateus 5:1-12 e Apocalipse 18:1-4", "1 Samuel 17 e Romanos 12"], correta: 1, explicacao: "O texto pede a leitura de Daniel 6:3-10 e Êxodo 20:8-11." },
        { id: "d2q3", pergunta: "Julgue: segundo o texto, Daniel tinha o hábito de orar três vezes ao dia.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto diz que Daniel habitualmente orava três vezes ao dia (v. 10), e esse hábito o ajudou a enfrentar a grande pressão do decreto de Dario." },
        { id: "d2q4", pergunta: "Segundo o texto, a que o sábado está relacionado?", opcoes: ["Apenas à participação em cultos formais", "À confiança em Deus e a um ritmo mais lento", "À realização de grandes viagens religiosas", "Ao cumprimento rigoroso das metas escolares"], correta: 1, explicacao: "O sábado está relacionado à confiança em Deus, à diminuição do ritmo para apreciar as dádivas que Ele nos concedeu." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-11-16",
      titulo: "ZOOM",
      conteudo: "Leia o Texto-Chave desta semana, que se encontra em Salmo 119:11-16. Esse capítulo da Bíblia tem algumas curiosidades. Além de ser o mais longo, foi escrito em forma de acróstico. São 22 seções, que representam as 22 letras do alfabeto hebraico. Acredita-se que ele tenha sido escrito por Davi.\n\nOs versos 11 a 16 demonstram a alegria do salmista em guardar a lei de Deus, meditar nela e andar nos caminhos do Senhor. Sempre devemos ler a Bíblia com o coração aberto para a reflexão.\n\nVeja o que o Comentário Bíblico Adventista (vol. 3, p. 1.006) diz a respeito da meditação: 'Quando a pessoa medita nas verdades da Palavra de Deus, estas verdades se tornam parte da vida. Uma leitura apressada, sem reflexão, realiza pouco bem. A meditação silenciosa permite que o Espírito Santo aplique devidamente as declarações gerais de princípio à experiência individual. [...] A meditação auxilia na proteção contra a tentação.' A mente que está repleta dos preceitos de Deus não tem espaço para pensamentos inferiores e degradantes. O jovem com uma mente guardada desta forma trilhará um caminho puro. O resultado natural é o prazer na lei de Deus. Ela se torna uma fonte de alegria e não um fardo.\n\nComo tem sido o seu contato com a Bíblia? Como você a enxerga? Fica a dica: Se ainda não sente prazer na leitura da Palavra de Deus, ore e se esforce para ler diariamente uma porção dela. Faça o teste!",
      versiculoChave: { texto: "A mente que está repleta dos preceitos de Deus não tem espaço para pensamentos inferiores e degradantes.", referencia: "Comentário Bíblico Adventista, vol. 3, p. 1.006" },
      perguntas: [
        { id: "d3q1", pergunta: "Segundo o texto, quantas seções tem o Salmo 119, representando as letras do alfabeto hebraico?", opcoes: ["10", "15", "22", "30"], correta: 2, explicacao: "São 22 seções, que representam as 22 letras do alfabeto hebraico." },
        { id: "d3q2", pergunta: "A quem se acredita que o Salmo 119 tenha sido escrito?", opcoes: ["Salomão", "Davi", "Moisés", "Isaías"], correta: 1, explicacao: "Acredita-se que ele tenha sido escrito por Davi." },
        { id: "d3q3", pergunta: "Julgue: segundo o Comentário Bíblico Adventista citado no texto, uma leitura apressada e sem reflexão realiza muito bem espiritual.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "O comentário diz que 'uma leitura apressada, sem reflexão, realiza pouco bem'." },
        { id: "d3q4", tipo: "ordenar", pergunta: "Coloque em ordem o que acontece com quem enche a mente da Palavra:", itens: ["Mente cheia dos preceitos de Deus", "Sem espaço para pensamentos ruins", "Trilha um caminho puro", "Sente prazer na lei de Deus"], explicacao: "A mente cheia dos preceitos de Deus não tem espaço para pensamentos inferiores; assim o jovem trilha um caminho puro, e o resultado natural é o prazer na lei de Deus, que vira alegria e não fardo." }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-11-17",
      titulo: "MAKING OF",
      conteudo: "A Bíblia inteira foi escrita num período que abrange mais de 1.600 anos. É uma obra de cerca de 40 autores, das mais variadas profissões: de humildes agricultores, pescadores até renomados reis.\n\nO Antigo Testamento foi escrito em hebraico, com exceção de algumas passagens em Esdras, Jeremias e Daniel, que foram escritas em aramaico. O Novo Testamento foi escrito em grego.\n\nNa batalha final contra Cristo e Seus seguidores, a falsificação será tão parecida com o verdadeiro que apenas os que conhecerem bem a Bíblia conseguirão identificar a diferença.\n\nA Bíblia é apresentada como a única proteção contra as armadilhas de Satanás. Por isso o inimigo tem trabalhado para que as pessoas não tenham interesse na leitura da Palavra de Deus.\n\nA Bíblia é comparada a um mapa que precisa ser examinado na jornada rumo ao Céu. Qualquer pessoa, com a ajuda do Espírito Santo, tem condição de entender a verdade bíblica. A Bíblia não é um livro apenas para pessoas cultas. Ela foi escrita de forma a alcançar todos os públicos.\n\nNa parábola das dez virgens (Mt 25:1-13), as lamparinas são representadas pela Bíblia, e o óleo, pelo Espírito Santo. Não basta a pessoa ter uma Bíblia. É preciso ter também o discernimento do Espírito Santo.",
      versiculoChave: { texto: "A mente que está repleta dos preceitos de Deus não tem espaço para pensamentos inferiores e degradantes.", referencia: "Comentário Bíblico Adventista, vol. 3, p. 1.006" },
      perguntas: [
        { id: "d4q1", pergunta: "Segundo o texto, ao longo de quantos anos a Bíblia inteira foi escrita?", opcoes: ["Mais de 500 anos", "Mais de 1.000 anos", "Mais de 1.600 anos", "Mais de 3.000 anos"], correta: 2, explicacao: "A Bíblia inteira foi escrita num período que abrange mais de 1.600 anos." },
        { id: "d4q2", pergunta: "Julgue: segundo o texto, partes de Esdras, Jeremias e Daniel foram escritas em aramaico.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O Antigo Testamento foi escrito em hebraico, com exceção de algumas passagens em Esdras, Jeremias e Daniel, escritas em aramaico." },
        { id: "d4q3", tipo: "pares", pergunta: "Ligue cada item ao que o texto diz sobre ele:", pares: [["Lamparinas (Mt 25)", "A Bíblia"], ["Óleo (Mt 25)", "O Espírito Santo"], ["Novo Testamento", "Escrito em grego"], ["Autores da Bíblia", "Cerca de 40"]], explicacao: "Na parábola das dez virgens, as lamparinas representam a Bíblia e o óleo, o Espírito Santo. O Novo Testamento foi escrito em grego, e a Bíblia tem cerca de 40 autores, de agricultores a reis." },
        { id: "d4q4", pergunta: "A que a Bíblia é comparada no texto, quanto à jornada rumo ao Céu?", opcoes: ["A uma bússola quebrada", "A um mapa que precisa ser examinado", "A um mero livro de histórias antigas", "A uma carta sem remetente"], correta: 1, explicacao: "A Bíblia é comparada a um mapa que precisa ser examinado na jornada rumo ao Céu." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-11-18",
      titulo: "EXTRAS",
      conteudo: "Leia e marque em sua Bíblia os textos adicionais desta semana. Qual deles mais chamou sua atenção? Por quê?\n\nNosso critério sempre deve ser: 'À lei e ao testemunho!' (Is 8:20). O exemplo de Jesus nos motiva a vivermos de acordo com a vontade de Deus, expressa em Sua Palavra. No final do tempo, é dito que 'Deus terá um povo que vai considerar a Bíblia, e a Bíblia somente, o padrão de todas as doutrinas e base de todas as reformas' (Os Resgatados, p. 302).\n\nEstamos nos preparando para fazer parte desse povo agora! Veja esta dica interessante: 'É o primeiro e mais elevado dever de toda pessoa racional aprender com base nas Escrituras qual é a verdade e então andar na luz, encorajando outros a fazer o mesmo' (p. 303).\n\nSeja inteligente e não apenas leia a Bíblia. Estude-a e pratique o que ela ensina. Você vai perceber o quanto ela é atual, pois é a revelação do plano da salvação do ser humano. Além disso, as bênçãos serão facilmente percebidas em sua vida.\n\nTextos adicionais: Provérbios 3:13-18; Isaías 8:19,20; 2Timóteo 4:3-5",
      versiculoChave: { texto: "Deus terá um povo que vai considerar a Bíblia, e a Bíblia somente, o padrão de todas as doutrinas e base de todas as reformas.", referencia: "Os Resgatados, p. 302" },
      perguntas: [
        { id: "d5q1", pergunta: "Segundo Isaías 8:20, citado no texto, qual deve ser sempre nosso critério?", opcoes: ["'Ao sentimento e à tradição!'", "'À lei e ao testemunho!'", "'À razão e à ciência!'", "'À experiência e à emoção!'"], correta: 1, explicacao: "'Nosso critério sempre deve ser: \"À lei e ao testemunho!\"' (Is 8:20)." },
        { id: "d5q2", tipo: "digitar", pergunta: "Complete: \"Deus terá um povo que vai considerar a Bíblia, e a Bíblia somente, o ___ de todas as doutrinas\" (Os Resgatados, p. 302)", resposta: "padrão", aceitas: ["padrao"], explicacao: "O povo de Deus no fim terá a Bíblia, e somente ela, como padrão de todas as doutrinas e base de todas as reformas — por isso vale estudá-la, e não só lê-la." },
        { id: "d5q3", pergunta: "Julgue: segundo o texto, basta ler a Bíblia, sem necessidade de estudá-la ou praticar o que ela ensina.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "O texto diz: 'Seja inteligente e não apenas leia a Bíblia. Estude-a e pratique o que ela ensina.'" },
        { id: "d5q4", pergunta: "Qual destes é um dos 'textos adicionais' sugeridos para esta semana?", opcoes: ["Provérbios 3:13-18", "Gênesis 1:1-5", "Salmo 23:1-6", "Eclesiastes 12:1-14"], correta: 0, explicacao: "Os textos adicionais incluem Provérbios 3:13-18, Isaías 8:19,20 e 2Timóteo 4:3-5." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-11-19",
      titulo: "PANORÂMICA",
      conteudo: "O título do capítulo 37 do livro Os Resgatados é 'Nossa Única Proteção' e apresenta a Bíblia como o único livro capaz de impedir que sejamos enganados pelo inimigo. Por meio dela podemos enxergar o caráter de Deus, as leis de Seu governo e entender qual é o objetivo da Trindade.\n\nEm nossos dias, a Bíblia se tornou um livro acessível (pelo menos na maior parte do mundo), mas quantos realmente a leem e conhecem seu conteúdo? Há um segredo em relação a ela: quanto mais você a ler, mais interessante ela se tornará. A Bíblia foi escrita de forma que toda pessoa, não importa o grau de instrução, consiga entender sua mensagem.\n\nDeus colocou à nossa disposição o Espírito Santo para ser nosso professor, e também anjos para nos ajudarem a lembrar das verdades bíblicas que necessitamos. O convite da lição desta semana é que você descubra a beleza e a importância da Bíblia e a faça dela o seu livro de estudo.\n\nLembre-se: 'O destino de todas as pessoas da Terra está prestes a ser decidido. [...] Devemos buscar agora uma experiência profunda e viva com as coisas de Deus. Não temos tempo a perder' (Os Resgatados, p. 304).\n\n'Pessoas cultas, com aparência de grande sabedoria, ensinam que as Escrituras possuem um significado secreto e espiritual que não é visto com facilidade na linguagem usada. Esses indivíduos são falsos mestres. [...] Se as pessoas aceitassem apenas o que a Bíblia realmente diz, realizariam uma obra que levaria milhares que hoje andam errantes na mentira para o aprisco de Cristo' (Os Resgatados, p. 303).",
      versiculoChave: { texto: "O destino de todas as pessoas da Terra está prestes a ser decidido. [...] Devemos buscar agora uma experiência profunda e viva com as coisas de Deus. Não temos tempo a perder.", referencia: "Os Resgatados, p. 304" },
      perguntas: [
        { id: "d6q1", pergunta: "Qual é o título do capítulo 37 do livro Os Resgatados, segundo o texto?", opcoes: ["'Nossa Única Proteção'", "'O Grande Conflito Final'", "'A Última Geração'", "'O Selo de Deus'"], correta: 0, explicacao: "O título do capítulo 37 do livro Os Resgatados é 'Nossa Única Proteção'." },
        { id: "d6q2", pergunta: "Segundo o texto, o que Deus colocou à nossa disposição para nos ajudar a entender e lembrar as verdades bíblicas?", opcoes: ["Apenas os pastores e teólogos", "O Espírito Santo e os anjos", "Somente os comentários bíblicos", "Apenas a tradição da igreja"], correta: 1, explicacao: "Deus colocou à nossa disposição o Espírito Santo para ser nosso professor, e também anjos para nos ajudarem a lembrar das verdades bíblicas." },
        { id: "d6q3", pergunta: "Julgue: segundo o texto, os falsos mestres dizem que a Bíblia tem um sentido secreto, difícil de ver.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "Os falsos mestres ensinam que as Escrituras possuem 'um significado secreto e espiritual que não é visto com facilidade'. A Bíblia foi escrita para que todos entendam sua mensagem." },
        { id: "d6q4", pergunta: "Segundo a citação de Os Resgatados (p. 304), o que está prestes a ser decidido?", opcoes: ["O destino de todas as pessoas da Terra", "Apenas o destino dos líderes religiosos", "O calendário das festividades bíblicas", "A localização do novo templo"], correta: 0, explicacao: "'O destino de todas as pessoas da Terra está prestes a ser decidido' (Os Resgatados, p. 304)." }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-11-20",
      titulo: "OFF",
      conteudo: "A lição desta semana enfatizou a importância da comunhão com Deus por meio da Sua Palavra e da obediência à Sua lei, especialmente quanto à guarda do sábado. Há bênçãos especiais para quem considera a ordem divina.\n\nEllen White termina o capítulo 37 do livro Os Resgatados com uma adequada comparação dos cristãos com árvores no jardim de Deus. Veja belo texto:\n\n'No verão, não se nota a diferença entre os ciprestes e as outras árvores. Mas, quando vêm as tempestades do inverno, os ciprestes permanecem intactos, ao passo que as outras árvores perdem a folhagem. Quando a oposição surgir, a intolerância voltar a prevalecer e a perseguição se acender, os descomprometidos e hipócritas voltarão desistidos da fé. Mas os cristãos verdadeiros permanecerão firmes, sua fé será mais forte e sua esperança ainda mais brilhante do que nos tempos de prosperidade' (p. 304).\n\nQue 'árvore' você se tornou? Veja o tipo de cristão descrito em Jeremias 17:8: 'É como uma árvore plantada junto ao rio, com raízes que se estendem até as correntes de água. [...] Não teme os longos meses de seca, e nunca deixa de produzir frutos.'\n\n'O caminho cristão não é o caminho intermediário entre extremos, mas sim, o caminho estreito entre precipícios.'\nDONALD BLOESCH\n\n'Se você tem sucesso, torna possível deixar uma herança para os outros. Mas se você deseja criar um legado, então precisa deixar algo nos outros. Quando você pensa com altruísmo e investe em outros, obtém a oportunidade de criar um legado que permanecerá.'\nJOHN MAXWELL\n\nALÉM DO ESTUDO: A Bíblia se tornou um livro sob ataque; não no sentido de lutarem contra ela, mas em afirmarem que ela precisa ser atualizada. Para não correr risco, preste atenção a este conselho sábio: 'Nunca devemos estudar a Bíblia sem oração. Somente o Espírito Santo pode nos levar a sentir a importância das coisas que compreendemos com facilidade ou nos impedir de distorcer verdades difíceis' (Os Resgatados, p. 304). Acesse e leia o capítulo 37 do livro Os Resgatados.",
      versiculoChave: { texto: "É como uma árvore plantada junto ao rio, com raízes que se estendem até as correntes de água. [...] Não teme os longos meses de seca, e nunca deixa de produzir frutos.", referencia: "Jeremias 17:8" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo a comparação de Ellen White, o que acontece com os ciprestes durante as tempestades de inverno, ao contrário de outras árvores?", opcoes: ["Eles perdem toda a folhagem", "Eles permanecem intactos", "Eles crescem mais rápido", "Eles mudam de cor"], correta: 1, explicacao: "'Quando vêm as tempestades do inverno, os ciprestes permanecem intactos, ao passo que as outras árvores perdem a folhagem.'" },
        { id: "d7q2", pergunta: "Segundo Jeremias 17:8, citado no texto, o que a árvore plantada junto ao rio nunca deixa de fazer?", opcoes: ["Perder as folhas no verão", "Produzir frutos", "Florescer no inverno", "Secar durante as chuvas"], correta: 1, explicacao: "'Não teme os longos meses de seca, e nunca deixa de produzir frutos' (Jeremias 17:8)." },
        { id: "d7q3", tipo: "relampago", pergunta: "Rodada relâmpago: revise a semana!", itens: [{ texto: "Davi tinha o hábito de orar três vezes ao dia.", verdadeiro: true }, { texto: "O Salmo 119 tem 12 seções, uma para cada tribo.", verdadeiro: false }, { texto: "Na parábola das dez virgens, o óleo representa o Espírito Santo.", verdadeiro: true }, { texto: "O Novo Testamento foi escrito em hebraico.", verdadeiro: false }, { texto: "Para Bloesch, o caminho cristão é o meio-termo entre extremos.", verdadeiro: false }], explicacao: "O Salmo 119 tem 22 seções, uma para cada letra do alfabeto hebraico. O Novo Testamento foi escrito em grego. E Bloesch diz que o caminho cristão é o caminho estreito entre precipícios, não o meio-termo." },
        { id: "d7q4", pergunta: "Segundo o conselho sábio citado em Além do Estudo (Os Resgatados, p. 304), o que nunca devemos fazer ao estudar a Bíblia?", opcoes: ["Usar comentários bíblicos", "Estudá-la sem oração", "Ler mais de um capítulo por dia", "Compartilhar o que aprendemos"], correta: 1, explicacao: "'Nunca devemos estudar a Bíblia sem oração' (Os Resgatados, p. 304)." }
      ]
    }
  ]
};

export const LICAO_LA_9 = {
  titulo: "Lição 9 - Salve-se Quem Puder! (21 a 27 de novembro)",
  semana: "2026-W47",
  trimestre: "Livro Aberto",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-11-21",
      titulo: "TEASER",
      conteudo: "Desde a ordem de Deus a Adão e Eva (Gn 2:17), até a advertência proclamada em alta voz pelo anjo de Apocalipse 18, muita coisa aconteceu. Os conselhos de Deus foram ignorados por alguns, enquanto outros assumiram o dever de obedecê-los. A despeito do registro passado da obediência ou desdém da humanidade às ordens divinas, Apocalipse 18 revela o fim da paciência de Deus para com o pecado. O anjo que João viu em sua visão ilumina a Terra inteira com seu esplendor.\n\nA progressão de Apocalipse 14, Ap 15, Ap 16, Ap 17, Ap 18 descreve o estado terrível do mundo ao nos aproximarmos da volta de Cristo. Ao contrário das previsões humanas, o anjo de Apocalipse 18 declara que o mundo não se tornará melhor. A verdade, revelada por Jesus, será completamente rejeitada. A mente e o coração humano serão endurecidos pelo pecado, e aqueles que decidirem defender a verdade estarão sujeitos a terríveis privações – e até mesmo à morte – especialmente ao defenderem a verdade sobre a santidade do sábado de Deus.\n\nÀ medida que o mundo se aproximar cada vez mais de seu fim, o Santo Espírito de Deus concederá poder especial para a proclamação da advertência final ao mundo. Deus aguarda sua decisão. Hoje é o tempo de atender à advertência divina de sair do sistema mundial de confusão, renunciar ao pecado e preparar-se para encontrar Jesus em paz.",
      versiculoChave: { texto: "Então ouvi outra voz do céu, que disse: 'Saiam dela, Meu povo! Não participem de seus pecados, ou serão castigados com ela. Pois os pecados dela se amontoaram até o céu, e Deus Se lembrou de seus atos perversos.'", referencia: "Apocalipse 18:4,5" },
      perguntas: [
        { id: "d1q1", pergunta: "Segundo o texto, o que Apocalipse 18 revela sobre a paciência de Deus?", opcoes: ["Que ela é infinita e nunca terá fim", "Que ela chegará ao fim quanto ao pecado", "Que ela já terminou há séculos", "Que ela depende do comportamento humano"], correta: 1, explicacao: "Apocalipse 18 revela o fim da paciência de Deus para com o pecado." },
        { id: "d1q2", pergunta: "Julgue: segundo o texto, o anjo de Apocalipse 18 declara que o mundo se tornará cada vez melhor.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "Ao contrário das previsões humanas, o anjo declara que o mundo não se tornará melhor." },
        { id: "d1q3", pergunta: "Segundo o texto, a que os defensores da verdade sobre a santidade do sábado estarão sujeitos?", opcoes: ["A um reconhecimento público imediato", "A terríveis privações e até à morte", "A recompensas financeiras", "A isenção de responsabilidades civis"], correta: 1, explicacao: "Aqueles que decidirem defender a verdade estarão sujeitos a terríveis privações – e até mesmo à morte." },
        { id: "d1q4", tipo: "digitar", pergunta: "Complete: \"Saiam dela, Meu ___! Não participem de seus pecados\" (Apocalipse 18:4)", resposta: "povo", explicacao: "Deus ainda chama de 'Meu povo' quem está dentro de Babilônia. O convite é sair do sistema de confusão e renunciar ao pecado enquanto há tempo." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-11-22",
      titulo: "ROTEIRO ORIGINAL",
      conteudo: "Por mais assustadora que uma história pareça, saber que o bem vence no final traz alívio para quem está envolvido nela. As profecias descritas no livro do Apocalipse não devem provocar medo e sim trazer alívio para os filhos de Deus. Elas mostram que tudo vai terminar bem para os fiéis. Leia em sua Bíblia o texto de Apocalipse 18:1-14 e depois responda às perguntas a seguir:\n\nVocê já havia lido esse texto antes? O que chamou sua atenção?\n\nQuem está falando? A quem é dirigida essa mensagem?\n\nObserve os pecados da mulher simbolicamente apresentada como Babilônia. Faça uma marcação em cada pecado que ela cometeu. Como as pessoas no mundo se relacionam com ela?\n\nQuem Babilônia representa? Ela é símbolo de quê?\n\nPor que o mundo lamenta por Babilônia depois que Deus começa a destruí-la? É possível se tornar tão apegado ao pecado que alguém literalmente chore diante do fato de ele ser extinto?\n\nQue duas lições você aprendeu dessa passagem bíblica?",
      versiculoChave: { texto: "Então ouvi outra voz do céu, que disse: 'Saiam dela, Meu povo! Não participem de seus pecados, ou serão castigados com ela. Pois os pecados dela se amontoaram até o céu, e Deus Se lembrou de seus atos perversos.'", referencia: "Apocalipse 18:4,5" },
      perguntas: [
        { id: "d2q1", pergunta: "Segundo o texto, qual passagem bíblica o Roteiro Original de hoje pede para ler?", opcoes: ["Apocalipse 18:1-14", "1 Tessalonicenses 4:13-18", "Mateus 24:1-14", "Gênesis 2:1-17"], correta: 0, explicacao: "O texto pede a leitura de Apocalipse 18:1-14." },
        { id: "d2q2", pergunta: "Segundo o texto, o que as profecias do livro do Apocalipse não devem provocar?", opcoes: ["Reflexão", "Medo", "Esperança", "Alívio"], correta: 1, explicacao: "As profecias 'não devem provocar medo e sim trazer alívio para os filhos de Deus'." },
        { id: "d2q3", pergunta: "Julgue: segundo o texto, a mulher descrita em Apocalipse 18 representa simbolicamente Babilônia.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto pede para observar 'os pecados da mulher simbolicamente apresentada como Babilônia'." },
        { id: "d2q4", pergunta: "Quantas lições o texto pede que você identifique ao final da leitura da passagem?", opcoes: ["Uma", "Duas", "Três", "Cinco"], correta: 1, explicacao: "O texto pergunta: 'Que duas lições você aprendeu dessa passagem bíblica?'" }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-11-23",
      titulo: "ZOOM",
      conteudo: "Leia o Texto-Chave desta semana, que se encontra em Apocalipse 18:4,5. O Comentário Bíblico Adventista (vol. 7, p. 917-919) apresenta informações importantes para compreender o que é Babilônia e o papel que ela vai desempenhar no tempo do fim:\n\nBabilônia (ou Babel) foi fundada por Ninrode (após o dilúvio), como um símbolo da descrença no Deus verdadeiro e da rebelião contra Sua vontade.\n\nNo idioma babilônico, significa 'porta dos deuses'. No hebraico, quer dizer 'confundir'.\n\nO profeta Isaías identifica Lúcifer como o rei invisível de Babilônia. No Antigo Testamento, Babilônia sempre aparece representando as forças do mal. Enquanto Jerusalém tipifica as forças do bem.\n\nNabucodonosor reconstruiu Babilônia e a tornou uma das maravilhas do mundo antigo. Quando o império se tornou orgulhoso e cruel, Deus humilhou Nabucodonosor e assegurou sua submissão. Por fim, a cidade perdeu sua importância ao longo dos anos e praticamente deixou de existir.\n\nDurante os primeiros séculos do cristianismo, Babilônia se transformou em um termo apropriado entre judeus e cristãos para descrever Roma imperial.\n\nBabilônia, tanto literal como simbólica, é reconhecida há muito tempo como uma inimiga tradicional da verdade e do povo de Deus.\n\nA expressão 'Deus Se lembrou' costuma significar que a paciência do Senhor está prestes a se esgotar. Em breve Ele dará aos seres humanos a retribuição por todo ato praticado, seja ele bom ou mau.\n\nEstamos vivendo no tempo da misericórdia de Deus. Precisamos nos preparar!",
      versiculoChave: { texto: "Então ouvi outra voz do céu, que disse: 'Saiam dela, Meu povo! Não participem de seus pecados, ou serão castigados com ela. Pois os pecados dela se amontoaram até o céu, e Deus Se lembrou de seus atos perversos.'", referencia: "Apocalipse 18:4,5" },
      perguntas: [
        { id: "d3q1", tipo: "ordenar", pergunta: "Coloque em ordem a história de Babilônia contada no texto:", itens: ["Fundada por Ninrode", "Reconstruída por Nabucodonosor", "Perde a importância e quase some", "Vira apelido de Roma imperial"], explicacao: "Ninrode fundou Babilônia depois do dilúvio; Nabucodonosor a reconstruiu; com o tempo ela praticamente deixou de existir; e, nos primeiros séculos do cristianismo, o nome passou a descrever Roma imperial." },
        { id: "d3q2", pergunta: "No hebraico, o que a palavra Babilônia significa, segundo o texto?", opcoes: ["'Porta dos deuses'", "'Confundir'", "'Terra prometida'", "'Cidade santa'"], correta: 1, explicacao: "No hebraico, Babilônia quer dizer 'confundir' (no idioma babilônico, significa 'porta dos deuses')." },
        { id: "d3q3", pergunta: "Julgue: segundo o texto, Jerusalém tipifica as forças do mal no Antigo Testamento, enquanto Babilônia tipifica as forças do bem.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "É o contrário: Babilônia sempre aparece representando as forças do mal, enquanto Jerusalém tipifica as forças do bem." },
        { id: "d3q4", pergunta: "Segundo o texto, o que a expressão 'Deus Se lembrou' costuma significar?", opcoes: ["Que Deus esqueceu os pecados do passado", "Que a paciência do Senhor vai se esgotar", "Que uma nova aliança está para começar", "Que o povo de Deus será recompensado imediatamente"], correta: 1, explicacao: "A expressão 'Deus Se lembrou' costuma significar que a paciência do Senhor está prestes a se esgotar." }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-11-24",
      titulo: "MAKING OF",
      conteudo: "O livro de Apocalipse inclui as visões dadas a João por Jesus Cristo enquanto ele estava preso em Patmos. Essa ilha existe ainda hoje. É relativamente pequena, e fica entre o grupo de ilhas do Mar Egeu, próximo à costa oeste da Turquia.\n\nChegará o tempo em que as grandes potências mundiais vão se unir em batalha contra os mandamentos de Deus. Todos serão obrigados a observar o domingo. Quem se recusar, será julgado merecedor da morte.\n\nOs imperadores romanos procuravam territórios afastados como Patmos para aprisionar rivais políticos e religiosos porque lá eles não teriam direitos legais nem acesso às cortes.\n\nDe acordo com alguns historiadores, acredita-se que João estivesse na casa dos noventa anos quando o imperador Domiciano o aprisionou em Patmos por dois anos. Foi durante esse tempo que Deus lhe concedeu a visão dos últimos dias.\n\nQuando a situação apertar, muitos escolherão o lado popular e se voltarão contra os servos do Senhor. Por sua vez, um grande número se posicionará ao lado de Deus e o Espírito Santo será derramado sobre grupos especiais. Leia o que diz Joel 2:28.\n\nO sábado será o grande teste de lealdade. Quem se mantiver fiel ao Criador, receberá o selo de Deus. Quem se opuser a Deus e escolher outro dia de guarda receberá a marca da besta.",
      versiculoChave: { texto: "Então ouvi outra voz do céu, que disse: 'Saiam dela, Meu povo! Não participem de seus pecados, ou serão castigados com ela. Pois os pecados dela se amontoaram até o céu, e Deus Se lembrou de seus atos perversos.'", referencia: "Apocalipse 18:4,5" },
      perguntas: [
        { id: "d4q1", pergunta: "Segundo o texto, onde fica a ilha de Patmos, onde João recebeu as visões de Apocalipse?", opcoes: ["No Mar Mediterrâneo, próximo ao Egito", "No Mar Egeu, perto da Turquia", "No Mar Vermelho, perto de Israel", "No Mar Negro, na Grécia"], correta: 1, explicacao: "Patmos fica entre o grupo de ilhas do Mar Egeu, próximo à costa oeste da Turquia." },
        { id: "d4q2", pergunta: "Julgue: segundo o texto, quem se recusar a observar o domingo no tempo do fim será julgado merecedor da morte.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto diz que todos serão obrigados a observar o domingo, e 'quem se recusar, será julgado merecedor da morte'." },
        { id: "d4q3", pergunta: "Segundo o texto, por que os imperadores romanos usavam locais como Patmos para aprisionar rivais?", opcoes: ["Porque lá havia tribunais romanos mais rigorosos", "Porque lá não teriam direitos nem acesso às cortes", "Porque a ilha ficava bem perto de Roma", "Porque era um local turístico popular entre os romanos"], correta: 1, explicacao: "Territórios afastados como Patmos eram usados porque os prisioneiros não teriam direitos legais nem acesso às cortes." },
        { id: "d4q4", tipo: "pares", pergunta: "Ligue cada nome ao que o texto diz sobre ele:", pares: [["Domiciano", "Prendeu João em Patmos"], ["Joel 2:28", "Espírito derramado"], ["Selo de Deus", "Quem é fiel ao Criador"], ["Marca da besta", "Quem escolhe outro dia"]], explicacao: "O imperador Domiciano prendeu João em Patmos por dois anos. Joel 2:28 fala do Espírito derramado. No teste do sábado, os fiéis ao Criador recebem o selo de Deus; quem escolhe outro dia de guarda recebe a marca da besta." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-11-25",
      titulo: "EXTRAS",
      conteudo: "Leia e marque em sua Bíblia os textos adicionais desta semana. Qual deles mais chamou sua atenção? Por quê?\n\nQue promessa é feita em Joel 2:23?\n\nFazendeiros e outros que trabalham na agricultura compreendem a importância das primeiras e das últimas chuvas. As chuvas do início – tipicamente na primavera – ajudam a plantação a se desenvolver. As chuvas do fim deixam a plantação pronta para a colheita. 'A grande obra do evangelho não terminará com menor demonstração do poder de Deus do que o seu princípio. As profecias que se cumpriram com o derramamento da chuva temporã no começo do evangelho se cumprirão novamente com a chuva serôdia em seu encerramento' (Os Resgatados, p. 309). O Senhor prometeu e Ele é fiel em cumprir!\n\nTextos adicionais: Joel 2:23; Josué 11:15; 1Coríntios 16:13",
      versiculoChave: { texto: "Alegrem-se, ó filhos de Sião, e regozijem-se no Senhor, o seu Deus, pois com fidelidade Ele lhes dá a chuva de outono. Ele manda a chuva para vocês, tanto a de outono como a de primavera, como antigamente.", referencia: "Joel 2:23" },
      perguntas: [
        { id: "d5q1", pergunta: "Segundo o texto, o que as chuvas do início (tipicamente na primavera) ajudam a fazer?", opcoes: ["Ajudam a plantação a se desenvolver", "Preparam o solo para o plantio seguinte", "Substituem a necessidade de irrigação", "Determinam o preço da colheita"], correta: 0, explicacao: "As chuvas do início ajudam a plantação a se desenvolver." },
        { id: "d5q2", pergunta: "Segundo a citação de Os Resgatados (p. 309), a que se compara o encerramento do evangelho?", opcoes: ["À chuva serôdia", "À seca prolongada", "Ao inverno rigoroso", "Ao vento forte"], correta: 0, explicacao: "A chuva serôdia é a chuva do fim, que deixa a plantação pronta para a colheita. 'As profecias que se cumpriram com o derramamento da chuva temporã no começo do evangelho se cumprirão novamente com a chuva serôdia em seu encerramento' (Os Resgatados, p. 309)." },
        { id: "d5q3", pergunta: "Julgue: segundo o texto, a grande obra do evangelho terminará com menor demonstração do poder de Deus do que seu princípio.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "O texto diz o contrário: 'A grande obra do evangelho não terminará com menor demonstração do poder de Deus do que o seu princípio.'" },
        { id: "d5q4", pergunta: "Qual destes é um dos 'textos adicionais' sugeridos para esta semana?", opcoes: ["Josué 11:15", "Gênesis 1:1", "Mateus 5:1", "Apocalipse 21:4"], correta: 0, explicacao: "Os textos adicionais incluem Joel 2:23, Josué 11:15 e 1Coríntios 16:13." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-11-26",
      titulo: "PANORÂMICA",
      conteudo: "Você já se fez a seguinte pergunta: Será que todas as pessoas terão oportunidade de ouvir sobre Jesus e tomar sua decisão a favor Dele ou contra Ele? O capítulo 38 do livro Os Resgatados responde com propriedade essa questão.\n\nNós não sabemos exatamente como isso vai acontecer, mas podemos acreditar que Deus é suficientemente poderoso para dar a oportunidade a todas as pessoas. Ele é justo e usará critérios justos. Nossa preocupação agora deve se concentrar no papel que devemos desempenhar em tudo isso. Como podemos colaborar para que as pessoas cheguem ao conhecimento da verdade? Nós podemos ser os instrumentos usados por Deus para levar a mensagem da salvação ao nosso próximo.\n\nÉ uma realidade que quanto mais amar a Deus e entender o significado do sacrifício de Jesus, mais você desejará contar isso para os outros. Acredite: não tem sensação melhor do que colaborar no processo de salvação de outro ser humano. Como? Testemunhando do que Jesus fez em sua vida! O tempo está se esgotando e a missão precisa ser cumprida. Você quer fazer parte dela? Então, envolva-se!\n\n'Ninguém recebe a ira de Deus até que a verdade seja esclarecida tanto à sua mente quanto à sua consciência e a pessoa a rejeite. Muitos nunca tiveram a oportunidade de ouvir verdades especiais para este tempo. O Deus que lê todo coração não permitirá que ninguém que deseja saber a verdade seja enganado quanto à relação às questões do conflito. Todos receberão luz suficiente para tomar uma decisão inteligente' (Os Resgatados, p. 306).",
      versiculoChave: { texto: "Ninguém recebe a ira de Deus até que a verdade seja esclarecida tanto à sua mente quanto à sua consciência e a pessoa a rejeite.", referencia: "Os Resgatados, p. 306" },
      perguntas: [
        { id: "d6q1", pergunta: "Qual capítulo do livro Os Resgatados responde à pergunta se todas as pessoas terão oportunidade de decidir a favor ou contra Jesus?", opcoes: ["Capítulo 36", "Capítulo 37", "Capítulo 38", "Capítulo 40"], correta: 2, explicacao: "O capítulo 38 do livro Os Resgatados responde a essa questão." },
        { id: "d6q2", pergunta: "Segundo o texto, como podemos colaborar para que as pessoas cheguem ao conhecimento da verdade?", opcoes: ["Levando a mensagem da salvação ao próximo", "Apenas orando em silêncio, sem ação prática", "Aguardando que os pastores façam esse trabalho", "Evitando falar de religião"], correta: 0, explicacao: "'Nós podemos ser os instrumentos usados por Deus para levar a mensagem da salvação ao nosso próximo.'" },
        { id: "d6q3", pergunta: "Julgue: segundo o texto, quanto mais alguém ama a Deus e entende o sacrifício de Jesus, menos deseja contar isso aos outros.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "É o contrário: quanto mais se ama a Deus e se entende o sacrifício de Jesus, mais se deseja contar isso aos outros." },
        { id: "d6q4", tipo: "multipla", pergunta: "Segundo a citação de Os Resgatados (p. 306), quais destas são verdadeiras? (marque todas)", opcoes: ["Ninguém recebe a ira de Deus sem conhecer a verdade", "Quem deseja saber a verdade será enganado", "Todos receberão luz suficiente para decidir", "Todos já ouviram as verdades para este tempo"], corretas: [0, 2], explicacao: "Ninguém recebe a ira de Deus antes de a verdade ser esclarecida e rejeitada, e todos receberão luz suficiente para decidir. Deus não deixará enganar quem deseja a verdade, e muitos ainda nunca ouviram as verdades para este tempo." }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-11-27",
      titulo: "OFF",
      conteudo: "As cenas finais da história deste mundo estão se aproximando. Jesus revelou muitos detalhes do que aconteceria pouco antes de Sua volta em Mateus 24 e Mateus 25. Apesar de os discípulos não terem entendido plenamente o significado das palavras de Jesus, Ele os advertiu do que aconteceria, mesmo que isso acontecesse apenas milhares de anos após Sua morte.\n\nApocalipse 18 revela um Deus muito firme e coerente, que sofre junto com os seres humanos e concede a cada um a oportunidade de ser salvo. O sistema mundial de confusão e pecado um dia será exterminado. Jesus voltará para salvar aqueles que permanecerem fiéis a Ele. Enquanto isso, os verdadeiros seguidores de Cristo têm uma obra muito importante a fazer. Eles devem desmascarar os pecados de Babilônia com os homens e mulheres para que possam tomar sua decisão a favor de Deus.\n\nIluminados pelo poder do Santo Espírito, os fiéis permanecerão firmes na Palavra de Deus, preferindo a morte e as privações a profanar o sábado ou a desobedecer a Deus, além de ajudarem outros a aceitarem o chamado para sair de Babilônia.\n\n'Ó Espírito Santo, habite inteiramente em meu coração. Ilumine os cantos escuros desta habitação negligenciada e espalhe no lugar agradáveis raios de luz.'\nAGOSTINHO\n\n'Pode ser que todo o seu propósito na vida seja simplesmente servir de advertência aos outros.'\nANÔNIMO\n\nReflita: 'Em todas as gerações, Deus tem enviado servos Seus para repreender o pecado no mundo e na igreja. Muitos reformadores começaram sua obra determinados a controlar fortemente seus ataques aos pecados da igreja e da nação. Tinham esperança de conduzir as pessoas de volta à Bíblia por meio do exemplo de uma vida cristã pura. E o Espírito de Deus tomou conta deles. Sem temer as consequências, não conseguiram se abster de pregar as doutrinas claras da Bíblia' (Os Resgatados, p. 306, 307). O tempo de viver isso novamente está chegando! Acesse e leia o capítulo 38 do livro Os Resgatados.",
      versiculoChave: { texto: "Ó Espírito Santo, habite inteiramente em meu coração. Ilumine os cantos escuros desta habitação negligenciada e espalhe no lugar agradáveis raios de luz.", referencia: "Agostinho" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo o texto, em quais capítulos do Evangelho de Mateus Jesus revelou detalhes sobre o que aconteceria antes de Sua volta?", opcoes: ["Mateus 5 e 6", "Mateus 24 e 25", "Mateus 13 e 14", "Mateus 1 e 2"], correta: 1, explicacao: "Jesus revelou muitos detalhes em Mateus 24 e Mateus 25." },
        { id: "d7q2", tipo: "relampago", pergunta: "Rodada relâmpago: revise a semana!", itens: [{ texto: "Babilônia foi fundada por Ninrode, depois do dilúvio.", verdadeiro: true }, { texto: "Em hebraico, Babilônia quer dizer 'porta dos deuses'.", verdadeiro: false }, { texto: "João recebeu as visões de Apocalipse na ilha de Patmos.", verdadeiro: true }, { texto: "Pelo texto, o domingo será o grande teste de lealdade.", verdadeiro: false }, { texto: "Apocalipse 18 mostra um Deus indiferente ao sofrimento humano.", verdadeiro: false }], explicacao: "Em hebraico, Babilônia quer dizer 'confundir' ('porta dos deuses' é no idioma babilônico). O grande teste de lealdade será o sábado. E Apocalipse 18 revela um Deus que sofre junto com os seres humanos." },
        { id: "d7q3", pergunta: "Segundo o texto, quem disse a frase 'Pode ser que todo o seu propósito na vida seja simplesmente servir de advertência aos outros'?", opcoes: ["Agostinho", "Anônimo", "John Maxwell", "Donald Bloesch"], correta: 1, explicacao: "A frase é atribuída a Anônimo." },
        { id: "d7q4", pergunta: "Segundo a citação final de Os Resgatados (p. 306, 307), o que muitos reformadores tinham esperança de fazer?", opcoes: ["Fundar novas denominações cristãs pelo mundo", "Levar as pessoas de volta à Bíblia pelo exemplo", "Conquistar poder político nas nações", "Ignorar os pecados da igreja para evitar conflitos"], correta: 1, explicacao: "'Tinham esperança de conduzir as pessoas de volta à Bíblia por meio do exemplo de uma vida cristã pura.'" }
      ]
    }
  ]
};

export const LICAO_LA_10 = {
  titulo: "Lição 10 - O Tempo de Angústia (28 de novembro a 4 de dezembro)",
  semana: "2026-W48",
  trimestre: "Livro Aberto",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-11-28",
      titulo: "TEASER",
      conteudo: "O tempo de angústia é um período que amedronta muitos adventistas do sétimo dia, como também pessoas de outra fé que aguardam a volta de Jesus. Mesmo que estejamos em paz com Deus, não podemos desconsiderar as cenas terríveis que se desenrolarão ao final da história deste mundo.\n\nAo serem proclamadas as palavras de Apocalipse 22:11, a decisão de toda humanidade estará selada. O injusto continuará praticando a injustiça e o santo será selado em sua santidade. Jesus concluirá o ministério de mediação em favor da humanidade e Satanás estará livre para usar todo o seu poder para perseguir os seguidores de Deus e conduzir o mundo caído ao precipício da destruição. Conforme Daniel 12:1 haverá, então, um tempo de angústia como nunca antes.\n\nApesar do tempo de prova, o pequeno grupo remanescente dos seguidores fiéis de Cristo resistirá até o fim. Esse grupo não profanará o sábado nem a fé em Jesus Cristo. Assim como Jacó na noite em que lutou com o anjo do Senhor (Gn 32:24-30), orarão fervorosamente rogando pela misericórdia de Deus e humilhando-se perante Ele.\n\nAo avaliarem sua vida, encontrarão poucas boas horas e muitos erros. Porém, terão se arrependido, confessado e abandonado todos os pecados. Agora é o tempo de ficar em paz com Deus. Agora é o tempo de abandonar o pecado e submeter-se ao Senhor – antes de o tempo de angústia chegar.",
      versiculoChave: { texto: "Nessa época, Miguel, o grande príncipe que guarda Seu povo, se levantará. Haverá um tempo de angústia como nunca houve desde que as nações vieram a existir. Nesse tempo, porém, todos de Seu povo que tiverem o nome escrito no livro serão salvos.", referencia: "Daniel 12:1" },
      perguntas: [
        { id: "d1q1", pergunta: "Segundo Daniel 12:1, citado no texto, quem se levantará como o grande príncipe que guarda o povo de Deus?", opcoes: ["Gabriel", "Miguel", "Rafael", "Moisés"], correta: 1, explicacao: "Daniel 12:1 diz que Miguel, o grande príncipe que guarda Seu povo, se levantará." },
        { id: "d1q2", pergunta: "Julgue: segundo o texto, depois que as palavras de Apocalipse 22:11 forem proclamadas, ainda haverá tempo para os injustos mudarem de vida.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "O texto diz que, quando essas palavras forem proclamadas, 'a decisão de toda humanidade estará selada'." },
        { id: "d1q3", tipo: "ordenar", pergunta: "Coloque em ordem os acontecimentos descritos no texto:", itens: ["Apocalipse 22:11 é proclamado", "Jesus conclui Sua mediação", "Satanás fica livre para perseguir", "Tempo de angústia como nunca houve"], explicacao: "Quando Apocalipse 22:11 for proclamado, a decisão de todos estará selada. Jesus concluirá a mediação, Satanás ficará livre para perseguir os fiéis, e então virá o tempo de angústia de Daniel 12:1." },
        { id: "d1q4", pergunta: "Segundo o texto, o que os fiéis remanescentes não profanarão, mesmo no tempo de prova?", opcoes: ["O sábado nem a fé em Jesus", "As tradições de sua família", "O calendário civil", "Os costumes antigos de sua cultura"], correta: 0, explicacao: "Esse grupo não profanará o sábado nem a fé em Jesus Cristo." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-11-29",
      titulo: "ROTEIRO ORIGINAL",
      conteudo: "A expressão 'angústia de Jacó' está ligada a uma amarga experiência que o patriarca passou antes de se encontrar com seu irmão, Esaú, que vinha em sua direção com um exército poderoso. Jacó não sabia, mas o verdadeiro livramento chegou antes desse encontro. Leia em sua Bíblia os textos de Apocalipse 22:11, Gênesis 32:24-30 e Salmo 91:1-8 para relembrar a relação desse episódio com o tempo do fim. Depois, responda às perguntas a seguir:\n\nQuem está falando em Apocalipse 22:11? Quem é o público?\n\nEm sua opinião, por que João deu essa descrição de acontecimentos, mesmo não podendo compreender totalmente o que ele estava vendo?\n\nO que Jacó acreditava que o anjo poderia fazer por ele? Lembre-se de uma ocasião em sua vida em que você 'lutou com Deus'.\n\nO Salmo 91 sugere que Deus sempre protegerá Seu povo da dor e do sofrimento. Isso é verdade? Davi experimentou isso em sua vida?\n\nQue garantia sobre o tempo de angústia você pode extrair desses versos?",
      versiculoChave: { texto: "Nessa época, Miguel, o grande príncipe que guarda Seu povo, se levantará. Haverá um tempo de angústia como nunca houve desde que as nações vieram a existir. Nesse tempo, porém, todos de Seu povo que tiverem o nome escrito no livro serão salvos.", referencia: "Daniel 12:1" },
      perguntas: [
        { id: "d2q1", pergunta: "A que experiência do patriarca Jacó a expressão 'angústia de Jacó' está ligada, segundo o texto?", opcoes: ["À fome que passou com a família no Egito", "À aflição antes de reencontrar Esaú", "À perda de seu rebanho", "Ao conflito com seu sogro Labão"], correta: 1, explicacao: "A expressão está ligada à amarga experiência que Jacó passou antes de se encontrar com seu irmão Esaú, que vinha com um exército poderoso." },
        { id: "d2q2", pergunta: "Quais textos bíblicos o Roteiro Original de hoje pede para ler sobre o tempo do fim?", opcoes: ["Apocalipse 22:11, Gênesis 32:24-30 e Salmo 91:1-8", "Êxodo 20 e Levítico 23", "Mateus 24:1-14, Lucas 21:5-28 e Apocalipse 13:1-18", "Isaías 53 e Salmo 22"], correta: 0, explicacao: "O texto pede a leitura de Apocalipse 22:11, Gênesis 32:24-30 e Salmo 91:1-8." },
        { id: "d2q3", pergunta: "Julgue: segundo o texto, Jacó já sabia, antes do encontro com Esaú, que o verdadeiro livramento já havia chegado.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "O texto diz que 'Jacó não sabia, mas o verdadeiro livramento chegou antes desse encontro' — ele não tinha certeza disso." },
        { id: "d2q4", pergunta: "Segundo o texto, o que o Salmo 91 sugere sobre a proteção de Deus?", opcoes: ["Que Deus sempre protegerá Seu povo da dor", "Que Deus abandona Seu povo", "Que a proteção de Deus depende da riqueza da pessoa", "Que apenas os sacerdotes recebem proteção divina"], correta: 0, explicacao: "O Salmo 91 sugere que Deus sempre protegerá Seu povo da dor e do sofrimento." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-11-30",
      titulo: "ZOOM",
      conteudo: "Leia o Texto-Chave desta semana, que se encontra em Daniel 12:1. Essa é uma maravilhosa promessa para os filhos de Deus que permanecerem fiéis até o fim. Podemos contar com Miguel, 'o grande príncipe, o defensor dos filhos do povo de Deus'. Esse nome vem do hebraico Mika'el, que quer dizer, literalmente, 'quem é como Deus?'. Daniel descreve Miguel como o protetor particular do povo de Deus na batalha entre o bem e o mal.\n\nCuriosamente, 'Miguel', como o nome de um ser celestial, ocorre apenas nas passagens apocalípticas (Dn 10:13,21; Dn 12:1; Jd 1:9; Ap 12:7), e em casos em que Cristo está em conflito direto com Satanás. O nome em hebraico é tanto uma pergunta quanto um desafio. Tendo em vista a rebelião de Satanás de se colocar no trono de Deus e ser 'semelhante ao Altíssimo', o nome Miguel é tão apropriado para Aquele que assumiu a tarefa de vindicar o caráter e refutar as pretensões de Satanás (CBA, vol. 4, p. 947).\n\nJesus Cristo está agora intercedendo por nós junto a Deus no Céu. Ele é o nosso defensor. Quando Sua obra de intercessão no Céu for concluída, Ele Se 'levantará' para Se preparar para voltar à Terra, salvar Seu povo, e destruir os ímpios.\n\nComo você se sente ao saber que um Ser tão poderoso luta e intercede por você? Mais do que isso: Ele salva, liberta e lhe dá a oportunidade de viver uma nova e feliz história.",
      versiculoChave: { texto: "O nome Miguel é tão apropriado para Aquele que assumiu a tarefa de vindicar o caráter e refutar as pretensões de Satanás.", referencia: "Comentário Bíblico Adventista, vol. 4, p. 947" },
      perguntas: [
        { id: "d3q1", pergunta: "O que o nome Miguel significa, literalmente, em hebraico, segundo o texto?", opcoes: ["'Deus é meu pastor'", "'Quem é como Deus?'", "'Príncipe da paz'", "'Luz do mundo'"], correta: 1, explicacao: "O nome vem do hebraico Mika'el, que quer dizer, literalmente, 'quem é como Deus?'" },
        { id: "d3q2", pergunta: "Segundo o texto, em que tipo de passagens bíblicas o nome 'Miguel' ocorre?", opcoes: ["Apenas nos Evangelhos", "Apenas nas cartas do apóstolo Paulo", "Nas passagens apocalípticas", "Apenas nos Salmos"], correta: 2, explicacao: "'Miguel' ocorre apenas nas passagens apocalípticas (Dn 10:13,21; Dn 12:1; Jd 1:9; Ap 12:7)." },
        { id: "d3q3", pergunta: "Julgue: segundo o texto, Miguel é descrito como o protetor particular do povo de Deus na batalha entre o bem e o mal.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "Daniel descreve Miguel como o protetor particular do povo de Deus na batalha entre o bem e o mal." },
        { id: "d3q4", pergunta: "Segundo o texto, o que Jesus Cristo está fazendo agora, junto a Deus no Céu?", opcoes: ["Aguardando em silêncio e passivamente o fim do mundo", "Intercedendo por nós como nosso defensor", "Reunindo um novo exército celestial", "Julgando apenas os anjos caídos"], correta: 1, explicacao: "Jesus Cristo está agora intercedendo por nós junto a Deus no Céu. Ele é o nosso defensor." }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-12-01",
      titulo: "MAKING OF",
      conteudo: "Todos os cristãos deveriam conhecer profundamente os livros de Daniel e de Apocalipse. As profecias reveladas neles ligam o passado, o presente e o futuro, mostrando o plano da salvação em tempo real.\n\nNeste momento, um julgamento está acontecendo no Céu. Quando essa obra for concluída, Jesus deixará o santuário e Se dirigirá à Terra para buscar os fiéis filhos de Deus.\n\nMultidões iradas acreditarão que os guardadores do sábado são os responsáveis pelos castigos divinos que cairão sobre a Terra.\n\nA incerteza quanto à questão se todos os nossos pecados estão perdoados será mais difícil de enfrentar do que os próprios eventos do tempo do fim. Por isso, a expressão 'angústia' é aplicada a esse período.\n\nSomente os que estudaram cuidadosamente as Escrituras e receberam o amor pela verdade serão protegidos do poderoso engano que tornará o mundo cativo. Pelo testemunho da Bíblia, detectarão o enganador em seu disfarce (Os Resgatados, p. 310).\n\nO tempo de angústia será um período difícil porque o Espírito será retirado da Terra e Satanás perseguirá violentamente os fiéis. No entanto, assim como Jacó, o povo de Deus se apegará às promessas divinas e anjos serão enviados para livrá-lo.\n\nSatanás se apresentará como Cristo. 'As pessoas se prostrarão diante dele. Ele erguerá as mãos e as abençoará. Sua voz será suave, mas cheia de melodia. Em tom compassivo, apresentará algumas das mesmas verdades celestiais que o Salvador proferiu. Curará doenças e então, na suposta personificação de Cristo, afirmará ter mudado o sábado para o domingo' (Os Resgatados, p. 315).",
      versiculoChave: { texto: "Nessa época, Miguel, o grande príncipe que guarda Seu povo, se levantará. Haverá um tempo de angústia como nunca houve desde que as nações vieram a existir. Nesse tempo, porém, todos de Seu povo que tiverem o nome escrito no livro serão salvos.", referencia: "Daniel 12:1" },
      perguntas: [
        { id: "d4q1", pergunta: "Segundo o texto, o que todos os cristãos deveriam conhecer profundamente?", opcoes: ["Os livros de Daniel e de Apocalipse", "Apenas os Evangelhos", "Os livros históricos do Antigo Testamento", "As cartas pastorais de Paulo"], correta: 0, explicacao: "Todos os cristãos deveriam conhecer profundamente os livros de Daniel e de Apocalipse." },
        { id: "d4q2", pergunta: "Julgue: segundo o texto, multidões iradas culparão os guardadores do sábado pelos castigos divinos que cairão sobre a Terra.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "'Multidões iradas acreditarão que os guardadores do sábado são os responsáveis pelos castigos divinos que cairão sobre a Terra.'" },
        { id: "d4q3", pergunta: "Segundo o texto, por que a expressão 'angústia' é aplicada a esse período do tempo do fim?", opcoes: ["Por causa apenas da fome espalhada pelo mundo", "Pela incerteza sobre o perdão dos pecados", "Por causa da falta de água potável", "Por causa do frio extremo"], correta: 1, explicacao: "A incerteza quanto ao perdão dos pecados será mais difícil de enfrentar do que os próprios eventos do tempo do fim; por isso a expressão 'angústia' é aplicada a esse período." },
        { id: "d4q4", tipo: "pares", pergunta: "Ligue cada um ao que o texto diz que vai acontecer:", pares: [["Satanás", "Vai se passar por Cristo"], ["Anjos", "Enviados para livrar o povo"], ["Jesus", "Deixará o santuário"], ["O Espírito", "Será retirado da Terra"]], explicacao: "Satanás se apresentará como Cristo e dirá ter mudado o sábado. Quando o julgamento terminar, Jesus deixará o santuário; o Espírito será retirado da Terra; mas anjos serão enviados para livrar o povo de Deus." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-12-02",
      titulo: "EXTRAS",
      conteudo: "Leia e marque em sua Bíblia os Textos adicionais desta semana. Dois deles são poderosas promessas divinas e o outro é um apelo para que tenhamos foco nas coisas certas em nossa vida. Qual deles é novo para você?\n\nAntes da segunda vinda de Jesus, os que permanecerem fiéis a Deus – especialmente com relação ao sábado – enfrentarão terrível perseguição. No entanto, Apocalipse 12:11 diz que eles não ficarão preocupados com a morte. Estarão preocupados em viver com Jesus Cristo para sempre.\n\nPara que tenhamos esse tipo de reação, precisamos desenvolver hoje uma fé tão grande em Deus que, no tempo de angústia, tenhamos condições de suportar o cansaço, a demora e a fome. Veja o que Ellen White disse a respeito: 'Aqueles que exercem pouca fé hoje correm o maior risco de cair sob o poder dos enganos de Satanás. E mesmo se suportarem a prova, serão afundados em angústia mais profunda porque não desenvolveram o hábito de confiar em Deus. Devemos obter agora a experiência de confiar em Suas promessas' (Os Resgatados, p. 313). Então, amigo, aproveite para se preparar hoje!\n\nTextos adicionais: Salmo 34:7; Deuteronômio 6:5; Salmo 30:5",
      versiculoChave: { texto: "E eles o venceram pelo sangue do Cordeiro e pela palavra do testemunho que deram; e não amaram a própria vida a ponto de recusarem a morte.", referencia: "Apocalipse 12:11" },
      perguntas: [
        { id: "d5q1", pergunta: "Segundo Apocalipse 12:11, citado no texto, com que os fiéis não se preocuparão diante da perseguição?", opcoes: ["Com a fome", "Com a morte", "Com o frio", "Com a solidão"], correta: 1, explicacao: "Apocalipse 12:11 diz que eles não ficarão preocupados com a morte, mas em viver com Jesus Cristo para sempre." },
        { id: "d5q2", pergunta: "Segundo a citação de Ellen White (Os Resgatados, p. 313), quem corre o maior risco de cair sob o poder dos enganos de Satanás?", opcoes: ["Aqueles que exercem pouca fé hoje", "Apenas os que nunca frequentaram a igreja", "Apenas os líderes religiosos", "Aqueles que vivem em grandes cidades"], correta: 0, explicacao: "'Aqueles que exercem pouca fé hoje correm o maior risco de cair sob o poder dos enganos de Satanás.'" },
        { id: "d5q3", pergunta: "Julgue: segundo o texto, mesmo quem suportar a prova do tempo do fim, mas não desenvolveu o hábito de confiar em Deus, será afundado em angústia mais profunda.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto diz que, mesmo suportando a prova, 'serão afundados em angústia mais profunda porque não desenvolveram o hábito de confiar em Deus'." },
        { id: "d5q4", tipo: "digitar", pergunta: "Complete: \"E eles o venceram pelo sangue do ___ e pela palavra do testemunho que deram\" (Apocalipse 12:11)", resposta: "Cordeiro", explicacao: "Os fiéis vencem pelo sangue do Cordeiro — Jesus — e pelo testemunho. Por isso não temem a morte: querem viver com Cristo para sempre." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-12-03",
      titulo: "PANORÂMICA",
      conteudo: "Aviso de spoiler! É assim que deveriam começar os capítulos 39 e 40 do livro Os Resgatados (O Grande Conflito na linguagem de hoje). Enquanto acompanhamos o desenrolar dos acontecimentos, a tensão aumenta cada vez mais. A situação chegará a um ponto tão complicado que parecerá que os 'bonzinhos' vão morrer no final.\n\nLeia este texto e tente imaginar uma cena: 'Aos olhos humanos, parecerá que o povo de Deus está prestes a morrer por sua fé, assim como os mártires antes deles. Será um tempo de terrível agonia. Os ímpios zombarão: Onde está agora a sua fé? Por que Deus não os livra de nossas mãos se realmente são o povo Dele?' (Os Resgatados, p. 317).\n\nNa sequência, o texto diz que Deus vai posicionar anjos ao redor de Seus filhos para protegê-los. As armas levantadas contra eles vão esbarrar em palha. E, quando parecer que não há mais saída... ATENÇÃO: A continuação da história está na lição da próxima semana. Não deixe de estudar! Você também vai saber por que o título do último livro da série Conflito se chama Os Resgatados. Até lá!\n\n'Quando a terceira mensagem angélica terminar, o povo de Deus terá concluído sua obra. Os fiéis receberam a chuva serôdia e estão preparados para os tempos difíceis à sua frente. A prova final chegou ao mundo, e todos aqueles que se mostraram leais à lei divina receberam o selo do Deus vivo. Então Jesus termina Seu ministério no santuário celestial e com alta voz exclama: Feito está!'",
      versiculoChave: { texto: "Aos olhos humanos, parecerá que o povo de Deus está prestes a morrer por sua fé, assim como os mártires antes deles. Será um tempo de terrível agonia.", referencia: "Os Resgatados, p. 317" },
      perguntas: [
        { id: "d6q1", tipo: "multipla", pergunta: "Segundo a citação final do dia, o que é verdade sobre o povo de Deus quando a terceira mensagem terminar? (marque todas)", opcoes: ["Recebeu a chuva serôdia", "Ainda não concluiu sua obra", "Recebeu o selo do Deus vivo por ser leal", "Ainda aguarda a prova final"], corretas: [0, 2], explicacao: "Quando a terceira mensagem terminar, o povo de Deus terá concluído sua obra, recebido a chuva serôdia e, por ser leal à lei divina, o selo do Deus vivo. A prova final já terá chegado." },
        { id: "d6q2", pergunta: "Segundo a citação de Os Resgatados (p. 317), o que os ímpios zombarão dizendo ao povo de Deus?", opcoes: ["'Onde está agora a sua fé?'", "'Vocês venceram!'", "'Perdoem-nos!'", "'Vamos nos juntar a vocês agora!'"], correta: 0, explicacao: "'Os ímpios zombarão: Onde está agora a sua fé? Por que Deus não os livra de nossas mãos...?'" },
        { id: "d6q3", pergunta: "Julgue: segundo o texto, Deus vai posicionar anjos ao redor de Seus filhos para protegê-los, e as armas levantadas contra eles esbarrarão em palha.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto diz exatamente isso: Deus posicionará anjos ao redor de Seus filhos, e as armas vão esbarrar em palha." },
        { id: "d6q4", pergunta: "Segundo a citação final do dia, o que Jesus exclama em alta voz ao terminar Seu ministério no santuário celestial?", opcoes: ["'Vem, Senhor Jesus!'", "'Feito está!'", "'Eis que venho em breve!'", "'Consumado é!'"], correta: 1, explicacao: "'Jesus termina Seu ministério no santuário celestial e com alta voz exclama: Feito está!'" }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-12-04",
      titulo: "OFF",
      conteudo: "O tempo de angústia será um período difícil para todos os seres humanos vivos na ocasião. Além de Satanás exercer ao máximo sua crueldade, os anjos de Deus derramarão pragas sobre a Terra que assolarão o mundo inteiro.\n\nEm meio ao caos mundial, um pequeno grupo de fiéis corajosos se recusará a ceder às pressões de Satanás. A santidade do sábado será a questão mais importante como demonstração de fidelidade a Deus, mas certamente não será a única. Os líderes religiosos culparão esse pequeno grupo de ser o responsável pelo sofrimento e confusão no mundo. Esse grupo será rigorosamente perseguido e alguns serão presos.\n\nApesar da perseguição, do sofrimento e das privações, esse grupo sobreviverá. Seu sacrifício influenciará milhares a aceitarem Jesus Cristo como Senhor e Salvador de sua vida. Não há como amenizar as terríveis cenas na Terra, mas nossa esperança deve estar firmemente enraizada nas seguintes palavras de Jesus: 'Eis que venho em breve! A Minha recompensa está comigo, e Eu retribuirei a cada um de acordo com o que fez' (Ap 22:12).\n\nVocê está preparado para enfrentar o tempo de angústia?\n\n'Se paciência é algo de valor, deve durar até o fim do tempo. E uma fé viva perseverará em meio à mais ameaçadora tempestade.'\nGANDHI\n\n'O que a lagarta chama de fim do mundo, o mestre chama de borboleta.'\nRICHARD BACH\n\nPensar no fim do mundo provoca que sentimento em você? De que forma você pode se preparar hoje para os últimos acontecimentos? Lembre-se de que Deus nunca desamparou Seus filhos fiéis. E desta vez não será diferente. Imagine como será o encontro de Adão com o seu Criador. Acesse e leia os capítulos 39 e 40 do livro Os Resgatados.",
      versiculoChave: { texto: "Eis que venho em breve! A Minha recompensa está comigo, e Eu retribuirei a cada um de acordo com o que fez.", referencia: "Apocalipse 22:12" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo o texto, além da crueldade de Satanás, o que os anjos de Deus derramarão sobre a Terra no tempo de angústia?", opcoes: ["Bênçãos materiais para todos os povos", "Pragas sobre o mundo inteiro", "Chuvas abundantes", "Riquezas guardadas para os fiéis"], correta: 1, explicacao: "Os anjos de Deus derramarão pragas sobre a Terra que assolarão o mundo inteiro." },
        { id: "d7q2", tipo: "relampago", pergunta: "Rodada relâmpago: revise a semana!", itens: [{ texto: "O nome Miguel quer dizer 'quem é como Deus?'.", verdadeiro: true }, { texto: "Os fiéis do fim são comparados a Elias no monte Carmelo.", verdadeiro: false }, { texto: "Satanás vai se apresentar como Cristo e curar doenças.", verdadeiro: true }, { texto: "Pelo texto, o sábado será a única questão de fidelidade.", verdadeiro: false }, { texto: "Hoje Jesus intercede por nós no Céu como nosso defensor.", verdadeiro: true }], explicacao: "Os fiéis do fim são comparados a Jacó, que lutou com o anjo, e não a Elias. E o sábado será a questão mais importante de fidelidade, mas não a única." },
        { id: "d7q3", pergunta: "Segundo Apocalipse 22:12, citado no texto, o que Jesus promete fazer quando vier?", opcoes: ["Ignorar as obras de cada um no juízo final", "Retribuir a cada um conforme o que fez", "Esquecer o passado de todos", "Adiar o juízo indefinidamente"], correta: 1, explicacao: "'Eis que venho em breve! A Minha recompensa está comigo, e Eu retribuirei a cada um de acordo com o que fez' (Ap 22:12)." },
        { id: "d7q4", pergunta: "Segundo Richard Bach, citado no texto, o que o mestre chama do que a lagarta chama de 'fim do mundo'?", opcoes: ["Um pesadelo", "Borboleta", "Descanso eterno", "Uma nova lagarta"], correta: 1, explicacao: "'O que a lagarta chama de fim do mundo, o mestre chama de borboleta' (Richard Bach)." }
      ]
    }
  ]
};
