// Primeira lição da temporada "Livro Aberto" (4º trimestre de 2026) — NÃO é
// continuação da temporada "Provado pelo Fogo" (data.ts..data5.ts): é o
// começo de uma nova, por isso o export tem prefixo próprio (LICAO_LA_*) em
// vez de seguir a numeração 1..13 que já está em uso pela temporada anterior.
export const LICAO_LA_1 = {
  titulo: "Lição 1 - Conhecendo a Si Mesmo (26 de setembro a 2 de outubro)",
  semana: "2026-W39",
  trimestre: "Livro Aberto",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-09-26",
      titulo: "TEASER",
      conteudo: "Geralmente nos deparamos com uma barreira em nosso crescimento apesar dos anos que passamos repetindo os padrões de atividades, educação e comportamento cristãos. Essa barreira é o resultado de hábitos emocionais profundamente enraizados de nosso passado. Essa barreira nos impede de saborear a doce experiência de uma vida madura e autêntica em Cristo.\n\nPoucos de nós dedicam tempo para refletir sobre o profundo (e sutil) impacto das influências exteriores em nossas decisões, palavras e sentimentos. Sem estar ciente de quem somos e de que modo as circunstâncias nos afetam, somos incapazes de lidar com a exposição às pressões e forças que operam contra nós. Acabamos vivendo a vida de outra pessoa, as expectativas de outros.\n\nComo um barco sem remo ou leme, somos jogados de um lado para o outro e viramos para qualquer lado que o vento da aprovação nos levar.\n\nApenas no momento em que nos conhecermos e descobrirmos em quem estamos nos tornando, por meio da obra de Cristo em nós, seremos capazes de transformar nossa vida em uma oferta aos nossos familiares, amigos, colegas de trabalho e membros da comunidade.\n\nDesenvolver um crescimento e uma espiritualidade autênticos requer planejamento intencional e propositual.",
      versiculoChave: { texto: "Você vem a mim com uma espada, uma lança e um dardo, mas eu vou enfrentá-lo em nome do Senhor dos Exércitos, o Deus dos exércitos de Israel, que você desafiou.", referencia: "1 Samuel 17:45" },
      perguntas: [
        { id: "d1q1", pergunta: "Segundo o texto, o que forma a barreira que impede um crescimento espiritual maduro?", opcoes: ["Falta de tempo livre para atividades", "A opinião dos pastores e líderes", "Hábitos emocionais enraizados no passado", "Problemas financeiros da família"], correta: 2, explicacao: "A barreira vem de hábitos emocionais profundamente enraizados do nosso passado." },
        { id: "d1q2", pergunta: "O texto diz que 'poucos de nós dedicam tempo' para refletir sobre algo específico. Sobre o quê?", opcoes: ["Sobre os planos que temos para o futuro distante", "Sobre os erros e falhas cometidos pelos outros", "Sobre a história e fundação da igreja local", "Sobre o impacto das influências externas em nós"], correta: 3, explicacao: "Poucos refletem sobre o impacto profundo e sutil das influências externas em suas decisões, palavras e sentimentos." },
        { id: "d1q3", pergunta: "A que o texto compara quem vive sem se conhecer nem entender como as circunstâncias o afetam?", opcoes: ["A um barco sem remo ou leme", "A uma casa sem fundação", "A uma árvore sem frutos", "A um exército sem general"], correta: 0, explicacao: "Somos comparados a um barco sem remo ou leme, jogado de um lado a outro pelo vento da aprovação." },
        { id: "d1q4", pergunta: "O que o texto diz que é necessário para um crescimento e espiritualidade autênticos?", opcoes: ["Isolamento social de longa duração", "Planejamento intencional e propositual da vida", "Apenas ter boa vontade no coração", "Sorte e boas oportunidades externas"], correta: 1, explicacao: "Requer planejamento intencional e propositual." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-09-27",
      titulo: "ROTEIRO ORIGINAL",
      conteudo: "Davi é um dos personagens mais lembrados da Bíblia por causa de sua coragem diante de situações difíceis e por sua ousadia em defender o nome de Deus. Temos muito o que aprender com a experiência dele, que foi chamado 'o homem segundo o coração de Deus'. Leia em sua Bíblia o texto de 1 Samuel 17:26-45 e depois pense nas perguntas a seguir:\n\nQue objeções, reclamações e insinuações Davi ouviu de sua família (v. 28), de Saul, o rei (v. 33, 38), e de Golias, o provocador (v. 41-45)?\n\nDavi alcançou um nível bastante elevado de diferenciação. Ele sabia quem era e não dependia da opinião pública nem tinha necessidade de aprovação. De que maneiras Davi permaneceu firme pelo que pensava, não permitindo que a pressão e a ansiedade dos outros o controlassem?\n\nNo verso 45, Davi exclama confiantemente: 'Você vem a mim com uma espada, uma lança e um dardo, mas eu vou enfrentá-lo em nome do Senhor dos Exércitos, o Deus dos exércitos de Israel, a quem você desafiou.' Por que ele sentia tanta confiança na ajuda de Deus?",
      versiculoChave: { texto: "Conheço a tua presunção e a maldade de teu coração; foi para ver a peleja que desceste.", referencia: "1 Samuel 17:28" },
      perguntas: [
        { id: "d2q1", pergunta: "Qual passagem bíblica o Roteiro Original de hoje pede para você ler?", opcoes: ["1 Samuel 16:1-13", "1 Samuel 17:26-45", "2 Samuel 7:1-17", "Salmo 23"], correta: 1, explicacao: "O texto de hoje pede a leitura de 1 Samuel 17:26-45." },
        { id: "d2q2", pergunta: "Segundo o texto, o que caracteriza uma pessoa que, como Davi, alcançou um alto nível de diferenciação emocional?", opcoes: ["Ela evita todo tipo de conflito e discussão", "Ela busca aprovação constante das pessoas ao redor", "Ela sabe quem é e não depende da opinião pública", "Ela concorda com todos só para manter a paz"], correta: 2, explicacao: "Davi sabia quem era e não dependia da opinião pública nem tinha necessidade de aprovação." },
        { id: "d2q3", pergunta: "De quem Davi ouviu objeções e insinuações, segundo o texto de hoje (v. 28, 33, 38, 41-45)?", opcoes: ["Apenas dos filisteus e dos amalequitas", "Apenas do profeta Samuel e dos sacerdotes", "Apenas dos soldados israelitas e dos oficiais", "De sua família, do rei Saul e de Golias"], correta: 3, explicacao: "Ele ouviu objeções de sua família (v. 28), de Saul (v. 33, 38) e de Golias (v. 41-45)." },
        { id: "d2q4", pergunta: "No verso 45, por que Davi exclama com tanta confiança diante de Golias?", opcoes: ["Porque ele vem em nome do Senhor dos Exércitos", "Porque ele tinha uma armadura mais forte", "Porque o exército de Israel era maior", "Porque Golias estava cansado da batalha"], correta: 0, explicacao: "Ele confiava porque vinha em nome do Senhor dos Exércitos, o Deus dos exércitos de Israel." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-09-28",
      titulo: "ZOOM",
      conteudo: "Leia o Texto-Chave desta semana, que se encontra em 1 Samuel 17:45. A Bíblia apresenta histórias importantes, que nos ajudam em nosso crescimento espiritual. Essa experiência de Davi revela o segredo de sua vitória: um relacionamento íntimo com Deus, que o ajudava a enxergar quem realmente ele era. No poder de Deus, ele se sentia capaz de fazer qualquer coisa - até mesmo derrotar o gigante filisteu.\n\nVeja de que forma o Comentário Bíblico Adventista (vol. 2, p. 578 e 579) descreve as três vitórias de Davi nesse episódio:\n\nA primeira ocorreu no momento em que ele não se deixou abalar pelo insulto de Eliabe, seu irmão mais velho. Davi recusou envolver-se numa troca insignificante de agressões verbais e mostrou que estava no controle de suas emoções. 'Se não tivesse aprendido a ter paciência com suas ovelhas, não teria sido capaz de demonstrar paciência com o irmão invejoso.'\n\nA segunda vitória foi conquistada ao Davi permanecer firme em suas crenças, mesmo diante da oposição da figura autoritária do rei. 'Sem jamais cogitar a possibilidade de uma intervenção divina, Saul plantou sementes de dúvida na mente de Davi e tentou-o a vestir sua própria armadura. Mas novamente, de maneira respeitosa, Davi conquistou a vitória sobre a dúvida apegando-se ao seu propósito inspirado pelo Céu de manter-se firme na fé e na total dependência do Senhor.'\n\nA vitória final foi a derrota pública de Golias.\n\nPense em sua vida. Há ocasiões em que você recua por medo ou age de maneira que não combina com você?",
      versiculoChave: { texto: "Você vem a mim com uma espada, uma lança e um dardo, mas eu vou enfrentá-lo em nome do Senhor dos Exércitos, o Deus dos exércitos de Israel, que você desafiou.", referencia: "1 Samuel 17:45" },
      perguntas: [
        { id: "d3q1", pergunta: "Qual foi a PRIMEIRA vitória de Davi, segundo o Comentário Bíblico Adventista?", opcoes: ["Derrotar Golias publicamente diante do exército", "Vestir a armadura pesada que Saul lhe ofereceu", "Não se abalar pelo insulto de Eliabe, seu irmão", "Recusar lutar contra o gigante filisteu"], correta: 2, explicacao: "A primeira vitória foi não se deixar abalar pelo insulto de Eliabe, seu irmão mais velho." },
        { id: "d3q2", pergunta: "O comentário liga a paciência de Davi com suas ovelhas a qual desafio posterior dele?", opcoes: ["A coragem de enfrentar Golias sozinho", "A sabedoria de recusar a armadura de Saul", "A confiança de falar diante do rei", "A paciência de suportar o irmão invejoso, Eliabe"], correta: 3, explicacao: "'Se não tivesse aprendido a ter paciência com suas ovelhas, não teria sido capaz de demonstrar paciência com o irmão invejoso' — a paciência pastoral é ligada à paciência com Eliabe." },
        { id: "d3q3", pergunta: "Qual foi a SEGUNDA vitória de Davi diante da oposição de Saul?", opcoes: ["Permanecer firme em suas crenças, apesar da dúvida de Saul", "Aceitar usar a armadura pesada oferecida pelo rei", "Desistir de lutar contra o gigante Golias", "Fugir escondido do acampamento israelita"], correta: 0, explicacao: "A segunda vitória foi permanecer firme em suas crenças, apegando-se à fé e à dependência do Senhor, apesar da dúvida que Saul tentou plantar." },
        { id: "d3q4", pergunta: "Qual foi a vitória FINAL de Davi nesse episódio?", opcoes: ["Ser coroado rei de Israel", "A derrota pública de Golias", "Ganhar a amizade de Saul", "Receber uma recompensa do povo"], correta: 1, explicacao: "A vitória final foi a derrota pública de Golias." }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-09-29",
      titulo: "MAKING OF",
      conteudo: "Características das pessoas que têm um verdadeiro relacionamento com Deus, segundo o capítulo 28 do livro Os Resgatados:\n\nCreram, foram batizadas e se levantaram para andar em novidade de vida. Pela fé em Cristo, decidiram seguir Seus passos, refletir Seu caráter e ser puras como Ele é puro.\n\nPassaram a amar as coisas que odiavam e a odiar o que antes amavam.\n\nOs orgulhosos ficaram mansos; os vaidosos e arrogantes se tornaram humildes.\n\nEstão mais interessadas em buscar o adorno interior — um caráter íntegro — do que o exterior.\n\nO relacionamento com Deus e as coisas eternas são o grande assunto de sua vida.\n\nReconhecem a Cristo como o único meio pelo qual o ser humano pode ser salvo. 'Aqueles que vivem mais perto de Jesus compreendem com maior clareza o quanto a humanidade é frágil e pecaminosa e que sua única esperança está nos méritos de um Salvador crucificado e ressurreto' (Os Resgatados, p. 240).",
      versiculoChave: { texto: "Aqueles que vivem mais perto de Jesus compreendem com maior clareza o quanto a humanidade é frágil e pecaminosa e que sua única esperança está nos méritos de um Salvador crucificado e ressurreto.", referencia: "Os Resgatados, p. 240" },
      perguntas: [
        { id: "d4q1", pergunta: "Segundo o texto de hoje, o que acontece com os orgulhosos que desenvolvem um verdadeiro relacionamento com Deus?", opcoes: ["Ficam mansos", "Tornam-se mais respeitados", "Ganham posições de liderança", "Perdem o interesse pela igreja"], correta: 0, explicacao: "Os orgulhosos ficaram mansos; os vaidosos e arrogantes se tornaram humildes." },
        { id: "d4q2", pergunta: "Julgue: segundo o texto, quem tem um verdadeiro relacionamento com Deus passa a se interessar mais pela aparência externa do que pelo caráter interior.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "É o contrário: essas pessoas buscam mais o adorno interior — um caráter íntegro — do que o exterior." },
        { id: "d4q3", pergunta: "Segundo o texto, qual é o único meio pelo qual o ser humano pode ser salvo?", opcoes: ["Suas próprias boas obras", "Sua dedicação religiosa", "Cristo", "O conhecimento bíblico acumulado"], correta: 2, explicacao: "Reconhecem a Cristo como o único meio pelo qual o ser humano pode ser salvo." },
        { id: "d4q4", pergunta: "De onde foram extraídas as informações apresentadas na seção Making Of de hoje?", opcoes: ["Do Comentário Bíblico Adventista", "De uma carta de Ellen White", "Do texto-chave da semana", "Do capítulo 28 do livro Os Resgatados"], correta: 3, explicacao: "As informações foram extraídas do capítulo 28 do livro Os Resgatados." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-09-30",
      titulo: "EXTRAS",
      conteudo: "Leia e marque em sua Bíblia os textos adicionais desta semana. Qual deles mais diretamente fala ao seu coração?\n\nPaulo incentiva os cristãos a não se conformarem com o padrão desta época, mas serem transformados. O apóstolo 'afirma que o cristão não deve reproduzir os costumes externos e passageiros deste mundo, mas ser transformado em sua natureza interior' (CBA, vol. 6, p. 678). Esse processo, que inclui tanto a separação dos costumes mundanos como a transformação interior, recebe o nome de santificação.\n\nTodos somos convidados a passarmos por uma renovação da mente. Como? Permitindo que o Espírito Santo tenha acesso e influencie nossa mente, para que reconheçamos a verdade e saibamos como viver de acordo com a vontade de Deus. Se a mente estiver renovada pelo Espírito Santo, a Palavra de Deus será interpretada corretamente. Se às vezes você tem dificuldade para entender o que a Bíblia diz, faça o teste. Afaste-se das coisas que atrapalham seu relacionamento com Deus e depois peça que o Espírito Santo o ajude a compreender o que está escrito. Você verá como sua mente se abrirá para as verdades contidas ali.\n\nTextos adicionais: Mateus 7:16; Tiago 2:14-16; Romanos 12:1,2",
      versiculoChave: { texto: "Não vos conformeis a este mundo, mas transformai-vos pela renovação da vossa mente, para que verifiqueis qual seja a boa, agradável e perfeita vontade de Deus.", referencia: "Romanos 12:2" },
      perguntas: [
        { id: "d5q1", pergunta: "Segundo o Comentário Bíblico Adventista (vol. 6, p. 678), o que o cristão não deve fazer?", opcoes: ["Estudar a Bíblia todos os dias de manhã", "Reproduzir os costumes passageiros do mundo", "Orar em público durante os cultos", "Participar ativamente da igreja local"], correta: 1, explicacao: "O cristão não deve reproduzir os costumes externos e passageiros deste mundo, mas ser transformado em sua natureza interior." },
        { id: "d5q2", pergunta: "Como é chamado o processo de separação dos costumes mundanos e transformação interior, segundo o texto?", opcoes: ["Conversão", "Batismo", "Santificação", "Justificação"], correta: 2, explicacao: "Esse processo recebe o nome de santificação." },
        { id: "d5q3", pergunta: "O que o texto sugere fazer quando você tem dificuldade para entender o que a Bíblia diz?", opcoes: ["Desistir de vez daquele trecho difícil da Bíblia", "Perguntar apenas à liderança local da igreja", "Trocar de tradução bíblica e não pensar mais nisso", "Afastar-se do que atrapalha e buscar o Espírito Santo"], correta: 3, explicacao: "O texto sugere afastar-se do que atrapalha o relacionamento com Deus e pedir que o Espírito Santo ajude a compreender." },
        { id: "d5q4", pergunta: "Qual destes é um dos 'textos adicionais' sugeridos para esta semana?", opcoes: ["Romanos 12:1,2", "João 3:16", "Salmo 23", "Apocalipse 21:4"], correta: 0, explicacao: "Os textos adicionais incluem Mateus 7:16, Tiago 2:14-16 e Romanos 12:1,2." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-10-01",
      titulo: "PANORÂMICA",
      conteudo: "Que sentimento vem à sua mente quando ouve a expressão 'reavivamento'? Apesar de ser uma palavra tão gasta, seu significado é muito simples. Tem que ver com o processo de tornar algo novamente vivo.\n\nNo capítulo 27 do livro Os Resgatados (O Grande Conflito na linguagem de hoje), Ellen White apresenta o que é o verdadeiro reavivamento e como ele pode ser percebido na vida de alguém. Separe um tempo para a leitura desse texto. Ele vai ajudá-lo a identificar a diferença entre aqueles que realmente levam a sério a vida cristã e os que apenas gostam de ostentar o título de cristãos.\n\nAqui está uma boa dica de como esse processo funciona: 'Cada passo de fé e obediência traz o crente para uma conexão mais próxima com a Luz do mundo. Os raios brilhantes do Sol da Justiça resplandecem sobre os servos de Deus, e eles devem refletir Seus raios. [...] A santidade do caráter divino será visível em Suas testemunhas' (Os Resgatados, p. 242). Sua vida está brilhando?\n\n'É pela contemplação que somos transformados (2Co 3:18). Assim como as pessoas negligenciaram os mandamentos nos quais Deus revelou perfeição e a santidade de Seu caráter, e sua mente se ligou a ensinos e teorias humanas, um declínio do viver santo dentro da igreja foi a consequência. Somente quando a lei de Deus for restaurada a sua posição de direito, um reavivamento de fé e espiritualidade autênticos poderá acontecer em meio a Seu professo povo' (Os Resgatados, p. 243).",
      versiculoChave: { texto: "E todos nós, com rosto descoberto, refletindo a glória do Senhor, somos transformados de glória em glória, na mesma imagem, como pelo Espírito do Senhor.", referencia: "2 Coríntios 3:18" },
      perguntas: [
        { id: "d6q1", pergunta: "O que significa, de forma simples, a palavra 'reavivamento', segundo o texto?", opcoes: ["Criar uma nova religião", "Aumentar o número de membros da igreja", "Tornar algo novamente vivo", "Reformar o prédio da igreja"], correta: 2, explicacao: "Reavivamento tem a ver com o processo de tornar algo novamente vivo." },
        { id: "d6q2", pergunta: "Segundo a citação do dia (Os Resgatados, p. 242), o que se torna visível nas testemunhas de Deus quando refletem os raios do Sol da Justiça?", opcoes: ["Sua fama entre as pessoas", "Seu conhecimento teológico", "Sua capacidade de pregar em público", "A santidade do caráter divino"], correta: 3, explicacao: "'A santidade do caráter divino será visível em Suas testemunhas' (Os Resgatados, p. 242)." },
        { id: "d6q3", pergunta: "Em qual capítulo do livro Os Resgatados Ellen White apresenta o verdadeiro reavivamento?", opcoes: ["Capítulo 27", "Capítulo 1", "Capítulo 28", "Capítulo 13"], correta: 0, explicacao: "O capítulo 27 do livro Os Resgatados apresenta o verdadeiro reavivamento." },
        { id: "d6q4", pergunta: "Segundo a citação do dia, por que houve um declínio do viver santo dentro da igreja?", opcoes: ["Porque a igreja cresceu rápido demais para se organizar bem", "Porque a mente das pessoas se ligou a teorias humanas", "Porque faltaram recursos financeiros para os projetos da igreja", "Porque os líderes mudaram de cidade em busca de novas oportunidades"], correta: 1, explicacao: "O declínio ocorreu porque a mente das pessoas se ligou a ensinos e teorias humanas, negligenciando os mandamentos que revelam o caráter de Deus." }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-10-02",
      titulo: "OFF",
      conteudo: "O décimo sexto presidente dos Estados Unidos da América, Abraham Lincoln, certa vez disse o seguinte: 'Você pode enganar algumas pessoas o tempo todo, e todas as pessoas por algum tempo, mas não pode enganar todas as pessoas o tempo todo.'\n\nPodemos tentar esconder quem somos conformando-nos aos padrões e aos comportamentos aceitos socialmente, que fazem com que pareçamos alguém que na realidade não somos. Mais cedo ou mais tarde, no entanto, a verdade virá à tona. A maneira como vivemos, agimos e tratamos os outros geralmente causará maior impacto na percepção das pessoas a nosso respeito (e de Cristo) do que as nossas palavras. Isso é inevitável.\n\nQue avaliação você faria de sua vida neste exato momento? Jesus disse que as pessoas serão reconhecidas por seus 'frutos' (Mt 7:16). Que tipo de frutos você está produzindo? Saborosos e atrativos? Lembre-se de que 'os seguidores de Cristo devem se tornar semelhantes a Ele - pela graça de Deus, formar um caráter em harmonia com os princípios de Sua santa lei. Essa é a santificação bíblica' (Os Resgatados, p. 239). Falando sério: que você se torne cada dia mais santo, no verdadeiro sentido da palavra, e que sua vida produza o maravilhoso fruto do Espírito!\n\n'Conhecer os outros é inteligência; conhecer a si mesmo é verdadeira sabedoria. Controlar os outros é sinal de força; controlar a si mesmo é verdadeiro poder' (Laozi).\n\nALÉM DO ESTUDO: Hoje se fala muito em Jesus e em uma espiritualidade particular, que tem a ver apenas com você e Deus. Esse pode ser considerado o verdadeiro reavivamento? A lei de Deus é exaltada e acontece uma transformação na vida? Acesse e leia o capítulo 27 do livro Os Resgatados.",
      versiculoChave: { texto: "Porque pelos seus frutos os conhecereis.", referencia: "Mateus 7:16" },
      perguntas: [
        { id: "d7q1", pergunta: "Quem disse a frase 'Você pode enganar algumas pessoas o tempo todo, e todas as pessoas por algum tempo, mas não pode enganar todas as pessoas o tempo todo'?", opcoes: ["Martinho Lutero", "Ellen White", "O apóstolo Paulo", "Abraham Lincoln"], correta: 3, explicacao: "A frase é atribuída a Abraham Lincoln, décimo sexto presidente dos EUA." },
        { id: "d7q2", pergunta: "Segundo o texto, o que geralmente causa MAIOR impacto na percepção das pessoas a nosso respeito (e de Cristo) do que nossas palavras?", opcoes: ["Como vivemos, agimos e tratamos os outros", "Nossa aparência física e as roupas que usamos", "Nossa posição social e o dinheiro que temos", "Nossos diplomas e conhecimentos religiosos"], correta: 0, explicacao: "'A maneira como vivemos, agimos e tratamos os outros geralmente causará maior impacto... do que as nossas palavras.'" },
        { id: "d7q3", pergunta: "Segundo Mateus 7:16, como as pessoas serão reconhecidas?", opcoes: ["Por seus discursos", "Por seus frutos", "Por sua aparência", "Por seus diplomas"], correta: 1, explicacao: "Jesus disse que as pessoas serão reconhecidas por seus 'frutos' (Mt 7:16)." },
        { id: "d7q4", pergunta: "Segundo a frase de Laozi citada hoje, o que é 'verdadeiro poder'?", opcoes: ["Controlar os outros", "Conhecer a si mesmo", "Controlar a si mesmo", "Ter inteligência"], correta: 2, explicacao: "'Controlar a si mesmo é verdadeiro poder' — Laozi." }
      ]
    }
  ]
};
