export const LICAO_ADULT_2 = {
  titulo: "Lição 2 - A mensagem da cruz (4 a 10 de julho)",
  semana: "2026-W27",
  trimestre: "1 e 2 Coríntios",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-07-04",
      titulo: "A mensagem da cruz",
      conteudo: "Cícero, um escritor e orador romano pagão, tinha dito ao povo romano para nem sequer pensar na cruz, de tão abominável que ela era como meio de morte.\n\nEmbora Cícero tenha morrido cerca de meio século antes de Jesus nascer, a sua declaração ilustra o desprezo com que os romanos encaravam a cruz. Era algo tão horrível que nem devia ser considerado.\n\nEm contraste, Paulo escreve: \"A mensagem da cruz... é o poder de Deus\" (1 Coríntios 1:18). Para Paulo, a cruz é o instrumento de reconciliação entre Deus e o ser humano (Efésios 2:16, Colossenses 1:20), o símbolo supremo da humildade de Jesus (Filipenses 2:8) e o lugar onde a nossa enorme dívida foi paga (Colossenses 2:14).\n\nA cruz é a resposta de Paulo aos problemas em Corinto. Não é preciso ler muito de 1 Coríntios para perceber que ele está profundamente preocupado com um grande problema: as divisões na igreja. Paulo está tão perplexo que, logo após as saudações iniciais (1 Coríntios 1:1–3) e a secção de ação de graças (1 Coríntios 1:4–9), este é o primeiro tema que ele aborda (1 Coríntios 1:10–17). Nesta semana, vamos voltar à poderosa mensagem da cruz como resposta a este problema e a outras questões em Corinto.\n\nEstude a lição desta semana para se preparar para o Sábado, 11 de Julho.",
      versiculoChave: { texto: "Pois a mensagem da cruz é loucura para os que perecem, mas para nós que somos salvos é o poder de Deus", referencia: "1 Coríntios 1:18" },
      perguntas: [
        { id: "d1q1", pergunta: "Quem foi Cícero, mencionado na introdução da lição?", opcoes: ["Um apóstolo cristão", "Um escritor e orador romano pagão", "Um imperador romano", "Um rabino judeu"], correta: 1, explicacao: "A resposta correta é: Um escritor e orador romano pagão." },
        { id: "d1q2", pergunta: "O que Cícero dizia sobre a cruz?", opcoes: ["Que era um símbolo de honra", "Que nem deveria ser pensada, de tão abominável", "Que representava a justiça romana", "Que era irrelevante"], correta: 1, explicacao: "A resposta correta é: Que nem deveria ser pensada, de tão abominável." },
        { id: "d1q3", pergunta: "Para Paulo, o que a mensagem da cruz representa?", opcoes: ["Loucura sem sentido", "O poder de Deus", "Uma tradição judaica antiga", "Um símbolo político"], correta: 1, explicacao: "A resposta correta é: O poder de Deus." },
        { id: "d1q4", pergunta: "Qual é o primeiro tema que Paulo aborda em 1 Coríntios, logo após as saudações e ação de graças?", opcoes: ["O casamento", "As divisões na igreja", "A ressurreição", "Os dons espirituais"], correta: 1, explicacao: "A resposta correta é: As divisões na igreja." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-07-05",
      titulo: "O evangelho da cruz",
      conteudo: "Paulo afirma que a mensagem da cruz é o poder de Deus para nós. Não é surpreendente que \"Jesus Cristo, e este crucificado\" seja o centro da sua pregação (1 Coríntios 2:2).\n\n1. Leia 1 Coríntios 1:17-31. Qual verdade essencial Paulo apresenta aqui?\n\nEm 1 Coríntios 1:18–31, Paulo trata do contraste entre a loucura humana e a sabedoria divina. A cruz tem o poder de revelar o pior do ser humano e o melhor de Deus. Esta secção de 1 Coríntios é introduzida pela declaração em 1 Coríntios 1:17. Como a cruz de Cristo não deve ser esvaziada do seu poder (1 Coríntios 1:17), a mensagem da cruz deve ocupar o lugar central da nossa pregação (ver também 1 Coríntios 2:2).\n\nPaulo diz que foi enviado não para batizar, mas para pregar o evangelho da cruz. Esta afirmação exige duas observações importantes. Primeiro, o verbo grego traduzido como \"enviar\" é apostellō, que tem a mesma raiz da palavra \"apóstolo\". Assim, a tarefa apostólica fundamental de Paulo era a proclamação do evangelho. Segundo, as palavras de Paulo sobre o batismo não significam que o batismo não seja importante, ou que seja menos importante do que a pregação. Ele estava, antes, a repreender aqueles que davam demasiada importância a quem realizava o batismo, em vez de se concentrarem em Aquele em quem foram batizados, Jesus.\n\nAo falar de \"sabedoria de palavras\" (1 Coríntios 1:17), Paulo não está a dizer que discursos eloquentes sejam maus em si mesmos. O ponto é que a sabedoria humana não deve obscurecer a mensagem da cruz. Esta expressão refere-se à retórica greco-romana. Em Atenas, Paulo usou lógica, ciência e filosofia, mas isso produziu poucos frutos. Por isso, \"decidiu seguir outro plano de trabalho em Corinto nos seus esforços para prender a atenção dos descuidados e indiferentes. Ele decidiu evitar argumentos e discussões elaboradas e 'não saber nada' entre os coríntios 'senão Jesus Cristo, e este crucificado'.\" — Ellen G. White, Atos dos Apóstolos, p. 155.\n\nDe que maneiras discursos elaborados podem obscurecer a mensagem da cruz? Por que a proclamação de \"Jesus Cristo, e este, crucificado\" produziu mais frutos em Corinto do que lógica, ciência e filosofia em Atenas? Ainda assim, há momentos em que lógica, filosofia e proclamação do evangelho se complementam?",
      versiculoChave: { texto: "Pois a mensagem da cruz é loucura para os que perecem, mas para nós que somos salvos é o poder de Deus", referencia: "1 Coríntios 1:18" },
      perguntas: [
        { id: "d2q1", pergunta: "Segundo o texto, o que ocupa o centro da pregação de Paulo?", opcoes: ["A lei de Moisés", "\"Jesus Cristo, e este crucificado\"", "A sabedoria grega", "Os milagres de Jesus"], correta: 1, explicacao: "A resposta correta é: \"Jesus Cristo, e este crucificado\"." },
        { id: "d2q2", pergunta: "O verbo grego \"apostellō\", usado por Paulo, está relacionado com qual palavra?", opcoes: ["\"Apóstolo\"", "\"Apocalipse\"", "\"Apologia\"", "\"Apostasia\""], correta: 0, explicacao: "A resposta correta é: \"Apóstolo\"." },
        { id: "d2q3", pergunta: "Ao falar de \"sabedoria de palavras\", o que Paulo quis dizer?", opcoes: ["Que discursos eloquentes são sempre maus", "Que a sabedoria humana não deve obscurecer a mensagem da cruz", "Que só filósofos podem pregar", "Que a lógica deve substituir a fé"], correta: 1, explicacao: "A resposta correta é: Que a sabedoria humana não deve obscurecer a mensagem da cruz." },
        { id: "d2q4", pergunta: "Em qual cidade Paulo usou lógica, ciência e filosofia, produzindo poucos frutos?", opcoes: ["Corinto", "Atenas", "Éfeso", "Roma"], correta: 1, explicacao: "A resposta correta é: Atenas." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-07-06",
      titulo: "Loucura para os que se perdem",
      conteudo: "Ao contrastar a loucura humana com a sabedoria divina, Paulo afirma que a \"mensagem da cruz é loucura para os que estão a perecer\" (1 Coríntios 1:18). Esta é a primeira de seis referências à loucura ou ao termo \"louco\" em 1 Coríntios 1:18–31.\n\n2. Leia 1 Coríntios 1:20, 21, 23, 25, 27. Como essas referências à \"loucura\" ajudam a entender o que Paulo quis dizer ao afirmar que a mensagem da cruz é \"loucura para os que se perdem\"?\n\nA palavra grega para \"loucura\" é mōria. Esta palavra ocorre apenas cinco vezes no Novo Testamento, todas em 1 Coríntios (1 Coríntios 1:18, 21, 23; 1 Coríntios 2:14; 1 Coríntios 3:19). Além de mōria, outras palavras da mesma família aparecem numerosas vezes no Novo Testamento.\n\nA referência à \"loucura\" em 1 Coríntios 1:18, 23 não tem como objetivo menosprezar a capacidade intelectual dos coríntios, mas sim chamar a atenção para a sua recusa em considerar a verdade do evangelho. Como resultado, Paulo também teve de confrontar comportamentos imorais e pensamentos incorretos, falta de discernimento e até rebelião contra Deus.\n\nPense na situação de Paulo nesta cidade. Ele chega a um lugar que se orgulha do seu suposto conhecimento, sabedoria e sofisticação cultural. E, nesse contexto, fala de um judeu da Galileia, Jesus de Nazaré, que foi crucificado pelos romanos e depois ressuscitou — tudo isso para pagar não apenas os seus pecados, mas os pecados do mundo inteiro. Este homem está a falar a sério? De que estava ele a falar? Não se tratava de um novo conceito filosófico profundo que pudesse ser analisado com ferramentas filosóficas; parecia loucura, absurdo, algo que qualquer coríntio culto e inteligente não poderia levar a sério.\n\nE, tão \"louca\" quanto a mensagem de Paulo soava aos pagãos, para muitos judeus a mensagem da cruz soava ainda pior. Que judeu estaria à espera de um Messias executado por Roma? O Messias deveria derrotar os romanos, não ser crucificado por eles.\n\nAssim, desde o início, Paulo tinha muitos obstáculos em Corinto. E, ainda assim, apesar de tudo isso, almas — judeus e gentios — foram ganhas para o evangelho.\n\nA mensagem aqui é: independentemente da oposição que enfrentamos, Deus tem pessoas que estão abertas para ouvir a verdade. Devemos estar prontos para ser usados por Ele para alcançar essas pessoas onde quer que estejam, mesmo em lugares hoje tão maus como Corinto era, ou até piores.",
      versiculoChave: { texto: "Pois a mensagem da cruz é loucura para os que perecem, mas para nós que somos salvos é o poder de Deus", referencia: "1 Coríntios 1:18" },
      perguntas: [
        { id: "d3q1", pergunta: "Qual é a palavra grega para \"loucura\" usada por Paulo?", opcoes: ["Sophia", "Mōria", "Charis", "Logos"], correta: 1, explicacao: "A resposta correta é: Mōria." },
        { id: "d3q2", pergunta: "Em quantas passagens do Novo Testamento essa palavra grega ocorre?", opcoes: ["Duas", "Cinco, todas em 1 Coríntios", "Dez", "Vinte"], correta: 1, explicacao: "A resposta correta é: Cinco, todas em 1 Coríntios." },
        { id: "d3q3", pergunta: "Por que a mensagem da cruz parecia loucura aos gregos cultos de Corinto?", opcoes: ["Porque não conheciam a filosofia", "Porque falar de um crucificado ressuscitado soava absurdo para sua sofisticação cultural", "Porque não tinham interesse em religião", "Porque já acreditavam em Jesus"], correta: 1, explicacao: "A resposta correta é: Porque falar de um crucificado ressuscitado soava absurdo para sua sofisticação cultural." },
        { id: "d3q4", pergunta: "Que tipo de Messias os judeus esperavam?", opcoes: ["Um Messias sofredor e humilde", "Um Messias que derrotasse os romanos", "Um Messias filósofo", "Um Messias comerciante"], correta: 1, explicacao: "A resposta correta é: Um Messias que derrotasse os romanos." }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-07-07",
      titulo: "Poder para os que são salvos",
      conteudo: "A mensagem de 1 Coríntios 1:18 é demasiado clara para que alguém perca o seu sentido. O que a cruz significa depende da forma como cada pessoa a vê. Ela é loucura para aqueles que estão em rebelião contra Deus, mas é poder para aqueles que desejam a Sua salvação.\n\n3. Leia Colossenses 1:20 e 1 Pedro 2:24. O que Jesus realizou por nós na cruz?\n\nComo já vimos, ao pregar o evangelho, é preciso evitar \"palavras de sabedoria eloquente, para que a cruz de Cristo não seja esvaziada do seu poder\" (1 Coríntios 1:17). À luz de 1 Coríntios 1:17, torna-se mais fácil compreender por que o oposto da loucura não é a sabedoria humana, mas sim o poder de Deus (1 Coríntios 1:18). A cruz, que é tão contrária à sabedoria humana, revela o quão insensata essa sabedoria realmente é.\n\nO texto grego de 1 Coríntios 1:18 sugere que \"os que estão a perecer\" estão a receber o resultado das suas próprias ações. O texto pode ser entendido assim: \"Pois a mensagem da cruz é loucura para aqueles que estão a destruir-se a si mesmos.\" O verbo grego apollymi (\"perecer\") também pode significar \"destruir\" (João 10:10). De facto, apollymi é traduzido como \"destruir\" em 1 Coríntios 1:19.\n\nO que está a acontecer aqui? Paulo fornece uma base bíblica para esta afirmação em 1 Coríntios 1:18, sobre aqueles que estão a perecer, ao citar em 1 Coríntios 1:19 as palavras de Deus em Isaías 29:14. Em 1 Coríntios 1:19, é Deus quem está por trás da destruição, o que parece contradizer a ideia de autodestruição mencionada anteriormente. No entanto, não há contradição. A ideia é que Deus destrói aquilo que já está a destruir-se a si mesmo.\n\nEm contraste com aqueles que estão a ser destruídos, a expressão \"para nós, que estamos a ser salvos\" (1 Coríntios 1:18) indica que a salvação vem apenas de Deus. Paulo está a dizer que estamos a ser salvos; isto é, não nos salvamos a nós mesmos. Evidentemente, não podemos fazê-lo. A nossa salvação tem uma fonte externa. Enquanto a destruição é causada pelo próprio ser humano, a salvação só pode ser concedida, um dom de graça aos pecadores. Como fica claro em 1 Coríntios 1:21, é Deus quem salva aqueles que creem. A loucura, neste sentido, é o ato de rejeitar o que Deus ofereceu à humanidade através da cruz de Cristo (1 Coríntios 1:30), trazendo assim a destruição sobre si mesmo.\n\n\"Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus, nosso Senhor\" (Romanos 6:23). De que maneiras esse verso reafirma o ensino de 1 Coríntios 1:18, 19?",
      versiculoChave: { texto: "Pois a mensagem da cruz é loucura para os que perecem, mas para nós que somos salvos é o poder de Deus", referencia: "1 Coríntios 1:18" },
      perguntas: [
        { id: "d4q1", pergunta: "O que o verbo grego \"apollymi\" (\"perecer\") também pode significar?", opcoes: ["Salvar", "Destruir", "Nascer", "Perdoar"], correta: 1, explicacao: "A resposta correta é: Destruir." },
        { id: "d4q2", pergunta: "Segundo o texto, quem está por trás da \"destruição\" mencionada em 1 Coríntios 1:19?", opcoes: ["O ser humano sozinho", "Deus, mas sobre aquilo que já se autodestrói", "O diabo apenas", "Os romanos"], correta: 1, explicacao: "A resposta correta é: Deus, mas sobre aquilo que já se autodestrói." },
        { id: "d4q3", pergunta: "O que a expressão \"para nós, que estamos a ser salvos\" indica?", opcoes: ["Que nos salvamos sozinhos", "Que a salvação vem apenas de Deus", "Que a salvação depende das boas obras", "Que ninguém pode ser salvo"], correta: 1, explicacao: "A resposta correta é: Que a salvação vem apenas de Deus." },
        { id: "d4q4", pergunta: "Segundo o texto, o que é \"loucura\" no contexto de 1 Coríntios 1:21?", opcoes: ["Aceitar a mensagem da cruz", "Rejeitar o que Deus ofereceu através da cruz", "Pregar o evangelho", "Buscar a sabedoria de Deus"], correta: 1, explicacao: "A resposta correta é: Rejeitar o que Deus ofereceu através da cruz." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-07-08",
      titulo: "Um Messias crucificado",
      conteudo: "Paulo escreveu que \"os judeus pedem sinais, e os gregos procuram sabedoria\" (1 Coríntios 1:22). A cruz — a ideia de Deus, o Messias, ser crucificado — não era o tipo de sinal que os judeus esperavam. Também não era o tipo de sabedoria que os gregos procuravam. Ela ia contra as expectativas de todos.\n\nDe facto, basta ler a reação dos discípulos à ideia de Jesus ser crucificado (ver Marcos 8:31–32; Marcos 9:30–32; Marcos 10:32–34) para perceber o quão estranha e até repulsiva era essa ideia, especialmente para os judeus. Como já foi dito, os judeus esperavam que o Messias derrotasse os romanos; mas isso não aconteceu, pelo menos não no sentido militar e humano de \"derrotar\".\n\nDurante séculos, a cruz tem sido, para os cristãos, um símbolo de fé. É difícil para os cristãos do século XXI compreenderem o quão \"absurda\" a ideia de um Deus crucificado era para a mentalidade do primeiro século.\n\nNo entanto, é precisamente por esta mensagem ser tão chocante que ela merece as nossas reflexões mais profundas. A imagem de um Messias crucificado torna claro para todo o universo até onde Deus estava disposto a ir para cumprir o plano da redenção. A própria ideia da cruz, e do Senhor a morrer nela, já é impressionante para nós, pecadores aqui na Terra. (Imagine, porém, o que isso deve ter significado para os seres sem pecado que conheciam e adoravam o Senhor Jesus no Céu!)\n\n4. Leia Atos 13:16-47 (especialmente os versos 26, 38 e 47). O que essa passagem nos ensina sobre o evangelho da cruz?\n\nPaulo diz que Cristo o enviou para pregar o evangelho. E, assim, Paulo prega a mensagem de um Messias crucificado (1 Coríntios 1:23). Ele retoma estas ideias em 1 Coríntios 2:1–5. O apóstolo foi fiel à comissão de Cristo. Ao proclamar o evangelho, não usou \"linguagem elevada ou sabedoria\" (1 Coríntios 2:1); em vez disso, concentrou-se apenas em \"Jesus Cristo, e este crucificado\" (1 Coríntios 2:2).\n\nA sua palavra e a sua mensagem \"não consistiram em palavras persuasivas de sabedoria, mas em demonstração do Espírito e de poder\" (1 Coríntios 2:4), porque, de facto, \"a sabedoria dos homens\" está em claro contraste com \"o poder de Deus\" (1 Coríntios 2:5).\n\nUm Messias crucificado era impensável. O que isso nos diz sobre Deus agir além de nossas expectativas? Por que lembrar disso quando as coisas não saem como queremos?",
      versiculoChave: { texto: "Pois a mensagem da cruz é loucura para os que perecem, mas para nós que somos salvos é o poder de Deus", referencia: "1 Coríntios 1:18" },
      perguntas: [
        { id: "d5q1", pergunta: "O que os judeus pediam, segundo 1 Coríntios 1:22?", opcoes: ["Sabedoria", "Sinais", "Riquezas", "Poder político"], correta: 1, explicacao: "A resposta correta é: Sinais." },
        { id: "d5q2", pergunta: "O que os gregos procuravam, segundo o mesmo texto?", opcoes: ["Sinais", "Sabedoria", "Milagres", "Riqueza"], correta: 1, explicacao: "A resposta correta é: Sabedoria." },
        { id: "d5q3", pergunta: "Como os discípulos reagiram inicialmente à ideia de Jesus ser crucificado (Marcos 8 e 9)?", opcoes: ["Com entusiasmo", "Com estranheza e até repulsa", "Com indiferença", "Não reagiram"], correta: 1, explicacao: "A resposta correta é: Com estranheza e até repulsa." },
        { id: "d5q4", pergunta: "Segundo Atos 13, qual é o foco da pregação de Paulo mencionado no texto?", opcoes: ["A lei cerimonial", "O evangelho da cruz", "A política romana", "A filosofia grega"], correta: 1, explicacao: "A resposta correta é: O evangelho da cruz." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-07-09",
      titulo: "Cristo, poder e sabedoria de Deus",
      conteudo: "Em 1 Coríntios 1:19, 20, 30 e 31, Paulo fala sobre como a sabedoria de Deus e a sabedoria humana são extremamente diferentes e, por isso, mutuamente exclusivas. Note que Paulo não rejeita a sabedoria em si, mas rejeita o tipo de sabedoria humana que tenta competir com Deus. A sabedoria humana é incapaz de libertar o ser humano do pecado. Somente Cristo, a sabedoria de Deus, pode realizar essa obra.\n\n\"[...] para nós, que somos salvos [a mensagem da cruz] é poder de Deus.\" (1 Coríntios 1:18)\n\"[...] para os que foram chamados, Cristo é poder de Deus.\" (1 Coríntios 1:24)\n\nTanto 1 Coríntios 1:18 como 1 Coríntios 1:24 mostram que Cristo é o poder de Deus, no sentido de que Ele tem o poder de salvar as pessoas dos seus pecados. De facto, \"aprouve a Deus salvar os que creem pela loucura da pregação\" (1 Coríntios 1:21). As expressões \"nós, que estamos a ser salvos\" (1 Coríntios 1:18), \"os que creem\" (1 Coríntios 1:21) e \"os chamados\" (1 Coríntios 1:24) referem-se ao mesmo grupo, ou seja, pessoas que vivem a experiência da salvação pela fé. \"O evangelho de Cristo… é o poder de Deus para a salvação de todo aquele que crê\" (Romanos 1:16).\n\nCristo não é apenas o poder, mas também a sabedoria de Deus. Isto significa que, através d'Ele, Deus enfrentou e resolveu o problema do pecado — um problema que a sabedoria humana era incapaz de resolver. A sabedoria deste mundo é incapaz de fazer com que as pessoas conheçam Deus (1 Coríntios 1:21). Em contraste, através de Cristo tornamo-nos sábios para a salvação (2 Timóteo 3:15).\n\n7. Leia 1 Coríntios 1:24-29. Observe palavras como \"loucura\", \"fraqueza\", \"poder\" e \"sabedoria\". Qual ensino Paulo transmite nesse texto?\n\nAo ler 1 Coríntios 1:24–29, também se deve notar os termos \"louco\" (ou \"loucura\") e \"fraco\" (ou \"fraqueza\"). O ponto é que a sabedoria humana pode considerar a mensagem da cruz como loucura e fraqueza. No entanto, \"a loucura de Deus é mais sábia do que os homens, e a fraqueza de Deus é mais forte do que os homens\" (1 Coríntios 1:25).\n\nIsto não significa que Deus seja fraco ou louco; é apenas uma expressão que mostra como o poder e a sabedoria de Deus estão muito acima de qualquer coisa humana.\n\n\"Não foram chamados muitos sábios segundo a carne, nem muitos poderosos, nem muitos de nobre nascimento\" (1 Coríntios 1:26). Qual mensagem esse verso traz para nós hoje?",
      versiculoChave: { texto: "Pois a mensagem da cruz é loucura para os que perecem, mas para nós que somos salvos é o poder de Deus", referencia: "1 Coríntios 1:18" },
      perguntas: [
        { id: "d6q1", pergunta: "Segundo 1 Coríntios 1:18 e 1:24, o que Cristo é para os que creem?", opcoes: ["Apenas um exemplo moral", "O poder de Deus", "Um profeta comum", "Um símbolo cultural"], correta: 1, explicacao: "A resposta correta é: O poder de Deus." },
        { id: "d6q2", pergunta: "O que a sabedoria humana é incapaz de fazer, segundo o texto?", opcoes: ["Construir cidades", "Libertar o ser humano do pecado", "Ensinar filosofia", "Escrever leis"], correta: 1, explicacao: "A resposta correta é: Libertar o ser humano do pecado." },
        { id: "d6q3", pergunta: "Que palavras-chave o texto destaca em 1 Coríntios 1:24-29?", opcoes: ["\"Riqueza\" e \"poder político\"", "\"Loucura\", \"fraqueza\", \"poder\" e \"sabedoria\"", "\"Guerra\" e \"paz\"", "\"Lei\" e \"graça\""], correta: 1, explicacao: "A resposta correta é: \"Loucura\", \"fraqueza\", \"poder\" e \"sabedoria\"." },
        { id: "d6q4", pergunta: "Segundo 1 Coríntios 1:26, que tipo de pessoas foram chamadas por Deus, em sua maioria?", opcoes: ["Muitos sábios e poderosos segundo a carne", "Não muitos sábios, nem muitos poderosos, nem muitos de nobre nascimento", "Apenas reis e sacerdotes", "Apenas filósofos gregos"], correta: 1, explicacao: "A resposta correta é: Não muitos sábios, nem muitos poderosos, nem muitos de nobre nascimento." }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-07-10",
      titulo: "Estudo Adicional - A mensagem da cruz",
      conteudo: "Leia Ellen G. White, O Desejado de Todas as Nações, \"A glória do Calvário\" (p. 596-609).\n\n\"Para as mentes de muitas pessoas que vivem no presente, a cruz do Calvário está rodeada de memórias sagradas. Associações santas estão ligadas às cenas da crucifixão. Mas nos dias de Paulo a cruz era considerada com sentimentos de repulsa e horror. Exaltar como Salvador da humanidade alguém que tivesse morrido na cruz naturalmente despertaria ridículo e oposição.\n\n\"Paulo bem sabia como a sua mensagem seria recebida tanto pelos judeus como pelos gregos de Corinto. Entre os seus ouvintes judeus havia muitos que ficariam indignados com a mensagem que ele estava prestes a proclamar. Na avaliação dos gregos, as suas palavras pareceriam uma loucura absurda. Ele seria considerado mentalmente fraco por tentar mostrar como a cruz poderia ter qualquer ligação com a elevação da raça humana ou com a salvação da humanidade.\n\n\"Mas para Paulo a cruz era o objeto de supremo interesse. Desde o momento em que foi detido na sua carreira de perseguição aos seguidores do Nazareno crucificado, ele nunca deixou de se gloriar na cruz. Naquele momento foi-lhe dada uma revelação do amor infinito de Deus, manifestado na morte de Cristo; e ocorreu uma transformação maravilhosa na sua vida, trazendo todos os seus planos e propósitos em harmonia com o céu. Ele sabia por experiência pessoal que, quando um pecador contempla o amor do Pai, visto no sacrifício do Seu Filho, e se rende à influência divina, ocorre uma mudança de coração, e daí em diante Cristo é tudo em todos.\" — Ellen G. White, Atos dos Apóstolos, p. 156.\n\nQuestões para discussão:\n\n1. Em que aspectos a sabedoria de Deus é tão diferente da sabedoria humana (1 Coríntios 1:25)?\n\n2. Cristo crucificado era escândalo para os judeus e loucura para os gregos. Quais temas bíblicos que pregamos hoje podem causar efeito semelhante no público moderno, e por quê?\n\n3. Paulo disse que a \"pessoa natural não aceita as coisas do Espírito de Deus\" (1 Coríntios 2:15). Então, como podemos falar de Jesus a essas pessoas? Ou nossas ações, por si mesmas, bastariam para alcançá-las?",
      versiculoChave: { texto: "Pois a mensagem da cruz é loucura para os que perecem, mas para nós que somos salvos é o poder de Deus", referencia: "1 Coríntios 1:18" },
      perguntas: [
        { id: "d7q1", pergunta: "Como os romanos geralmente encaravam a cruz, segundo Ellen White?", opcoes: ["Com respeito e admiração", "Com repulsa e horror", "Com indiferença total", "Como símbolo de vitória militar"], correta: 1, explicacao: "A resposta correta é: Com repulsa e horror." },
        { id: "d7q2", pergunta: "Como os judeus reagiam à mensagem da cruz pregada por Paulo?", opcoes: ["Com aceitação imediata", "Com indignação", "Com curiosidade apenas", "Sem nenhuma reação"], correta: 1, explicacao: "A resposta correta é: Com indignação." },
        { id: "d7q3", pergunta: "O que, segundo o texto, transformou a vida de Paulo?", opcoes: ["Uma vitória militar", "A revelação do amor infinito de Deus na morte de Cristo", "Um cargo político", "Uma herança financeira"], correta: 1, explicacao: "A resposta correta é: A revelação do amor infinito de Deus na morte de Cristo." },
        { id: "d7q4", pergunta: "Para os gregos de Corinto, como a mensagem de Paulo era vista?", opcoes: ["Como sabedoria suprema", "Como loucura absurda", "Como ciência avançada", "Como poesia elegante"], correta: 1, explicacao: "A resposta correta é: Como loucura absurda." }
      ]
    }
  ]
};

export const LICAO_ADULT_3 = {
  titulo: "Lição 3 - Unidade em Cristo (11 a 17 de julho)",
  semana: "2026-W28",
  trimestre: "1 e 2 Coríntios",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-07-11",
      titulo: "Unidade em Cristo",
      conteudo: "Aqueles que observam a vida selvagem sabem que algumas criaturas vivem em alcateias, manadas ou grupos de diferentes tamanhos. Desde lobos e golfinhos até mesmo formigas-de-correição, esses animais permanecem juntos.\n\nOs chimpanzés são especialmente conhecidos pelos seus fortes laços sociais, chegando a viver em grupos de 15 a 150 indivíduos. No entanto, esses relacionamentos nem sempre são harmoniosos, e por vezes os chimpanzés lutam entre si.\n\nOs seres humanos são um pouco semelhantes; isto é, não apenas tendem a viver em grupos, mas também, por vezes, entram em conflito dentro desses grupos. E essa é uma realidade até mesmo nas nossas igrejas! Formam-se panelinhas ou grupos fechados, muitas vezes em torno de algum líder carismático. E, pior ainda, às vezes um grupo não se dá bem com os outros.\n\nJá viu isso acontecer na sua igreja? Se sim, então tem uma ideia do problema que Paulo enfrentou em Corinto. Esta semana, analisaremos 1 Coríntios 1–4, onde o apóstolo Paulo trata do problema das divisões e contendas na igreja e de como superá-las, nomeadamente, através da unidade em Cristo.\n\nEstude a lição desta semana para se preparar para o Sábado, 18 de Julho.",
      versiculoChave: { texto: "Irmãos, pelo nome de nosso Senhor Jesus Cristo, peço-lhes que todos estejam de acordo naquilo que falam e que não haja divisões entre vocês, pelo contrário, que vocês sejam unidos no mesmo modo de pensar e num mesmo propósito", referencia: "1 Coríntios 1:10" },
      perguntas: [
        { id: "d1q1", pergunta: "Que exemplos de animais o texto cita para ilustrar vida em grupo?", opcoes: ["Peixes e pássaros apenas", "Lobos, golfinhos e formigas-de-correição", "Répteis apenas", "Insetos apenas"], correta: 1, explicacao: "A resposta correta é: Lobos, golfinhos e formigas-de-correição." },
        { id: "d1q2", pergunta: "Em grupos de quantos indivíduos os chimpanzés costumam viver, segundo o texto?", opcoes: ["2 a 5", "15 a 150", "500 a 1000", "Apenas em pares"], correta: 1, explicacao: "A resposta correta é: 15 a 150." },
        { id: "d1q3", pergunta: "Segundo o texto, o que se forma nas igrejas em torno de líderes carismáticos?", opcoes: ["Comunhão perfeita", "Panelinhas ou grupos fechados", "Escolas bíblicas", "Conselhos administrativos"], correta: 1, explicacao: "A resposta correta é: Panelinhas ou grupos fechados." },
        { id: "d1q4", pergunta: "Quais capítulos de 1 Coríntios serão estudados nesta semana, segundo o texto?", opcoes: ["1 Coríntios 5-8", "1 Coríntios 1-4", "1 Coríntios 10-13", "1 Coríntios 14-16"], correta: 1, explicacao: "A resposta correta é: 1 Coríntios 1-4." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-07-12",
      titulo: "O Problema das panelinhas na igreja",
      conteudo: "O apelo de Paulo para que \"não haja divisões entre vocês, mas que sejam unidos em um mesmo pensamento e em um mesmo parecer\" (1 Coríntios 1:10) domina os quatro primeiros capítulos de 1 Coríntios. De fato, a maioria dos estudiosos concorda que a unidade é o tema abrangente que une todas as partes da carta.\n\n1. Leia 1 Coríntios 1:12-17. Como esse trecho mostra o absurdo que é formar \"panelinhas\" em torno de líderes locais? Qual é a solução proposta por Paulo?\n\nPaulo emprega palavras fortes para retratar a falta de unidade entre os membros da igreja em Corinto. Ele usa os termos gregos schisma (\"divisão\", 1 Coríntios 1:10) e eris (\"contenda\", 1 Coríntios 1:11). O substantivo schisma (assim como o verbo schizō, \"dividir\") é usado em outras passagens do Novo Testamento para descrever divergências de opinião que resultam em facções. Por sua vez, o substantivo eris (\"contenda\") aparece frequentemente em listas de vícios que não devem ser praticados pelos cristãos.\n\n2. Leia Romanos 1:29; Romanos 13:13, 1 Coríntios 3:3; 2 Coríntios 12:20 e Gálatas 5:20. Quais outros pecadores são listados juntamente com eris (\"brigas\", \"discórdias\")? O que isso revela sobre a gravidade desse mal?\n\nAs divergências na igreja de Corinto vieram à tona, inclusive na forma de processos judiciais entre os membros (1 Coríntios 6:1-3). \"Digo isso para a vergonha de vocês\", disse Paulo (1 Coríntios 6:5), a respeito desses processos entre os membros da igreja. De fato, eles não deixaram de lado suas diferenças nem mesmo durante a celebração da Ceia do Senhor (1 Coríntios 11:17-22).\n\nO problema da falta de unidade entre os membros da igreja é tão assustador, e Paulo está tão preocupado com isso, que este é o primeiro assunto que ele aborda nesta carta aos Coríntios.\n\nLeia novamente 1 Coríntios 1:12-17. Reflita. Como esse trecho mostra o perigo que as \"panelinhas\" representam para a unidade da igreja? O que sua igreja local pode fazer para evitar esse problema?",
      versiculoChave: { texto: "Irmãos, pelo nome de nosso Senhor Jesus Cristo, peço-lhes que todos estejam de acordo naquilo que falam e que não haja divisões entre vocês, pelo contrário, que vocês sejam unidos no mesmo modo de pensar e num mesmo propósito", referencia: "1 Coríntios 1:10" },
      perguntas: [
        { id: "d2q1", pergunta: "Quais palavras gregas Paulo usa para descrever a falta de unidade em Corinto?", opcoes: ["Charis e agape", "Schisma e eris", "Logos e sophia", "Pistis e elpis"], correta: 1, explicacao: "A resposta correta é: Schisma e eris." },
        { id: "d2q2", pergunta: "O que \"schisma\" significa?", opcoes: ["Amor", "Divisão", "Paz", "Sabedoria"], correta: 1, explicacao: "A resposta correta é: Divisão." },
        { id: "d2q3", pergunta: "Como as divergências na igreja de Corinto se manifestaram, segundo o texto?", opcoes: ["Apenas em discussões privadas", "Até em processos judiciais entre membros", "Não houve manifestação prática", "Apenas em cartas"], correta: 1, explicacao: "A resposta correta é: Até em processos judiciais entre membros." },
        { id: "d2q4", pergunta: "Mesmo durante qual celebração os coríntios não deixaram de lado suas diferenças?", opcoes: ["O batismo", "A Ceia do Senhor", "O casamento", "A Páscoa judaica"], correta: 1, explicacao: "A resposta correta é: A Ceia do Senhor." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-07-13",
      titulo: "Centrados em Jesus",
      conteudo: "3. Leia 1 Coríntios 1:10. O que Paulo quis dizer com a orientação: \"Sejam unidos no mesmo modo de pensar e num mesmo propósito\"?\n\nA formação de \"panelinhas\" constituía, aqui, uma negação da própria fidelidade a Cristo (1 Coríntios 1:10). Deus nos chamou \"para a comunhão de seu Filho, Jesus Cristo, nosso Senhor\" (1 Coríntios 1:9). Nosso Senhor é Cristo, e devemos estar centrados Nele. Portanto, a resposta às perguntas retóricas \"Cristo está dividido? Paulo foi crucificado por vocês? Ou vocês foram batizados em nome de Paulo?\" (1 Coríntios 1:13) é um sonoro \"Não!\". Cristo não está dividido. Foi Cristo quem foi crucificado por nós. Fomos batizados \"em nome do Pai, do Filho e do Espírito Santo\" (Mateus 28:19).\n\nPaulo menciona que somos \"o corpo de Cristo e, individualmente, membros desse corpo\" (1 Coríntios 12:27). Embora o corpo tenha muitas partes — cada uma com sua função —, ele ainda é um só corpo. Para que o corpo funcione adequadamente, cada parte precisa desempenhar sua função de acordo com suas capacidades. Essa metáfora indica que Paulo busca unidade, não uniformidade. Ele busca unidade na diversidade. Mais do que isso, ele busca unidade apesar da diversidade.\n\nContudo, todos os pensamentos e opiniões devem ser submetidos a Cristo, nosso Senhor. O fato de Cristo ser nosso Senhor é um conceito tão importante para Paulo que ele o menciona repetidamente na abertura de 1 Coríntios (1 Coríntios 1:2, 7, 8, 9, 10). Assim, antes de Paulo abordar a questão das panelinhas e dos líderes humanos, ele enfatiza que todos nós temos Jesus como nosso Senhor. A igreja não está centrada em líderes humanos. Os cristãos estão centrados em Jesus.\n\nA ênfase na soberania de Jesus nos versículos iniciais de 1 Coríntios nos ajuda a entender o que Paulo quis dizer com as palavras: \"Sejam unidos em um mesmo pensamento e em um mesmo parecer\" (1 Coríntios 1:10). O termo grego traduzido como \"unidos\" vem do verbo katartizō, que sugere que algo deve ser restaurado à sua condição original. Quando grupos se formam em torno de líderes humanos, os relacionamentos dentro da igreja precisam ser restaurados à sua condição original, e isso pode acontecer por meio da unidade em Cristo e da morte para o ego que ela implica.\n\nNas últimas décadas, a Igreja Adventista do Sétimo Dia tem destacado o ministério dos pequenos Grupos. Qual é a diferença entre \"panelinhas\" e Pequenos Grupos? Como evitar que Pequenos Grupos se transformem em \"panelinhas\"?",
      versiculoChave: { texto: "Irmãos, pelo nome de nosso Senhor Jesus Cristo, peço-lhes que todos estejam de acordo naquilo que falam e que não haja divisões entre vocês, pelo contrário, que vocês sejam unidos no mesmo modo de pensar e num mesmo propósito", referencia: "1 Coríntios 1:10" },
      perguntas: [
        { id: "d3q1", pergunta: "O que a formação de \"panelinhas\" representava, segundo o texto?", opcoes: ["Um sinal de crescimento espiritual", "Uma negação da fidelidade a Cristo", "Uma prática recomendada por Paulo", "Um costume romano"], correta: 1, explicacao: "A resposta correta é: Uma negação da fidelidade a Cristo." },
        { id: "d3q2", pergunta: "Segundo Paulo, o corpo de Cristo tem muitas partes, mas...", opcoes: ["Cada uma funciona de forma independente", "Ainda é um só corpo", "Apenas uma parte é importante", "As partes competem entre si"], correta: 1, explicacao: "A resposta correta é: Ainda é um só corpo." },
        { id: "d3q3", pergunta: "O termo grego \"katartizō\", traduzido como \"unidos\", sugere o quê?", opcoes: ["Criar algo novo", "Restaurar algo à sua condição original", "Destruir divisões pela força", "Ignorar diferenças"], correta: 1, explicacao: "A resposta correta é: Restaurar algo à sua condição original." },
        { id: "d3q4", pergunta: "Segundo o texto, Paulo busca unidade...", opcoes: ["Na uniformidade total", "Na diversidade, apesar da diversidade", "Apenas entre líderes", "Somente doutrinária, sem aplicação prática"], correta: 1, explicacao: "A resposta correta é: Na diversidade, apesar da diversidade." }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-07-14",
      titulo: "Sabedoria e maturidade",
      conteudo: "De modo geral, as panelinhas surgem de uma visão excessivamente elevada dos líderes humanos. Isso representa uma grande ameaça à unidade da igreja e à saúde espiritual de seus membros, pois uma visão distorcida do ministério cristão pode levar uma igreja a dar importância desmedida a certos líderes, em detrimento de outros. A consequência desse comportamento é uma atmosfera de competição, que pode dividir a igreja. Além disso, se tratarmos os líderes humanos como centrais para nossa identidade cristã, corremos o risco de afastar Cristo da posição correta em nossas vidas.\n\n4. Leia 1 Coríntios 3:1-4. Como Paulo descreveu a imaturidade espiritual dos coríntios?\n\nPaulo deixa claro que a maturidade espiritual leva o crente a apreciar a sabedoria de Deus (1 Coríntios 2:6, 7), que nos é comunicada pelo Espírito (1 Coríntios 2:13) e que contrasta com a sabedoria desta era (1 Coríntios 2:6), a sabedoria humana (1 Coríntios 2:13). A sabedoria de Deus é revelada na cruz de Cristo (1 Coríntios 2:1-4). Mais precisamente, a sabedoria de Deus é revelada no sofrimento, morte e ressurreição de Cristo. Assim, antes de retomar seu apelo à unidade (1 Coríntios 3:1-17), Paulo quer que seus leitores reconheçam a necessidade da verdadeira sabedoria e maturidade em Cristo.\n\nCristãos sábios e maduros são pessoas espirituais, não carnais, não como crianças (1 Coríntios 3:1). Eles comparam coisas espirituais com coisas espirituais, porque \"as coisas do Espírito... são discernidas espiritualmente\" (1 Coríntios 2:13, 14). Cristãos sábios e maduros se alimentam de alimento sólido, não de leite (1 Coríntios 3:2; compare com Hebreus 5:12). O crente \"que se alimenta de leite é inexperiente na palavra da justiça, pois ainda é criança. Mas o alimento sólido é para os adultos, os quais, pela prática constante, têm o discernimento treinado para distinguir o bem do mal\" (Hebreus 5:13, 14). Cristãos sábios e maduros não dizem: \"Eu sou de Paulo\" ou \"Eu sou de Apolo\" (1 Coríntios 3:4), referindo-se a pessoas diferentes.\n\nAfinal, essas pessoas são, como eles, \"cooperadores de Deus\" (1 Coríntios 3:9). Nós, como igreja, somos o campo, o edifício e o templo de Deus (1 Coríntios 3:9, 16, 17). Todos pertencemos a Deus por meio de Cristo (1 Coríntios 3:11).\n\nQuais experiências você já teve de grande decepção com alguém que admirava muito? Se isso aconteceu, quais lições tirou desse episódio?",
      versiculoChave: { texto: "Irmãos, pelo nome de nosso Senhor Jesus Cristo, peço-lhes que todos estejam de acordo naquilo que falam e que não haja divisões entre vocês, pelo contrário, que vocês sejam unidos no mesmo modo de pensar e num mesmo propósito", referencia: "1 Coríntios 1:10" },
      perguntas: [
        { id: "d4q1", pergunta: "De onde surgem, em geral, as \"panelinhas\" na igreja, segundo o texto?", opcoes: ["De uma visão excessivamente elevada dos líderes humanos", "Da falta de recursos financeiros", "Da ausência de pregações", "De conflitos com outras religiões"], correta: 0, explicacao: "A resposta correta é: De uma visão excessivamente elevada dos líderes humanos." },
        { id: "d4q2", pergunta: "Como Paulo descreve os coríntios em 1 Coríntios 3:1-4?", opcoes: ["Espiritualmente maduros", "Espiritualmente imaturos, como crianças", "Sábios e experientes", "Livres de qualquer problema"], correta: 1, explicacao: "A resposta correta é: Espiritualmente imaturos, como crianças." },
        { id: "d4q3", pergunta: "O que caracteriza cristãos sábios e maduros, segundo o texto?", opcoes: ["Dizer \"eu sou de Paulo\" ou \"eu sou de Apolo\"", "Comparar coisas espirituais com coisas espirituais", "Alimentar-se apenas de leite espiritual", "Evitar o discernimento"], correta: 1, explicacao: "A resposta correta é: Comparar coisas espirituais com coisas espirituais." },
        { id: "d4q4", pergunta: "Segundo Hebreus 5:13,14, citado no texto, o alimento sólido é para quem?", opcoes: ["Para crianças na fé", "Para os adultos, com discernimento treinado", "Para os líderes apenas", "Para ninguém, pois todos devem beber leite"], correta: 1, explicacao: "A resposta correta é: Para os adultos, com discernimento treinado." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-07-15",
      titulo: "Servir como Cristo",
      conteudo: "5. Leia 1 Coríntios 4:1, 2. Que visão correta devemos ter a respeito de líderes humanos?\n\nEm 1 Coríntios 3:1-4, Paulo sugere que as panelinhas resultam da falta de maturidade espiritual. No entanto, antes de abordar esse tópico, ele afirma: \"Temos a mente de Cristo\" (1 Coríntios 2:16). Essa frase provavelmente se refere à maneira de pensar e agir de Cristo. Em outras palavras, o crente tem \"a mente de Cristo\" quando pensa e age como Cristo. Colocar essa mente em prática em todos os aspectos da vida não é tão fácil, não é mesmo? No mundo greco-romano, havia muita competição entre figuras políticas, filósofos, pensadores e líderes religiosos. O anseio por aprovação cultural aparentemente levou a igreja de Corinto a seguir padrões seculares. Isso pode representar um perigo também para a igreja hoje.\n\n6. Leia Filipenses 2:5-8. Como esse texto nos ajuda a entender o que é a \"mente de Cristo\" (1 Coríntios 2:16)?\n\nAssim como em Corinto, divisões também estavam ocorrendo na igreja de Filipos (Filipenses 2:1-4), talvez em menor grau. Filipenses 2:1-8 nos ensina que um serviço à semelhança de Cristo exige morrer para si mesmo e para as ambições egoístas, buscando, em vez disso, abençoar os outros acima de nós mesmos, como fez Jesus.\n\nUma servidão semelhante à de Cristo é o que Paulo quis dizer com a expressão \"servos de Cristo\" (1 Coríntios 4:1). Essa expressão pode transmitir a ideia de que eles servem a Cristo como assistentes ou subordinados. É evidente que uma visão correta dos líderes humanos se baseia no exemplo de liderança de Cristo. Os servos são ainda descritos como \"mordomos\" (1 Coríntios 4:1, 2). Um mordomo é uma pessoa a quem foi confiada a administração dos bens de outra pessoa. E tudo o que temos, de qualquer forma, pertence a Cristo.\n\nReflita, em oração, na mensagem de Filipenses 2:5-8. Como compreender o amor abnegado de Deus por nós? E como aprender a morrer para nós mesmos de modo que, em nossa esfera, possamos imitar esse amor?",
      versiculoChave: { texto: "Irmãos, pelo nome de nosso Senhor Jesus Cristo, peço-lhes que todos estejam de acordo naquilo que falam e que não haja divisões entre vocês, pelo contrário, que vocês sejam unidos no mesmo modo de pensar e num mesmo propósito", referencia: "1 Coríntios 1:10" },
      perguntas: [
        { id: "d5q1", pergunta: "O que significa ter \"a mente de Cristo\", segundo o texto?", opcoes: ["Ter conhecimento acadêmico elevado", "Pensar e agir como Cristo", "Ser um grande orador", "Ter poder político"], correta: 1, explicacao: "A resposta correta é: Pensar e agir como Cristo." },
        { id: "d5q2", pergunta: "Segundo Filipenses 2:5-8, o que um serviço semelhante ao de Cristo exige?", opcoes: ["Buscar reconhecimento público", "Morrer para si mesmo e para ambições egoístas", "Evitar servir aos outros", "Buscar riqueza material"], correta: 1, explicacao: "A resposta correta é: Morrer para si mesmo e para ambições egoístas." },
        { id: "d5q3", pergunta: "Como Paulo descreve os líderes cristãos em 1 Coríntios 4:1?", opcoes: ["Reis e senhores", "Servos de Cristo e mordomos", "Filósofos gregos", "Juízes da igreja"], correta: 1, explicacao: "A resposta correta é: Servos de Cristo e mordomos." },
        { id: "d5q4", pergunta: "O que é um \"mordomo\", segundo a explicação do texto?", opcoes: ["Alguém que possui tudo para si", "Alguém a quem foi confiada a administração dos bens de outra pessoa", "Um título apenas honorário", "Um cargo político romano"], correta: 1, explicacao: "A resposta correta é: Alguém a quem foi confiada a administração dos bens de outra pessoa." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-07-16",
      titulo: "Estilo de vida que reflete a cruz",
      conteudo: "O fato de não devermos formar panelinhas, especialmente em torno de líderes humanos, não significa que não devamos apoiar nossos líderes. Devemos valorizar e ajudar aqueles que lideram o trabalho da igreja. Deus comissiona pessoas para realizar o Seu ministério na Terra. Líderes da igreja que demonstram um estilo de vida que reflete a submissão representada pela Cruz são dignos de serem ouvidos e seguidos.\n\nE isso acontece porque somente a Cruz tem o poder de reverter qualquer forma de controle manipulador em favor da submissão à Palavra de Deus. Líderes semelhantes a Cristo atribuem o sucesso de seu ministério somente a Deus. Em seu ministério terreno, até mesmo Jesus, como homem, atribuiu glória a Deus (João 17:4).\n\nSegundo Paulo, o ministério cristão fiel deve estar fundamentado no que podemos chamar de teologia da Cruz. A Cruz é a revelação de Deus de Sua sabedoria e poder para salvar. Ao mesmo tempo, ela também revela a sabedoria humana como loucura. Em 1 Coríntios 4:1-13, Paulo deixa claro como é essa teologia da Cruz. Primeiro, ele indica que é Deus quem estabelece o padrão para a liderança cristã (1 Coríntios 4:1-5). Segundo, ele aponta para o fato de que o sofrimento é a marca registrada do verdadeiro ministério cristão (1 Coríntios 4:9, 11-13). Este segundo ponto merece ser mais bem desenvolvido.\n\n7. Leia 2 Coríntios 11:23-28 e Colossenses 1:24. O que esses textos ensinam sobre o significado de sofrer por amor a Cristo?\n\nOs líderes cristãos seguem os passos de Jesus, estando dispostos a sofrer por seus irmãos e irmãs, e até mesmo, se necessário, a morrer pelo seu ministério. Paulo se refere a si mesmo e a Apolo como \"homens condenados à morte\" (1 Coríntios 4:9). Eles são retratados enfrentando a falta de comida e água, além de estarem \"mal vestidos, espancados e sem teto\" (1 Coríntios 4:11). Ademais, foram insultados, perseguidos, difamados e \"considerados como o lixo do mundo, a escória de todas as coisas até agora\" (1 Coríntios 4:12, 13). Além disso, ao se referir ironicamente aos coríntios como ricos, reis, sábios e distintos (1 Coríntios 4:8, 10), Paulo demonstra que o orgulho não deve ter lugar na verdadeira liderança cristã, pois é a raiz da divisão na igreja (1 Coríntios 4:6).\n\nQuanto você já sofreu por amor a Cristo? Quais lições sua resposta revela?",
      versiculoChave: { texto: "Irmãos, pelo nome de nosso Senhor Jesus Cristo, peço-lhes que todos estejam de acordo naquilo que falam e que não haja divisões entre vocês, pelo contrário, que vocês sejam unidos no mesmo modo de pensar e num mesmo propósito", referencia: "1 Coríntios 1:10" },
      perguntas: [
        { id: "d6q1", pergunta: "Segundo o texto, não formar panelinhas significa que não devemos apoiar os líderes?", opcoes: ["Sim, devemos ignorá-los", "Não; devemos valorizar e ajudar quem lidera o trabalho da igreja", "Sim, líderes não merecem apoio", "O texto não trata desse assunto"], correta: 1, explicacao: "A resposta correta é: Não; devemos valorizar e ajudar quem lidera o trabalho da igreja." },
        { id: "d6q2", pergunta: "O que tem o poder de reverter o controle manipulador em favor da submissão à Palavra de Deus?", opcoes: ["A tradição", "A Cruz", "A hierarquia eclesiástica", "A riqueza da igreja"], correta: 1, explicacao: "A resposta correta é: A Cruz." },
        { id: "d6q3", pergunta: "Segundo o texto, o que é a marca registrada do verdadeiro ministério cristão?", opcoes: ["O sucesso financeiro", "O sofrimento", "A popularidade", "O poder político"], correta: 1, explicacao: "A resposta correta é: O sofrimento." },
        { id: "d6q4", pergunta: "Como Paulo se refere a si mesmo e a Apolo em 1 Coríntios 4:9?", opcoes: ["Reis vitoriosos", "Homens condenados à morte", "Sábios do mundo", "Ricos e distintos"], correta: 1, explicacao: "A resposta correta é: Homens condenados à morte." }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-07-17",
      titulo: "Estudo Adicional - Unidade em Cristo",
      conteudo: "Leia Ellen G. White, Atos dos Apóstolos. \"O preparo dos Doze\" (p. 12-16).\n\n\"A unidade e a unicidade do remanescente de Deus que crê na verdade transmitem ao mundo uma poderosa convicção de que eles possuem a verdade e são o povo escolhido e singular de Deus. Essa unidade e unicidade desconcertam o inimigo, e ele está determinado a impedir que isso aconteça. A verdade presente, crida no coração e exemplificada na vida, torna o povo de Deus um só e lhe confere uma poderosa influência.\" — Ellen G. White, Testemunhos para a Igreja, vol. 1, p. 296.\n\n\"Deus está conduzindo um povo a se firmar em perfeita unidade sobre a plataforma da verdade eterna. Cristo se entregou ao mundo para que pudesse 'purificar para si um povo peculiar, zeloso de boas obras'. Esse processo de purificação visa expurgar a igreja de toda injustiça e do espírito de discórdia e contenda, para que possam edificar em vez de destruir e concentrar suas energias na grande obra que têm pela frente. Deus deseja que todo o Seu povo chegue à unidade da fé.\n\nA oração de Cristo, pouco antes de Sua crucificação, foi para que Seus discípulos fossem um, assim como Ele era um com o Pai, para que o mundo cresse que o Pai O havia enviado. Essa oração tocante e maravilhosa ressoa através dos séculos, até os nossos dias; pois Suas palavras foram: 'Não rogo somente por estes, mas também por aqueles que vierem a crer em Mim, por intermédio da Sua palavra'\" (João 17:20) — Ellen G. White, Testemunhos para a Igreja, vol. 4, p. 17.\n\nQuestões para discussão:\n\n1. Leia 1 Coríntios 4:9-13 e observe como os apóstolos são retratados. Em que esse retrato contrasta com as características de liderança valorizadas em nosso mundo? O que esse texto ensina sobre o quanto os padrões de Deus podem diferir dos padrões do mundo?\n\n2. Em 1 Coríntios 4:16, Paulo exorta os coríntios a imitá-lo. Você imitaria líderes humanos? Em que imitar um líder difere de exaltá-lo indevidamente – e até perigosamente?",
      versiculoChave: { texto: "Irmãos, pelo nome de nosso Senhor Jesus Cristo, peço-lhes que todos estejam de acordo naquilo que falam e que não haja divisões entre vocês, pelo contrário, que vocês sejam unidos no mesmo modo de pensar e num mesmo propósito", referencia: "1 Coríntios 1:10" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo Ellen White, o que a unidade do povo de Deus transmite ao mundo?", opcoes: ["Fraqueza", "Uma poderosa convicção de que possuem a verdade", "Confusão", "Nada de relevante"], correta: 1, explicacao: "A resposta correta é: Uma poderosa convicção de que possuem a verdade." },
        { id: "d7q2", pergunta: "O que a oração de Cristo, pouco antes da crucificação, pedia para Seus discípulos?", opcoes: ["Que fossem ricos", "Que fossem um, assim como Ele era um com o Pai", "Que dominassem o mundo", "Que se dividissem em grupos especializados"], correta: 1, explicacao: "A resposta correta é: Que fossem um, assim como Ele era um com o Pai." },
        { id: "d7q3", pergunta: "Segundo o texto, o processo de purificação da igreja visa expurgar o quê?", opcoes: ["Apenas pecados financeiros", "Toda injustiça e o espírito de discórdia e contenda", "As tradições antigas", "A diversidade cultural"], correta: 1, explicacao: "A resposta correta é: Toda injustiça e o espírito de discórdia e contenda." },
        { id: "d7q4", pergunta: "Segundo a pergunta de discussão sobre 1 Coríntios 4:16, o que Paulo exorta os coríntios a fazer?", opcoes: ["Rejeitá-lo como líder", "Imitá-lo", "Ignorar seus ensinos", "Substituí-lo por outro apóstolo"], correta: 1, explicacao: "A resposta correta é: Imitá-lo." }
      ]
    }
  ]
};
