export const LICAO_ADULT_1 = {
  titulo: "Lição 1 - O ministério de Paulo em Corinto (27 de junho a 3 de julho)",
  semana: "2026-W26",
  trimestre: "1 e 2 Coríntios",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-06-27",
      titulo: "O ministério de Paulo em Corinto",
      conteudo: "O grande missionário inglês William Carey costumava dizer que consertava sapatos para pagar suas despesas, mas seu verdadeiro negócio era ganhar almas.\n\nDa mesma forma, Paulo trabalhava como fabricante de tendas para ganhar a vida (Atos 18:1-3), mas seu verdadeiro negócio era, é claro, ganhar pessoas para Cristo.\n\nEsta semana, vamos dar uma olhada no ministério de Paulo à igreja na cidade de Corinto. A igreja, como veremos, estava repleta de problemas, muitos dos quais não eram diferentes dos que nossas igrejas enfrentam hoje, quase dois mil anos depois. De fato, qualquer pessoa que esteja no cristianismo há algum tempo, ou que tenha se envolvido no trabalho da igreja, poderia perguntar: Você já encontrou algum grupo cristão que não tenha problemas? A resposta é, obviamente, óbvia.\n\nPaulo enfrenta desafios em Corinto, mas o faz com a mensagem da Cruz (1 Coríntios 2:2). A fidelidade a essa mensagem é também o caminho para enfrentarmos os desafios que temos hoje. Como veremos esta semana e ao longo deste trimestre, a mensagem de 1 e 2 Coríntios também se aplica às nossas vidas.\n\nEstude a lição desta semana para se preparar para o sábado, 4 de julho.",
      versiculoChave: { texto: "Certa noite Paulo teve uma visão em que o Senhor lhe disse: 'Não tenha medo! Pelo contrário; fale e não fique calado, porque Eu estou com você, e ninguém ousará lhe fazer mal, pois tenho muito povo nesta cidade'", referencia: "Atos 18:9, 10" },
      perguntas: [
        { id: "d1q1", pergunta: "Qual comparação o texto usa para ilustrar alguém que tem um ofício, mas cuja verdadeira missão é outra?", opcoes: ["Um professor que também é pastor", "William Carey, que consertava sapatos, mas seu negócio era ganhar almas", "Um médico que evangeliza pacientes", "Um rei que também era sacerdote"], correta: 1, explicacao: "A resposta correta é: William Carey, que consertava sapatos, mas seu negócio era ganhar almas." },
        { id: "d1q2", pergunta: "Qual era o ofício de Paulo para se sustentar enquanto pregava?", opcoes: ["Pescador", "Fabricante de tendas", "Carpinteiro", "Escriba"], correta: 1, explicacao: "A resposta correta é: Fabricante de tendas." },
        { id: "d1q3", pergunta: "Com que mensagem Paulo enfrentou os desafios da igreja em Corinto?", opcoes: ["A mensagem da lei", "A mensagem dos profetas", "A mensagem da Cruz", "A mensagem da sabedoria grega"], correta: 2, explicacao: "A resposta correta é: A mensagem da Cruz." },
        { id: "d1q4", pergunta: "Segundo o texto, os problemas da igreja de Corinto eram...", opcoes: ["Totalmente diferentes dos problemas das igrejas de hoje", "Muito semelhantes aos que as igrejas enfrentam hoje", "Inexistentes, pois a igreja era exemplar", "Resolvidos antes da chegada de Paulo"], correta: 1, explicacao: "A resposta correta é: Muito semelhantes aos que as igrejas enfrentam hoje." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-06-28",
      titulo: "Paulo, apóstolo de Jesus, chamado por Deus",
      conteudo: "Paulo começa a sua carta aos Coríntios identificando-se como apóstolo de Jesus, chamado \"pela vontade de Deus\" (1 Coríntios 1:1; compare com 2 Coríntios 1:1). A sua convicção acerca de quem ele é em relação a Jesus é tão firme que, com poucas exceções, esta é a forma como ele inicia todas as suas cartas.\n\n1. Leia 1 Coríntios 1:1 e Romanos 1:1. Quais dois aspectos do ministério de Paulo são destacados nesses textos? (Veja também Gálatas 1:1).\n\nPaulo fala do seu chamado e apostolado como o cumprimento da vontade de Deus. Ele está convencido de que o seu chamado não vem dos homens, mas de Deus (Gálatas 1:1). Paulo foi chamado por Deus desde o ventre de sua mãe, assim como Jeremias (Jeremias 1:5), como um ato da graça de Deus (Gálatas 1:15), e isso aconteceu para que ele proclamasse o evangelho de Cristo entre os gentios.\n\nEm 1 Coríntios 15:8, Paulo inclui-se entre aqueles a quem Cristo apareceu após a Ressurreição (1 Coríntios 15:5–7). Alguns versículos mais adiante, ele dá a entender que o seu chamado para ser apóstolo foi resultado desse encontro com Jesus (1 Coríntios 15:9–11). O título \"apóstolo de Jesus\" engloba uma série de conceitos. Em primeiro lugar, transmite a ideia de alguém que é enviado por Jesus. No entanto, Paulo também utiliza esta expressão para identificar-se como servo de Cristo (Romanos 1:1, Tito 1:1, Gálatas 1:10), bem como pregador e mestre (1 Timóteo 2:7, 2 Timóteo 1:11). Quer Paulo pregue, quer ensine, Cristo está sempre em evidência. Em resumo, Paulo é um apóstolo de Jesus.\n\nJesus não é apenas o centro do apostolado de Paulo; Ele é o centro da vida de Paulo. Os pensamentos e sentimentos de Paulo estavam cheios da presença de Jesus. A prova disso é que ele se refere repetidamente a Jesus na saudação inicial e na seção de agradecimento de 1 Coríntios nove vezes em nove versículos (1 Coríntios 1:1-9). Paulo amava tanto Jesus que não conseguia parar de pensar e falar sobre Ele. Queria compartilhar Jesus com aqueles que estavam sob os seus cuidados para que a vida deles também fosse centrada em Cristo. Embora Paulo tenha sido chamado para ser apóstolo, eles foram chamados para ser seguidores fiéis de Jesus, em qualquer função para a qual o Senhor os chamasse.\n\nPaulo foi chamado para ser apóstolo. Qual é o seu chamado e como você sabe que essa é a sua vocação? Se você acha que não tem um chamado, o que pode estar errado na sua caminhada com Deus?",
      versiculoChave: { texto: "Certa noite Paulo teve uma visão em que o Senhor lhe disse: 'Não tenha medo! Pelo contrário; fale e não fique calado, porque Eu estou com você, e ninguém ousará lhe fazer mal, pois tenho muito povo nesta cidade'", referencia: "Atos 18:9, 10" },
      perguntas: [
        { id: "d2q1", pergunta: "Como Paulo se identifica no início da carta aos Coríntios?", opcoes: ["Servo dos judeus", "Apóstolo de Jesus, chamado pela vontade de Deus", "Rei de Corinto", "Discípulo de João Batista"], correta: 1, explicacao: "A resposta correta é: Apóstolo de Jesus, chamado pela vontade de Deus." },
        { id: "d2q2", pergunta: "Segundo o texto, de onde vem o chamado de Paulo?", opcoes: ["Dos homens", "De Deus, não dos homens", "Do imperador romano", "Da sinagoga de Corinto"], correta: 1, explicacao: "A resposta correta é: De Deus, não dos homens." },
        { id: "d2q3", pergunta: "Com quem Paulo se comparou quanto ao chamado desde o ventre da mãe?", opcoes: ["Isaías", "Jeremias", "Davi", "Moisés"], correta: 1, explicacao: "A resposta correta é: Jeremias." },
        { id: "d2q4", pergunta: "Quantas vezes Paulo menciona Jesus na saudação e ação de graças iniciais de 1 Coríntios (1:1-9)?", opcoes: ["Três vezes", "Cinco vezes", "Nove vezes", "Doze vezes"], correta: 2, explicacao: "A resposta correta é: Nove vezes." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-06-29",
      titulo: "De Atenas a Corinto",
      conteudo: "2. Leia Atos 17:16-34. Em que lugar Paulo esteve antes de ir a Corinto, e o que ele fez lá?\n\nAtos dos Apóstolos 17:16–34 descreve a pregação de Paulo aos atenienses antes de sua ida para Corinto. Aparentemente, ele não planejava visitar Atenas naquele momento, mas foi para lá com a ajuda de alguns amigos devido à oposição que enfrentou em Bereia (Atos dos Apóstolos 17:13–15).\n\nAqueles que acompanharam Paulo até Atenas retornaram a Bereia com a instrução de que Timóteo e Silas se juntassem a ele o mais rápido possível (Atos 17:15). Atos 17:16–34 relata o que Paulo fez enquanto os aguardava. Ele falou sobre Jesus na sinagoga, na praça pública e no Areópago. Paulo realmente não conseguia parar de falar sobre Jesus e aproveitava todas as oportunidades para fazê-lo.\n\n3. Leia Atos 18:1-11. O que Paulo fez ao chegar a Corinto e durante toda a sua permanência na cidade?\n\nPaulo foi para Corinto durante a sua segunda viagem missionária. Lucas informa-nos que Paulo permaneceu ali durante um ano e meio.\n\nComo de costume, Paulo inicia a sua atividade missionária na sinagoga (Atos 18:4–6). Atos 17:1, 2 menciona que esse era o seu costume. Ele seguia a estratégia de \"primeiro ao judeu\" (Romanos 1:16, Atos 13:46), exatamente como Jesus havia ordenado aos Seus apóstolos (ver Atos 1:8).\n\nQuando, finalmente, Silas e Timóteo se juntaram a ele em Corinto, Paulo \"se dedicava totalmente à palavra, testemunhando aos judeus que Jesus era o Cristo\" (Atos 18:5). Durante a sua permanência em Corinto, ele esteve ocupado \"ensinando a palavra de Deus\" (Atos 18:11).\n\nFoi também nesse contexto que ele expressou aquelas famosas palavras, afirmando que estava \"decidido a nada saber entre\" os coríntios \"senão a Jesus Cristo e este crucificado\" (1 Coríntios 2:2).\n\nO que podemos aprender, a partir da atuação missionária de Paulo em Atenas e Corinto, sobre aproveitar cada oportunidade para anunciar o evangelho? Pense nas oportunidades que você tem de compartilhar Jesus e em como utilizá-las.",
      versiculoChave: { texto: "Certa noite Paulo teve uma visão em que o Senhor lhe disse: 'Não tenha medo! Pelo contrário; fale e não fique calado, porque Eu estou com você, e ninguém ousará lhe fazer mal, pois tenho muito povo nesta cidade'", referencia: "Atos 18:9, 10" },
      perguntas: [
        { id: "d3q1", pergunta: "Onde Paulo esteve pregando antes de ir para Corinto?", opcoes: ["Éfeso", "Atenas", "Roma", "Jerusalém"], correta: 1, explicacao: "A resposta correta é: Atenas." },
        { id: "d3q2", pergunta: "Por que Paulo foi para Atenas?", opcoes: ["Planejava evangelizar a cidade havia anos", "Foi levado por amigos devido à oposição em Bereia", "Foi exilado pelos romanos", "Recebeu ordem do imperador"], correta: 1, explicacao: "A resposta correta é: Foi levado por amigos devido à oposição em Bereia." },
        { id: "d3q3", pergunta: "Quanto tempo Paulo permaneceu em Corinto, segundo Lucas?", opcoes: ["Seis meses", "Um ano e meio", "Três anos", "Uma semana"], correta: 1, explicacao: "A resposta correta é: Um ano e meio." },
        { id: "d3q4", pergunta: "Qual estratégia Paulo seguia ao chegar a uma nova cidade?", opcoes: ["Falar primeiro com os líderes políticos", "Iniciar pela sinagoga, \"primeiro ao judeu\"", "Evitar sinagogas", "Pregar apenas em praças públicas"], correta: 1, explicacao: "A resposta correta é: Iniciar pela sinagoga, \"primeiro ao judeu\"." }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-06-30",
      titulo: "A cidade de Corinto",
      conteudo: "4. Leia Atos 18:1-3; 1 Coríntios 5:9-11; 1 Coríntios 8:4. A partir desses textos, o que podemos concluir sobre a economia, a moralidade e a vida religiosa de Corinto?\n\nCorinto era um importante centro do mundo antigo, reconhecido pelo seu comércio próspero. A cidade foi destruída por Roma em 146 a.C. e reconstruída por Júlio César como uma colónia romana em 44 a.C. É essa Corinto romanizada que aparece no Novo Testamento. Na época de Paulo, Corinto era uma das rivais de Atenas e até a tinha superado em vários aspetos. Corinto possuía dois portos importantes que facilitavam a troca de mercadorias e o desenvolvimento do seu comércio.\n\nDe facto, Paulo escolheu Corinto devido à sua importância e à sua localização geográfica privilegiada. \"Apresentava-se assim uma oportunidade para a propagação do evangelho. Uma vez estabelecido em Corinto, este seria prontamente comunicado a todas as partes do mundo.\" — Ellen G. White, A Vida de Paulo, p. 69.\n\nAlém disso, o comércio florescente de Corinto tornaria mais fácil para Paulo sustentar-se produzindo e vendendo tendas enquanto proclamava o evangelho naquela cidade (Atos 18:2, 3). Evidentemente, o trabalho missionário numa cidade grande e rica não estava livre de desafios. Corinto era marcada por um evidente pluralismo religioso (1 Coríntios 8:5), como demonstravam os seus numerosos santuários construídos em homenagem a divindades como Apolo, Atena e Afrodite, entre outras, bem como o culto a deuses egípcios como Serápis e Ísis.\n\nAlém dessa confusão religiosa, Corinto também era conhecida pela sua libertinagem sexual. Estrabão, geógrafo e historiador grego, menciona que havia 1.000 prostitutas sagradas dedicadas ao culto de Afrodite no seu templo em Corinto. Embora muitos estudiosos vejam essa afirmação com desconfiança e a relacionem com a propaganda ateniense contra Corinto, a prostituição ritual era comum no mundo antigo. A imoralidade sexual era um problema em Corinto, assim como em muitos outros lugares. A idolatria e a imoralidade faziam parte da vida quotidiana, e esta triste realidade explica grande parte do conteúdo de 1 Coríntios e 2 Coríntios.\n\nEm Corinto, Paulo enfrentou o desafio de uma sociedade idólatra e permissiva. Quais aspectos da cultura atual dificultam a pregação do evangelho? Como superá-los? Em que medida nossas cidades diferem – se é que diferem – de Corinto?",
      versiculoChave: { texto: "Certa noite Paulo teve uma visão em que o Senhor lhe disse: 'Não tenha medo! Pelo contrário; fale e não fique calado, porque Eu estou com você, e ninguém ousará lhe fazer mal, pois tenho muito povo nesta cidade'", referencia: "Atos 18:9, 10" },
      perguntas: [
        { id: "d4q1", pergunta: "O que tornava Corinto um importante centro comercial?", opcoes: ["Suas montanhas", "Seus dois portos importantes", "Suas minas de ouro", "Sua universidade"], correta: 1, explicacao: "A resposta correta é: Seus dois portos importantes." },
        { id: "d4q2", pergunta: "Quem reconstruiu Corinto como colônia romana?", opcoes: ["Nero", "Júlio César", "Augusto", "Alexandre, o Grande"], correta: 1, explicacao: "A resposta correta é: Júlio César." },
        { id: "d4q3", pergunta: "Corinto era marcada por que características, segundo o texto?", opcoes: ["Austeridade religiosa e pobreza", "Pluralismo religioso e libertinagem sexual", "Isolamento cultural", "Ausência de comércio"], correta: 1, explicacao: "A resposta correta é: Pluralismo religioso e libertinagem sexual." },
        { id: "d4q4", pergunta: "Por que Paulo escolheu Corinto como base de trabalho?", opcoes: ["Por ser pequena e tranquila", "Por sua importância e localização estratégica para espalhar o evangelho", "Por já ter familiares lá", "Por ordem direta do imperador"], correta: 1, explicacao: "A resposta correta é: Por sua importância e localização estratégica para espalhar o evangelho." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-07-01",
      titulo: "Muita gente nesta cidade",
      conteudo: "5. Leia Atos 18:4-8. Quais foram os resultados da pregação de Paulo?\n\nAlgumas obras de Paulo entre os judeus em Corinto não foram tão frutíferas quanto ele desejava. Ele teve de enfrentar hostilidade e ódio. A Bíblia diz que \"eles se opunham e blasfemavam\" (Atos 18:6). Quando o objeto do verbo grego blasphēmeō (\"blasfemar\") é um ser humano, o significado é \"insultar\" ou \"difamar\". Em outras palavras, eles procuravam manchar a reputação de Paulo e impedir que ele tivesse êxito nos seus esforços missionários.\n\nFelizmente, o trabalho de Paulo na sinagoga de Corinto não foi em vão. Afinal, Deus estava à frente dessa missão. Ele prometeu: \"A minha palavra não voltará para Mim vazia\" (Isaías 55:11).\n\nAlguns judeus não esperavam que Crispo, o principal da sinagoga, e toda a sua família aceitassem Jesus como o Messias e fossem batizados (Atos 18:8). Além disso, \"muitos dos coríntios, ouvindo, criam e eram batizados\" (Atos 18:8), muito provavelmente também por causa da influência de Crispo.\n\n6. Leia Atos 18:9, 10. O que podemos deduzir sobre a reação de Paulo diante dos desafios em Corinto? Como Deus encorajou Seu servo?\n\nLogo após Paulo deixar a sinagoga, ele teve uma experiência que lhe trouxe encorajamento. O próprio Cristo apareceu-lhe de noite numa visão, com palavras que fazem lembrar Isaías 41:10: \"Não temas, porque Eu sou contigo\".\n\nDe facto, Paulo admite que esteve em Corinto \"em fraqueza, temor e grande tremor\" (1 Coríntios 2:3). Ele teve de sair de Bereia para Atenas devido à forte oposição que enfrentou. Ao que parece, pensava que teria de deixar Corinto pela mesma razão: a grande resistência ao seu trabalho. Mas desta vez isso não aconteceria.\n\nJesus disse-lhe: \"Porque Eu tenho muito povo nesta cidade\" (Atos 18:10). E Paulo era o instrumento escolhido por Cristo para levar a essas pessoas a mensagem da salvação.\n\nLeia Isaías 41:10. Quais promessas preciosas esse breve verso nos oferece? Como essas palavras devem impactar sua vida diária?",
      versiculoChave: { texto: "Certa noite Paulo teve uma visão em que o Senhor lhe disse: 'Não tenha medo! Pelo contrário; fale e não fique calado, porque Eu estou com você, e ninguém ousará lhe fazer mal, pois tenho muito povo nesta cidade'", referencia: "Atos 18:9, 10" },
      perguntas: [
        { id: "d5q1", pergunta: "Como os judeus reagiram à pregação de Paulo na sinagoga?", opcoes: ["Aceitaram imediatamente", "Opuseram-se e blasfemaram", "Ficaram indiferentes", "Pediram para ele ficar mais tempo"], correta: 1, explicacao: "A resposta correta é: Opuseram-se e blasfemaram." },
        { id: "d5q2", pergunta: "Quem era Crispo?", opcoes: ["Um apóstolo", "O principal da sinagoga que creu e foi batizado", "Um governador romano", "Um filósofo grego"], correta: 1, explicacao: "A resposta correta é: O principal da sinagoga que creu e foi batizado." },
        { id: "d5q3", pergunta: "O que Jesus disse a Paulo na visão noturna em Corinto?", opcoes: ["\"Vá embora desta cidade\"", "\"Não temas... tenho muito povo nesta cidade\"", "\"Espere por Silas e Timóteo\"", "\"Construa um templo aqui\""], correta: 1, explicacao: "A resposta correta é: \"Não temas... tenho muito povo nesta cidade\"." },
        { id: "d5q4", pergunta: "Como Paulo descreveu seu estado emocional em Corinto (1 Coríntios 2:3)?", opcoes: ["Com grande confiança e orgulho", "Em fraqueza, temor e grande tremor", "Indiferente aos resultados", "Cheio de raiva"], correta: 1, explicacao: "A resposta correta é: Em fraqueza, temor e grande tremor." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-07-02",
      titulo: "As cartas de Paulo aos coríntios",
      conteudo: "7. Leia 1 Coríntios 1:11-13; 4:14; 5:11; 7:1; 14:37, 40. Leia também 2 Coríntios 1:12; 2:9; 11:3; 13:10. Com base nesses textos, por que Paulo escreveu cartas aos cristãos de Corinto?\n\nPaulo estava em Éfeso quando escreveu 1 Coríntios (1 Coríntios 16:5–9). A família de Cloé foi até ele com a notícia de que as coisas não estavam a correr muito bem em Corinto (1 Coríntios 1:11). Em 1 Coríntios 1–6, Paulo aborda os problemas relatados pela família de Cloé. Esses problemas incluíam divisões e facções, imoralidade sexual, processos judiciais entre irmãos e prostituição.\n\nPaulo também recebeu uma carta contendo perguntas específicas (1 Coríntios 7:1). A sua resposta ocupa o restante da epístola, a partir do capítulo 7. As perguntas estavam relacionadas com casamento, divórcio, celibato, alimentos sacrificados aos ídolos, comportamento no culto, uso dos dons espirituais e compreensão incorreta da ressurreição. A igreja de Corinto era muito problemática e imatura. Talvez a sua igreja local também enfrente muitos problemas. Ainda assim, a igreja de Corinto provavelmente enfrentava dificuldades ainda maiores.\n\nA primeira carta de Paulo aos Coríntios é muito relevante para os nossos dias. Afinal, não enfrentamos nós, em alguma medida, alguns dos mesmos problemas em muitas das nossas igrejas? Esta carta tem muito a dizer-nos. Ela é \"uma das mais ricas, instrutivas e poderosas de todas as suas cartas.\" — Ellen G. White, Atos dos Apóstolos, p. 192.\n\nPaulo pode ter escrito três ou quatro cartas aos coríntios (compare com 2 Coríntios 10:9). Ele escreveu uma carta anterior a 1 Coríntios (1 Coríntios 5:9), mas essa carta perdeu-se. Antes de 2 Coríntios, escreveu outra carta que os estudiosos chamam de \"carta severa\" (2 Coríntios 2:3, 4, 9; 2 Coríntios 7:8), mas essa também se perdeu. Alguns acreditam que Paulo esteja a referir-se a 1 Coríntios, ou que partes dessa carta tenham sido preservadas em 2 Coríntios. Por meio de 2 Coríntios, percebemos que os membros da igreja em Corinto eram fortemente influenciados pela cultura ao seu redor. Eles valorizavam a competição, o poder e a riqueza — coisas que também podem representar desafios para a igreja nos dias de hoje. Em contraste, Paulo procurava formar uma cultura centrada em Cristo, uma maneira de enxergar o mundo através da lente do evangelho.\n\nLeia novamente 2 Coríntios 2:4. O que esse texto revela sobre o quanto Paulo se importava com aquelas pessoas? Por outro lado, quão frio o nosso coração pode ser para com os outros?",
      versiculoChave: { texto: "Certa noite Paulo teve uma visão em que o Senhor lhe disse: 'Não tenha medo! Pelo contrário; fale e não fique calado, porque Eu estou com você, e ninguém ousará lhe fazer mal, pois tenho muito povo nesta cidade'", referencia: "Atos 18:9, 10" },
      perguntas: [
        { id: "d6q1", pergunta: "Quem trouxe a Paulo a notícia dos problemas na igreja de Corinto?", opcoes: ["Timóteo", "A família de Cloé", "Silas", "Apolo"], correta: 1, explicacao: "A resposta correta é: A família de Cloé." },
        { id: "d6q2", pergunta: "Onde Paulo estava quando escreveu 1 Coríntios?", opcoes: ["Corinto", "Éfeso", "Roma", "Filipos"], correta: 1, explicacao: "A resposta correta é: Éfeso." },
        { id: "d6q3", pergunta: "Quantas cartas Paulo pode ter escrito aos coríntios, segundo o texto?", opcoes: ["Apenas uma", "Três ou quatro", "Dez", "Nenhuma além de 1 e 2 Coríntios"], correta: 1, explicacao: "A resposta correta é: Três ou quatro." },
        { id: "d6q4", pergunta: "O que aconteceu com a \"carta severa\" e a carta anterior a 1 Coríntios mencionadas no texto?", opcoes: ["Foram preservadas na íntegra", "Se perderam", "Foram traduzidas para o grego moderno", "Nunca existiram"], correta: 1, explicacao: "A resposta correta é: Se perderam." }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-07-03",
      titulo: "Estudo Adicional - O ministério de Paulo em Corinto",
      conteudo: "Leia Ellen G. White, Atos dos Apóstolos, \"Corinto\" (p. 155-161).\n\n\"Ao pregar o evangelho em Corinto, o apóstolo seguiu um caminho diferente daquele que havia marcado seus trabalhos em Atenas. [...] Ele decidiu evitar argumentos e discussões elaboradas e 'não saber nada' entre os coríntios 'a não ser Jesus Cristo, e este crucificado'.\" — Ellen G. White, Atos dos Apóstolos, p. 155.\n\n\"Paulo teve um certo sucesso\", mas \"duvidava da sabedoria de construir uma igreja a partir do material que encontrou lá. Ele considerava Corinto um campo de trabalho muito questionável e decidiu deixá-lo. . . .\"\n\n\"Enquanto ponderava sobre deixar a cidade em busca de um campo mais promissor, [...] o Senhor lhe apareceu numa visão noturna e disse: 'Não tenha medo; mas fale, [...] pois tenho muita gente nesta cidade.' Paulo entendeu isso como uma ordem para permanecer em Corinto e uma garantia de que o Senhor daria fruto à semente semeada. [...] Uma grande igreja foi inscrita sob a bandeira de Jesus Cristo.\" — Ellen G. White, A Vida de Paulo, p. 74, 75.\n\n\"Há registros de que Paulo trabalhou um ano e seis meses em Corinto. Seus esforços, porém, não se limitaram exclusivamente àquela cidade. [...] Ele fez de Corinto seu quartel-general. [...] Diversas igrejas foram assim fundadas. [...] A ausência de Paulo das igrejas sob seus cuidados foi parcialmente suprida por comunicações importantes e impactantes, que foram geralmente recebidas como a palavra de Deus. [...] Essas epístolas foram lidas nas igrejas.\" — A vida de Paulo, p. 76.\n\nQuestões para discussão:\n\n1. Por um momento, Paulo pensou em desistir de sua obra missionária em Corinto e deixar a cidade. O que o fez mudar de ideia? Como isso pode nos ajudar quando queremos desistir da missão?\n\n2. Os coríntios eram fortemente influenciados pela cultura ao redor. Essa também é uma dura realidade entre nós hoje. Como estar no mundo (João 17:11, 15) sem nos deixarmos influenciar por ele? Como nossa igreja tem sido negativamente influenciada pela cultura que a cerca?",
      versiculoChave: { texto: "Certa noite Paulo teve uma visão em que o Senhor lhe disse: 'Não tenha medo! Pelo contrário; fale e não fique calado, porque Eu estou com você, e ninguém ousará lhe fazer mal, pois tenho muito povo nesta cidade'", referencia: "Atos 18:9, 10" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo Ellen White, o que Paulo decidiu evitar ao pregar em Corinto?", opcoes: ["Falar sobre a cruz", "Argumentos e discussões elaboradas", "Visitar sinagogas", "Fazer tendas"], correta: 1, explicacao: "A resposta correta é: Argumentos e discussões elaboradas." },
        { id: "d7q2", pergunta: "O que fez Paulo mudar de ideia sobre deixar Corinto?", opcoes: ["Um conselho de Timóteo", "A visão em que o Senhor disse que tinha muita gente naquela cidade", "Uma carta de Éfeso", "A chegada de Silas"], correta: 1, explicacao: "A resposta correta é: A visão em que o Senhor disse que tinha muita gente naquela cidade." },
        { id: "d7q3", pergunta: "Segundo o texto de Ellen White, quanto tempo Paulo trabalhou em Corinto?", opcoes: ["Seis meses", "Um ano e seis meses", "Dois anos", "Uma semana"], correta: 1, explicacao: "A resposta correta é: Um ano e seis meses." },
        { id: "d7q4", pergunta: "O que supria parcialmente a ausência de Paulo das igrejas sob seus cuidados?", opcoes: ["Visitas de outros apóstolos", "Suas cartas/epístolas", "Nada, as igrejas ficavam sem orientação", "Visitas do imperador"], correta: 1, explicacao: "A resposta correta é: Suas cartas/epístolas." }
      ]
    }
  ]
};
