export const LICAO_LA_11 = {
  titulo: "Lição 11 - O Fim do Mundo (5 a 11 de dezembro)",
  semana: "2026-W49",
  trimestre: "Livro Aberto",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-12-05",
      titulo: "TEASER",
      conteudo: "O tempo de angústia será um período terrível para aqueles que não conhecem a Deus, mas para o Seu povo será um momento de vitória. Deus protegerá Seu povo.\n\nMuitas vezes, nos concentramos nas grandes dificuldades do tempo do fim e nos esquecemos de enfatizar o infinito poder de Deus para libertar e proteger Seus fiéis.\n\nTer medo dos acontecimentos do tempo do fim é natural. Na verdade, até mesmo os que não professam nenhuma religião ficam nervosos ao observar os sinais ao nosso redor. Muitas pessoas depositam a fé em antigos calendários que predizem a data do fim do mundo. Outras criam teorias da conspiração para explicar os sinais da volta de Jesus. Outras ainda afirmam que este mundo será destruído por alienígenas ou que o próprio ser humano se autodestruirá com uma guerra nuclear. Algumas creem que um asteroide atingirá nosso planeta e destruirá a vida por completo. Por que há tanta especulação sobre o fim do mundo? Porque Deus colocou algo em nosso coração para nos advertir. Ao olharmos para Deus, sabemos que Jesus virá para nos libertar da miséria e da dor. Quando não olhamos para Deus, nosso coração se enche de temor do desconhecido e de um terrível senso de impotência e falta de controle.\n\nDeus protegerá o Seu povo. Ele o libertará. Precisamos sempre nos lembrar disso! Não estamos sozinhos, mas seguros nos braços poderosos de Deus.",
      versiculoChave: { texto: "Nessa época, Miguel, o grande príncipe que guarda Seu povo, se levantará. [...] Muitos dos que estão mortos e enterrados ressuscitarão, alguns para a vida eterna e outros para a vergonha e a desonra eterna.", referencia: "Daniel 12:1,2" },
      perguntas: [
        { id: "d1q1", pergunta: "Segundo o texto, para quem o tempo de angústia será um momento de vitória?", opcoes: ["Para os que não conhecem a Deus", "Para o povo de Deus", "Para os incrédulos em geral", "Para nenhum grupo específico"], correta: 1, explicacao: "Para o povo de Deus, o tempo de angústia será um momento de vitória, diz o texto." },
        { id: "d1q2", pergunta: "Julgue: segundo o texto, algumas pessoas explicam os sinais do fim por meio de teorias da conspiração ou da crença em um asteroide que destruiria a Terra.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto cita teorias da conspiração e a crença de que um asteroide atingiria e destruiria o planeta." },
        { id: "d1q3", pergunta: "Segundo o texto, o que Deus colocou em nosso coração, segundo a explicação dada para tanta especulação sobre o fim do mundo?", opcoes: ["Algo para nos advertir", "Um desejo por aventura", "Curiosidade científica", "Medo da tecnologia"], correta: 0, explicacao: "'Porque Deus colocou algo em nosso coração para nos advertir', diz o texto." },
        { id: "d1q4", pergunta: "O que acontece com nosso coração quando NÃO olhamos para Deus, segundo o texto?", opcoes: ["Ele se enche de coragem e determinação", "Ele se enche de temor do desconhecido e impotência", "Ele permanece indiferente aos acontecimentos", "Ele se volta automaticamente para a ciência"], correta: 1, explicacao: "Quando não olhamos para Deus, nosso coração se enche de temor do desconhecido e de um terrível senso de impotência e falta de controle." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-12-06",
      titulo: "ROTEIRO ORIGINAL",
      conteudo: "Quando pensa na volta de Jesus, que sentimentos você tem? Medo, insegurança, alegria, confiança, ansiedade? Os sentimentos costumam estar relacionados e ser proporcionais ao conhecimento que temos das situações. Quanto você sabe a respeito da volta de Jesus? Leia em sua Bíblia as seguintes passagens: Daniel 12:1,2; Apocalipse 1:7; Apocalipse 7:14-17; 1 Tessalonicenses 4:16-18; João 14:1-4. Elas vão ajudá-lo a ter uma ideia da sequência dos eventos. Depois, responda às perguntas abaixo:\n\nCom base nesses textos, que tipo de imagem mental você faz sobre a vinda de Jesus?\n\nQue recompensas estão destinadas àqueles que têm sido fiéis a Deus?\n\nEm sua opinião, o que significa ser fiel a Deus? O que Ele espera de nós?\n\nVocê acha que permanecer firme pelo corpo de doutrinas da igreja, e até mesmo morrer por causa delas, é o que Deus espera de nós? A doutrina vai ser importante no 'tempo do fim'? Por que sim ou por que não?",
      versiculoChave: { texto: "Nessa época, Miguel, o grande príncipe que guarda Seu povo, se levantará. [...] Muitos dos que estão mortos e enterrados ressuscitarão, alguns para a vida eterna e outros para a vergonha e a desonra eterna.", referencia: "Daniel 12:1,2" },
      perguntas: [
        { id: "d2q1", pergunta: "Quais destas passagens bíblicas o Roteiro Original de hoje pede para ler?", opcoes: ["Daniel 12:1,2; Apocalipse 1:7; Ap 7:14-17; 1Tessalonicenses 4:16-18; João 14:1-4", "Gênesis 1-3; Êxodo 20; Levítico 16", "Mateus 24; Marcos 13; Lucas 21", "Apocalipse 21 e 22 apenas"], correta: 0, explicacao: "O texto pede a leitura de Daniel 12:1,2; Apocalipse 1:7; Ap 7:14-17; 1Tessalonicenses 4:16-18; João 14:1-4." },
        { id: "d2q2", pergunta: "Segundo o texto, os sentimentos que temos a respeito da volta de Jesus costumam ser proporcionais a quê?", opcoes: ["Ao conhecimento que temos das situações", "À idade que temos", "Ao tamanho da nossa igreja", "Ao número de amigos cristãos que temos"], correta: 0, explicacao: "'Os sentimentos costumam estar relacionados e ser proporcionais ao conhecimento que temos das situações.'" },
        { id: "d2q3", pergunta: "Julgue: segundo o texto, saber a respeito da volta de Jesus não influencia os sentimentos que temos sobre esse evento.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "Pelo contrário: os sentimentos costumam ser proporcionais ao conhecimento que temos das situações, segundo o texto." },
        { id: "d2q4", pergunta: "O texto de hoje pergunta sobre recompensas destinadas a quem?", opcoes: ["Àqueles que têm sido fiéis a Deus", "Apenas aos apóstolos originais", "Aos anjos que guardam o povo de Deus", "Aos que constroem templos"], correta: 0, explicacao: "O texto pergunta que recompensas estão destinadas àqueles que têm sido fiéis a Deus." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-12-07",
      titulo: "ZOOM",
      conteudo: "Leia o Texto-Chave desta semana, que se encontra em Daniel 12:1,2. Observe que é a continuação do verso da semana passada. O destaque aqui está na ressurreição. As pessoas que despertarão do sono da morte quando Jesus voltar são aquelas que O escolheram como Senhor de sua vida. Elas ouvirão a Sua voz e acordarão para encontrar-se com Ele.\n\nSobre elas é dito o seguinte: 'Os últimos traços da maldição do pecado serão removidos. Na mente, na alma e no corpo, os fiéis de Cristo refletirão a perfeita imagem de seu Senhor' (Os Resgatados, p. 323). Os justos vivos também serão transformados e levados para o Céu junto com os fiéis ressuscitados, para viverem eternamente felizes. Será um momento incrível!\n\nNo entanto, o texto bíblico fala de um outro grupo que também será ressuscitado, mas com outro objetivo. Veja quem fará parte da chamada ressurreição especial:\n\n'Aqueles que zombaram de Cristo em Sua humilhação estão ali. [...] Ali está o arrogante Herodes que ridicularizou Seu título real. Ali estão os homens que colocaram a coroa de espinhos em Sua fronte e a imitação de cetro em Sua mão – aqueles que se prostraram perante Ele em zombaria blasfema, que cuspiram no Príncipe da vida. Aqueles que cravaram os pregos em Suas mãos e pés olharão para as marcas com terror e remorso' (Os Resgatados, p. 322). Além destes, estarão ali os sacerdotes e governantes que crucificaram Jesus.\n\nNossas escolhas hoje estão determinando a que grupo desejamos pertencer. Que nossa reação seja de alegria com o retorno de Jesus!",
      versiculoChave: { texto: "Nessa época, Miguel, o grande príncipe que guarda Seu povo, se levantará. [...] Muitos dos que estão mortos e enterrados ressuscitarão, alguns para a vida eterna e outros para a vergonha e a desonra eterna.", referencia: "Daniel 12:1,2" },
      perguntas: [
        { id: "d3q1", pergunta: "Em que texto se encontra o Texto-Chave desta semana, segundo o Zoom de hoje?", opcoes: ["Daniel 12:1,2", "Apocalipse 20:6", "1 Tessalonicenses 4:17", "João 14:3"], correta: 0, explicacao: "O Texto-Chave desta semana se encontra em Daniel 12:1,2, conforme o texto de hoje." },
        { id: "d3q2", pergunta: "Segundo o Comentário citado (Os Resgatados, p. 323), o que acontecerá aos últimos traços da maldição do pecado?", opcoes: ["Serão removidos", "Serão registrados como lembrança", "Permanecerão visíveis para sempre", "Serão transferidos para Satanás"], correta: 0, explicacao: "'Os últimos traços da maldição do pecado serão removidos', segundo Os Resgatados, p. 323." },
        { id: "d3q3", pergunta: "Segundo o texto, quem faz parte do outro grupo da 'ressurreição especial' mencionado hoje?", opcoes: ["Apenas os apóstolos de Jesus", "Apenas os profetas do Antigo Testamento", "Aqueles que zombaram de Cristo, como Herodes e os que O crucificaram", "Apenas os anjos que anunciaram a ressurreição"], correta: 2, explicacao: "O texto cita os que zombaram de Cristo, o arrogante Herodes, os soldados e os sacerdotes e governantes que O crucificaram." },
        { id: "d3q4", pergunta: "Julgue: segundo o texto, a 'ressurreição especial' descrita hoje é composta por fiéis que creram em Cristo e por isso serão recompensados.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "Pelo contrário: a ressurreição especial inclui os que zombaram de Cristo, como Herodes, os soldados e os que O crucificaram — não os fiéis recompensados." }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-12-08",
      titulo: "MAKING OF",
      conteudo: "Quando parecer não haver nenhuma saída para o povo de Deus e as multidões estiverem prestes a avançar sobre os fiéis, se ouvirá uma voz que abalará os céus e a terra. Acontecerá um grande terremoto e o mar se agitará em fúria. Os ímpios ficarão aterrorizados, mas os salvos louvarão a Deus pelo livramento.\n\nA nuvem que anuncia a vinda de Jesus será pequena e escura no início. À medida que o Salvador Se aproximar, ela se tornará branca e cada vez maior. A base dela é descrita como uma glória semelhante ao fogo consumidor. Acima dela estará o arco-íris da aliança.\n\nOs salvos são chamados na Bíblia de 'os resgatados'.\n\nTodas as pessoas verão Cristo voltar. Ele usará uma coroa de glória na fronte. E em Seu manto e em Sua coxa estará escrito: 'REI DOS REIS E SENHOR DOS SENHORES' (Apocalipse 19:16).\n\n'Embora as tristezas, dores e tentações da Terra tenham acabado e sua causa tenha sido removida, o povo de Deus sempre terá o conhecimento distinto e inteligente do preço de sua salvação. A cruz será o cântico dos remidos ao longo de toda a eternidade' (Os Resgatados, p. 326).\n\nO próprio Jesus colocará a coroa de glória na cabeça dos vencedores. Cada um receberá a coroa com um novo nome (Apocalipse 2:17) e a inscrição: santidade ao Senhor.",
      versiculoChave: { texto: "REI DOS REIS E SENHOR DOS SENHORES", referencia: "Apocalipse 19:16" },
      perguntas: [
        { id: "d4q1", pergunta: "Como a Bíblia chama os salvos, segundo o texto de hoje?", opcoes: ["Os eleitos apenas", "Os resgatados", "Os vencedores da fé", "Os remanescentes puros"], correta: 1, explicacao: "'Os salvos são chamados na Bíblia de os resgatados', diz o texto." },
        { id: "d4q2", pergunta: "O que estará escrito no manto e na coxa de Jesus quando Ele voltar, segundo Apocalipse 19:16 citado no texto?", opcoes: ["Rei dos Reis e Senhor dos Senhores", "Santo, Santo, Santo é o Senhor", "Fiel e Verdadeiro", "Alfa e Ômega"], correta: 0, explicacao: "Estará escrito 'REI DOS REIS E SENHOR DOS SENHORES' (Ap 19:16)." },
        { id: "d4q3", pergunta: "Segundo o texto, como será descrita a base da nuvem que anuncia a vinda de Jesus?", opcoes: ["Como uma escuridão total e fria", "Como uma glória semelhante ao fogo consumidor", "Como uma névoa fina e transparente", "Como um brilho azulado suave"], correta: 1, explicacao: "A base da nuvem é descrita como uma glória semelhante ao fogo consumidor, com o arco-íris da aliança acima dela." },
        { id: "d4q4", pergunta: "Julgue: segundo o texto, cada vencedor receberá uma coroa com um novo nome e a inscrição 'santidade ao Senhor'.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto afirma que cada vencedor receberá a coroa com um novo nome (Ap 2:17) e a inscrição: santidade ao Senhor." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-12-09",
      titulo: "EXTRAS",
      conteudo: "Leia e marque em sua Bíblia os textos adicionais desta semana.\n\nO texto de Eclesiastes 3:11,12 é muito bonito. Salomão disse que Deus colocou o desejo pela eternidade no coração do homem. O plano divino era que o ser humano vivesse eternamente. Se Adão e Eva não tivessem desobedecido, esse teria sido o destino da humanidade. No entanto, ao pecar, o casal teve que deixar o jardim do Éden e não pôde mais se alimentar da árvore da vida, que era o que os manteria vivendo para sempre.\n\nMuitas vezes Satanás se aproveita desse 'desejo pela eternidade' para enganar as pessoas e convencê-las de que o ser humano é naturalmente imortal. Essa é uma grande mentira. A imortalidade só será restituída à humanidade quando ela tiver acesso novamente à árvore da vida. Só poderemos receber esse presente de volta por causa do que Jesus fez por todos nós. Como disse João (3:36, NVI): 'Quem crê no Filho tem a vida eterna; já quem rejeita o Filho não verá a vida.'\n\nA profecia diz que, por ocasião da volta de Jesus, Adão será ressuscitado e conduzido ao Éden restaurado, onde poderá novamente se alimentar da árvore da vida, para então, sim, viver eternamente. Que boa notícia, não é? Ele e todos nós viveremos felizes para sempre.\n\nTextos adicionais: Miquéias 6:8; Eclesiastes 3:11,12; Mateus 24:36-39.",
      versiculoChave: { texto: "Quem crê no Filho tem a vida eterna; já quem rejeita o Filho não verá a vida.", referencia: "João 3:36 (NVI)" },
      perguntas: [
        { id: "d5q1", pergunta: "Segundo o texto, o que Salomão disse que Deus colocou no coração do homem (Eclesiastes 3:11)?", opcoes: ["O desejo pela eternidade", "O desejo por riquezas", "O medo da morte", "O desejo por sabedoria"], correta: 0, explicacao: "Salomão disse que Deus colocou o desejo pela eternidade no coração do homem." },
        { id: "d5q2", pergunta: "O que Adão e Eva perderam o direito de fazer depois de pecar, segundo o texto?", opcoes: ["De orar diretamente a Deus", "De se alimentar da árvore da vida", "De trabalhar a terra", "De ter filhos"], correta: 1, explicacao: "Ao pecar, o casal não pôde mais se alimentar da árvore da vida, que era o que os manteria vivendo para sempre." },
        { id: "d5q3", pergunta: "Julgue: segundo o texto, a Bíblia ensina que o ser humano é naturalmente imortal, e por isso não precisa da árvore da vida.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "O texto chama isso de 'grande mentira'; a imortalidade só será restituída quando tivermos acesso novamente à árvore da vida, por causa do que Jesus fez por nós." },
        { id: "d5q4", pergunta: "Segundo João 3:36 (NVI), citado no texto, o que acontece com quem rejeita o Filho?", opcoes: ["Recebe uma segunda chance após mil anos", "Não verá a vida", "Vive eternamente, mas sem alegria", "Se torna anjo caído"], correta: 1, explicacao: "'Já quem rejeita o Filho não verá a vida' (João 3:36, NVI)." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-12-10",
      titulo: "PANORÂMICA",
      conteudo: "Ellen White nos dá um vislumbre único de Deus após a destruição do pecado. Leia todo o capítulo 40 do livro Os Resgatados. Ela conta como acontecerá o livramento do povo de Deus e dá os detalhes desse evento tão grandioso da história deste mundo: a volta de Jesus para buscar os redimidos.\n\nAs últimas palavras desse capítulo descrevem a reação de Deus Pai e do Seu Filho. Depois de tudo o que Jesus suportou na Terra, depois de toda a miséria do pecado e da batalha ter sido travada entre o bem e o mal, Deus e Jesus concordaram que valeu a pena. Sabe por quê? Porque travar essa batalha trouxe você para o lar! Você, pessoalmente, vale todo esse esforço. Saber disso não torna mais fácil acreditar que Deus está completamente interessado em você e no que precisa ser feito para tê-lo com Ele no Céu?\n\n'Ficará claro que o Deus infinito em sabedoria não poderia inventar nenhum plano para a nossa salvação, com exceção do sacrifício do próprio Filho. Sua recompensa por esse sacrifício será a alegria de povoar a Terra com os seres resgatados, santos, felizes e imortais. O valor de cada pessoa é tão grande que o Pai ficará satisfeito com o preço pago. O próprio Cristo, ao ver os frutos de Seu grande sacrifício, estará satisfeito' (Os Resgatados, p. 327).",
      versiculoChave: { texto: "Nessa época, Miguel, o grande príncipe que guarda Seu povo, se levantará. [...] Muitos dos que estão mortos e enterrados ressuscitarão, alguns para a vida eterna e outros para a vergonha e a desonra eterna.", referencia: "Daniel 12:1,2" },
      perguntas: [
        { id: "d6q1", pergunta: "Qual capítulo do livro Os Resgatados o texto de hoje pede para ler por completo?", opcoes: ["Capítulo 40", "Capítulo 27", "Capítulo 41", "Capítulo 13"], correta: 0, explicacao: "O texto pede a leitura de todo o capítulo 40 do livro Os Resgatados." },
        { id: "d6q2", pergunta: "Segundo o texto, o que trouxe Deus e Jesus a concordar que 'valeu a pena', depois de toda a batalha entre o bem e o mal?", opcoes: ["O fato de trazer você para o lar", "O fim do sofrimento dos anjos", "A destruição definitiva de Satanás", "A criação de um novo universo"], correta: 0, explicacao: "'Porque travar essa batalha trouxe você para o lar!' — foi isso que fez valer a pena, segundo o texto." },
        { id: "d6q3", pergunta: "Segundo a citação de Os Resgatados (p. 327), qual seria a recompensa de Deus pelo sacrifício do próprio Filho?", opcoes: ["A alegria de povoar a Terra com os seres resgatados, santos, felizes e imortais", "O fim de todo o Universo", "A criação de novos anjos", "Um novo julgamento para os salvos"], correta: 0, explicacao: "'Sua recompensa por esse sacrifício será a alegria de povoar a Terra com os seres resgatados, santos, felizes e imortais.'" },
        { id: "d6q4", pergunta: "Julgue: segundo o texto, o valor de cada pessoa salva é tão grande que o Pai ficará satisfeito com o preço pago por sua salvação.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "'O valor de cada pessoa é tão grande que o Pai ficará satisfeito com o preço pago', segundo Os Resgatados, p. 327." }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-12-11",
      titulo: "OFF",
      conteudo: "Muitas vezes, ao pensarmos no tempo de angústia e nas coisas que sobrevirão aos que escolheram confiar no Senhor e guardar Seus mandamentos, ficamos tomados de medo e pavor. Pensamos nas dificuldades e duras provações que teremos que enfrentar. Ficamos ansiosos ao imaginar as cenas que precederão a volta de Jesus. Mas não precisamos sentir-nos assim. Deus prometeu cuidar de Seu povo durante esse período crítico.\n\nSe lermos as promessas ao longo da Bíblia a respeito de como Deus cuidará de Seu povo sem permitir que pereçam, se lermos as descrições do Espírito de Profecia de como Deus protegerá Seu povo e o libertará, perceberemos que não temos nada a temer.\n\nA libertação de Deus vai muito além desse tempo difícil. Ele nos libertará deste mundo de pecado e nos dará um lar em que não mais haverá dor ou morte. Ele nos libertará da tristeza, da ansiedade e do medo. Todo sofrimento será esquecido.\n\nQual será a reação a tanto amor?\n\nAcredite: vale a pena confiar em Deus!\n\n'O mundo é muito diferente agora. Visto que homens detêm em suas mãos mortais o poder para abolir todas as formas de pobreza humana e todas as formas de vida humana' (John F. Kennedy).\n\n'A sobrevivência do planeta tem se tornado tão incerta que qualquer esforço, qualquer pensamento que pressupõe um futuro garantido representa um risco muito grande' (Elias Canetti).\n\nVeja este importante detalhe sobre a reação dos ímpios à volta de Jesus: 'As piadas zombeteiras terminam; os lábios mentirosos são silenciados. Nada se ouve, a não ser a voz de oração e o som de pranto. Os ímpios oram para ser enterrados debaixo das rochas, em vez de precisar enfrentar a face Daquele a quem desprezaram. Conhecem muito bem aquela voz que penetra o ouvido dos mortos. Quantas vezes, em tons mais ternos, essa mesma voz os chamou ao arrependimento! Quantas vezes eles a ouviram nos apelos de um amigo, um irmão, um Redentor. Oh, se tão somente fosse a voz de um estranho! A voz desperta memórias de advertências que eles desprezaram e de convites que recusaram' (Os Resgatados, p. 322).",
      versiculoChave: { texto: "Nessa época, Miguel, o grande príncipe que guarda Seu povo, se levantará. [...] Muitos dos que estão mortos e enterrados ressuscitarão, alguns para a vida eterna e outros para a vergonha e a desonra eterna.", referencia: "Daniel 12:1,2" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo o texto, o que Deus prometeu fazer com Seu povo durante o tempo de angústia?", opcoes: ["Cuidar dele durante esse período crítico", "Retirá-lo da Terra imediatamente", "Testá-lo com novas provações", "Ignorar suas orações temporariamente"], correta: 0, explicacao: "'Deus prometeu cuidar de Seu povo durante esse período crítico', diz o texto." },
        { id: "d7q2", pergunta: "Segundo o texto, além da tristeza e do medo, de que mais a libertação de Deus nos livrará?", opcoes: ["Da ansiedade, e todo sofrimento será esquecido", "Apenas das doenças físicas", "Da necessidade de trabalhar", "Da convivência com outras pessoas"], correta: 0, explicacao: "'Ele nos libertará da tristeza, da ansiedade e do medo. Todo sofrimento será esquecido.'" },
        { id: "d7q3", pergunta: "Segundo a citação atribuída a John F. Kennedy no texto de hoje, o que os homens detêm em suas mãos mortais?", opcoes: ["O poder para abolir todas as formas de pobreza e de vida humana", "O poder de curar todas as doenças", "O controle sobre o clima do planeta", "A capacidade de viajar a outros planetas"], correta: 0, explicacao: "JFK é citado dizendo que os homens detêm em suas mãos mortais o poder para abolir todas as formas de pobreza humana e todas as formas de vida humana." },
        { id: "d7q4", pergunta: "Julgue: segundo o texto de hoje, os ímpios, ao voltarem na ressurreição especial, poderão ouvir novamente a voz que antes desprezaram, chamando-os ao arrependimento.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto (Os Resgatados, p. 322) diz que eles conhecem bem aquela voz que já os chamou ao arrependimento muitas vezes." }
      ]
    }
  ]
};

export const LICAO_LA_12 = {
  titulo: "Lição 12 - Terra Purificada (12 a 18 de dezembro)",
  semana: "2026-W50",
  trimestre: "Livro Aberto",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-12-12",
      titulo: "TEASER",
      conteudo: "Depois do milênio, a Terra será renovada, mas nessa ocasião também os ímpios serão destruídos. Essa não é uma imagem que idealizamos, no entanto, esse ato é necessário para que o pecado seja erradicado de uma vez por todas, e assim, vivamos em paz e felicidade por toda eternidade.\n\nO sentimento de pena é natural ao conhecermos o fim dos ímpios. Ellen White, porém, concedeu-nos uma visão singular do que passará na mente deles antes de serem destruídos. Não haverá arrependimento pela dor e sofrimento que causaram, mas decepção e tristeza pela vitória e triunfo de Deus. São irredimíveis.\n\nO amor de Deus por nós, e pelo ímpio irredimível, é muito maior do que podemos imaginar. Deus não deseja destruir ninguém e por isso tem esperado tanto, para que todos tenham a oportunidade de arrepender-se e mudar. O milênio será um período em que comprovaremos a bondade e a justiça de Deus ao julgar os seres humanos. Teremos a oportunidade de fazer perguntas, entender o motivo da decisão divina e testemunhar Deus provar Sua bondade ao Universo.\n\nVocê sonha com esse momento?",
      versiculoChave: { texto: "Contudo, o dia do Senhor virá como um ladrão. Os céus desaparecerão com terrível estrondo, e até os elementos serão consumidos pelo fogo, e a terra e tudo que nela há serão expostos.", referencia: "2 Pedro 3:10" },
      perguntas: [
        { id: "d1q1", pergunta: "Segundo o texto, por que a destruição dos ímpios, depois do milênio, é necessária?", opcoes: ["Para que o pecado seja erradicado de uma vez por todas", "Para aumentar o número de anjos no Céu", "Para provar que Deus é mais forte que Satanás", "Para punir apenas os líderes do mal"], correta: 0, explicacao: "É necessário 'para que o pecado seja erradicado de uma vez por todas', diz o texto." },
        { id: "d1q2", pergunta: "Segundo Ellen White, citada no texto, o que os ímpios NÃO sentirão antes de serem destruídos?", opcoes: ["Arrependimento pela dor e sofrimento que causaram", "Decepção pela derrota", "Tristeza pelo triunfo de Deus", "Medo do fogo"], correta: 0, explicacao: "'Não haverá arrependimento pela dor e sofrimento que causaram, mas decepção e tristeza pela vitória e triunfo de Deus.'" },
        { id: "d1q3", pergunta: "Qual é o propósito do milênio, segundo o texto de hoje?", opcoes: ["Comprovar a bondade e a justiça de Deus ao julgar os seres humanos", "Dar tempo para Satanás se arrepender", "Preparar a Nova Jerusalém para descer à Terra", "Permitir que os ímpios ressuscitem imediatamente"], correta: 0, explicacao: "'O milênio será um período em que comprovaremos a bondade e a justiça de Deus ao julgar os seres humanos.'" },
        { id: "d1q4", pergunta: "Julgue: segundo o texto, o amor de Deus até pelo ímpio irredimível é muito maior do que podemos imaginar.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "'O amor de Deus por nós, e pelo ímpio irredimível, é muito maior do que podemos imaginar', afirma o texto." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-12-13",
      titulo: "ROTEIRO ORIGINAL",
      conteudo: "Dragão, serpente, correntes, abismo, tronos, julgamento, lago de fogo... O que esses elementos têm que ver com o fim deste mundo? Você vai descobrir ao ler a passagem bíblica para o estudo desta semana: o capítulo 20 de Apocalipse apresenta em lances rápidos e objetivos a sequência dos eventos relacionados ao fim do grande conflito. Depois de ler o texto, responda às perguntas a seguir:\n\nComo será o julgamento dos ímpios (ou perversos, em algumas versões)?\n\nComo os salvos estarão envolvidos no processo?\n\nEm sua opinião, os salvos vão julgar os ímpios, ou vão julgar as decisões de Deus?\n\nDeus permitirá que Ele próprio seja julgado?\n\nO castigo do lago de fogo parece uma penalidade excessivamente severa? Por que sim ou por que não?\n\nQual o objetivo desse julgamento final? A quem ele pretende convencer?",
      versiculoChave: { texto: "Contudo, o dia do Senhor virá como um ladrão. Os céus desaparecerão com terrível estrondo, e até os elementos serão consumidos pelo fogo, e a terra e tudo que nela há serão expostos.", referencia: "2 Pedro 3:10" },
      perguntas: [
        { id: "d2q1", pergunta: "Qual capítulo bíblico o Roteiro Original de hoje pede para ler?", opcoes: ["Apocalipse 20", "Apocalipse 21", "Daniel 7", "2 Pedro 3"], correta: 0, explicacao: "O texto pede a leitura do capítulo 20 de Apocalipse." },
        { id: "d2q2", pergunta: "Segundo o texto, o capítulo indicado apresenta o quê?", opcoes: ["A sequência dos eventos relacionados ao fim do grande conflito", "A genealogia dos reis de Israel", "As cartas às sete igrejas", "Os detalhes da criação do mundo"], correta: 0, explicacao: "O capítulo 20 de Apocalipse 'apresenta em lances rápidos e objetivos a sequência dos eventos relacionados ao fim do grande conflito'." },
        { id: "d2q3", pergunta: "Qual destas perguntas o texto de hoje propõe para reflexão?", opcoes: ["A quem esse julgamento final pretende convencer?", "Quantos anjos existem no Céu?", "Qual é a capital de Israel?", "Quantos livros tem o Apocalipse?"], correta: 0, explicacao: "O texto pergunta: 'Qual o objetivo desse julgamento final? A quem ele pretende convencer?'" },
        { id: "d2q4", pergunta: "Julgue: segundo o texto de hoje, o julgamento final envolve apenas Deus, sem qualquer participação dos salvos.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "O texto pergunta justamente como os salvos estarão envolvidos no processo de julgamento, sugerindo que eles participam dele." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-12-14",
      titulo: "ZOOM",
      conteudo: "Leia o Texto-Chave desta semana, que se encontra em 2 Pedro 3:10. Para entender melhor o contexto dessa passagem, é preciso ler o verso anterior, que diz: 'O Senhor não retarda a Sua promessa, ainda que alguns a julguem demorada. Pelo contrário, Ele é paciente para com vocês, não querendo que ninguém pereça, mas que todos cheguem ao arrependimento' (v. 9).\n\nA promessa aqui se refere à vinda de Jesus. Ainda que alguns pensem que Ele não virá ou que está demorando muito para isso acontecer, nada mudará os planos de Deus. Cristo virá, com certeza! 'Qualquer aparente demora na vinda do Senhor é devida ao desejo de Deus de manter aberta a porta da salvação enquanto houver esperança de arrependimento para qualquer pecador' (CBA, vol. 7, p. 677).\n\nPedro chama a atenção para o fato de que muitos serão apanhados de surpresa porque viveram como se não tivessem que prestar contas para ninguém. Achavam que podiam fazer o que bem entendessem e que ficariam impunes por suas más ações. O apóstolo demonstra mais preocupação pelas pessoas do que pelos eventos em si. 'Ele entrou em detalhes sobre os acontecimentos dos últimos dias a fim de mostrar [aos leitores de sua carta] a necessidade imperativa de santidade' (CBA).\n\nEstá muito, muito perto de Jesus voltar a este mundo. Os sinais e as profecias estão se cumprindo. No entanto, poucos estão atentos. Nosso papel é alertar as pessoas e convidá-las a conhecer o maravilhoso Salvador.",
      versiculoChave: { texto: "O Senhor não retarda a Sua promessa, ainda que alguns a julguem demorada. Pelo contrário, Ele é paciente para com vocês, não querendo que ninguém pereça, mas que todos cheguem ao arrependimento.", referencia: "2 Pedro 3:9" },
      perguntas: [
        { id: "d3q1", pergunta: "Onde se encontra o Texto-Chave desta semana, segundo o Zoom de hoje?", opcoes: ["2 Pedro 3:10", "Apocalipse 20:10", "Daniel 12:2", "1 Tessalonicenses 4:17"], correta: 0, explicacao: "O Texto-Chave desta semana se encontra em 2 Pedro 3:10." },
        { id: "d3q2", pergunta: "Segundo o verso anterior ao texto-chave (2 Pedro 3:9), por que o Senhor não é rápido em cumprir Sua promessa?", opcoes: ["Porque Ele é paciente, não querendo que ninguém pereça", "Porque ainda faltam recursos no Céu", "Porque os anjos ainda não terminaram sua obra", "Porque a Terra ainda não está pronta fisicamente"], correta: 0, explicacao: "'Ele é paciente para com vocês, não querendo que ninguém pereça, mas que todos cheguem ao arrependimento.'" },
        { id: "d3q3", pergunta: "Segundo o texto, por que muitos serão apanhados de surpresa com a volta de Jesus?", opcoes: ["Por acharem que não teriam que prestar contas a ninguém", "Por não conhecerem a Bíblia", "Por viverem isolados demais", "Por confiarem demais nas profecias"], correta: 0, explicacao: "Muitos viveram como se não tivessem que prestar contas a ninguém e achavam que ficariam impunes por suas más ações." },
        { id: "d3q4", pergunta: "Julgue: segundo o CBA citado no texto, qualquer aparente demora na vinda do Senhor é devida ao desejo de Deus de manter aberta a porta da salvação.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "'Qualquer aparente demora na vinda do Senhor é devida ao desejo de Deus de manter aberta a porta da salvação enquanto houver esperança de arrependimento para qualquer pecador' (CBA, vol. 7, p. 677)." }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-12-15",
      titulo: "MAKING OF",
      conteudo: "Os ímpios vão se voltar contra os pastores infiéis e líderes religiosos, acusando-os de serem os responsáveis por sua perdição. Eles serão atacados e mortos.\n\nDurante mil anos (a profecia do milênio), Satanás ficará em prisão domiciliar na Terra. 'Prisão' é uma linguagem simbólica para dizer que o inimigo estará impedido de agir. Afinal, não haverá ninguém a quem ele possa tentar. Os salvos estarão no Céu e os ímpios estarão mortos.\n\nPor ocasião da volta de Cristo, todos os ímpios serão mortos. Eles não vão resistir ao resplendor de Sua glória.\n\nA expressão 'abismo' mencionada em Apocalipse 20:1-3 representa a Terra em confusão e trevas. É nela que Satanás ficará aprisionado.\n\nO santuário terrestre era uma representação do santuário celestial. Assim como o sumo sacerdote transferia a culpa dos pecados do povo para o bode emissário no dia da expiação, Satanás será declarado culpado de todo mal que levou as pessoas a cometerem.\n\nNesse período (mil anos), os santos, em união com Cristo, vão julgar os ímpios, decidindo cada caso de acordo com as más ações deles. Satanás e os anjos maus também serão julgados nessa ocasião.",
      versiculoChave: { texto: "Contudo, o dia do Senhor virá como um ladrão. Os céus desaparecerão com terrível estrondo, e até os elementos serão consumidos pelo fogo, e a terra e tudo que nela há serão expostos.", referencia: "2 Pedro 3:10" },
      perguntas: [
        { id: "d4q1", pergunta: "Segundo o texto, contra quem os ímpios se voltarão quando ressuscitarem, culpando-os por sua perdição?", opcoes: ["Contra os pastores infiéis e líderes religiosos", "Contra os anjos guardiões", "Contra os pais e familiares", "Contra os governos civis"], correta: 0, explicacao: "Os ímpios se voltarão contra os pastores infiéis e líderes religiosos, acusando-os de serem responsáveis por sua perdição." },
        { id: "d4q2", pergunta: "O que a 'prisão domiciliar' de Satanás durante o milênio significa, segundo o texto?", opcoes: ["Que o inimigo estará impedido de agir, pois não há ninguém para tentar", "Que Satanás ficará fisicamente acorrentado no Céu", "Que ele poderá visitar a Terra ocasionalmente", "Que ele governará a Terra sozinho por mil anos"], correta: 0, explicacao: "'Prisão' é linguagem simbólica: o inimigo estará impedido de agir, pois não haverá ninguém a quem ele possa tentar." },
        { id: "d4q3", pergunta: "O que representa a expressão 'abismo' mencionada em Apocalipse 20:1-3, segundo o texto?", opcoes: ["A Terra em confusão e trevas", "O céu mais alto", "Um lugar literal debaixo do oceano", "O templo de Jerusalém destruído"], correta: 0, explicacao: "A expressão 'abismo' representa a Terra em confusão e trevas, onde Satanás ficará aprisionado." },
        { id: "d4q4", pergunta: "Julgue: segundo o texto, durante o milênio os santos, em união com Cristo, vão julgar os ímpios, decidindo cada caso de acordo com as más ações deles.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto afirma que os santos, em união com Cristo, vão julgar os ímpios durante o milênio, caso a caso." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-12-16",
      titulo: "EXTRAS",
      conteudo: "Leia e marque em sua Bíblia os textos adicionais desta semana. Algum deles é novo para você? Que novidade ele apresentou?\n\nObserve que Deus nos incentiva a colocá-Lo à prova. Ele é todo justiça e misericórdia, por isso não precisamos ter medo do juízo.\n\nDurante o milênio, depois de Jesus nos levar para o Céu e antes de voltarmos para a nova Terra, estaremos ocupados revendo, ou 'julgando', as decisões de Deus. Satanás acusou Deus de ser injusto, e o planeta Terra foi usado como demonstração dos ideais de Satanás. Deus foi justo? A Bíblia diz que os santos vão julgar o mundo (1 Coríntios 6:2). 'Em união com Cristo, eles julgarão os ímpios' (Os Resgatados, p. 331).\n\nMalaquias 3:10 nos diz para provarmos a Deus e testá-Lo em Sua palavra. O milênio oferecerá uma oportunidade para fazermos exatamente isto – aprofundar e fazer todas as perguntas que precisarmos. De que respostas você precisa? Saiba que Deus, por meio da Bíblia, lhe dá todas elas!\n\nTextos adicionais: Jó 40:1,2; Malaquias 3:10; Salmo 32:7.",
      versiculoChave: { texto: "Contudo, o dia do Senhor virá como um ladrão. Os céus desaparecerão com terrível estrondo, e até os elementos serão consumidos pelo fogo, e a terra e tudo que nela há serão expostos.", referencia: "2 Pedro 3:10" },
      perguntas: [
        { id: "d5q1", pergunta: "Segundo o texto, por que não precisamos ter medo do juízo de Deus?", opcoes: ["Porque Ele é todo justiça e misericórdia", "Porque o juízo nunca de fato ocorrerá", "Porque só os anjos serão julgados", "Porque o juízo é apenas simbólico"], correta: 0, explicacao: "'Ele é todo justiça e misericórdia, por isso não precisamos ter medo do juízo', diz o texto." },
        { id: "d5q2", pergunta: "Segundo 1 Coríntios 6:2, citado no texto, quem vai julgar o mundo?", opcoes: ["Os santos", "Apenas os anjos", "Apenas Cristo, sozinho", "Os patriarcas do Antigo Testamento"], correta: 0, explicacao: "'A Bíblia diz que os santos vão julgar o mundo' (1 Coríntios 6:2)." },
        { id: "d5q3", pergunta: "Segundo o texto, o planeta Terra foi usado como demonstração de quê?", opcoes: ["Dos ideais de Satanás", "Da tecnologia humana", "Da beleza da criação apenas", "Do poder político dos impérios"], correta: 0, explicacao: "'Satanás acusou Deus de ser injusto, e o planeta Terra foi usado como demonstração dos ideais de Satanás.'" },
        { id: "d5q4", pergunta: "Julgue: segundo o texto, Malaquias 3:10 nos convida a provar e testar a Deus em Sua palavra.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "'Malaquias 3:10 nos diz para provarmos a Deus e testá-Lo em Sua palavra', afirma o texto." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-12-17",
      titulo: "PANORÂMICA",
      conteudo: "O capítulo 41 do livro Os Resgatados (O Grande Conflito na linguagem de hoje) tem como título 'A Terra em Ruínas'. Nele se encontra explicação para muitos dos termos mencionados em Apocalipse 20 e uma visão geral de tudo o que acontecerá após a vinda de Cristo – mais precisamente entre a primeira ressurreição e a segunda –, envolvendo o período dos mil anos da profecia.\n\nAtualmente há muitos meios de entretenimento apresentando releituras de histórias conhecidas, dando ênfase ao passado dos vilões, como se a chave para compreender o comportamento deles estivesse nas injustiças que eles sofreram antes de se tornarem assumidamente maus. Fique esperto!\n\nA Bíblia diz que os maus não terão justificativas no acerto de contas. Não permita que o pensamento de que Deus pode ter cometido injustiça contra alguém se instale de uma forma sutil em sua mente. A verdade precisa ser analisada sem qualquer contaminação com o erro.\n\n'Quando a voz de Deus der fim ao cativeiro de Seu povo, ocorrerá um terrível despertamento em meio àqueles que perderam tudo no grande conflito da vida. [...] Com terror, assistem à destruição de seus ídolos. Venderam a própria alma por prazeres terrenos e não se tornaram ricos para Deus. Sua vida foi um fracasso e seus prazeres ficaram amargos. [...] Os ímpios lamentam os resultados, por serem os que são, mas não se arrependem de sua maldade' (Os Resgatados, p. 328).",
      versiculoChave: { texto: "Contudo, o dia do Senhor virá como um ladrão. Os céus desaparecerão com terrível estrondo, e até os elementos serão consumidos pelo fogo, e a terra e tudo que nela há serão expostos.", referencia: "2 Pedro 3:10" },
      perguntas: [
        { id: "d6q1", pergunta: "Qual é o título do capítulo 41 do livro Os Resgatados, segundo o texto?", opcoes: ["A Terra em Ruínas", "O Grande Julgamento", "Mil Anos de Silêncio", "O Fim do Pecado"], correta: 0, explicacao: "O capítulo 41 do livro Os Resgatados tem como título 'A Terra em Ruínas'." },
        { id: "d6q2", pergunta: "O texto adverte para ficarmos espertos com que tipo de narrativa comum no entretenimento atual?", opcoes: ["Releituras que enfatizam o passado dos vilões para justificá-los", "Documentários históricos sobre a igreja", "Filmes sobre viagens espaciais", "Novelas sobre família"], correta: 0, explicacao: "O texto adverte sobre releituras que dão ênfase ao passado dos vilões, como se isso justificasse seu comportamento." },
        { id: "d6q3", pergunta: "Segundo o texto, o que a Bíblia diz sobre os maus no acerto de contas final?", opcoes: ["Que eles não terão justificativas", "Que eles poderão apelar da sentença", "Que receberão uma segunda chance", "Que serão perdoados automaticamente"], correta: 0, explicacao: "'A Bíblia diz que os maus não terão justificativas no acerto de contas.'" },
        { id: "d6q4", pergunta: "Julgue: segundo a citação de Os Resgatados no texto de hoje, os ímpios lamentam os resultados de sua maldade e verdadeiramente se arrependem dela.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "O texto diz o contrário: 'Os ímpios lamentam os resultados, por serem os que são, mas não se arrependem de sua maldade.'" }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-12-18",
      titulo: "OFF",
      conteudo: "Pense na pessoa que você mais ama no mundo. Pense em seu sentimento mais sincero por ela, e em como você se sentiria triste diante da ideia de perdê-la. O amor que você sente por ela é pequeno demais comparado ao amor por você que Deus sente por cada pessoa que já existiu.\n\nAlguém certa vez disse que o 'lago de fogo' mencionado na Bíblia é uma prova do amor de Deus. Se Deus não nos amasse tanto, Ele não daria a chance de escolher. Se Deus não nos respeitasse tanto, Ele não permitiria que nos separássemos Dele. O amor de Deus é tão forte que permitiu que Seu próprio coração fosse entristecido pela escolha do ser humano pelo mal.\n\nOs ímpios não serão destruídos pelo desejo de Deus de causar dor aos seres desobedientes. Eles serão destruídos porque a glória de Deus, que traz conforto àqueles que se mantiveram ligados a Ele, é insuportável para os rebeldes a ponto de consumi-los.\n\nNa ocasião em que Deus destruir o pecado e purificar a Terra, o Universo será finalmente libertado da dor, da frustração, da raiva, da depressão; enfim, do resultado da desobediência à lei de Deus. Viveremos sem medo por toda a eternidade.\n\n'O pecado não é prejudicial porque é proibido, mas é proibido porque é prejudicial' (Benjamin Franklin).\n\n'Um pecado provoca um novo e real terror quando surge a chance de ser descoberto' (Mark Twain).\n\nSomos advertidos a não confiar em pessoas que se posicionam contrariamente à Palavra de Deus. Chegará o tempo em que elas receberão a punição por essa má obra. Leia os textos de Jeremias 23:12 e de Ezequiel 13:22. Deus leva a sério a responsabilidade de um ser humano por desencaminhar outros.",
      versiculoChave: { texto: "Contudo, o dia do Senhor virá como um ladrão. Os céus desaparecerão com terrível estrondo, e até os elementos serão consumidos pelo fogo, e a terra e tudo que nela há serão expostos.", referencia: "2 Pedro 3:10" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo o texto, por que os ímpios serão destruídos, segundo a explicação dada?", opcoes: ["Porque a glória de Deus é insuportável para os rebeldes, a ponto de consumi-los", "Porque Deus deseja causar dor aos desobedientes", "Porque não houve tempo suficiente para se arrependerem", "Porque os anjos exigem a destruição deles"], correta: 0, explicacao: "'Eles serão destruídos porque a glória de Deus... é insuportável para os rebeldes a ponto de consumi-los.'" },
        { id: "d7q2", pergunta: "O que o Universo será, segundo o texto, quando Deus destruir o pecado e purificar a Terra?", opcoes: ["Finalmente libertado da dor, da frustração, da raiva e da depressão", "Reduzido a um único planeta habitado", "Reconstruído do zero, sem memória do passado", "Dividido entre o bem e o mal para sempre"], correta: 0, explicacao: "'O Universo será finalmente libertado da dor, da frustração, da raiva, da depressão; enfim, do resultado da desobediência à lei de Deus.'" },
        { id: "d7q3", pergunta: "Segundo a citação atribuída a Mark Twain no texto de hoje, quando surge um 'novo e real terror' relacionado ao pecado?", opcoes: ["Quando surge a chance de ele ser descoberto", "Quando a pessoa envelhece", "Quando alguém confessa publicamente", "Quando não há mais como escondê-lo de Deus"], correta: 0, explicacao: "'Um pecado provoca um novo e real terror quando surge a chance de ser descoberto' — Mark Twain." },
        { id: "d7q4", pergunta: "Julgue: segundo o texto, o 'lago de fogo' pode ser entendido como uma prova do amor de Deus, que respeita a escolha do ser humano até o fim.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto afirma que 'alguém certa vez disse que o lago de fogo... é uma prova do amor de Deus', ligado ao respeito de Deus pela escolha humana." }
      ]
    }
  ]
};

export const LICAO_LA_13 = {
  titulo: "Lição 13 - Terra Renovada (19 a 25 de dezembro)",
  semana: "2026-W51",
  trimestre: "Livro Aberto",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-12-19",
      titulo: "TEASER",
      conteudo: "O que acontecerá depois do milênio? Cristo voltará novamente à Terra, mas agora estará acompanhado não só dos anjos, mas também dos resgatados. A história precisa ser concluída. Os maus ainda não receberam sua punição.\n\nSatanás tentará seu ataque final contra Deus. Ele não estará sozinho. Comandará um exército de milhões incontáveis. De acordo com Ellen White, haverá nesse grupo reis e generais que nunca perderam uma única batalha. As armas de guerra serão construídas por engenheiros com muita habilidade. Líderes militares formarão companhias e divisões. Mas quando essa multidão inumerável avançar em direção à Cidade Santa, algo surpreendente acontecerá.\n\nA lição desta semana apresenta o desfecho maravilhoso do plano da salvação. Tudo o que estava na mente da Trindade quando este mundo foi originalmente criado se concretizará. O ser humano – objeto do maior amor que o Universo já conheceu – viverá no lugar que Deus idealizou desde o início. Teremos o privilégio de ver a Terra renovada. Aqui será não apenas a nossa morada, mas o lugar onde o próprio Deus escolheu habitar (Apocalipse 21:3). Agora é o tempo de assumir um compromisso real com Deus, de viver como um verdadeiro herdeiro do Rei.\n\nQual é a sua decisão?",
      versiculoChave: { texto: "E vi a cidade santa, a nova Jerusalém, que descia do céu, da parte de Deus, como uma noiva belamente vestida para seu marido. Ouvi uma forte voz. [...] O próprio Deus estará com eles. Ele lhes enxugará dos olhos toda lágrima, e não haverá mais morte. [...] Todas essas coisas passaram para sempre.", referencia: "Apocalipse 21:2-4" },
      perguntas: [
        { id: "d1q1", pergunta: "Segundo o texto, quem acompanhará Cristo em Sua volta à Terra depois do milênio?", opcoes: ["Apenas os anjos", "Os anjos e também os resgatados", "Apenas os resgatados, sem anjos", "Nenhum acompanhante, Ele virá sozinho"], correta: 1, explicacao: "Cristo voltará 'acompanhado não só dos anjos, mas também dos resgatados'." },
        { id: "d1q2", pergunta: "Contra quem Satanás lançará seu ataque final, segundo o texto?", opcoes: ["Contra Deus", "Contra os anjos rebeldes", "Contra o restante dos ímpios", "Contra a natureza da Terra"], correta: 0, explicacao: "'Satanás tentará seu ataque final contra Deus', diz o texto." },
        { id: "d1q3", pergunta: "Segundo o texto, o ser humano é descrito como o quê, em relação ao amor do Universo?", opcoes: ["Objeto do maior amor que o Universo já conheceu", "Uma criação secundária e menos importante", "Um experimento ainda em teste", "Um mistério que nunca será resolvido"], correta: 0, explicacao: "O ser humano é descrito como 'objeto do maior amor que o Universo já conheceu'." },
        { id: "d1q4", pergunta: "Julgue: segundo o texto, na Terra renovada o lugar será apenas a morada dos salvos, sem que o próprio Deus escolha habitar ali.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "O texto diz o contrário: será 'o lugar onde o próprio Deus escolheu habitar' (Ap 21:3)." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-12-20",
      titulo: "ROTEIRO ORIGINAL",
      conteudo: "No último capítulo da Bíblia, João descreve o que o anjo lhe mostrou da cidade santa. O rio da água da vida, o trono de Deus e do Cordeiro, a árvore da vida, com seus frutos e folhas. Ele fala também do que não haverá lá. Leia o texto em sua Bíblia, que se encontra em Apocalipse 22:1-14. Depois, responda às perguntas a seguir:\n\nQuais são as características da Nova Jerusalém descritas nos versos 1-6?\n\nO que fica de cada lado do rio? Para que serve?\n\nCompare essa passagem com Ezequiel 47:1-12; Joel 3:18; e Zacarias 14:8. Quais são as semelhanças? Quais são as diferenças? O que essas visões nos dizem sobre Deus?\n\nO que é preciso fazer para estar lá? Como as escolhas que você faz aqui influenciam sua decisão de participar ou não da experiência descrita por João?",
      versiculoChave: { texto: "E vi a cidade santa, a nova Jerusalém, que descia do céu, da parte de Deus, como uma noiva belamente vestida para seu marido. Ouvi uma forte voz. [...] O próprio Deus estará com eles. Ele lhes enxugará dos olhos toda lágrima, e não haverá mais morte. [...] Todas essas coisas passaram para sempre.", referencia: "Apocalipse 21:2-4" },
      perguntas: [
        { id: "d2q1", pergunta: "Em qual capítulo bíblico o Roteiro Original de hoje pede para ler?", opcoes: ["Apocalipse 22:1-14", "Apocalipse 20:1-10", "Gênesis 2:8-14", "Ezequiel 1:1-14"], correta: 0, explicacao: "O texto pede a leitura de Apocalipse 22:1-14." },
        { id: "d2q2", pergunta: "Segundo o texto, o que João descreve no último capítulo da Bíblia?", opcoes: ["O rio da água da vida, o trono de Deus e do Cordeiro, e a árvore da vida", "Apenas a destruição final de Satanás", "A genealogia completa de Jesus", "As pragas do Egito"], correta: 0, explicacao: "João descreve 'o rio da água da vida, o trono de Deus e do Cordeiro, a árvore da vida, com seus frutos e folhas'." },
        { id: "d2q3", pergunta: "Quais outras passagens bíblicas o texto sugere comparar com Apocalipse 22?", opcoes: ["Ezequiel 47:1-12; Joel 3:18; Zacarias 14:8", "Salmo 1; Salmo 23; Salmo 91", "Mateus 5; Mateus 6; Mateus 7", "Gênesis 1; Gênesis 2; Gênesis 3"], correta: 0, explicacao: "O texto sugere comparar com Ezequiel 47:1-12; Joel 3:18; e Zacarias 14:8." },
        { id: "d2q4", pergunta: "Julgue: segundo o texto de hoje, o capítulo lido também fala sobre o que NÃO haverá na cidade santa.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "'Ele fala também do que não haverá lá', diz o texto." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-12-21",
      titulo: "ZOOM",
      conteudo: "Leia o Texto-Chave desta semana, que se encontra em Apocalipse 21:2-4. João viu a Cidade Santa descendo do Céu e a descreveu como uma noiva que vem ao encontro do noivo. A expressão 'adornada' vem do grego kosmos. Sabe a palavra 'cosmético'? Deriva daí. A forma verbal indica que o processo de embelezamento começou no passado e agora havia chegado ao fim. Foi um longo preparo. Mas valeu a pena. A beleza da cidade encantou os olhos do profeta. Porém, a alegria ficou realmente completa quando João viu Deus vindo habitar na Terra renovada. Ele estará com os seres humanos por toda a eternidade. Pense no significado disso. Será demais!\n\nNo livro Visões do Céu (p. 148), Ellen White faz o seguinte comentário a respeito da nova Terra: 'Ali, quando for removido o véu que obscurece a nossa visão, e nossos olhos contemplarem aquele mundo de beleza que ora apanhamos lampejos pelo microscópio; quando olharmos às glórias dos céus hoje esquadrinhadas de longe pelo telescópio; quando, removida a mácula do pecado, a Terra aparecer na beleza do Senhor nosso Deus – que campo se abrirá ao nosso estudo! Ali o estudante da ciência poderá ler os relatórios da criação sem divisar coisa alguma que recorde a lei do mal. Poderá escutar a melodia das vozes da natureza, e não perceberá nenhuma nota de lamento ou tristeza. Poderá enxergar em todas as coisas criadas, contemplar no vasto Universo, escrito em grandes letras, o nome de Deus; e nem na Terra, nem no mar ou no céu permanecerá um indício que seja do mal.'",
      versiculoChave: { texto: "E vi a cidade santa, a nova Jerusalém, que descia do céu, da parte de Deus, como uma noiva belamente vestida para seu marido. Ouvi uma forte voz. [...] O próprio Deus estará com eles. Ele lhes enxugará dos olhos toda lágrima, e não haverá mais morte. [...] Todas essas coisas passaram para sempre.", referencia: "Apocalipse 21:2-4" },
      perguntas: [
        { id: "d3q1", pergunta: "Segundo o texto, de que palavra grega vem a expressão 'adornada', usada para descrever a Cidade Santa?", opcoes: ["Kosmos", "Agape", "Logos", "Doxa"], correta: 0, explicacao: "'A expressão adornada vem do grego kosmos', da qual deriva a palavra 'cosmético'." },
        { id: "d3q2", pergunta: "Segundo o texto, quando a alegria de João ficou realmente completa?", opcoes: ["Quando ele viu Deus vindo habitar na Terra renovada", "Quando ele viu o rio da água da vida", "Quando ele contou os doze portões da cidade", "Quando ele mediu o tamanho da cidade"], correta: 0, explicacao: "'A alegria ficou realmente completa quando João viu Deus vindo habitar na Terra renovada.'" },
        { id: "d3q3", pergunta: "Segundo a citação de Ellen White (Visões do Céu, p. 148), o que o estudante da ciência poderá fazer na Terra renovada?", opcoes: ["Ler os relatórios da criação sem encontrar nada que recorde a lei do mal", "Estudar apenas por meio de telescópios avançados", "Reescrever a história da criação do zero", "Aprender uma nova língua criada por Deus"], correta: 0, explicacao: "'Ali o estudante da ciência poderá ler os relatórios da criação sem divisar coisa alguma que recorde a lei do mal.'" },
        { id: "d3q4", pergunta: "Julgue: segundo a citação de Ellen White, na Terra renovada ainda restará algum indício do mal na Terra, no mar ou no céu.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "O texto diz o contrário: 'nem na Terra, nem no mar ou no céu permanecerá um indício que seja do mal.'" }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-12-22",
      titulo: "MAKING OF",
      conteudo: "Depois do milênio, Deus ressuscitará os ímpios para que eles recebam sua punição. Satanás vai alegar que ele mesmo os ressuscitou e os instigará a se unirem para tentar tomar a Cidade Santa.\n\nNesse empreendimento, Satanás não se identificará como o inimigo de Deus. Vai dizer que ele é o verdadeiro dono do mundo e que sua herança foi injustamente tirada de suas mãos.\n\nLúcifer verá em pé, junto ao Pai, um anjo de presença majestosa. É Gabriel, ocupando a exaltada posição que antes havia sido dele (querubim cobridor).\n\nMais próximos do trono, estarão aqueles que um dia trabalharam para o inimigo, mas que se arrependeram e escolheram o lado de Jesus. Eles serão o exemplo vivo do poder de Deus na vida de alguém que busca ao Senhor.\n\nAs portas da cidade serão fechadas e Cristo aparecerá de forma que todos os inimigos O vejam. Ele estará sentado em um trono, cuja base é de ouro polido. A glória de Deus O envolverá e o brilho de Sua presença iluminará toda a Terra.\n\nOs ímpios assistirão (como um filme panorâmico) toda a sequência da vida de Jesus na Terra, desde o Seu nascimento até Sua crucifixão. Ali estarão Herodes, Pilatos, os soldados que zombaram de Jesus e toda a multidão que O condenou. Todos reconhecerão que Deus é justo ao excluí-los do Céu.\n\nSatanás reconhecerá sua rebelião, se prostrará e admitirá a justiça de sua sentença. No entanto, seu caráter permanecerá o mesmo. Ele ainda tentará convencer os ímpios a batalharem contra os santos. Mas eles desistem. Nesse momento descerá fogo do céu e os consumirá a todos. O fogo que destrói os ímpios purificará a Terra e ela será renovada.",
      versiculoChave: { texto: "E vi a cidade santa, a nova Jerusalém, que descia do céu, da parte de Deus, como uma noiva belamente vestida para seu marido. Ouvi uma forte voz. [...] O próprio Deus estará com eles. Ele lhes enxugará dos olhos toda lágrima, e não haverá mais morte. [...] Todas essas coisas passaram para sempre.", referencia: "Apocalipse 21:2-4" },
      perguntas: [
        { id: "d4q1", pergunta: "Segundo o texto, o que Satanás alegará ter feito com os ímpios ressuscitados, após o milênio?", opcoes: ["Que ele mesmo os ressuscitou", "Que ele os salvou do fogo eterno", "Que ele os transformou em anjos", "Que ele os enviou de volta ao Éden"], correta: 0, explicacao: "Satanás vai alegar que ele mesmo ressuscitou os ímpios e os instigará a se unirem contra a Cidade Santa." },
        { id: "d4q2", pergunta: "Quem ocupa, junto ao Pai, a posição de destaque que antes era de Lúcifer, segundo o texto?", opcoes: ["Gabriel", "Miguel, apenas em nome simbólico", "Nenhum anjo, o posto ficou vazio", "Um dos 24 anciãos"], correta: 0, explicacao: "É Gabriel, ocupando a exaltada posição que antes havia sido de Lúcifer, o querubim cobridor." },
        { id: "d4q3", pergunta: "O que os ímpios assistirão, descrito no texto como 'um filme panorâmico'?", opcoes: ["Toda a sequência da vida de Jesus na Terra, do nascimento à crucificação", "Apenas a criação do mundo", "A história completa de Israel", "Os mil anos do milênio em detalhes"], correta: 0, explicacao: "Os ímpios assistirão toda a sequência da vida de Jesus na Terra, desde o nascimento até a crucificação." },
        { id: "d4q4", pergunta: "Julgue: segundo o texto, depois de reconhecer a justiça de sua sentença, o caráter de Satanás muda e ele desiste de lutar contra os santos.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "O texto diz que, apesar de reconhecer a sentença, 'seu caráter permanecerá o mesmo' e ele ainda tentará convencer os ímpios a batalharem contra os santos." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-12-23",
      titulo: "EXTRAS",
      conteudo: "Leia e marque em sua Bíblia os textos adicionais desta semana. Qual deles mais falou ao seu coração? Por quê?\n\nO autor Max Lucado usa o seguinte exemplo para ilustrar o desejo pela eternidade que Deus colocou no coração do homem:\n\nPegue um peixe e coloque-o na praia. Observe-o se mexer e lutar. Ele está feliz? Não! Como você pode deixá-lo feliz? Dando-lhe uma moto nova? Alimentando-o com sorvete bem geladinho? Dando-lhe uma linda namorada? Ou um smartphone de última geração? Talvez um casaco bem quentinho e sapatos confortáveis?\n\nEnquanto todas essas coisas podem deixar você feliz por um tempo, o peixe só ficará completamente satisfeito quando você o colocar de volta na água. Ele foi criado para viver na água, não na praia. E nós nunca estaremos completamente satisfeitos neste mundo, porque não fomos feitos para viver neste mundo. Sim, apreciamos as diversões. E algumas coisas nos deixam felizes por um tempo. E haverá momentos de alegria. Mas até chegarmos ao Céu nunca estaremos completamente satisfeitos, porque fomos criados para viver com Deus – face a face.\n\nQuanto mais pensarmos nas coisas que Deus tem preparado para nós, mais fácil será fazermos melhores escolhas aqui.\n\nTextos adicionais: Apocalipse 3:21; 1 João 3:2; João 5:24.",
      versiculoChave: { texto: "E vi a cidade santa, a nova Jerusalém, que descia do céu, da parte de Deus, como uma noiva belamente vestida para seu marido. Ouvi uma forte voz. [...] O próprio Deus estará com eles. Ele lhes enxugará dos olhos toda lágrima, e não haverá mais morte. [...] Todas essas coisas passaram para sempre.", referencia: "Apocalipse 21:2-4" },
      perguntas: [
        { id: "d5q1", pergunta: "Segundo o exemplo de Max Lucado, o que aconteceria a um peixe colocado na praia com uma moto nova, sorvete e outros agrados?", opcoes: ["Ficaria feliz apenas por um tempo, mas não completamente satisfeito", "Ficaria completamente satisfeito para sempre", "Voltaria sozinho para a água imediatamente", "Não sentiria nenhuma diferença"], correta: 0, explicacao: "Essas coisas podem deixar o peixe feliz por um tempo, mas ele só fica completamente satisfeito de volta na água — assim como nós, só seremos completamente satisfeitos com Deus." },
        { id: "d5q2", pergunta: "Segundo o texto, por que nunca estaremos completamente satisfeitos neste mundo?", opcoes: ["Porque não fomos feitos para viver neste mundo", "Porque a vida é sempre muito curta", "Porque o dinheiro nunca é suficiente", "Porque as pessoas sempre decepcionam"], correta: 0, explicacao: "'Nós nunca estaremos completamente satisfeitos neste mundo, porque não fomos feitos para viver neste mundo.'" },
        { id: "d5q3", pergunta: "Julgue: segundo o texto, só estaremos completamente satisfeitos quando chegarmos ao Céu, pois fomos criados para viver com Deus face a face.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "'Até chegarmos ao Céu nunca estaremos completamente satisfeitos, porque fomos criados para viver com Deus – face a face.'" },
        { id: "d5q4", pergunta: "Quais são os textos adicionais sugeridos para esta semana, segundo o texto?", opcoes: ["Apocalipse 3:21; 1 João 3:2; João 5:24", "Gênesis 1; Gênesis 2; Gênesis 3", "Salmo 23; Salmo 91; Salmo 100", "Mateus 5; Mateus 6; Mateus 7"], correta: 0, explicacao: "Os textos adicionais desta semana são Apocalipse 3:21; 1 João 3:2; e João 5:24." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-12-24",
      titulo: "PANORÂMICA",
      conteudo: "Que palavras! Como devemos desejar que elas se tornem uma realidade logo. O capítulo 42 do livro Os Resgatados apresenta toda a sequência de acontecimentos após o milênio, com a destruição completa do pecado, até a purificação e renovação da Terra. Separe um tempo para ler e tente imaginar as cenas que são descritas ali.\n\nO grande conflito realmente chegará ao fim. Satanás tentou provar que sua rebelião tinha justificativa, que Deus não era digno de confiança e que Sua lei tirava a liberdade de Suas criaturas. 'Por milhares de anos, esse chefe da conspiração vendeu mentiras como se fossem verdades', diz Ellen White. Ele levou grandes multidões a aceitar essa versão do grande conflito. Mas a verdade virá à tona. Cada pergunta sobre a verdade e o erro será completamente respondida. Cristo será exaltado acima de qualquer nome e o mal nunca mais existirá! Seu coração vibra com essa esperança?\n\n'O grande conflito terminou. Pecado e pecadores já não existem. O Universo inteiro está purificado. Um único pulso de harmonia e júbilo ecoa pela vasta criação. Daquele que criou todas as coisas, fluem luz, vida e felicidade através do espaço ilimitado. Desde o menor dos átomos, até o maior dos mundos, todas as coisas, animadas e inanimadas, em sua beleza imaculada e alegria perfeita, declaram que Deus é amor' (Os Resgatados, p. 341).",
      versiculoChave: { texto: "E vi a cidade santa, a nova Jerusalém, que descia do céu, da parte de Deus, como uma noiva belamente vestida para seu marido. Ouvi uma forte voz. [...] O próprio Deus estará com eles. Ele lhes enxugará dos olhos toda lágrima, e não haverá mais morte. [...] Todas essas coisas passaram para sempre.", referencia: "Apocalipse 21:2-4" },
      perguntas: [
        { id: "d6q1", pergunta: "Qual capítulo do livro Os Resgatados apresenta a sequência de acontecimentos após o milênio, segundo o texto?", opcoes: ["Capítulo 42", "Capítulo 40", "Capítulo 27", "Capítulo 41"], correta: 0, explicacao: "O capítulo 42 do livro Os Resgatados apresenta essa sequência de acontecimentos." },
        { id: "d6q2", pergunta: "Segundo Ellen White, citada no texto, o que Satanás fez por milhares de anos, como 'chefe da conspiração'?", opcoes: ["Vendeu mentiras como se fossem verdades", "Construiu exércitos para atacar o Céu", "Escreveu livros contra a Bíblia", "Convenceu os anjos a se render"], correta: 0, explicacao: "'Por milhares de anos, esse chefe da conspiração vendeu mentiras como se fossem verdades', diz Ellen White." },
        { id: "d6q3", pergunta: "Segundo a citação de Os Resgatados (p. 341), o que declara toda a criação, desde o menor átomo até o maior mundo?", opcoes: ["Que Deus é amor", "Que o mal ainda pode retornar", "Que a batalha nunca terminou", "Que Satanás foi perdoado"], correta: 0, explicacao: "'Todas as coisas... em sua beleza imaculada e alegria perfeita, declaram que Deus é amor.'" },
        { id: "d6q4", pergunta: "Julgue: segundo o texto, cada pergunta sobre a verdade e o erro será completamente respondida quando o grande conflito terminar.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "'Cada pergunta sobre a verdade e o erro será completamente respondida. Cristo será exaltado acima de qualquer nome e o mal nunca mais existirá!'" }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-12-25",
      titulo: "OFF",
      conteudo: "Tem gente que pensa que viver no Céu e depois na nova Terra será graça e monótono. Não é essa a visão que a Bíblia apresenta. Veja apenas alguns lances do que acontecerá na Terra renovada, conforme descritos no último capítulo do livro Os Resgatados:\n\nOs salvos construirão casas e nelas habitarão. Também plantarão e comerão do seu fruto (Isaías 65:21).\n\nNão haverá mais morte, nem tristeza, nem choro, nem dor (Apocalipse 21:4).\n\nOs resgatados vão poder interagir livremente com o Pai e o Filho. Também ouvirão da boca dos fiéis de todas as eras o testemunho de sua salvação.\n\nA mente dos imortais estudará as maravilhas do poder criador, os mistérios do amor redentor. Os remidos poderão desenvolver as mais grandiosas iniciativas, alcançar seus mais elevados objetivos e cumprir suas mais nobres ambições.\n\nSem a limitação da mortalidade, voarão incansavelmente para mundos distantes.\n\nCom uma visão livre de impedimentos, contemplarão a glória da criação.\n\nVocê não pode ficar fora disso tudo. Deus prometeu que nossa história terá um verdadeiro final feliz!\n\n'Apenas uma pessoa na Bíblia recebeu uma promessa direta do Céu – um ladrão' (Philip Yancey).\n\n'Natal é a ocasião em que Deus desceu as escadas do Céu com um bebê em Seus braços' (R. Eugene Sterner).\n\nO último capítulo do livro Os Resgatados é esclarecedor. É o spoiler do que acontecerá com o ser humano depois do milênio no Céu. Tire um tempo para a leitura. Você se surpreenderá com os detalhes!",
      versiculoChave: { texto: "E vi a cidade santa, a nova Jerusalém, que descia do céu, da parte de Deus, como uma noiva belamente vestida para seu marido. Ouvi uma forte voz. [...] O próprio Deus estará com eles. Ele lhes enxugará dos olhos toda lágrima, e não haverá mais morte. [...] Todas essas coisas passaram para sempre.", referencia: "Apocalipse 21:2-4" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo o texto, o que os salvos poderão fazer na Terra renovada, segundo Isaías 65:21?", opcoes: ["Construir casas e habitar nelas, além de plantar e comer do fruto", "Apenas descansar sem nenhuma atividade", "Viajar entre planetas sem limites físicos", "Reconstruir suas antigas casas na Terra atual"], correta: 0, explicacao: "'Os salvos construirão casas e nelas habitarão. Também plantarão e comerão do seu fruto' (Isaías 65:21)." },
        { id: "d7q2", pergunta: "Segundo o texto, o que os resgatados poderão fazer livremente na Terra renovada?", opcoes: ["Interagir livremente com o Pai e o Filho", "Apenas observar Deus à distância", "Visitar a Terra antiga quando quiserem", "Reencontrar apenas os familiares mais próximos"], correta: 0, explicacao: "'Os resgatados vão poder interagir livremente com o Pai e o Filho.'" },
        { id: "d7q3", pergunta: "Julgue: segundo o texto, a visão bíblica da eternidade é de graça e monotonia, sem novidades para os salvos.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "O texto afirma o contrário: 'Não é essa a visão que a Bíblia apresenta' — há casas, plantações, viagens a mundos distantes e objetivos grandiosos a cumprir." },
        { id: "d7q4", pergunta: "Segundo a citação de Philip Yancey no texto de hoje, quem recebeu uma promessa direta do Céu na Bíblia?", opcoes: ["Um ladrão", "Um rei poderoso", "Um sacerdote famoso", "Um profeta anônimo"], correta: 0, explicacao: "'Apenas uma pessoa na Bíblia recebeu uma promessa direta do Céu – um ladrão' (Philip Yancey)." }
      ]
    }
  ]
};
