export const LICAO_LA_5 = {
  titulo: "Lição 5 - Armadilha (24 a 30 de outubro)",
  semana: "2026-W43",
  trimestre: "Livro Aberto",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-10-24",
      titulo: "TEASER",
      conteudo: "A morte tem sido uma das questões mais controversas no meio cristão. Muitas pessoas acreditam que a alma é imortal, outras não creem em nenhuma forma de vida após a morte, ainda outras creem na ressurreição final; e por fim há outras que nem mesmo têm certeza do que acreditam.\n\nA lição desta semana apresentará mais informações a respeito do que a Bíblia revela sobre a morte. Mostrará também de que maneira a crença na imortalidade da alma pode levar ao ocultismo ou ao espiritismo. A morte não é limbo, inferno, Céu ou purgatório, mas simplesmente 'o deixar de existir'. Não existe uma alma que vive fora do corpo e que tem uma personalidade ou a capacidade de pensar. Ao morrer, o ser humano simplesmente deixa de existir. Seu corpo se desintegra.\n\nO ser humano não possui uma alma; ele é uma alma, a junção do corpo e do fôlego de vida. Ao longo da Bíblia encontramos exemplos dessa verdade. Basta ler o que está em Eclesiastes 9:4-6. Leia o texto bíblico e aproveite o estudo para esclarecer qualquer dúvida quanto a esse assunto.",
      versiculoChave: { texto: "Quando sua vida se vai, voltam ao pó, todos os seus planos morrem com eles.", referencia: "Salmo 146:4" },
      perguntas: [
        { id: "d1q1", pergunta: "Segundo o texto, como a morte é descrita, ao invés de limbo, inferno, Céu ou purgatório?", opcoes: ["Como um estado de purificação temporária", "Como o simples 'deixar de existir'", "Como uma jornada para outro planeta", "Como um sono consciente e vigilante"], correta: 1, explicacao: "O texto diz que a morte não é limbo, inferno, Céu ou purgatório, mas simplesmente 'o deixar de existir'." },
        { id: "d1q2", pergunta: "De acordo com o texto, o que é o ser humano, segundo a Bíblia?", opcoes: ["Uma alma que habita dentro de um corpo", "Uma alma, a junção do corpo e do fôlego de vida", "Um espírito imortal preso à matéria", "Um corpo vazio sem qualquer propósito"], correta: 1, explicacao: "O ser humano não possui uma alma; ele é uma alma, a junção do corpo e do fôlego de vida." },
        { id: "d1q3", pergunta: "Julgue: segundo o texto, existe uma alma que continua a viver fora do corpo, com personalidade e capacidade de pensar, mesmo depois da morte.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "O texto afirma o contrário: não existe uma alma que vive fora do corpo com personalidade ou capacidade de pensar; ao morrer, o ser humano deixa de existir." },
        { id: "d1q4", pergunta: "Qual referência bíblica o texto sugere ler para confirmar que o ser humano não tem consciência após a morte?", opcoes: ["Eclesiastes 9:4-6", "Apocalipse 20:1-3", "Mateus 5:1-12", "Salmo 23:1-6"], correta: 0, explicacao: "O texto recomenda ler Eclesiastes 9:4-6 para esclarecer o assunto." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-10-25",
      titulo: "ROTEIRO ORIGINAL",
      conteudo: "O conceito da alma imortal não se originou de um ensinamento bíblico. Na verdade, foi propagado por filósofos gregos pagãos, ou pelo menos foi por meio deles que posteriormente essa ideia caminhou para a teologia cristã.\n\nLeia em sua Bíblia os textos de Gênesis 3:1-5; Salmo 146:4; Isaías 38:19 e Apocalipse 16:13,14. Eles servem de base para a compreensão da questão da mortalidade do ser humano. Depois da leitura, responda às seguintes perguntas:\n\nEm sua opinião, por que a questão da imortalidade versus mortalidade da alma é um assunto tão discutido entre as denominações cristãs?\n\nA sociedade tem muita responsabilidade quanto à obra de incutir essa ideia da imortalidade da alma em nossa mente. Você pode pensar em alguns exemplos de mídia/filmes/televisão que apoiam essa declaração?\n\nPor que a serpente enganou Eva com a mentira da imortalidade?\n\nSatanás pode usar a ideia da alma imortal para induzir as pessoas a acreditar em doutrinas espíritas. Você consegue pensar em alguns exemplos de como isso funcionaria?\n\nUma vez que entende que os mortos estão 'dormindo', inconscientes e não podem se comunicar, de que tipo de enganos comuns você está protegido? Por quê, então, a compreensão desse assunto é tão importante?",
      versiculoChave: { texto: "Quando sua vida se vai, voltam ao pó, todos os seus planos morrem com eles.", referencia: "Salmo 146:4" },
      perguntas: [
        { id: "d2q1", pergunta: "Segundo o texto, de onde se originou o conceito da alma imortal?", opcoes: ["De um ensinamento bíblico claro", "De filósofos gregos pagãos", "De uma visão do apóstolo João", "De um concílio da igreja primitiva"], correta: 1, explicacao: "O conceito não se originou de um ensinamento bíblico, mas foi propagado por filósofos gregos pagãos." },
        { id: "d2q2", pergunta: "Quais textos bíblicos o Roteiro Original pede para ler nesta semana?", opcoes: ["Gênesis 3:1-5; Salmo 146:4; Isaías 38:19 e Apocalipse 16:13,14", "Mateus 24; Marcos 13 e Lucas 21", "Daniel 2; Daniel 7 e Apocalipse 13", "1 Coríntios 15 e 1 Tessalonicenses 4"], correta: 0, explicacao: "O texto pede a leitura de Gênesis 3:1-5; Salmo 146:4; Isaías 38:19 e Apocalipse 16:13,14." },
        { id: "d2q3", pergunta: "Julgue: segundo o texto, entender que os mortos estão 'dormindo' e inconscientes protege a pessoa de enganos espíritas.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto afirma que compreender esse estado dos mortos protege contra enganos comuns, por isso é importante." },
        { id: "d2q4", pergunta: "Segundo o texto, por que a serpente enganou Eva?", opcoes: ["Com a promessa de riquezas materiais", "Com a mentira da imortalidade", "Com a promessa de poder político", "Com a promessa de longa vida terrena apenas"], correta: 1, explicacao: "A pergunta do roteiro destaca que a serpente enganou Eva com a mentira da imortalidade." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-10-26",
      titulo: "ZOOM",
      conteudo: "Leia o Texto-Chave desta semana, que se encontra em Salmo 146:4. Esse é um dos versos bíblicos mais enfáticos a respeito do que a morte representa.\n\nPara entender como o conceito de imortalidade foi introduzido na história do ser humano, é preciso voltar ao Éden e acompanhar a conversa entre a serpente (Satanás) e a mulher (Eva). Perceba quais eram as intenções do inimigo: 'Satanás, que incitou a rebelião no Céu, queria levar os habitantes da Terra a se unir a ele em sua guerra contra Deus. Adão e Eva permaneceram felizes ao obedecer à lei divina - um testemunho constante contra o argumento que Satanás havia defendido no Céu de que a lei de Deus era opressora. O inimigo estava determinado a provocar a queda do casal para que pudesse tomar posse da Terra e estabelecer seu reino aqui em oposição ao Altíssimo' (Os Resgatados, p. 272).\n\nA mentira de que eles teriam vida mesmo se desobedecessem foi o primeiro sermão pregado sobre a imortalidade da alma. 'Após a queda, Satanás instruiu seus anjos a instigar a crença de que elas são naturalmente imortais' (p. 273).\n\nA Bíblia, por sua vez, é clara quanto ao estado dos seres humanos na morte. Eles não têm consciência de nada, voltam ao pó e não podem fazer mais nenhum plano. São, portanto, mortais.\n\nLeia o texto de Eclesiastes 9:5 (NVI) e complete os espaços em branco: 'Pois os vivos sabem que vão morrer, mas os mortos nada sabem; para eles não haverá mais recompensa, e já não se tem lembrança deles.'",
      versiculoChave: { texto: "Quando sua vida se vai, voltam ao pó, todos os seus planos morrem com eles.", referencia: "Salmo 146:4" },
      perguntas: [
        { id: "d3q1", pergunta: "Segundo a citação de Os Resgatados (p. 272), qual era a intenção do inimigo ao provocar a queda do casal?", opcoes: ["Salvar a humanidade do pecado", "Tomar posse da Terra e estabelecer seu reino em oposição a Deus", "Ensinar Adão e Eva sobre agricultura", "Proteger o Éden de outros anjos"], correta: 1, explicacao: "'O inimigo estava determinado a provocar a queda do casal para que pudesse tomar posse da Terra e estabelecer seu reino aqui em oposição ao Altíssimo' (Os Resgatados, p. 272)." },
        { id: "d3q2", pergunta: "Segundo o texto, qual foi o primeiro sermão pregado sobre a imortalidade da alma?", opcoes: ["A mentira de que os anjos caídos podem ser vistos", "A mentira de que eles teriam vida mesmo se desobedecessem", "A ideia de que o pecado seria perdoado automaticamente", "A crença de que Deus abandonaria a Terra"], correta: 1, explicacao: "'A mentira de que eles teriam vida mesmo se desobedecessem foi o primeiro sermão pregado sobre a imortalidade da alma' (p. 273)." },
        { id: "d3q3", pergunta: "Julgue: segundo o texto, a Bíblia ensina que os seres humanos mortos têm consciência e podem fazer planos.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "O texto afirma o contrário: os mortos não têm consciência de nada, voltam ao pó e não podem fazer mais nenhum plano." },
        { id: "d3q4", pergunta: "Onde se encontra o Texto-Chave desta semana, segundo o início do texto de hoje?", opcoes: ["Salmo 146:4", "João 11:25", "1 Tessalonicenses 4:16", "Gênesis 2:7"], correta: 0, explicacao: "O texto começa dizendo: 'Leia o Texto-Chave desta semana, que se encontra em Salmo 146:4.'" }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-10-27",
      titulo: "MAKING OF",
      conteudo: "Há denominações que acreditam que os mortos bons já estão no Céu. Essa crença não é bíblica. Imagine como eles poderiam viver felizes acompanhando as tristezas, decepções e angústias de seus queridos na Terra? A Bíblia ensina que os mortos dormem até o dia da ressurreição e não participam de nada que diz respeito aos habitantes da Terra.\n\nAdão e Eva não eram naturalmente imortais. A imortalidade deles estava condicionada à obediência.\n\nSatanás criou tanto a heresia do tormento eterno - segundo a qual o pecador é lançado por Deus no inferno para se contorcer nas chamas eternas - quanto o erro oposto, de que Deus é tão amoroso que salvará toda a humanidade, mesmo aqueles que desobedecem às Suas leis.\n\n'O príncipe do mal tem poder para fazer surgir diante das pessoas a aparência de amigos falecidos. A falsificação é perfeita, reproduzida com precisão extraordinária' (Os Resgatados, p. 281). Os anjos caídos tomam a forma das pessoas mortas e enganam os desprevenidos.\n\nFoi profetizado que o espiritismo moderno se apresentaria na forma da bruxaria, e isso atrairia muitas pessoas. Esse seria um novo disfarce que Satanás usaria para enganar os seres humanos.\n\nNo espiritismo, Jesus é apresentado como um ser puro, o modelo de ser humano mais perfeito que já viveu e digno de ser imitado. No entanto, Ele não passa disso. A pessoa se torna boa por seus próprios méritos. Não necessita de um Salvador. A lei de Deus não é devidamente compreendida e, por isso, não é valorizada. Essa tem sido uma armadilha para muitas pessoas.",
      versiculoChave: { texto: "O príncipe do mal tem poder para fazer surgir diante das pessoas a aparência de amigos falecidos. A falsificação é perfeita, reproduzida com precisão extraordinária.", referencia: "Os Resgatados, p. 281" },
      perguntas: [
        { id: "d4q1", pergunta: "Segundo o texto, o que a Bíblia ensina sobre os mortos, ao contrário da crença de que já estão no Céu?", opcoes: ["Que eles continuam observando os vivos", "Que dormem até o dia da ressurreição", "Que se tornam anjos imediatamente", "Que vivem em outro planeta"], correta: 1, explicacao: "A Bíblia ensina que os mortos dormem até o dia da ressurreição e não participam de nada que diz respeito aos habitantes da Terra." },
        { id: "d4q2", pergunta: "Segundo o texto, a imortalidade de Adão e Eva estava condicionada a quê?", opcoes: ["À obediência", "À sua localização geográfica", "Ao número de filhos que tivessem", "À idade que alcançassem"], correta: 0, explicacao: "Adão e Eva não eram naturalmente imortais; a imortalidade deles estava condicionada à obediência." },
        { id: "d4q3", pergunta: "Julgue: segundo o texto, Satanás criou apenas uma heresia sobre o destino dos mortos, a do tormento eterno no inferno.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "O texto menciona duas heresias opostas: o tormento eterno e a ideia de que Deus salvará toda a humanidade mesmo os desobedientes." },
        { id: "d4q4", pergunta: "Segundo o texto, como o espiritismo apresenta a figura de Jesus?", opcoes: ["Como alguém irrelevante para a salvação", "Como um ser puro e perfeito, mas dispensável, já que a pessoa se salva por seus próprios méritos", "Como um anjo caído disfarçado", "Como um profeta menor entre outros"], correta: 1, explicacao: "No espiritismo, Jesus é apresentado como puro e perfeito, mas a pessoa se torna boa por seus próprios méritos e não necessita de um Salvador." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-10-28",
      titulo: "EXTRAS",
      conteudo: "Leia e marque em sua Bíblia os textos adicionais desta semana. Observe que eles apontam para a ressurreição de Jesus como a esperança que podemos manter de que um dia os que morreram crendo em Cristo também serão ressuscitados.\n\nÉ confortador acreditar no que a Bíblia diz! Como um estudioso das Escrituras, veja como Martinho Lutero enxergava a questão da morte: 'Devemos aprender a ver nossa morte sob o ponto de vista certo, para que não precisemos ficar alarmados quanto a isso, como os descrentes; porque em Cristo na verdade não há morte, mas um agradável, suave e breve sono, que nos traz alívio desse vale de lágrimas, de pecado e de temor, e do fim da morte real e de todos os infortúnios desta vida [...] até o tempo em que Ele nos chamará e nos despertará junto com todos os Seus filhos queridos para a glória e alegria eternas. [...] Toda a Escritura fornece esse consolo' (A Compend of Luther's Theology, p. 242).\n\nA Bíblia é a fonte segura que oferece as respostas para todos os dilemas do ser humano. Quem se apegar a ela não será enganado!\n\nTextos adicionais: 1 Coríntios 15:15; 1 Coríntios 15:17,18; Atos 13:36,37",
      versiculoChave: { texto: "Em Cristo na verdade não há morte, mas um agradável, suave e breve sono, que nos traz alívio desse vale de lágrimas.", referencia: "A Compend of Luther's Theology, p. 242" },
      perguntas: [
        { id: "d5q1", pergunta: "Segundo Martinho Lutero, citado no texto, o que é a morte para quem está em Cristo?", opcoes: ["Um castigo definitivo e sem esperança", "Um agradável, suave e breve sono", "Uma reencarnação em nova forma", "Um mistério que a Bíblia não explica"], correta: 1, explicacao: "Lutero descreve que 'em Cristo na verdade não há morte, mas um agradável, suave e breve sono'." },
        { id: "d5q2", pergunta: "Julgue: segundo o texto, os textos adicionais desta semana apontam para a ressurreição de Jesus como esperança para os que morreram crendo Nele.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto afirma que os textos adicionais apontam para a ressurreição de Jesus como a esperança de que os mortos em Cristo também serão ressuscitados." },
        { id: "d5q3", pergunta: "Segundo o texto, qual é a fonte segura que oferece respostas para os dilemas do ser humano?", opcoes: ["A tradição popular", "A ciência moderna", "A Bíblia", "A filosofia grega"], correta: 2, explicacao: "'A Bíblia é a fonte segura que oferece as respostas para todos os dilemas do ser humano.'" },
        { id: "d5q4", pergunta: "Qual destes é um dos textos adicionais sugeridos para esta semana?", opcoes: ["1 Coríntios 15:15", "João 3:16", "Salmo 23", "Romanos 8:1"], correta: 0, explicacao: "Os textos adicionais incluem 1 Coríntios 15:15; 1 Coríntios 15:17,18 e Atos 13:36,37." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-10-29",
      titulo: "PANORÂMICA",
      conteudo: "Os capítulos 33 e 34 do livro Os Resgatados ajudam a esclarecer vários pontos sobre a imortalidade. Separe um tempo para lê-los com bastante atenção.\n\nObserve que a imortalidade tinha sido prometida ao ser humano sob a condição de obediência. Com a transgressão do primeiro casal esse status foi perdido. Sempre que essa história é contada, nossa atenção se volta para a árvore que ficava no meio do jardim, cujo fruto deveria ser comido. Porém, havia outra árvore ali igualmente importante. 'Para que pudesse possuir uma existência sem fim, o homem deveria continuar a comer da árvore da vida. Não tendo mais esse direito, sua vitalidade iria diminuir gradualmente até que a vida se acabasse' (Os Escolhidos, p. 28).\n\nQuando a Terra for restaurada, teremos um grande privilégio: comeremos do fruto da árvore da vida, e aí sim viveremos felizes para sempre!\n\n'O fruto da árvore da vida tinha poder para manter a vida para sempre. Adão continuaria a ter livre acesso à árvore e nunca morreria; mas, ao pecar, foi excluído da árvore da vida e se tornou sujeito à morte. Ele perdeu a imortalidade por causa de seu pecado. Não haveria nenhuma esperança para a humanidade caída se Deus não houvesse levado a imortalidade a seu alcance por meio do sacrifício de Seu Filho' (Os Resgatados, p. 273).",
      versiculoChave: { texto: "O fruto da árvore da vida tinha poder para manter a vida para sempre. Adão continuaria a ter livre acesso à árvore e nunca morreria; mas, ao pecar, foi excluído da árvore da vida e se tornou sujeito à morte. Ele perdeu a imortalidade por causa de seu pecado.", referencia: "Os Resgatados, p. 273" },
      perguntas: [
        { id: "d6q1", pergunta: "Segundo o texto, sob qual condição a imortalidade tinha sido prometida ao ser humano?", opcoes: ["Sob a condição de riqueza", "Sob a condição de obediência", "Sob a condição de sabedoria", "Sob a condição de longevidade"], correta: 1, explicacao: "A imortalidade tinha sido prometida ao ser humano sob a condição de obediência." },
        { id: "d6q2", pergunta: "Segundo a citação do dia, o que aconteceria com a vitalidade do homem se ele não continuasse a comer da árvore da vida?", opcoes: ["Permaneceria a mesma para sempre", "Aumentaria gradualmente", "Diminuiria gradualmente até que a vida se acabasse", "Se transformaria em outra forma de energia"], correta: 2, explicacao: "'Não tendo mais esse direito, sua vitalidade iria diminuir gradualmente até que a vida se acabasse.'" },
        { id: "d6q3", pergunta: "Julgue: segundo o texto, Adão perdeu a imortalidade por causa do seu pecado, tornando-se sujeito à morte.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto confirma que Adão, ao pecar, foi excluído da árvore da vida, tornou-se sujeito à morte e perdeu a imortalidade por causa de seu pecado." },
        { id: "d6q4", pergunta: "Segundo o texto, quais capítulos do livro Os Resgatados ajudam a esclarecer pontos sobre a imortalidade?", opcoes: ["Capítulos 10 e 11", "Capítulos 33 e 34", "Capítulos 1 e 2", "Capítulos 40 e 41"], correta: 1, explicacao: "Os capítulos 33 e 34 do livro Os Resgatados ajudam a esclarecer vários pontos sobre a imortalidade." }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-10-30",
      titulo: "OFF",
      conteudo: "Satanás é astuto. A Bíblia revela que muitas vezes ele se apresenta como um anjo de luz. É especialista em fazer com que uma pessoa e as suas mentiras apelem aos nossos sentidos e emoções. A única maneira de conhecer a verdade é por meio de Jesus Cristo. Precisamos sempre dedicar tempo para estudar a Palavra de Deus e orar. Do contrário, estaremos cada vez mais sujeitos a sermos enganados e iludidos. Devemos estar abertos para aprender a verdade e permitir que Deus a revele a nós - e não acreditar nas mentiras do inimigo.\n\nA Bíblia deve ser nosso guia, e não as tradições humanas ou nossos próprios desejos. Se nos submetermos plenamente a Deus com sinceridade de coração para aprender Sua verdade, Ele não permitirá que permaneçamos na ignorância.\n\nAo apresentar a primeira mentira a Eva, Satanás sabia que a ideia de ser imortal como Deus atrairia sua atenção, mas ela estava prestes a conhecer uma dura realidade. O adversário ofereceu conhecimento. Adão e Eva precisavam de discernimento. Ele prometeu vida na desobediência. Apenas a obediência e o sacrifício de Jesus podem proporcionar a vida eterna.\n\n'Você não tem uma alma. Você é uma alma. O que você tem é um corpo' (C. S. Lewis).\n\n'Entretanto, deixe-me garantir-lhe que a ideia de que alguns já estão no inferno e alguns no Céu é algo que nunca será capaz de provar pelas Escrituras' (John Frith).\n\nALÉM DO ESTUDO: Reflita sobre isto: 'Se fosse verdade que todos vão direto para o Céu após a morte, faríamos bem em desejar a morte, em lugar da vida. Essa crença já levou muitos a cometer suicídio. Quando se veem sobrecarregados por problemas e decepções, parece fácil para eles cortar o fio da vida e entrar na alegria do mundo eterno. Em Sua Palavra, Deus concedeu evidências conclusivas de que castigará aqueles que desprezarem Sua lei' (Os Resgatados, p. 275). Acesse e leia os capítulos 33 e 34 do livro Os Resgatados.",
      versiculoChave: { texto: "Quando sua vida se vai, voltam ao pó, todos os seus planos morrem com eles.", referencia: "Salmo 146:4" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo C. S. Lewis, citado no texto, o que o ser humano de fato é?", opcoes: ["Um corpo com uma alma anexada", "Uma alma; o que ele tem é um corpo", "Um espírito sem forma", "Uma mente independente do corpo"], correta: 1, explicacao: "'Você não tem uma alma. Você é uma alma. O que você tem é um corpo' (C. S. Lewis)." },
        { id: "d7q2", pergunta: "Segundo o texto, qual é a única maneira de conhecer a verdade?", opcoes: ["Por meio da tradição familiar", "Por meio de Jesus Cristo", "Por meio da ciência", "Por meio da opinião popular"], correta: 1, explicacao: "'A única maneira de conhecer a verdade é por meio de Jesus Cristo.'" },
        { id: "d7q3", pergunta: "Julgue: segundo o texto, apenas a obediência e o sacrifício de Jesus podem proporcionar a vida eterna.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto afirma exatamente isso: 'Apenas a obediência e o sacrifício de Jesus podem proporcionar a vida eterna.'" },
        { id: "d7q4", pergunta: "Segundo o texto, o que Satanás ofereceu a Eva, e do que Adão e Eva precisavam?", opcoes: ["Ofereceu proteção; precisavam de coragem", "Ofereceu conhecimento; precisavam de discernimento", "Ofereceu riqueza; precisavam de humildade", "Ofereceu poder; precisavam de paciência"], correta: 1, explicacao: "'O adversário ofereceu conhecimento. Adão e Eva precisavam de discernimento.'" }
      ]
    }
  ]
};

export const LICAO_LA_6 = {
  titulo: "Lição 6 - Quem é o Anticristo? (31 de outubro a 6 de novembro)",
  semana: "2026-W44",
  trimestre: "Livro Aberto",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-10-31",
      titulo: "TEASER",
      conteudo: "O tema abordado esta semana, sem dúvida, tem sido uma das razões principais de muitas tensões inamistosas entre os adventistas do sétimo dia e outras denominações. Precisamos estudar esse assunto de maneira que não ofendamos as pessoas de outra fé, mas, ao mesmo tempo, não podemos menosprezar a mensagem vital da Igreja Adventista do Sétimo Dia de sermos firmes em nossas convicções pessoais, mesmo em meio à corrupção política, abuso de poder e a contrafação da verdadeira adoração a Deus.\n\nÉ importante lembrar que essa profecia se aplica à igreja e seus líderes e não aos fiéis seguidores que creem no que estão obedecendo à vontade de Deus. Há pessoas sinceras em todas as denominações, que são fiéis à luz que receberam. No momento certo, Deus as chamará para fazer parte de Seu rebanho e demonstrarem sua fidelidade a Ele em meio à maior provação de toda a história.\n\nAs profecias de Apocalipse 13 podem ajudar-nos a entender a estratégia do inimigo nos últimos dias. Por meio da união da igreja com o Estado, Satanás sabe que muitos serão enganados, que a falsa adoração será imposta e a liberdade religiosa negada. Este é o tempo de permanecermos firmes em Cristo, certos de que Ele é a nossa única segurança.",
      versiculoChave: { texto: "Não se deixem enganar pelo que dizem, pois esse dia não virá até que surja a rebelião e venha o homem da perversidade, aquele que traz destruição. Ele se exaltará e se oporá a tudo que o povo chama de 'deus' e a todo objeto de culto, e até se sentará no templo de Deus e se fará passar por Deus.", referencia: "2 Tessalonicenses 2:3,4" },
      perguntas: [
        { id: "d1q1", pergunta: "Segundo o texto, sobre quem essa profecia se aplica?", opcoes: ["Apenas aos adventistas do sétimo dia", "À igreja e seus líderes, não aos fiéis seguidores sinceros", "Apenas aos governos seculares", "Apenas a uma nação específica"], correta: 1, explicacao: "'É importante lembrar que essa profecia se aplica à igreja e seus líderes e não aos fiéis seguidores que creem no que estão obedecendo à vontade de Deus.'" },
        { id: "d1q2", pergunta: "Segundo o texto, quais profecias podem ajudar a entender a estratégia do inimigo nos últimos dias?", opcoes: ["As profecias de Apocalipse 13", "As profecias de Isaías 40", "As profecias de Jeremias 31", "As profecias de Ezequiel 1"], correta: 0, explicacao: "'As profecias de Apocalipse 13 podem ajudar-nos a entender a estratégia do inimigo nos últimos dias.'" },
        { id: "d1q3", pergunta: "Julgue: segundo o texto, por meio da união da igreja com o Estado, a falsa adoração será imposta e a liberdade religiosa negada.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto afirma que, por meio dessa união, 'muitos serão enganados, que a falsa adoração será imposta e a liberdade religiosa negada'." },
        { id: "d1q4", pergunta: "Segundo o texto, o que devemos evitar ao estudar esse assunto sobre outras denominações?", opcoes: ["Estudar o assunto de forma alguma", "Ofender pessoas de outra fé", "Concordar com todas as opiniões", "Ignorar as próprias convicções"], correta: 1, explicacao: "'Precisamos estudar esse assunto de maneira que não ofendamos as pessoas de outra fé.'" }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-11-01",
      titulo: "ROTEIRO ORIGINAL",
      conteudo: "O estudo das profecias pode ser algo fascinante, especialmente se considerarmos a bondade de Deus em apresentar a revelação e o significado delas para o nosso tempo. Uma definição simples para profecia é: conhecer o fim da história antes que ela aconteça. A passagem bíblica desta semana está relacionada a uma importante profecia. Leia em sua Bíblia Apocalipse 13:1-18 e depois responda às seguintes perguntas:\n\nObserve a referência ao leopardo, ao urso e ao leão no verso 2. Agora compare isso ao simbolismo usado em Daniel 7. Com a ajuda de um comentário bíblico, pesquise que poderes governamentais esses animais representam: Leopardo, Urso, Leão.\n\nComo esses poderes se comparam aos poderes representados pela estátua em Daniel 2?\n\nEm sua opinião, por que João se refere a esses poderes em ordem inversa de Daniel?\n\nHá quatro referências nesse capítulo ao 'dragão'. Leia Apocalipse 12:7-9 para identificar o dragão.\n\nAo ler os versos 17 e 18, o que você sabe sobre a marca da besta e o número?",
      versiculoChave: { texto: "Não se deixem enganar pelo que dizem, pois esse dia não virá até que surja a rebelião e venha o homem da perversidade, aquele que traz destruição. Ele se exaltará e se oporá a tudo que o povo chama de 'deus' e a todo objeto de culto, e até se sentará no templo de Deus e se fará passar por Deus.", referencia: "2 Tessalonicenses 2:3,4" },
      perguntas: [
        { id: "d2q1", pergunta: "Segundo o texto, qual é a definição simples de profecia apresentada?", opcoes: ["Uma mensagem de conforto emocional", "Conhecer o fim da história antes que ela aconteça", "Uma interpretação livre dos sonhos", "Um relato do passado da igreja"], correta: 1, explicacao: "'Uma definição simples para profecia é: conhecer o fim da história antes que ela aconteça.'" },
        { id: "d2q2", pergunta: "Qual capítulo bíblico o Roteiro Original pede para ler nesta semana?", opcoes: ["Apocalipse 13:1-18", "Daniel 9:24-27", "Mateus 24:1-14", "Apocalipse 17:1-18"], correta: 0, explicacao: "O texto pede a leitura de Apocalipse 13:1-18." },
        { id: "d2q3", pergunta: "Julgue: segundo o texto, o simbolismo do leopardo, do urso e do leão em Apocalipse 13:2 deve ser comparado ao simbolismo usado em Daniel 7.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "O texto pede para comparar a referência ao leopardo, ao urso e ao leão com o simbolismo usado em Daniel 7." },
        { id: "d2q4", pergunta: "Segundo o texto, quantas referências ao 'dragão' há no capítulo de Apocalipse 13, e onde se deve ler para identificá-lo?", opcoes: ["Duas referências; Apocalipse 20", "Quatro referências; Apocalipse 12:7-9", "Uma referência; Gênesis 3", "Três referências; Daniel 2"], correta: 1, explicacao: "'Há quatro referências nesse capítulo ao dragão. Leia Apocalipse 12:7-9 para identificar o dragão.'" }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-11-02",
      titulo: "ZOOM",
      conteudo: "Leia o Texto-Chave desta semana, que se encontra em 2Tessalonicenses 2:3,4. O comentário extraído da Life Application Bible, diz o seguinte a respeito dessa passagem bíblica:\n\n'Através da história tem havido pessoas que personificaram o mal e que foram hostis a tudo que representa a Cristo (ver 1João 2:18; 1João 4:3; 2João 1:7). Esses anticristos têm existido em todas as gerações e continuarão a operar o mal. Então, exatamente antes da segunda vinda de Cristo, aparecerá aquele que traz destruição total, ele será instrumento de Satanás, equipado com o poder de Satanás (2Ts 2:9). É perigoso, no entanto, rotular qualquer pessoa como o anticristo e tentar predizer a vinda de Cristo com base nessa suposição. Paulo menciona o iníquo não para que pudéssemos tentar identificá-lo, mas para que pudéssemos estar preparados para qualquer coisa que ameaçasse nossa fé. Se nossa fé é forte, não precisamos ter medo de quem ou o que surgirem, porque sabemos que esse perverso já foi vencido por Deus, não importa quão poderoso ele se torne ou quão terrível nossa situação pareça. Deus está no controle, e será vitorioso. Nossa tarefa é estar preparados para o retorno de Cristo e espalhar as boas-novas para que mais pessoas também estejam preparadas.'\n\nA palavra-chave aqui é PREPARO. Como podemos nos preparar agora para não sermos enganados quando o anticristo se manifestar? De que forma as suas escolhas pessoais podem estar influenciando seu preparo?",
      versiculoChave: { texto: "Não se deixem enganar pelo que dizem, pois esse dia não virá até que surja a rebelião e venha o homem da perversidade, aquele que traz destruição. Ele se exaltará e se oporá a tudo que o povo chama de 'deus' e a todo objeto de culto, e até se sentará no templo de Deus e se fará passar por Deus.", referencia: "2 Tessalonicenses 2:3,4" },
      perguntas: [
        { id: "d3q1", pergunta: "Segundo o comentário da Life Application Bible citado, o que os anticristos têm feito ao longo da história?", opcoes: ["Ajudado a igreja a crescer", "Existido em todas as gerações, continuando a operar o mal", "Desaparecido após o primeiro século", "Se convertido ao cristianismo verdadeiro"], correta: 1, explicacao: "'Esses anticristos têm existido em todas as gerações e continuarão a operar o mal.'" },
        { id: "d3q2", pergunta: "Segundo o comentário citado, por que é perigoso rotular uma pessoa específica como o anticristo?", opcoes: ["Porque é proibido por lei", "Porque não há registro bíblico do termo", "Porque isso leva a tentar predizer a vinda de Cristo com base numa suposição arriscada", "Porque o anticristo já foi identificado oficialmente"], correta: 2, explicacao: "'É perigoso, no entanto, rotular qualquer pessoa como o anticristo e tentar predizer a vinda de Cristo com base nessa suposição.'" },
        { id: "d3q3", pergunta: "Julgue: segundo o texto, a palavra-chave para não sermos enganados quando o anticristo se manifestar é PREPARO.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "'A palavra-chave aqui é PREPARO. Como podemos nos preparar agora para não sermos enganados...'" },
        { id: "d3q4", pergunta: "Onde se encontra o Texto-Chave desta semana, segundo o início do texto de hoje?", opcoes: ["2 Tessalonicenses 2:3,4", "Apocalipse 13:1", "Daniel 7:25", "1 João 2:18"], correta: 0, explicacao: "'Leia o Texto-Chave desta semana, que se encontra em 2Tessalonicenses 2:3,4.'" }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-11-03",
      titulo: "MAKING OF",
      conteudo: "Católico vem do grego katholikos e quer dizer 'universal'. A igreja recebeu o nome de Romana quando Constantino, o imperador de Roma, se converteu ao cristianismo. Ele foi o responsável por introduzir muitas das suas práticas pagãs no cristianismo.\n\nQuando uma pessoa confessa seu pecado a outra - um mortal imperfeito - esperando ser perdoada, a imagem de Deus fica distorcida. Deus não autorizou nenhum ser humano a se colocar como Seu intercessor na Terra. Quem faz isso está ocupando o lugar de Cristo.\n\nNa Igreja Católica, o papa é chamado de 'vigário de Cristo'. O termo 'vigário' vem do latim vicarius, que quer dizer 'substituto' ou 'no lugar de'.\n\n'O mundo protestante descobrirá as intenções de Roma somente quando for tarde demais para escapar da armadilha. Ela cresce silenciosamente em poder. Suas doutrinas exercem influência sobre o poder legislativo, sobre as igrejas e sobre o coração das pessoas. [...] Logo, todo aquele que crer na Palavra de Deus e a ela obedecer enfrentará censura e perseguição' (Os Resgatados, p. 295).\n\n'A observância do domingo é um costume que se originou com Roma, e a Igreja Católica a reivindica como sinal de sua autoridade. [...] O primeiro esforço legal para impor o domingo foi a lei promulgada por Constantino. Embora fosse, em essência, um estatuto pagão, o imperador o fez vigorar depois que aceitou as formalidades do cristianismo' (Os Resgatados, p. 291).",
      versiculoChave: { texto: "O mundo protestante descobrirá as intenções de Roma somente quando for tarde demais para escapar da armadilha.", referencia: "Os Resgatados, p. 295" },
      perguntas: [
        { id: "d4q1", pergunta: "Segundo o texto, de onde vem a palavra 'católico' e o que ela significa?", opcoes: ["Do latim 'papa', significando 'pai'", "Do grego katholikos, significando 'universal'", "Do hebraico 'kadosh', significando 'santo'", "Do grego 'ekklesia', significando 'assembleia'"], correta: 1, explicacao: "'Católico vem do grego katholikos e quer dizer universal.'" },
        { id: "d4q2", pergunta: "Segundo o texto, o que acontece quando uma pessoa confessa seu pecado a outro mortal esperando ser perdoada?", opcoes: ["Nada muda, pois é uma prática bíblica normal", "A imagem de Deus fica distorcida, pois ninguém foi autorizado a ocupar o lugar de Cristo como intercessor", "É a única forma correta de buscar perdão", "Isso fortalece a fé de quem confessa"], correta: 1, explicacao: "'Deus não autorizou nenhum ser humano a se colocar como Seu intercessor na Terra. Quem faz isso está ocupando o lugar de Cristo.'" },
        { id: "d4q3", pergunta: "Julgue: segundo o texto, o termo 'vigário', usado para o papa, vem do latim vicarius e significa 'substituto' ou 'no lugar de'.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "'O termo vigário vem do latim vicarius, que quer dizer substituto ou no lugar de.'" },
        { id: "d4q4", pergunta: "Segundo a citação de Os Resgatados (p. 291), qual foi o primeiro esforço legal para impor o domingo?", opcoes: ["Um decreto do apóstolo Pedro", "A lei promulgada por Constantino", "Uma resolução do Concílio de Niceia", "Uma ordem do imperador Nero"], correta: 1, explicacao: "'O primeiro esforço legal para impor o domingo foi a lei promulgada por Constantino.'" }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-11-04",
      titulo: "EXTRAS",
      conteudo: "Leia e marque em sua Bíblia os textos adicionais desta semana. Você observou que a expressão 'espírito de profecia' é bíblica? Está em Apocalipse 19:10 e também foi mencionada no capítulo 12, verso 17.\n\nA Igreja Adventista do Sétimo Dia reconhece o ministério de Ellen G. White como a manifestação especial do 'espírito' ou 'dom' de profecia para os nossos dias. Não consideramos os escritos da profetisa um substituto nem um acréscimo à Bíblia. Eles são a luz menor que guia as pessoas à luz maior. O livro sagrado é a única regra de fé.\n\nDe acordo com o Comentário Bíblico Adventista (vol. 7, p. 974): 'Os escritos do espírito de profecia não apresentam uma nova forma de salvação, mas têm o propósito de levar as pessoas a entender e apreciar a Bíblia', ajudando-as a se apropriar da fonte de salvação ali revelada. Quem aprecia os escritos proféticos sente maior satisfação ainda na leitura da Bíblia!\n\nTextos adicionais: Atos 16:7; Apocalipse 19:10; Apocalipse 20:12",
      versiculoChave: { texto: "Os escritos do espírito de profecia não apresentam uma nova forma de salvação, mas têm o propósito de levar as pessoas a entender e apreciar a Bíblia.", referencia: "Comentário Bíblico Adventista, vol. 7, p. 974" },
      perguntas: [
        { id: "d5q1", pergunta: "Segundo o texto, onde a expressão 'espírito de profecia' aparece na Bíblia?", opcoes: ["Em Apocalipse 19:10", "Em Gênesis 1:1", "Em Mateus 5:1", "Em Salmo 100:1"], correta: 0, explicacao: "A expressão 'espírito de profecia' está em Apocalipse 19:10 e também foi mencionada no capítulo 12, verso 17." },
        { id: "d5q2", pergunta: "Segundo o texto, como a igreja adventista considera os escritos de Ellen G. White em relação à Bíblia?", opcoes: ["Como um substituto da Bíblia", "Como um acréscimo obrigatório à Bíblia", "Como a luz menor que guia à luz maior, sem substituir a Bíblia", "Como um livro sem qualquer valor espiritual"], correta: 2, explicacao: "'Não consideramos os escritos da profetisa um substituto nem um acréscimo à Bíblia. Eles são a luz menor que guia as pessoas à luz maior.'" },
        { id: "d5q3", pergunta: "Julgue: segundo o Comentário Bíblico Adventista citado, os escritos do espírito de profecia apresentam uma nova forma de salvação.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "O CBA afirma o contrário: 'Os escritos do espírito de profecia não apresentam uma nova forma de salvação, mas têm o propósito de levar as pessoas a entender e apreciar a Bíblia.'" },
        { id: "d5q4", pergunta: "Qual destes é um dos textos adicionais sugeridos para esta semana?", opcoes: ["Atos 16:7", "Mateus 6:9", "Salmo 119:105", "Romanos 1:16"], correta: 0, explicacao: "Os textos adicionais incluem Atos 16:7; Apocalipse 19:10 e Apocalipse 20:12." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-11-05",
      titulo: "PANORÂMICA",
      conteudo: "Ellen G. White dirige palavras fortes contra a Igreja Católica Romana. É preciso ler todo o capítulo 35 do livro Os Resgatados (O Grande Conflito na linguagem de hoje) para entender o contexto de suas palavras e compreender o motivo de sua indignação.\n\nEla apela para que façamos da Bíblia o guia da nossa vida. Insiste para que conheçamos as profecias e tenhamos consciência do tempo em que estamos vivendo. O inimigo não está brincando. Sabendo que lhe resta pouco tempo, está convergindo toda a sua força para executar as obras de engano.\n\nÉ assim que a mensageira do Senhor chama nossa atenção: 'Com exceção daqueles a quem o poder de Deus mantém, pela fé, firmados em Sua Palavra, o mundo inteiro se deixará levar por esse engano. As pessoas estão rapidamente sendo emboladas até o sono da sensação de uma segurança fatal e somente o derramamento da ira divina as despertará' (Os Resgatados, p. 286). Agora é o tempo para despertarmos e deixar nossas lâmpadas abastecidas com o azeite do Espírito Santo!\n\n'A pompa e as cerimônias do sistema de culto católico têm um poder sedutor e fascinante que engana muitos. Começam a ver a Igreja Romana como a porta do Céu. Somente aqueles cujos pés estão firmes no alicerce da verdade e cujo coração foi renovado pelo Espírito de Deus estão seguros contra sua influência. O que a maioria das pessoas quer é apenas a forma de piedade, sem seu poder' (Os Resgatados, p. 288).",
      versiculoChave: { texto: "O mundo inteiro se deixará levar por esse engano; somente o derramamento da ira divina os despertará.", referencia: "Os Resgatados, p. 286" },
      perguntas: [
        { id: "d6q1", pergunta: "Segundo o texto, qual capítulo do livro Os Resgatados é indicado para entender as palavras de Ellen White contra a Igreja Católica Romana?", opcoes: ["Capítulo 20", "Capítulo 35", "Capítulo 5", "Capítulo 12"], correta: 1, explicacao: "'É preciso ler todo o capítulo 35 do livro Os Resgatados... para entender o contexto de suas palavras.'" },
        { id: "d6q2", pergunta: "Segundo a citação (Os Resgatados, p. 286), quem não será enganado pelo mundo inteiro?", opcoes: ["Apenas os líderes religiosos", "Aqueles a quem o poder de Deus mantém, pela fé, firmados em Sua Palavra", "Apenas os que vivem isolados da sociedade", "Ninguém, pois todos serão enganados"], correta: 1, explicacao: "'Com exceção daqueles a quem o poder de Deus mantém, pela fé, firmados em Sua Palavra, o mundo inteiro se deixará levar por esse engano.'" },
        { id: "d6q3", pergunta: "Julgue: segundo a citação do dia (Os Resgatados, p. 288), a maioria das pessoas quer apenas a forma de piedade, sem seu poder.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "'O que a maioria das pessoas quer é apenas a forma de piedade, sem seu poder' (Os Resgatados, p. 288)." },
        { id: "d6q4", pergunta: "Segundo o texto, o que devemos fazer agora, enquanto aguardamos o tempo do fim?", opcoes: ["Nos preocupar apenas com questões financeiras", "Deixar nossas lâmpadas abastecidas com o azeite do Espírito Santo", "Evitar estudar as profecias", "Confiar apenas na força humana"], correta: 1, explicacao: "'Agora é o tempo para despertarmos e deixar nossas lâmpadas abastecidas com o azeite do Espírito Santo!'" }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-11-06",
      titulo: "OFF",
      conteudo: "A palavra anticristo literalmente significa 'no lugar de Cristo'. Geralmente pensamos no prefixo 'anti' como 'contra'. Para ser mais preciso, esse prefixo significa 'em vez de'.\n\nNão há muitas passagens bíblicas mencionando o anticristo, mas elas são suficientes para nos ajudar a identificá-lo. Veja algumas referências (NVI):\n\n1João 2:22: 'Quem é o mentiroso, senão aquele que nega que Jesus é o Cristo? Este é o anticristo: aquele que nega o Pai e o Filho.'\n\n1João 4:3: 'Vocês podem reconhecer o Espírito de Deus deste modo: todo espírito que confessa que Jesus Cristo veio em carne procede de Deus; mas todo espírito que não confessa Jesus não procede de Deus. Esse é o espírito do anticristo acerca do qual vocês ouviram que viria, e agora já está no mundo.'\n\n2João 1:7: 'De fato, muitos enganadores têm saído pelo mundo, os quais não confessam que Jesus Cristo veio no corpo. Tal é o enganador e o anticristo.'\n\nToda vez que a palavra anticristo aparece na Bíblia encontra-se no contexto de minar e menosprezar o ministério e a pessoa de Jesus. Precisamos estar atentos para não permitirmos que nada, nem ninguém ocupe o lugar de Cristo em nossa vida.\n\n'A humildade é a chave para experimentar o poder de Deus' (Jim Cymbala).\n\n'A igreja deve se lembrar de que não é o senhor ou o servo do estado, mas a consciência do estado' (Martin Luther King Jr.).\n\nALÉM DO ESTUDO: A própria Ellen G. White escreveu que suas obras não seriam necessárias se as pessoas estudassem a Bíblia do jeito certo. Infelizmente, hoje há muitas pessoas que desprezam o dom profético e preferem fazer suas próprias interpretações da Bíblia, com o risco certo de distorcer seu conteúdo. Lembre-se de que o Espírito de Profecia continua sendo um muro de proteção para aqueles que nele acreditam. Acesse e leia o capítulo 35 do livro Os Resgatados.",
      versiculoChave: { texto: "Quem é o mentiroso, senão aquele que nega que Jesus é o Cristo? Este é o anticristo: aquele que nega o Pai e o Filho.", referencia: "1 João 2:22" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo o texto, o que a palavra 'anticristo' literalmente significa?", opcoes: ["'Contra Cristo'", "'No lugar de Cristo'", "'Sem Cristo'", "'Antes de Cristo'"], correta: 1, explicacao: "'A palavra anticristo literalmente significa no lugar de Cristo.'" },
        { id: "d7q2", pergunta: "Segundo 1 João 2:22, citado no texto, quem é chamado de mentiroso e anticristo?", opcoes: ["Aquele que nega que Jesus é o Cristo", "Aquele que jejua em público", "Aquele que não vai à igreja", "Aquele que duvida das profecias"], correta: 0, explicacao: "'Quem é o mentiroso, senão aquele que nega que Jesus é o Cristo? Este é o anticristo: aquele que nega o Pai e o Filho.'" },
        { id: "d7q3", pergunta: "Julgue: segundo o texto, toda vez que a palavra anticristo aparece na Bíblia, está no contexto de minar e menosprezar o ministério e a pessoa de Jesus.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "'Toda vez que a palavra anticristo aparece na Bíblia encontra-se no contexto de minar e menosprezar o ministério e a pessoa de Jesus.'" },
        { id: "d7q4", pergunta: "Segundo a citação de Martin Luther King Jr. no texto, do que a igreja deve se lembrar que não é?", opcoes: ["Do senhor ou do servo do estado, mas da consciência do estado", "De uma instituição política", "De um lugar de reuniões sociais apenas", "De uma organização sem propósito espiritual"], correta: 0, explicacao: "'A igreja deve se lembrar de que não é o senhor ou o servo do estado, mas a consciência do estado' (Martin Luther King Jr.)." }
      ]
    }
  ]
};

export const LICAO_LA_7 = {
  titulo: "Lição 7 - Os Descendentes (7 a 13 de novembro)",
  semana: "2026-W45",
  trimestre: "Livro Aberto",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-11-07",
      titulo: "TEASER",
      conteudo: "Depois dos ataques de 11 de setembro de 2001, a palavra 'terrorismo' entrou definitivamente para a história da humanidade. Cada vez é possível ver com mais frequência notícias relacionadas a novas modalidades de terrorismo.\n\nDe acordo com especialistas em combate ao terrorismo, ainda que as potências mundiais se encontrem fortalecidas contra atentados bem planejados, os maiores desafios são os ataques pequenos e caseiros. O mundo passou a ficar em constante estado de alerta.\n\nA Bíblia revela que um pouco antes da volta de Jesus haverá caos e confusão no mundo. O maligno incitará todos os ataques terroristas que puder para destruir o maior número possível.\n\nA lição desta semana apresenta um tema supernatural. O cenário predito por Ellen White há mais de um século tornou-se realidade em escala global. Por isso, nunca foi tão necessário refletirmos a espiritualidade, autoridade, respeito e obediência quanto agora.\n\nOs sinais indicam que a volta de Jesus está muito próxima. Você se considera pronto para esse evento? Tem mantido comunhão com Ele todos os dias e todas as noites? Aguarda ansiosamente por esse encontro? As pessoas à sua volta sabem de sua esperança?",
      versiculoChave: { texto: "O dragão se enfureceu com a mulher e passou a lutar contra o restante de seus filhos, todos os que obedecem aos mandamentos de Deus e se mantêm fiéis no testemunho de Jesus.", referencia: "Apocalipse 12:17" },
      perguntas: [
        { id: "d1q1", pergunta: "Segundo o texto, o que entrou definitivamente para a história da humanidade após os ataques de 11 de setembro de 2001?", opcoes: ["A palavra 'terrorismo'", "A palavra 'globalização'", "A palavra 'pandemia'", "A palavra 'crise'"], correta: 0, explicacao: "'Depois dos ataques de 11 de setembro de 2001, a palavra terrorismo entrou definitivamente para a história da humanidade.'" },
        { id: "d1q2", pergunta: "Segundo especialistas citados no texto, quais são os maiores desafios no combate ao terrorismo atualmente?", opcoes: ["Os ataques cibernéticos apenas", "Os ataques pequenos e caseiros", "Os ataques a bancos internacionais", "Os ataques marítimos"], correta: 1, explicacao: "'Os maiores desafios são os ataques pequenos e caseiros.'" },
        { id: "d1q3", pergunta: "Julgue: segundo o texto, a Bíblia revela que um pouco antes da volta de Jesus haverá caos e confusão no mundo.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "'A Bíblia revela que um pouco antes da volta de Jesus haverá caos e confusão no mundo.'" },
        { id: "d1q4", pergunta: "Segundo o texto, o que os sinais atuais indicam sobre a volta de Jesus?", opcoes: ["Que ela está muito distante", "Que ela está muito próxima", "Que ela já não é mais esperada", "Que ela depende de decisões humanas"], correta: 1, explicacao: "'Os sinais indicam que a volta de Jesus está muito próxima.'" }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-11-08",
      titulo: "ROTEIRO ORIGINAL",
      conteudo: "A Bíblia descreve um quadro preciso de como o mundo estará quando o tempo do fim se aproximar. Leia em sua Bíblia os textos de 2 Pedro 3:8-18 e 2 Timóteo 3:1-5 para ter uma ideia. Depois, responda às perguntas a seguir:\n\nComo a mensagem enviada por Pedro aos crentes a respeito dos últimos dias se compara com o trecho da carta de Paulo a Timóteo? Qual era a preocupação dos apóstolos?\n\nEm que os textos são semelhantes?\n\nEm que são diferentes?\n\nQue conselhos Pedro deu aos crentes?\n\nCom base no que se sabe sobre a história de Pedro, o que mais você esperaria que ele dissesse aos cristãos que aguardavam o retorno de Jesus?\n\nE sobre Paulo, o que mais você esperaria que ele dissesse aos cristãos que aguardavam o retorno de Jesus?",
      versiculoChave: { texto: "O dragão se enfureceu com a mulher e passou a lutar contra o restante de seus filhos, todos os que obedecem aos mandamentos de Deus e se mantêm fiéis no testemunho de Jesus.", referencia: "Apocalipse 12:17" },
      perguntas: [
        { id: "d2q1", pergunta: "Quais textos bíblicos o Roteiro Original pede para ler hoje?", opcoes: ["2 Pedro 3:8-18 e 2 Timóteo 3:1-5", "Mateus 24 e Marcos 13", "Daniel 12 e Apocalipse 22", "1 Tessalonicenses 5 e 2 Tessalonicenses 1"], correta: 0, explicacao: "O texto pede a leitura de 2 Pedro 3:8-18 e 2 Timóteo 3:1-5." },
        { id: "d2q2", pergunta: "Segundo o texto, o que a Bíblia descreve nesses textos sobre o mundo?", opcoes: ["Um quadro preciso de como o mundo estará quando o tempo do fim se aproximar", "Apenas a história do povo de Israel", "Uma lista de reis antigos", "Um relato sobre a criação do mundo"], correta: 0, explicacao: "'A Bíblia descreve um quadro preciso de como o mundo estará quando o tempo do fim se aproximar.'" },
        { id: "d2q3", pergunta: "Julgue: segundo o texto, a preocupação de Pedro e de Paulo nos textos citados era idêntica, sem nenhuma diferença entre eles.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "O texto pede para comparar semelhanças e diferenças entre as duas passagens, indicando que existem diferenças a serem observadas." },
        { id: "d2q4", pergunta: "O que o Roteiro Original pede para refletir com base na história de Pedro e Paulo?", opcoes: ["O que mais se esperaria que eles dissessem aos cristãos que aguardavam o retorno de Jesus", "Quais roupas eles usavam", "Onde eles nasceram", "Quantos filhos eles tiveram"], correta: 0, explicacao: "O texto pergunta o que mais se esperaria que Pedro e Paulo dissessem aos cristãos que aguardavam o retorno de Jesus." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-11-09",
      titulo: "ZOOM",
      conteudo: "Leia o Texto-Chave desta semana, que se encontra em Apocalipse 12:17. O verso dá a descrição daqueles a quem Satanás irá perseguir no tempo do fim. São os DESCENDENTES da mulher! A figura da mulher é representada na Bíblia pela igreja.\n\n'Aqueles que amam e guardam os mandamentos de Deus são detestáveis à sinagoga de Satanás, e os poderes do mal manifestarão seu ódio para com eles na máxima extensão possível. João previu o conflito entre a igreja remanescente e o poder do mal' (CBA, vol. 7, p. 1.088).\n\nChegará o tempo em que haverá apenas dois grupos na Terra: os obedientes a Deus, que escolherem estar sob a bandeira de Jesus Cristo, e os desobedientes, que estarão sob a bandeira da rebelião. No centro dessa grande batalha estará a lei de Deus.\n\n'O grande conflito que está sendo travado agora não é mera luta de homem contra homem. De um lado está o Príncipe da Vida, agindo como substituto e penhor do ser humano; do outro, o príncipe das trevas, tendo sob seu comando os anjos caídos' (p. 1.089).\n\nVocê acredita na Bíblia? É obediente aos mandamentos de Deus? Acredita no Espírito de Profecia? Se sim, então você faz parte dos DESCENDENTES mencionados nesse texto! Não aceite que essa palavra tão especial seja manchada ao ser aplicada a outro grupo por aí. Rebeldia não combina com o caráter dos filhos de Deus.",
      versiculoChave: { texto: "O dragão se enfureceu com a mulher e passou a lutar contra o restante de seus filhos, todos os que obedecem aos mandamentos de Deus e se mantêm fiéis no testemunho de Jesus.", referencia: "Apocalipse 12:17" },
      perguntas: [
        { id: "d3q1", pergunta: "Segundo o texto, quem são os 'DESCENDENTES' mencionados em Apocalipse 12:17?", opcoes: ["Os descendentes literais de Abraão apenas", "Os filhos da mulher, que representa a igreja", "Apenas os apóstolos originais", "Os habitantes de Roma"], correta: 1, explicacao: "O verso descreve aqueles a quem Satanás perseguirá; são os DESCENDENTES da mulher, que representa a igreja." },
        { id: "d3q2", pergunta: "Segundo o Comentário Bíblico Adventista citado, o que João previu quanto ao conflito final?", opcoes: ["O conflito entre nações apenas", "O conflito entre a igreja remanescente e o poder do mal", "O conflito entre duas denominações cristãs", "Um conflito apenas econômico"], correta: 1, explicacao: "'João previu o conflito entre a igreja remanescente e o poder do mal' (CBA, vol. 7, p. 1.088)." },
        { id: "d3q3", pergunta: "Julgue: segundo o texto, no centro da grande batalha entre os dois grupos que existirão na Terra estará a lei de Deus.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "'No centro dessa grande batalha estará a lei de Deus.'" },
        { id: "d3q4", pergunta: "Segundo a citação do dia, quem age como substituto e penhor do ser humano no grande conflito?", opcoes: ["O príncipe das trevas", "O Príncipe da Vida", "Os anjos caídos", "Os líderes religiosos humanos"], correta: 1, explicacao: "'De um lado está o Príncipe da Vida, agindo como substituto e penhor do ser humano; do outro, o príncipe das trevas.'" }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-11-10",
      titulo: "MAKING OF",
      conteudo: "O 'testemunho de Jesus' é o 'Espírito de Profecia', que significa que Jesus Se comunica com Seu povo por meio da profecia.\n\nO último grande conflito entre a verdade e o erro envolverá a lei de Deus. De um lado estarão os que seguem a Bíblia e do outro estarão os que baseiam sua religião nas fábulas e tradições humanas.\n\nUm dos principais enganos do inimigo consiste em misturar a falsidade com a porção exata da verdade. Assim, fica mais fácil acreditar na mentira.\n\nSatanás concentrará suas estratégias em dois grandes erros para enredar as pessoas em seus enganos: apresentar o conceito da imortalidade da alma, disfarçado na forma do espiritismo, e defender a santidade do domingo no lugar do sábado.\n\n'É objetivo de Satanás instigar as nações à guerra, porque dessa maneira consegue distrair as pessoas do preparo para o juízo e para a eternidade' (Os Resgatados, p. 299).\n\nA profecia diz que os Estados Unidos, uma nação predominantemente protestante, dará uma mão ao espiritismo e a outra ao poder romano. Por meio dessa união, as pessoas perderão os direitos à liberdade religiosa.\n\n'Satanás estudou os segredos da natureza e usa todo o seu poder para controlar os elementos até onde Deus permite.' Por desprezarem as leis de Deus, o Senhor está retirando Sua proteção do mundo.",
      versiculoChave: { texto: "É objetivo de Satanás instigar as nações à guerra, porque dessa maneira consegue distrair as pessoas do preparo para o juízo e para a eternidade.", referencia: "Os Resgatados, p. 299" },
      perguntas: [
        { id: "d4q1", pergunta: "Segundo o texto, o que significa o 'testemunho de Jesus'?", opcoes: ["Um livro apócrifo", "O 'Espírito de Profecia', ou seja, Jesus Se comunicando com Seu povo por meio da profecia", "Um ritual da igreja primitiva", "Um sinal visível no céu"], correta: 1, explicacao: "'O testemunho de Jesus é o Espírito de Profecia, que significa que Jesus Se comunica com Seu povo por meio da profecia.'" },
        { id: "d4q2", pergunta: "Segundo o texto, o que envolverá o último grande conflito entre a verdade e o erro?", opcoes: ["A moeda utilizada nos países", "A lei de Deus", "O idioma falado pelas nações", "A localização geográfica das igrejas"], correta: 1, explicacao: "'O último grande conflito entre a verdade e o erro envolverá a lei de Deus.'" },
        { id: "d4q3", pergunta: "Julgue: segundo o texto, um dos principais enganos do inimigo é misturar a falsidade com a porção exata da verdade.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "'Um dos principais enganos do inimigo consiste em misturar a falsidade com a porção exata da verdade.'" },
        { id: "d4q4", pergunta: "Segundo o texto, quais são os dois grandes erros em que Satanás concentrará suas estratégias?", opcoes: ["A imortalidade da alma e a santidade do domingo no lugar do sábado", "O ateísmo e o materialismo", "A guerra e a fome", "A tecnologia e a ciência"], correta: 0, explicacao: "'Satanás concentrará suas estratégias em dois grandes erros: apresentar o conceito da imortalidade da alma... e defender a santidade do domingo no lugar do sábado.'" }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-11-11",
      titulo: "EXTRAS",
      conteudo: "Leia e marque em sua Bíblia os textos adicionais desta semana. Qual deles mais chamou a sua atenção? Por quê?\n\nExiste uma grande diferença entre dizer que se acredita e realmente acreditar. Por enquanto, temos liberdade e, de certa forma, vivemos confortáveis com nossa religião e nossas crenças. Mas como será quando isso nos for tirado?\n\nAssim como só podemos lembrar das respostas para uma prova difícil se tivermos a matéria, os textos da Palavra de Deus apenas virão à nossa mente se eles tiverem sido lidos e entendidos.\n\nA Bíblia é a arma mais poderosa que Deus nos confiou nesta batalha cósmica entre o bem e o mal. Ela apresenta a verdade que desmascara a mentira. Aproveite o tempo que ainda resta e torne uma prioridade em sua vida o conhecimento do livro sagrado. Você será beneficiado agora e também no futuro.\n\nTextos adicionais: Ezequiel 33:31,32; 1 Coríntios 11:1; Tito 2:15",
      versiculoChave: { texto: "O dragão se enfureceu com a mulher e passou a lutar contra o restante de seus filhos, todos os que obedecem aos mandamentos de Deus e se mantêm fiéis no testemunho de Jesus.", referencia: "Apocalipse 12:17" },
      perguntas: [
        { id: "d5q1", pergunta: "Segundo o texto, qual é a diferença destacada entre dizer que se acredita e realmente acreditar?", opcoes: ["Não há nenhuma diferença", "Existe uma grande diferença, testada quando a liberdade religiosa for tirada", "A diferença está apenas na quantidade de orações feitas", "A diferença é apenas teórica, sem aplicação prática"], correta: 1, explicacao: "'Existe uma grande diferença entre dizer que se acredita e realmente acreditar... Mas como será quando isso nos for tirado?'" },
        { id: "d5q2", pergunta: "Segundo o texto, a que é comparado o processo de lembrar os textos bíblicos quando forem necessários?", opcoes: ["A lembrar as respostas de uma prova difícil, só possível se a matéria foi estudada antes", "A decorar hinos da igreja", "A aprender uma língua estrangeira", "A memorizar datas históricas"], correta: 0, explicacao: "'Assim como só podemos lembrar das respostas para uma prova difícil se tivermos a matéria, os textos da Palavra de Deus apenas virão à nossa mente se eles tiverem sido lidos e entendidos.'" },
        { id: "d5q3", pergunta: "Julgue: segundo o texto, a Bíblia é chamada de a arma mais poderosa que Deus confiou aos Seus filhos nesta batalha cósmica entre o bem e o mal.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "'A Bíblia é a arma mais poderosa que Deus nos confiou nesta batalha cósmica entre o bem e o mal.'" },
        { id: "d5q4", pergunta: "Qual destes é um dos textos adicionais sugeridos para esta semana?", opcoes: ["Ezequiel 33:31,32", "Isaías 6:1", "Salmo 91", "Lucas 15:11"], correta: 0, explicacao: "Os textos adicionais incluem Ezequiel 33:31,32; 1 Coríntios 11:1 e Tito 2:15." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-11-12",
      titulo: "PANORÂMICA",
      conteudo: "O capítulo 36 do livro Os Resgatados (O Grande Conflito na linguagem de hoje) detalha o passo a passo da estratégia de Satanás quando a história deste mundo estiver chegando ao fim. Tome um tempo para ler com atenção.\n\nO ataque do inimigo será dirigido aos que obedecem aos mandamentos de Deus e creem no Espírito de Profecia. Ele tem trabalhado para levar o mundo ao caos completo. Depois, obterá sucesso ao influenciar líderes e convencer as pessoas de que a observância do domingo ajudaria muito a melhorar a moralidade da sociedade. Por meio do espiritismo, ele realizará milagres e maravilhas, incluindo a cura de doentes. Atrairá a atenção para suas obras. Quando o pequeno grupo de guardadores do sábado se recusar a reverenciar o domingo, o inimigo exercerá seu poder de destruição. Então afirmarão que a ira divina está sobre a Terra por causa deles; como se eles estivessem impedindo a restauração do povo ao favor de Deus e sua prosperidade material.\n\nAí você sabe o que acontece em seguida, não é? Conhecer a Bíblia dá uma vantagem tremenda aos filhos de Deus. Nós sabemos como essa história termina!\n\n'Satanás usará seu poder de realizar maravilhas contra aqueles que obedecem a Deus em lugar de leis humanas. [...] Quem honra o sábado bíblico será culpado como inimigo da lei e da ordem, acusado de destruir os limites morais da sociedade, causando ilegalidade e corrupção, invocando assim os juízos de Deus sobre a Terra' (Os Resgatados, p. 300).",
      versiculoChave: { texto: "Satanás usará seu poder de realizar maravilhas contra aqueles que obedecem a Deus em lugar de leis humanas.", referencia: "Os Resgatados, p. 300" },
      perguntas: [
        { id: "d6q1", pergunta: "Segundo o texto, qual capítulo do livro Os Resgatados detalha a estratégia de Satanás para o fim dos tempos?", opcoes: ["Capítulo 36", "Capítulo 1", "Capítulo 20", "Capítulo 15"], correta: 0, explicacao: "'O capítulo 36 do livro Os Resgatados detalha o passo a passo da estratégia de Satanás quando a história deste mundo estiver chegando ao fim.'" },
        { id: "d6q2", pergunta: "Segundo o texto, o que o inimigo tentará convencer as pessoas a acreditar sobre a observância do domingo?", opcoes: ["Que ela não tem nenhuma importância", "Que ela ajudaria a melhorar a moralidade da sociedade", "Que ela deve ser abolida", "Que ela é uma invenção recente"], correta: 1, explicacao: "O inimigo obterá sucesso ao convencer as pessoas de que a observância do domingo ajudaria muito a melhorar a moralidade da sociedade." },
        { id: "d6q3", pergunta: "Julgue: segundo o texto, quando o pequeno grupo de guardadores do sábado se recusar a reverenciar o domingo, o inimigo exercerá seu poder de destruição contra eles.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "'Quando o pequeno grupo de guardadores do sábado se recusar a reverenciar o domingo, o inimigo exercerá seu poder de destruição.'" },
        { id: "d6q4", pergunta: "Segundo a citação de Os Resgatados (p. 300), de que será acusado quem honra o sábado bíblico?", opcoes: ["De ser um herói nacional", "De ser inimigo da lei e da ordem, culpado de destruir os limites morais da sociedade", "De ser um grande líder político", "De ser um cientista respeitado"], correta: 1, explicacao: "'Quem honra o sábado bíblico será culpado como inimigo da lei e da ordem, acusado de destruir os limites morais da sociedade.'" }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-11-13",
      titulo: "OFF",
      conteudo: "Certamente há coisas específicas que devemos fazer enquanto aguardamos a volta de Jesus. Guilherme Miller, o fiel estudioso da Bíblia, que erroneamente interpretou Daniel 8:14 como representando a volta de Jesus à Terra, descobriu essa verdade em seus últimos anos de vida. Antes de sua morte, Miller confidenciou ao amigo Hendrix:\n\n- Agora sei quando Jesus voltará.\n\n- Sério? - o amigo respondeu. - Você errou a última vez. Quando acha que Jesus voltará?\n\nO idoso Miller respondeu:\n\n- Jesus voltará hoje, hoje, hoje... até Ele voltar.\n\nNós também sabemos quando Jesus voltará. Ele voltará hoje, hoje, por isso devemos orar. Hoje, por isso devemos amar. Hoje, por isso devemos servir. Hoje... até Ele voltar.\n\nPrecisamos conhecer as profecias relativas ao tempo do fim e estar preparados para cada momento da história deste mundo. Deus já revelou o maravilhoso desfecho para aqueles que O amam e que obedecem à Sua lei. Ele nunca desamparará Seus filhos. Todas as Suas promessas serão cumpridas. Acredite em Sua Palavra!\n\n'Felizes os que lavam as suas vestes, e assim têm direito à árvore da vida e podem entrar na cidade pelas portas' (Ap 22:14).\n\n'O fruto do Espírito cresce apenas no jardim da obediência' (Terry Fullam).\n\n'A religião é, em sua essência, um meio de negar a autoridade do restante do mundo' (Stephen Carter).\n\n'A autoridade espiritual procede não de títulos e posições, mas de uma vida autêntica' (Wayne Jacobsen).\n\nALÉM DO ESTUDO: Reflita sobre esta importante declaração: 'Quem ensina as pessoas a tratar os mandamentos de Deus sem respeito está semeando desobediência para colher desobediência. Quando as pessoas descartam por completo as restrições da lei divina, logo também desconsiderarão as leis humanas' (Os Resgatados, p. 297). Acesse e leia o capítulo 36 do livro Os Resgatados.",
      versiculoChave: { texto: "Felizes os que lavam as suas vestes, e assim têm direito à árvore da vida e podem entrar na cidade pelas portas.", referencia: "Apocalipse 22:14" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo o texto, o que Guilherme Miller interpretou erroneamente sobre Daniel 8:14?", opcoes: ["Que representava o fim do mundo pelo fogo", "Que representava a volta de Jesus à Terra", "Que representava o início de uma nova era", "Que representava a destruição de Jerusalém"], correta: 1, explicacao: "Miller 'erroneamente interpretou Daniel 8:14 como representando a volta de Jesus à Terra.'" },
        { id: "d7q2", pergunta: "Segundo o texto, o que o idoso Miller respondeu quando o amigo Hendrix perguntou quando Jesus voltaria?", opcoes: ["'Nunca saberemos.'", "'Jesus voltará hoje, hoje, hoje... até Ele voltar.'", "'Em mil anos exatos.'", "'Isso é um segredo que não devo revelar.'"], correta: 1, explicacao: "O idoso Miller respondeu: 'Jesus voltará hoje, hoje, hoje... até Ele voltar.'" },
        { id: "d7q3", pergunta: "Julgue: segundo o texto, Deus já revelou o maravilhoso desfecho para aqueles que O amam e obedecem à Sua lei, e Ele nunca desamparará Seus filhos.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "'Deus já revelou o maravilhoso desfecho para aqueles que O amam e que obedecem à Sua lei. Ele nunca desamparará Seus filhos.'" },
        { id: "d7q4", pergunta: "Segundo Apocalipse 22:14, citado no texto, quem tem direito à árvore da vida e pode entrar na cidade pelas portas?", opcoes: ["Os que lavam as suas vestes", "Os que constroem grandes templos", "Os que pregam em praças públicas", "Os que jejuam quarenta dias"], correta: 0, explicacao: "'Felizes os que lavam as suas vestes, e assim têm direito à árvore da vida e podem entrar na cidade pelas portas' (Ap 22:14)." }
      ]
    }
  ]
};

