// Primeira lição da temporada de adultos do 4º trimestre de 2026 (sobre o dom
// profético) — NÃO é continuação de "1 e 2 Coríntios" (dataAdult1..5): é o
// começo de uma nova, por isso o export tem prefixo próprio (LICAO_PROF_*) em
// vez de seguir a numeração 1..13 que já está em uso pela temporada anterior.
export const TRIMESTRE_PROF = "O dom de profecia";

const VERSO_L1 = { texto: "Antigamente, Deus falou, muitas vezes e de muitas maneiras, aos pais, pelos profetas, mas, nestes últimos dias, nos falou pelo Filho, a quem constituiu herdeiro de todas as coisas e pelo qual também fez o Universo", referencia: "Hebreus 1:1, 2" };

export const LICAO_PROF_1 = {
  titulo: "Lição 1 - O Criador fala (26 de setembro a 2 de outubro)",
  semana: "2026-W39",
  trimestre: TRIMESTRE_PROF,
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-09-26",
      titulo: "O Criador fala",
      conteudo: "A tecnologia permite a muitos de nós manter contato com amigos e familiares distantes. Isso é muito bom. Mas, ainda assim, nada se compara a encontrar alguém pessoalmente. Algo especial acontece quando nos reunimos, trocamos abraços e conversamos face a face.\n\nNesta semana, vamos relembrar que os seres humanos foram criados para um relacionamento face a face com o Criador. O pecado, porém, destruiu essa conexão íntima. A fim de restaurar a comunicação com Suas criaturas amadas, Deus providenciou meios para falar conosco. A forma mais conhecida dessa comunicação divina com a humanidade ocorre por meio de porta-vozes cuidadosamente escolhidos, os profetas, que transmitem as mensagens de Deus. Alguns deles tiveram seus escritos preservados na Bíblia; outros, porém, não.\n\nO propósito final de Deus é restaurar em nós Sua imagem, que o pecado desfigurou. Uma restauração que será completa quando Deus criar \"novos céus e nova Terra, nos quais habita a justiça\" (2 Pedro 3:13). Até lá, o Senhor continua a falar conosco e a usar Seus profetas para isso.",
      versiculoChave: VERSO_L1,
      perguntas: [
        { id: "d1q1", tipo: "digitar", pergunta: "Complete: \"Nestes últimos dias, nos falou pelo ___\" (Hebreus 1:2)", resposta: "Filho", aceitas: ["o Filho"], explicacao: "Hebreus 1:2 diz que, nestes últimos dias, Deus nos falou pelo Filho, por meio de quem também fez o Universo — a revelação mais plena de Deus." },
        { id: "d1q2", pergunta: "Verdadeiro ou falso: segundo a lição, todos os profetas tiveram seus escritos preservados na Bíblia.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "Falso. O texto diz que alguns profetas tiveram seus escritos preservados na Bíblia; outros, porém, não." },
        { id: "d1q3", pergunta: "Segundo o texto, quando a restauração da imagem de Deus em nós será completa?", opcoes: ["Quando Deus criar novos céus e nova Terra", "Quando cada pessoa ler a Bíblia inteira", "Quando os profetas terminarem de escrever", "Quando a pessoa decide se batizar"], correta: 0, explicacao: "A restauração será completa quando Deus criar \"novos céus e nova Terra, nos quais habita a justiça\" (2 Pedro 3:13)." },
        { id: "d1q4", pergunta: "Que comparação abre a lição desta semana?", opcoes: ["Uma carta perdida que chega anos depois", "Contato à distância x encontro face a face", "Um rádio que perdeu a sintonia da estação", "Um pai que ensina o filho pequeno a ler e escrever"], correta: 1, explicacao: "A tecnologia nos mantém em contato, mas nada se compara ao encontro pessoal — assim fomos criados para um relacionamento face a face com Deus." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-09-27",
      titulo: "Comunicação no Éden",
      conteudo: "Gênesis 1 e 2 apresentam o relato da criação. Deus criou um mundo belo e colocou nele Adão e Eva, o ponto alto de Sua obra criadora. Os seres humanos se diferenciavam de todas as outras criaturas da Terra porque foram feitos \"à imagem de Deus\" (Gênesis 1:27) – algo dito apenas a respeito deles, e não, por exemplo, das aves ou de outros animais. Como portadores dessa imagem, deveriam viver de maneira plena em todas as dimensões da existência, experimentar o amor em suas diversas formas e andar em comunhão com o próprio Deus.\n\nAlém disso, lemos em Gênesis 2:18-23 que Deus criou Eva como companheira de Adão porque \"não é bom que o homem esteja só\" (Gênesis 2:18). Desde o princípio, a humanidade foi criada com uma natureza social. Hoje, os sociólogos reconhecem que a interação humana traz inúmeros benefícios para a saúde física e emocional, enquanto a solidão pode ser mortal.\n\nNão é de admirar, portanto, que, após a criação de Eva, o homem tenha exclamado: \"Esta, afinal, é osso dos meus ossos e carne da minha carne; será chamada varoa, porque do varão foi tirada\" (Gênesis 2:23). A estrutura familiar formada por um homem e uma mulher, unidos em matrimônio, é a primeira instituição social que Deus providenciou para os seres humanos, a fim de que experimentassem plena comunhão. Por isso, não surpreende que um dos principais objetivos de Satanás seja destruir os fundamentos da família original.\n\n1. Leia Gênesis 1:27, 28; 2:15-17; e 3:9. Que tipo de comunicação existia entre Deus e os seres humanos no jardim do Éden?\n\nAdão e Eva desfrutavam de comunhão face a face com o Senhor. Como seres inteligentes, tinham condições de se encontrar com Ele e ouvir Suas instruções. Na qualidade de mordomos do maravilhoso jardim de Deus, cresciam em conhecimento e habilidade enquanto cuidavam de toda a vida vegetal e animal. A cada dia, tinham também um momento especial com o Criador, \"quando soprava o vento suave da tarde\" (Gênesis 3:8). O sábado, em particular, parte essencial do ato criador de Deus, foi separado como um tempo especial dedicado à comunhão entre o Senhor e Seus filhos (Gênesis 2:2, 3; Êxodo 20:8-11). Nesse dia, nossos primeiros pais experimentavam de modo singular o amor e o cuidado de Deus por eles.\n\nÉ difícil para nós, hoje, imaginar como era a vida antes do pecado. Ainda assim, mesmo agora, de que maneira o mundo natural aponta para a criação original de Deus?",
      versiculoChave: VERSO_L1,
      perguntas: [
        { id: "d2q1", pergunta: "Segundo o texto, o que diferenciava os seres humanos de todas as outras criaturas da Terra?", opcoes: ["Terem recebido o jardim para morar", "Terem sido feitos à imagem de Deus", "Terem dado nome a todos os animais", "Terem sido criados no sexto dia"], correta: 1, explicacao: "Somente dos seres humanos se diz que foram feitos \"à imagem de Deus\" (Gênesis 1:27) — não das aves nem dos outros animais." },
        { id: "d2q2", pergunta: "Qual frase de Gênesis 2:18 mostra que a humanidade foi criada com uma natureza social?", opcoes: ["\"Sede fecundos, multiplicai-vos e enchei a terra\"", "\"Do pó és e ao pó tornarás\"", "\"Não é bom que o homem esteja só\"", "\"Cultivai e guardai o jardim\""], correta: 2, explicacao: "Deus criou Eva como companheira de Adão porque \"não é bom que o homem esteja só\" (Gênesis 2:18)." },
        { id: "d2q3", pergunta: "Verdadeiro ou falso: segundo a lição, Adão e Eva tinham um momento especial com o Criador \"quando soprava o vento suave da tarde\".", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "Verdadeiro. Gênesis 3:8 é citado para mostrar esse encontro diário com Deus, além da comunhão especial do sábado." },
        { id: "d2q4", pergunta: "Segundo a lição, qual foi a primeira instituição social que Deus providenciou para os seres humanos?", opcoes: ["A congregação de adoradores", "O conselho dos anciãos", "O sacerdócio levítico", "A família, pelo casamento"], correta: 3, explicacao: "A família formada por um homem e uma mulher unidos em matrimônio foi a primeira instituição social criada por Deus — por isso Satanás tanto a ataca." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-09-28",
      titulo: "Escondendo-se de Deus",
      conteudo: "Deus é amor (1 João 4:8) e não criou seres humanos como \"robôs\", pois o amor envolve escolha. Adão e Eva precisavam ser criados livres; caso contrário, eles não poderiam amar de verdade.\n\nAssim, Adão e Eva tinham liberdade para obedecer ou desobedecer ao Criador. A realidade dessa liberdade de escolha aparece na ordem para que não comessem da árvore do conhecimento do bem e do mal (veja Gênesis 2:15-17). Por que Deus os advertiria contra comer daquela árvore se eles não tivessem liberdade para desobedecer?\n\n\"Nossos primeiros pais, embora criados inocentes e santos, não foram colocados fora da possibilidade de praticar o mal. Deus os fez como seres morais livres, capazes de reconhecer a sabedoria e benignidade de Seu caráter e a justiça de Suas ordens, e com ampla liberdade de prestar obediência ou recusá-la. Deviam desfrutar comunhão com Deus e com os santos anjos [...]. Sem liberdade de opção, sua obediência não teria sido voluntária, mas forçada\" (Ellen G. White, Patriarcas e Profetas, p. 24, 25).\n\n2. Por que Adão e Eva tentaram se esconder do Criador depois de desobedecer-Lhe? Gênesis 3:1-8 (compare com Jeremias 23:24; Hebreus 4:13)\n\nGênesis 3 descreve a queda de Adão e Eva. Depois do diálogo entre a serpente (Satanás) e Eva, nossos primeiros pais foram tentados a comer da árvore proibida. O tentador usou o poder das palavras, das emoções e de seduções aprazíveis para convencer Eva – e, por meio dela, Adão – a ir contra a ordem de Deus. Ela percebeu que a árvore era \"boa para se comer\", \"agradável aos olhos\" e \"desejável para dar entendimento\" (Gênesis 3:6). A promessa de Satanás de que seriam \"como Deus, conhecedores do bem e do mal\" soou irresistível (Gênesis 3:5, NVI).\n\nO discurso enganoso de Satanás ocultou do primeiro casal as consequências da sua desobediência. Quando desobedeceram, seus olhos imediatamente \"se abriram\", e perceberam que \"estavam nus\" (Gênesis 3:7). O \"manto\" de Deus, de luz e glória (Salmo 104:1, 2), que refletia a imagem divina, havia desaparecido. Não é de admirar que Adão e Eva tenham se escondido do Criador – como se fosse realmente possível esconder-se de Deus. O pecado nos enche de culpa e, tomados por esse sentimento, desejamos fugir da presença do Senhor.\n\nQual tem sido sua experiência com a vergonha e a tentativa de se esconder de Deus após pecar?",
      versiculoChave: VERSO_L1,
      perguntas: [
        { id: "d3q1", pergunta: "Segundo o texto, por que Deus não criou os seres humanos como \"robôs\"?", opcoes: ["Porque o amor envolve escolha", "Porque os anjos já obedeciam sem questionar", "Porque o jardim pedia criatividade", "Porque Satanás exigiu isso"], correta: 0, explicacao: "Deus é amor (1 João 4:8), e o amor só é verdadeiro quando há liberdade de escolha." },
        { id: "d3q2", pergunta: "Quem disse? \"Sem liberdade de opção, sua obediência não teria sido voluntária, mas forçada.\"", opcoes: ["O apóstolo Paulo", "Ellen G. White", "O profeta Isaías", "Moisés"], correta: 1, explicacao: "A frase é de Ellen G. White, em Patriarcas e Profetas, p. 24, 25, citada na lição." },
        { id: "d3q3", tipo: "ordenar", pergunta: "Coloque em ordem os acontecimentos de Gênesis 3:", itens: ["A serpente dialoga com Eva", "O casal come do fruto", "Os olhos deles se abrem", "Adão e Eva se escondem"], explicacao: "Depois do diálogo com a serpente, o casal comeu do fruto; os olhos \"se abriram\" e perceberam que estavam nus (Gênesis 3:7) — então tentaram se esconder de Deus, como se isso fosse possível." },
        { id: "d3q4", pergunta: "Verdadeiro ou falso: segundo a lição, depois de pecar, Adão e Eva conseguiram se esconder de Deus por algum tempo.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "Falso. Eles tentaram se esconder \"como se fosse realmente possível esconder-se de Deus\" — o que não é (Jeremias 23:24; Hebreus 4:13)." }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-09-29",
      titulo: "Deus busca a humanidade",
      conteudo: "Gênesis 3:8-10 mostra que Deus tomou a iniciativa de buscar Seus filhos decaídos. A pergunta \"Onde você está?\" (Gênesis 3:9) foi retórica, pois Deus sabia o que Adão e Eva tinham feito e onde estavam. Ainda assim, o pecado interrompeu a comunicação habitual que existia entre Ele e o primeiro casal. A preocupação imediata de Deus foi restaurar o diálogo com Seus filhos, encontrar-Se com eles e lhes dar esperança em meio ao desespero. De fato, o verbo hebraico qara, \"chamar\", em Gênesis 3:9, é usado com frequência para descrever o chamado de Deus a fim de estabelecer comunicação com Seu povo.\n\n3. Leia Lucas 15:11-32. De que maneira essa parábola reflete o que aconteceu em Gênesis 3:9, 10?\n\nA atitude de Deus ao buscar Adão e Eva revela o amor incondicional por Seus filhos. O Senhor nunca desiste de nós (veja Lucas 15:1-32). Ele vai muito longe para restabelecer comunhão conosco, mesmo quando tentamos nos esconder. Antes da crucifixão, quando Pedro negou Jesus três vezes, Cristo \"voltou-Se e fixou os olhos\" nele (Lucas 22:61). Mesmo sem dizer uma palavra, Ele Se comunicou com Pedro e procurou alcançar Seu amigo que havia falhado.\n\nPerceba como o pecado abalou repentinamente o relacionamento entre Adão e Eva (Gênesis 3:11-13). Em vez de confessar seu pecado individual, começaram a culpar outros. Adão culpou Eva e, indiretamente, o próprio Deus, pois foi Ele quem lhe dera a esposa: \"A mulher que me deste para estar comigo, ela me deu da árvore, e eu comi\" (Gênesis 3:12). Eva, por sua vez, culpou a serpente: \"A serpente me enganou, e eu comi\" (Gênesis 3:13). Nenhum dos dois, pelo menos naquele primeiro momento, assumiu a própria culpa. Quão pouco mudou em 6 mil anos!\n\nA verdade é que o pecado afetou todos os seres humanos. O apóstolo Paulo descreve muito bem nossa condição em Romanos 7:15-24, ao falar da angústia de desejar fazer o que é certo e, ainda assim, perceber que faz o contrário: \"Porque nem mesmo compreendo o meu próprio modo de agir, pois não faço o que prefiro, e sim o que detesto\" (Romanos 7:15). Quem não se identifica com isso? O que Paulo escreveu é profundo. Somos criaturas marcadas pela queda, que continuam fazendo aquilo que sabem que não deveriam fazer.\n\nNossa única esperança, afirma Paulo, é a libertação \"por Jesus Cristo, nosso Senhor\" (Romanos 7:25). É por isso que Deus continua a nos buscar: para nos conduzir a Jesus, o único que pode nos moldar à Sua imagem e nos salvar das consequências destruidoras do pecado.",
      versiculoChave: VERSO_L1,
      perguntas: [
        { id: "d4q1", pergunta: "Que pergunta Deus fez a Adão em Gênesis 3:9 — retórica, pois Ele já sabia a resposta?", opcoes: ["\"Por que você fugiu?\"", "\"O que você fez?\"", "\"Onde você está?\"", "\"Quem a enganou?\""], correta: 2, explicacao: "\"Onde você está?\" não era falta de informação: era Deus tomando a iniciativa de restaurar o diálogo com Seus filhos." },
        { id: "d4q2", pergunta: "Qual parábola de Jesus a lição usa para refletir Deus buscando Adão e Eva?", opcoes: ["O bom samaritano", "O filho pródigo", "O semeador", "Os talentos"], correta: 1, explicacao: "Lucas 15:11-32: assim como o pai da parábola, Deus toma a iniciativa de restaurar o relacionamento com o filho perdido." },
        { id: "d4q3", pergunta: "Verdadeiro ou falso: segundo o texto, quando Deus o questionou, Adão confessou seu pecado e assumiu toda a culpa.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "Falso. Adão culpou Eva (e indiretamente Deus), e Eva culpou a serpente. Nenhum dos dois assumiu a própria culpa naquele momento." },
        { id: "d4q4", pergunta: "Depois que Pedro O negou três vezes, como Jesus Se comunicou com ele, segundo Lucas 22:61?", opcoes: ["Escreveu algo no chão diante dele", "Voltou-Se e fixou os olhos nele", "Mandou João levar um recado a ele", "Chamou-o pelo nome em voz alta"], correta: 1, explicacao: "Mesmo sem dizer uma palavra, Cristo \"voltou-Se e fixou os olhos\" em Pedro, buscando o amigo que havia falhado." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-09-30",
      titulo: "Expulsos do jardim",
      conteudo: "Uma das consequências mais devastadoras do pecado foi a separação entre Deus e a humanidade. Adão e Eva foram expulsos do Éden e já não podiam falar com o Senhor face a face. O profeta Isaías descreveu essa condição radical: \"Mas as iniquidades de vocês fazem separação entre vocês e o seu Deus; e os pecados que vocês cometem O levam a esconder o Seu rosto de vocês\" (Isaías 59:2). De fato, Adão e Eva continuavam sendo filhos de Deus; porém, as consequências do pecado não puderam ser evitadas, e eles tiveram que deixar o Éden – nada seria como antes.\n\n4. Leia Êxodo 19:16-22. Como o pecado alterou nossa comunicação com Deus?\n\nO pecado transformou a vida humana de inúmeras maneiras (veja Gênesis 3:14-24), em aspectos que nem conseguimos imaginar, pois tudo o que conhecemos é um mundo de pecado. Por causa da queda, a terra foi amaldiçoada e produziria \"espinhos e ervas daninhas\". Os seres humanos agora vivenciariam a dor, trabalhariam arduamente para obter o sustento, até que, por fim, morressem e voltassem ao pó – a morte é a mais contundente lembrança do pecado.\n\nAinda assim, Adão e Eva receberam a promessa de uma solução para enfrentar os danos do pecado. Embora nossos primeiros pais já não pudessem ver Deus nem falar com Ele diretamente, deixaram o Éden com esperança, para o presente e para o futuro. Deus tomou a iniciativa e lhes revelou Seu plano de resgate.\n\nGênesis 3:15, chamado de \"primeira promessa do evangelho\", estava carregado de esperança para eles (e ainda está para nós), apesar do que havia acontecido. A promessa de um Redentor vindouro traria inimizade contra o pecado e ofereceria à humanidade uma esperança de salvação. Na verdade, o fato de Deus ter provido vestes para Adão e Eva antes de saírem do jardim foi um ato simbólico, que apontava para a redenção futura. Por meio da morte e ressurreição de Jesus, a comunhão com Deus seria restaurada (João 14:1-3).\n\nAli mesmo no Éden, logo após a entrada do pecado, a humanidade recebeu a esperança e a promessa de que o problema do pecado seria definitivamente resolvido. Desde o momento em que houve pecado, houve também a promessa de um Salvador.\n\nO que você sentiu ao errar? Culpa? Vergonha? Desprezo próprio? Quais foram as consequências? De que maneira sua fé em Deus e na promessa do evangelho o impediram de desistir?",
      versiculoChave: VERSO_L1,
      perguntas: [
        { id: "d5q1", tipo: "multipla", pergunta: "Quais destas consequências do pecado a lição menciona? (marque todas)", opcoes: ["Separação entre Deus e a humanidade", "Terra amaldiçoada, com espinhos", "Fim da promessa de um Redentor", "Trabalho árduo para o sustento"], corretas: [0, 1, 3], explicacao: "O pecado trouxe separação (Isaías 59:2), terra amaldiçoada e trabalho árduo (Gênesis 3:17-19). Mas a promessa não acabou: Gênesis 3:15, a \"primeira promessa do evangelho\", anunciou o Redentor ali mesmo no Éden." },
        { id: "d5q2", pergunta: "Complete Isaías 59:2: \"As iniquidades de vocês fazem ___ entre vocês e o seu Deus.\"", opcoes: ["afastamento", "tropeço", "separação", "silêncio"], correta: 2, explicacao: "O pecado gera separação: \"os pecados que vocês cometem O levam a esconder o Seu rosto de vocês\" (Isaías 59:2)." },
        { id: "d5q3", pergunta: "Segundo o texto, que gesto de Deus antes da saída do Éden foi um ato simbólico apontando para a redenção futura?", opcoes: ["Plantar uma árvore fora do jardim", "Prover vestes para Adão e Eva", "Acender um fogo para aquecê-los", "Ensinar a construir um altar"], correta: 1, explicacao: "Deus proveu vestes para Adão e Eva — um símbolo de que Ele mesmo cobriria a culpa humana por meio do Redentor." },
        { id: "d5q4", pergunta: "Verdadeiro ou falso: segundo a lição, a morte é a mais contundente lembrança do pecado.", opcoes: ["Verdadeiro", "Falso"], correta: 0, explicacao: "Verdadeiro. O texto afirma que, por causa da queda, os seres humanos voltariam ao pó, e \"a morte é a mais contundente lembrança do pecado\"." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-10-01",
      titulo: "Porta-vozes de Deus",
      conteudo: "5. O que os textos a seguir revelam sobre a maneira como Deus tem falado à humanidade depois da entrada do pecado? Hebreus 1:1, 2; Romanos 1:19, 20; Romanos 12:6; 2 Timóteo 3:16, 17; João 14:7-9; João 10:27-30\n\nApesar do pecado, Deus encontrou muitas formas de Se comunicar com os seres humanos decaídos. Uma delas é a criação. A natureza revela de modo poderoso as obras maravilhosas de Deus. Cientistas se impressionam com as maravilhas do Universo e com a complexidade até mesmo das formas de vida mais \"simples\". Ao mesmo tempo, a própria natureza expõe as consequências da queda, sendo a morte de todos os seres vivos o lembrete mais contundente.\n\nOutra forma pela qual Deus tem falado à humanidade é por meio dos profetas – pessoas que Ele escolheu como porta-vozes. O Senhor falou, por exemplo, com Noé, Abraão, Moisés e Daniel, revelando Sua vontade para o Seu povo. Em essência, as mensagens proféticas de Deus reafirmam, vez após vez, que Ele não Se esqueceu de Seus filhos e continua ao lado deles. E, embora muitos profetas tenham deixado textos que chegaram até nós como parte das Escrituras, nem todos escreveram livros da Bíblia.\n\nMesmo assim, muitas palavras dos profetas foram preservadas nas Escrituras (2 Timóteo 3:16, 17). A Bíblia é uma revelação do próprio Deus. Por meio de Suas palavras, aprendemos quem Ele é, sentimos Seu amor incansável e descobrimos Sua orientação sobre como devemos viver.\n\nAlém disso, é por meio da Bíblia que compreendemos quem somos, de onde viemos e para onde estamos indo. Nela encontramos o propósito de Deus para nossa vida.\n\nNo entanto, a forma mais eficaz pela qual Deus nos falou foi por meio de Jesus Cristo, que, naturalmente, nos é revelado nas Escrituras. Assim como Deus buscou Adão e Eva no jardim do Éden, Cristo veio buscar e salvar o perdido (Lucas 19:10). Ele declarou: \"Quem vê a Mim vê o Pai\" (João 14:9). Por Sua vida, morte e ressurreição, Cristo cumpriu a promessa feita a Adão e Eva no Éden. Ele veio e morreu em nosso lugar para que, por meio Dele, tenhamos a vida eterna.\n\nDepois da ascensão de Jesus ao Céu, o Espírito Santo continua a nos guiar \"em toda a verdade\" e a nos falar sobre as \"coisas que estão para acontecer\" (João 16:13).\n\nQuanto consolo você encontra ao saber que Jesus – Seu amor, Seu caráter e Seu sacrifício – revela quem o Pai realmente é?",
      versiculoChave: VERSO_L1,
      perguntas: [
        { id: "d6q1", pergunta: "Segundo a lição, qual foi a forma mais eficaz pela qual Deus nos falou?", opcoes: ["A natureza", "Os sonhos e visões", "Jesus Cristo", "A lei no Sinai"], correta: 2, explicacao: "A natureza, os profetas e as Escrituras falam de Deus, mas a forma mais eficaz foi Jesus: \"Quem vê a Mim vê o Pai\" (João 14:9)." },
        { id: "d6q2", pergunta: "Qual destes NÃO aparece na lista de profetas com quem, segundo o texto, Deus falou?", opcoes: ["Noé", "Abraão", "Daniel", "Jonas"], correta: 3, explicacao: "O texto cita como exemplos Noé, Abraão, Moisés e Daniel. Jonas foi profeta, mas não está nessa lista." },
        { id: "d6q3", pergunta: "Verdadeiro ou falso: a lição afirma que a natureza revela apenas a bondade de Deus, sem mostrar nenhum sinal da queda.", opcoes: ["Verdadeiro", "Falso"], correta: 1, explicacao: "Falso. A natureza revela as obras de Deus, mas também expõe as consequências da queda — a morte dos seres vivos é o lembrete mais forte." },
        { id: "d6q4", tipo: "pares", pergunta: "Ligue cada frase à sua referência:", pares: [["\"Quem vê a Mim vê o Pai\"", "João 14:9"], ["Veio buscar e salvar o perdido", "Lucas 19:10"], ["Guiará \"em toda a verdade\"", "João 16:13"], ["Toda a Escritura é inspirada", "2 Timóteo 3:16"]], explicacao: "A lição mostra várias vozes de Deus: as Escrituras inspiradas (2 Timóteo 3:16), Jesus, que revela o Pai (João 14:9) e veio buscar o perdido (Lucas 19:10), e o Espírito, que guia em toda a verdade (João 16:13)." },
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-10-02",
      titulo: "Ellen White",
      conteudo: "A comunicação de Deus não se limitou aos tempos bíblicos. Ele continua falando aos seres humanos, e Suas palavras ainda se manifestam em nosso tempo, até a volta de Cristo.\n\nEllen Gould Harmon e sua irmã gêmea, Elizabeth, nasceram em 26 de novembro de 1827, em Gorham, Maine, nos Estados Unidos. Eram as caçulas entre oito filhos de Eunice e Robert Harmon. Alguns anos depois, a família se mudou para Portland, Maine. Aos 9 anos, Ellen sofreu um trauma que a afetou física, emocional e socialmente. Em um parque perto de casa, uma colega de escola, em um acesso de raiva, atirou uma pedra que atingiu seu rosto e a deixou semiconsciente por várias semanas. Esse acidente interrompeu abruptamente sua educação formal e trouxe desafios de saúde que a acompanhariam por toda a vida, além de afetar sua autoestima e o convívio social.\n\nNesse contexto de dor e incerteza, a jovem Ellen passou a pensar em seu destino eterno. Ela tinha medo de Deus e se sentia indigna do Céu. Esses temores se intensificaram quando a família Harmon aceitou a mensagem milerita da breve volta de Jesus. Mesmo depois de seu batismo por imersão na Igreja Metodista, em 1842, Ellen ainda não se sentia digna do amor de Deus e \"acreditava que estava perdida para sempre\" (Testemunhos Para a Igreja, v. 1, p. 25; veja também p. 17-34).\n\nEllen teve dois sonhos que começaram a mudar sua visão sobre Deus. Mas foi apenas quando conheceu Levi Stockman, um pastor metodista, que ela compreendeu e experimentou de fato o amor e a graça divinos. Mais tarde, ela escreveu: \"A fé tomou posse de meu coração. Experimentei um inexprimível amor por Deus, e tinha o testemunho de Seu Espírito de que meus pecados estavam perdoados. Minhas opiniões a respeito do Pai estavam mudadas. Considerava-O agora um Pai bondoso e afetuoso, em vez de um tirano severo que forçava as pessoas a uma obediência cega. Meu coração se deixava conduzir a Ele em amor profundo e fervoroso\" (Vida e Ensinos, p. 23). Ao compreender a doutrina bíblica do estado dos mortos, Ellen entendeu gradualmente que não existe um inferno eterno. Sua nova compreensão do caráter de Deus e de Seu amor foi transformadora. Ellen White passou a amar profundamente a Jesus e O serviu por toda a vida.\n\nRespostas às perguntas da semana: 1. Havia comunicação direta, clara e íntima, com diálogo pessoal entre Deus e o ser humano. 2. Eles se esconderam por causa da culpa e do medo, mesmo sendo impossível ocultar-se de Deus. 3. Assim como Deus buscou o ser humano caído, o pai da parábola toma a iniciativa de restaurar o relacionamento com o filho perdido. 4. O pecado trouxe separação, medo e necessidade de mediação na relação entre Deus e a humanidade. 5. Eles revelam que Deus continua falando por meio da criação, dos profetas, das Escrituras e, de modo supremo, por meio de Jesus Cristo.",
      versiculoChave: VERSO_L1,
      perguntas: [
        { id: "d7q1", pergunta: "Quando e onde Ellen Gould Harmon nasceu?", opcoes: ["Em 1844, em Portland, Maine", "Em 1827, em Gorham, Maine", "Em 1815, em Boston", "Em 1863, em Battle Creek, Michigan"], correta: 1, explicacao: "Ellen e sua irmã gêmea, Elizabeth, nasceram em 26 de novembro de 1827, em Gorham, Maine. Depois a família se mudou para Portland." },
        { id: "d7q2", pergunta: "O que aconteceu com Ellen aos 9 anos, interrompendo sua educação formal?", opcoes: ["Caiu de um cavalo a caminho da escola", "Foi atingida no rosto por uma pedra", "Contraiu uma febre que durou meses", "Perdeu a casa em um incêndio"], correta: 1, explicacao: "Uma colega, num acesso de raiva, atirou uma pedra que atingiu seu rosto e a deixou semiconsciente por várias semanas." },
        { id: "d7q3", pergunta: "Como se chamava a irmã gêmea de Ellen?", opcoes: ["Henriqueta", "Mary", "Elizabeth", "Anna"], correta: 2, explicacao: "Ellen e Elizabeth eram as caçulas entre os oito filhos de Eunice e Robert Harmon." },
        { id: "d7q4", tipo: "relampago", pergunta: "Rodada relâmpago: revise a semana!", itens: [{ texto: "Fomos criados para um relacionamento face a face com o Criador.", verdadeiro: true }, { texto: "Segundo a lição, Deus criou Adão e Eva como \"robôs\" obedientes.", verdadeiro: false }, { texto: "Em Gênesis 3:9, Deus perguntou a Adão: \"Onde você está?\"", verdadeiro: true }, { texto: "A lição chama Gênesis 3:15 de \"primeira lei moral\".", verdadeiro: false }, { texto: "Ellen só entendeu a graça de Deus ao conhecer o pastor Levi Stockman.", verdadeiro: true }], explicacao: "Fomos feitos para comunhão face a face; Deus nos criou livres, não como robôs, porque o amor envolve escolha. Ele buscou Adão (\"Onde você está?\") e deu a \"primeira promessa do evangelho\" (Gênesis 3:15). E Ellen compreendeu o amor de Deus com a ajuda de Levi Stockman." },
      ]
    }
  ]
};
