export const LICAO_ADULT_4 = {
  titulo: "Lição 4 - Pecado na igreja (18 a 24 de julho)",
  semana: "2026-W29",
  trimestre: "1 e 2 Coríntios",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-07-18",
      titulo: "Pecado na igreja",
      conteudo: "Nossos cérebros são como esponjas: tudo o que entra em contato com eles através dos nossos sentidos permanece. Podemos não estar conscientes da maior parte do que entra (seríamos incapazes de pensar com clareza se nos lembrássemos de tudo), mas tudo está lá e, em certa medida, influencia o que pensamos, sentimos e fazemos.\n\nÉ por isso que é tão fácil para nós, mesmo como cristãos, sermos afetados por todas as coisas ruins ao nosso redor. A igreja cristã, desde o início, tem lutado com esse problema. De onde, por exemplo, surgiu a observância do domingo? A igreja simplesmente a inventou? Claro que não. Ela surgiu da cultura ao seu redor.\n\nE podemos ver esse princípio se desdobrando aqui em Corinto. Após um apelo contra o partidarismo (1 Coríntios 1–4), Paulo agora se volta para questões relacionadas à imoralidade sexual, processos judiciais, prostituição, casamento e celibato (1 Coríntios 5–7). Os padrões do mundo os afetavam profundamente. As divisões descritas em 1 Coríntios 1–4 abriram caminho para o comportamento moral denunciado nos capítulos seguintes. Como Paulo busca abordar esse pecado na igreja e que lições podemos extrair do que ele escreveu?\n\nEstude a lição desta semana para se preparar para o Sábado, 25 de Julho.",
      versiculoChave: { texto: "Será que vocês não sabem que o coração de você é santuário do Espírito Santo, que está em vocês e que vocês receberam de Deus, e que vocês não pertencem a vocês mesmos? Por que vocês foram comprados por preço. Agora, pois, glorifiquem a Deus no corpo de vocês", referencia: "1 Coríntios 6:19, 20" },
      perguntas: [
        { id: "d1q1", pergunta: "Segundo o texto, nossos cérebros são comparados a quê?", opcoes: ["Um disco rígido vazio", "Esponjas que absorvem tudo ao redor", "Um filtro que bloqueia o mal", "Uma tela em branco"], correta: 1, explicacao: "A resposta correta é: Esponjas que absorvem tudo ao redor." },
        { id: "d1q2", pergunta: "De onde, segundo o texto, surgiu a observância do domingo?", opcoes: ["De uma ordem direta de Paulo", "Da cultura ao redor da igreja", "Diretamente das Escrituras", "De um concílio apostólico"], correta: 1, explicacao: "A resposta correta é: Da cultura ao redor da igreja." },
        { id: "d1q3", pergunta: "Após o apelo contra o partidarismo (1 Coríntios 1-4), para que assuntos Paulo se volta em 1 Coríntios 5-7?", opcoes: ["Dons espirituais", "Imoralidade sexual, processos judiciais, casamento e celibato", "A ressurreição", "A segunda vinda"], correta: 1, explicacao: "A resposta correta é: Imoralidade sexual, processos judiciais, casamento e celibato." },
        { id: "d1q4", pergunta: "Segundo o texto, o que abriu caminho para o comportamento moral denunciado em 1 Coríntios 5-7?", opcoes: ["A perseguição romana", "As divisões descritas em 1 Coríntios 1-4", "A chegada de Timóteo", "A fome em Corinto"], correta: 1, explicacao: "A resposta correta é: As divisões descritas em 1 Coríntios 1-4." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-07-19",
      titulo: "Incoerência entre fé e prática",
      conteudo: "Ao longo da história cristã, teólogos, pastores e leigos estudaram o Novo Testamento para determinar como a igreja deveria ser. Admiramos, por exemplo, a igreja de Atos. Mas rapidamente perdemos de vista um elemento significativo: as pessoas têm problemas. Parece que também podemos ler o Novo Testamento para ver o que a Bíblia diz sobre como uma igreja não deveria ser. As cartas de Paulo aos Coríntios são um bom ponto de partida.\n\n1. Leia 1 Coríntios 5:1-13. Que situação escandalosa Paulo descreve nesse trecho, e por que ela é tão perturbadora?\n\nA expressão \"a mulher de seu pai\" (1 Coríntios 5:1) sugere que Paulo se refere à relação incestuosa entre um homem e sua madrasta. Essa situação provavelmente foi relatada \"pelos da casa de Cloé\" (1 Coríntios 1:11). O incesto era considerado um pecado tão terrível que \"não era tolerado nem mesmo entre os pagãos\" (1 Coríntios 5:1). E, no entanto, isso estava acontecendo em uma igreja cristã primitiva? As palavras de Paulo em 1 Coríntios 5:1, 2 mostram que ele está chocado com o relato de que um membro da igreja estava fazendo isso.\n\nContudo, essa situação ruim piora ainda mais. Paulo fica ainda mais perplexo ao perceber que, em vez de se arrependerem da situação, os coríntios se orgulhavam de tolerar tal pecado (1 Coríntios 5:1, 2). Assim, ele pretende corrigir não apenas o homem imoral, mas também a igreja por sua aparente dissonância entre fé e prática. De fato, Paulo deixa claro constantemente que a atitude indulgente da igreja em relação ao homem incestuoso exigia uma correção. Mas orgulhar-se de um escândalo sexual como esse, e até mesmo vangloriar-se dele (1 Coríntios 5:2, 6)! Isso era demais para Paulo suportar. O que havia de errado com essas pessoas?\n\nNão temos uma explicação para o motivo pelo qual a igreja de Corinto foi tão tolerante com o homem incestuoso. Talvez ele fosse um membro rico de quem a igreja se beneficiava? Ou talvez, porque \"todas as coisas são lícitas\" (1 Coríntios 6:12), eles não julgaram a situação da maneira correta. Simplesmente não sabemos.\n\nQuaisquer que fossem os verdadeiros motivos, eles se tornaram cegos para uma violação flagrante das Escrituras (Levítico 18:7, 8). E eles até se orgulhavam disso.\n\nQuais práticas claramente condenadas nas Escrituras corremos o risco de tolerar em nome do \"amor\" e da \"aceitação\"?",
      versiculoChave: { texto: "Será que vocês não sabem que o coração de você é santuário do Espírito Santo, que está em vocês e que vocês receberam de Deus, e que vocês não pertencem a vocês mesmos? Por que vocês foram comprados por preço. Agora, pois, glorifiquem a Deus no corpo de vocês", referencia: "1 Coríntios 6:19, 20" },
      perguntas: [
        { id: "d2q1", pergunta: "Que situação escandalosa Paulo descreve em 1 Coríntios 5?", opcoes: ["Um roubo na igreja", "Uma relação incestuosa entre um homem e sua madrasta", "Uma briga entre líderes", "Um caso de mentira"], correta: 1, explicacao: "A resposta correta é: Uma relação incestuosa entre um homem e sua madrasta." },
        { id: "d2q2", pergunta: "Como a igreja de Corinto reagia a essa situação, segundo o texto?", opcoes: ["Corrigiu o homem imediatamente", "Orgulhava-se de tolerar tal pecado", "Expulsou-o sem julgamento", "Ignorou completamente o caso"], correta: 1, explicacao: "A resposta correta é: Orgulhava-se de tolerar tal pecado." },
        { id: "d2q3", pergunta: "Segundo o texto, esse tipo de incesto era tolerado até entre...", opcoes: ["Os cristãos apenas", "Nem mesmo entre os pagãos", "Todos os povos antigos", "Os romanos oficialmente"], correta: 1, explicacao: "A resposta correta é: Nem mesmo entre os pagãos." },
        { id: "d2q4", pergunta: "Quem provavelmente relatou essa situação a Paulo?", opcoes: ["Timóteo", "Os da casa de Cloé", "Apolo", "Silas"], correta: 1, explicacao: "A resposta correta é: Os da casa de Cloé." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-07-20",
      titulo: "Lidando com escândalos",
      conteudo: "Lidar com questões de sexualidade é sempre difícil. Foi difícil para Paulo, e também é para nós. Nessas situações, devemos ser fiéis às Escrituras e abordar o assunto com oração e amor. Nunca devemos nos esquecer de que nosso objetivo é a restauração.\n\n2. Leia novamente 1 Coríntios 5:1-13. Como Paulo orientou a igreja a lidar com esse texto?\n\nPaulo deixa claro em 1 Coríntios 5 que escândalos sexuais exigem disciplina na igreja. Ele diz que o homem incestuoso deve ser afastado (1 Coríntios 5:2), julgado (1 Coríntios 5:3), entregue a Satanás (1 Coríntios 5:5) e \"expulso\" (1 Coríntios 5:13). Os membros da igreja foram instruídos a \"não se associarem\" com ele (1 Coríntios 5:9, 11) e nem mesmo \"comerem com tal pessoa\" (1 Coríntios 5:11). Paulo emprega uma linguagem forte que pode soar ofensiva aos ouvidos modernos, mas suas palavras devem ser compreendidas em seu contexto histórico. Além disso, é preciso lembrar que ele está lidando com um estilo de vida flagrantemente pecaminoso. Geralmente, em situações extremas, uma linguagem forte é necessária. De qualquer forma, uma breve explicação de algumas expressões é útil.\n\n\"Que ele seja removido do meio de vocês\" (1 Coríntios 5:2; também 1 Coríntios 5:13). Isso se refere à disciplina na igreja.\n\n\"Entreguem este homem a Satanás\" (1 Coríntios 5:5). Como este homem não escolheu estar sob a proteção de Deus, vivendo em obediência a Ele, ele se tornaria vulnerável a Satanás. Portanto, essa expressão pode simplesmente significar algo como \"Que ele colha os frutos de suas decisões\".\n\n\"Não se associe\" (1 Coríntios 5:9, 11), \"nem mesmo coma com tal pessoa\" (1 Coríntios 5:11). A convivência próxima com pessoas sexualmente imorais era considerada perigosa porque elas poderiam influenciar outros a imitar sua conduta. Nos tempos antigos, compartilhar uma refeição também podia significar compartilhar valores. Todos nós somos suscetíveis às influências que nos cercam e precisamos nos proteger da melhor maneira possível, especialmente ao lidar com algo assim.\n\n\"Para que o seu espírito seja salvo\" (1 Coríntios 5:5). A disciplina na igreja tem caráter reabilitador. Ela visa trazer os pecadores de volta à razão e levá-los a abandonar seus estilos de vida pecaminosos. Possivelmente, é isso que Paulo quis dizer com \"destruição da carne\" (1 Coríntios 5:5). É possível também que o homem incestuoso em 1 Coríntios 5 seja o homem arrependido mencionado posteriormente (ver 2 Coríntios 2:5-10). A disciplina na igreja atinge seu propósito quando o membro transgressor é reintegrado à comunhão da igreja.",
      versiculoChave: { texto: "Será que vocês não sabem que o coração de você é santuário do Espírito Santo, que está em vocês e que vocês receberam de Deus, e que vocês não pertencem a vocês mesmos? Por que vocês foram comprados por preço. Agora, pois, glorifiquem a Deus no corpo de vocês", referencia: "1 Coríntios 6:19, 20" },
      perguntas: [
        { id: "d3q1", pergunta: "Segundo Paulo, o que deveria acontecer com o homem incestuoso?", opcoes: ["Ser promovido a líder", "Ser removido/expulso do meio da igreja", "Ser ignorado", "Receber um cargo de ensino"], correta: 1, explicacao: "A resposta correta é: Ser removido/expulso do meio da igreja." },
        { id: "d3q2", pergunta: "O que significa \"entregar este homem a Satanás\", segundo o texto?", opcoes: ["Uma maldição eterna", "Ele colher os frutos de suas próprias decisões, fora da proteção de Deus", "Uma sentença de morte física", "Uma expressão sem significado"], correta: 1, explicacao: "A resposta correta é: Ele colher os frutos de suas próprias decisões, fora da proteção de Deus." },
        { id: "d3q3", pergunta: "Qual é o propósito final da disciplina na igreja, segundo o texto?", opcoes: ["Humilhar publicamente o pecador", "Que o espírito do pecador seja salvo, de forma reabilitadora", "Proteger a reputação financeira da igreja", "Substituir o pecador por outro membro"], correta: 1, explicacao: "A resposta correta é: Que o espírito do pecador seja salvo, de forma reabilitadora." },
        { id: "d3q4", pergunta: "Por que os membros foram instruídos a não comer com a pessoa em pecado?", opcoes: ["Por razões de higiene", "Porque a convivência próxima poderia influenciar outros a imitar a conduta", "Por uma lei romana", "Não há explicação no texto"], correta: 1, explicacao: "A resposta correta é: Porque a convivência próxima poderia influenciar outros a imitar a conduta." }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-07-21",
      titulo: "Protegendo a identidade da igreja",
      conteudo: "Em 1 Coríntios 6:1-11, Paulo continua sua discussão sobre como os cristãos devem abordar questões que envolvem pessoas na igreja.\n\n3. Leia 1 Coríntios 5:3, 12, 13; 6:1-11. Paulo prossegue tratando de como os cristãos devem lidar com questões que envolvem membros da igreja.\n\nA palavra grega pragma em 1 Coríntios 6:1, traduzida como \"assunto\" na Nova Versão Internacional, é um termo genérico que significa \"coisa\". Aqui, refere-se a uma questão legal. É importante lembrar que 1 Coríntios 6:1-11 não se refere a um caso criminal. A autoridade dos tribunais civis em matéria criminal é afirmada em Romanos 13:1-5. Paulo aborda um caso de litígio logo após um caso de imoralidade sexual, assim como Moisés fez em Deuteronômio 22:22-24. Isso demonstra o quanto a maneira de Paulo lidar com os problemas na igreja se baseia nas Escrituras.\n\nO fato de o caso em 1 Coríntios 6:1-11 estar entremeado por passagens que tratam de imoralidade sexual (1 Coríntios 5, 1 Coríntios 6:12-20) pode sugerir que a \"questão\" em 1 Coríntios 6:1 também se refira à imoralidade sexual. Não sabemos ao certo qual é o caso, se uma questão civil menor, como uma disputa de propriedade, ou um problema sexual.\n\nIndependentemente da solução final, Paulo não ficou satisfeito ao ver os membros da igreja levando a questão a um tribunal civil. Não poderiam eles, como irmãos e irmãs em Cristo, ter resolvido o problema entre si, em vez de levar a questão perante \"os injustos\" (1 Coríntios 6:1)?\n\nÉ possível também, como alguns supõem, que os litigantes de 1 Coríntios 6:1 sejam o pai e o filho de 1 Coríntios 5:1. Em todo caso, não é necessário entender a questão para compreender o ponto principal. Paulo se preocupava com a identidade da igreja como comunidade cristã, tal como vista por pessoas de fora. Os cristãos não devem expor seus problemas internos em público (1 Coríntios 6:6). Tampouco devem usar meios seculares para julgar assuntos internos. No mundo romano, indivíduos de maior riqueza ou posição política tendiam a ser favorecidos nos tribunais. Em contrapartida, os cristãos devem exercer um julgamento semelhante ao de Cristo e se distinguir dos padrões seculares.\n\nPense nas listas de pecados de 1 Coríntios 5:10,11; 1 Coríntios 6:9, 10. Por que Paulo listou pecados sexuais ao lado de idolatria, furto, avareza e extorsão?",
      versiculoChave: { texto: "Será que vocês não sabem que o coração de você é santuário do Espírito Santo, que está em vocês e que vocês receberam de Deus, e que vocês não pertencem a vocês mesmos? Por que vocês foram comprados por preço. Agora, pois, glorifiquem a Deus no corpo de vocês", referencia: "1 Coríntios 6:19, 20" },
      perguntas: [
        { id: "d4q1", pergunta: "O que a palavra grega \"pragma\" significa em 1 Coríntios 6:1?", opcoes: ["Pecado", "Assunto/coisa, referindo-se a uma questão legal", "Perdão", "Oração"], correta: 1, explicacao: "A resposta correta é: Assunto/coisa, referindo-se a uma questão legal." },
        { id: "d4q2", pergunta: "Qual era a preocupação de Paulo ao ver membros levando questões a tribunais civis?", opcoes: ["O custo do processo", "Expor os problemas internos da igreja publicamente", "A demora dos tribunais romanos", "A falta de advogados cristãos"], correta: 1, explicacao: "A resposta correta é: Expor os problemas internos da igreja publicamente." },
        { id: "d4q3", pergunta: "Segundo o texto, no mundo romano, quem tendia a ser favorecido nos tribunais?", opcoes: ["Os mais pobres", "Indivíduos de maior riqueza ou posição política", "Os estrangeiros", "Os escravos"], correta: 1, explicacao: "A resposta correta é: Indivíduos de maior riqueza ou posição política." },
        { id: "d4q4", pergunta: "Qual comparação o texto faz entre Paulo e Moisés quanto à ordem dos assuntos abordados?", opcoes: ["Nenhuma relação", "Ambos tratam de litígio logo após um caso de imoralidade sexual", "Ambos escreveram sobre dons espirituais", "Ambos condenaram apenas o roubo"], correta: 1, explicacao: "A resposta correta é: Ambos tratam de litígio logo após um caso de imoralidade sexual." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-07-22",
      titulo: "Antídoto contra a imoralidade sexual",
      conteudo: "4. Leia 1 Tessalonicenses 4:1-8. O que esse texto ensina sobre a relação entre a santificação e a abstinência da imoralidade sexual?\n\nEmbora Paulo estivesse escrevendo para outra pessoa nos textos acima, o princípio pode ser aplicado de forma geral, a todos os cristãos, o que ainda nos leva à pergunta: O que estava acontecendo em Corinto? Por que todos esses problemas?\n\nAlguns em Corinto aparentemente acreditavam que, como o evangelho os havia libertado, tinham permissão para fazer qualquer coisa. Argumentavam que, assim como o estômago foi feito para o alimento, o corpo foi feito para o sexo, e o sexo para o corpo (1 Coríntios 6:13). Paulo responde que isso é uma deturpação da liberdade cristã. A falta de integridade em assuntos sexuais é incompatível com a identidade cristã e constitui um mau uso da liberdade concedida ao homem pelo evangelho (Romanos 8:2; Gálatas 5:13). Fomos libertos do pecado, não \"libertos\" para cometê-lo (Romanos 8:2; Romanos 6:18, 22). De fato, \"o corpo é [...] para o Senhor, e o Senhor para o corpo\" (1 Coríntios 6:13). Pertencemos a Cristo (1 Coríntios 6:15), e quem somos deve influenciar o que fazemos. Uma coisa está inextricavelmente ligada à outra. Isso é retratado em 1 Coríntios 6 de três maneiras diferentes.\n\nPrimeiramente, somos identificados como lavados, santificados e justificados \"em nome do Senhor Jesus e pelo Espírito do nosso Deus\" (1 Coríntios 6:11). Os pecados listados em 1 Coríntios 6:9, 10, bem como a imoralidade sexual denunciada em 1 Coríntios 6:12-20, não têm lugar na vida daqueles que foram lavados, santificados e justificados.\n\nEm segundo lugar, somos membros de Cristo (1 Coríntios 6:15). Isso significa que devemos estar unidos a Cristo (1 Coríntios 6:17). A imoralidade sexual é uma violação dessa união (1 Coríntios 6:13, 15). Quem se une a uma pessoa em relações sexuais extraconjugais torna-se \"um só corpo\" com ela (1 Coríntios 6:16). A união com Cristo por meio do Espírito deve determinar a ética cristã em assuntos sexuais.\n\nTerceiro, nossos corpos são \"templos do Espírito Santo\" (1 Coríntios 6:19, 20). A única maneira de viver uma vida santa com integridade em assuntos sexuais é ter um relacionamento íntimo com Cristo por meio do Espírito Santo. Em outra passagem, Paulo se refere à experiência de ser um templo do Espírito em termos de apresentar o corpo \"como sacrifício vivo, santo e agradável a Deus\" (Romanos 12:1).\n\nPense nos estragos que os pecados sexuais têm causado à humanidade. O que isso nos diz sobre a seriedade com que os cristãos devem tratar esse tema?",
      versiculoChave: { texto: "Será que vocês não sabem que o coração de você é santuário do Espírito Santo, que está em vocês e que vocês receberam de Deus, e que vocês não pertencem a vocês mesmos? Por que vocês foram comprados por preço. Agora, pois, glorifiquem a Deus no corpo de vocês", referencia: "1 Coríntios 6:19, 20" },
      perguntas: [
        { id: "d5q1", pergunta: "Qual argumento alguns em Corinto usavam para justificar a imoralidade sexual?", opcoes: ["Que o corpo foi feito para o sexo, assim como o estômago para o alimento", "Que o casamento era proibido", "Que Paulo havia autorizado", "Que não havia problema porque eram gentios"], correta: 0, explicacao: "A resposta correta é: Que o corpo foi feito para o sexo, assim como o estômago para o alimento." },
        { id: "d5q2", pergunta: "Segundo o texto, fomos libertos do pecado para...", opcoes: ["Cometê-lo livremente", "Não cometê-lo", "Ignorá-lo", "Discuti-lo publicamente"], correta: 1, explicacao: "A resposta correta é: Não cometê-lo." },
        { id: "d5q3", pergunta: "De que somos \"membros\", segundo 1 Coríntios 6:15, mencionado no texto?", opcoes: ["Da sinagoga", "De Cristo", "Do império romano", "De uma seita grega"], correta: 1, explicacao: "A resposta correta é: De Cristo." },
        { id: "d5q4", pergunta: "Segundo 1 Coríntios 6:19,20, o que são nossos corpos?", opcoes: ["Propriedade exclusiva nossa", "Templos do Espírito Santo", "Meros instrumentos biológicos", "Irrelevantes para a fé"], correta: 1, explicacao: "A resposta correta é: Templos do Espírito Santo." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-07-23",
      titulo: "Casados e solteiros",
      conteudo: "A afirmação de Paulo de que o corpo \"é o templo do Espírito Santo\" (1 Coríntios 6:19) ocorre no contexto de uma advertência contra a imoralidade sexual. Ser um templo do Espírito é o único meio de viver uma vida santa. A igreja é uma comunidade cristã que se distingue do ambiente ao seu redor. É a presença do Espírito Santo que torna isso possível.\n\n5. Leia 1 Coríntios 6:19, 20; 1 Coríntios 7:1-9. Como esse trecho esclarece, na prática, o mandamento: \"Fujam da imoralidade sexual!\" (1 Coríntios 6:18)?\n\nHá lições importantes sobre sexualidade em 1 Coríntios 7. De forma geral, este capítulo pode ser dividido em duas seções: (1) instruções sobre o casamento (1 Coríntios 7:1-24) e (2) instruções sobre a solteirice (1 Coríntios 7:25-40). 1 Coríntios 7 nos ajuda a entender que falar sobre sexualidade é importante e necessário.\n\nNo entanto, ao ler 1 Coríntios 7, devemos lembrar que Paulo está respondendo a perguntas específicas relacionadas a questões da igreja de Corinto. Caso contrário, algumas declarações poderiam levar à impressão de que ele tem uma visão negativa do casamento, o que não é o caso (1 Timóteo 4:1-3, 1 Timóteo 5:14; também Hebreus 13:4).\n\nCuriosamente, a ordem \"fujam da imoralidade sexual\" em 1 Coríntios 6:18 está entre parênteses da ideia de se unir a Cristo (1 Coríntios 6:17) e ser um templo do Espírito (1 Coríntios 6:19). Existe maneira melhor de fugir da imoralidade sexual? Claro que não.\n\nAlém disso, Deus criou o sexo, mas ele deve ser desfrutado somente no casamento. O sexo é um privilégio daqueles que estão em um casamento entre homem e mulher, o único tipo sancionado na Bíblia.\n\nAo dizer \"fujam da imoralidade sexual\", Paulo pode estar se referindo à história de José (Gênesis 39:6-18). A Bíblia diz que, diante das investidas lascivas da esposa de Potifar, José \"fugiu da casa\" (Gênesis 39:18). Isso é mencionado pelo menos quatro vezes em Gênesis 39:6-18. A Bíblia não diz isso diretamente, mas está implícito que José esperou para ter relações sexuais somente no casamento (Gênesis 41:45). Ele era um homem cheio do Espírito Santo (Gênesis 41:38) e queria fazer o que era reto aos olhos de Deus.\n\nDe que maneiras podemos, como igreja, nos proteger das visões deturpadas de sexualidade que dominam a cultura?",
      versiculoChave: { texto: "Será que vocês não sabem que o coração de você é santuário do Espírito Santo, que está em vocês e que vocês receberam de Deus, e que vocês não pertencem a vocês mesmos? Por que vocês foram comprados por preço. Agora, pois, glorifiquem a Deus no corpo de vocês", referencia: "1 Coríntios 6:19, 20" },
      perguntas: [
        { id: "d6q1", pergunta: "Em que duas seções o texto divide 1 Coríntios 7?", opcoes: ["Alimentação e jejum", "Instruções sobre casamento e sobre solteirice", "Dons espirituais e disciplina", "Oração e evangelismo"], correta: 1, explicacao: "A resposta correta é: Instruções sobre casamento e sobre solteirice." },
        { id: "d6q2", pergunta: "A ordem \"fujam da imoralidade sexual\" (1 Coríntios 6:18) está relacionada a que ideias, segundo o texto?", opcoes: ["Unir-se a Cristo e ser templo do Espírito", "Riqueza e poder", "Tradição judaica apenas", "Nenhuma relação especial"], correta: 0, explicacao: "A resposta correta é: Unir-se a Cristo e ser templo do Espírito." },
        { id: "d6q3", pergunta: "Que exemplo bíblico o texto cita de alguém que \"fugiu\" da tentação sexual?", opcoes: ["Davi", "José, fugindo da esposa de Potifar", "Sansão", "Salomão"], correta: 1, explicacao: "A resposta correta é: José, fugindo da esposa de Potifar." },
        { id: "d6q4", pergunta: "Segundo o texto, qual é o único tipo de relação sexual sancionado na Bíblia?", opcoes: ["Qualquer relação consensual", "No casamento entre homem e mulher", "Relações fora do casamento, se por amor", "O texto não define isso"], correta: 1, explicacao: "A resposta correta é: No casamento entre homem e mulher." }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-07-24",
      titulo: "Estudo Adicional - Pecado na igreja",
      conteudo: "Leia Ellen G. White, Atos dos Apóstolos, \"Mensagem de advertência e apelo\", p. 190–196.\n\nCuriosamente, no catálogo de vícios em 1 Coríntios 5:10, 11 e 6:9, 10, a idolatria e a embriaguez são listadas juntamente com a imoralidade sexual. Como Paulo recorda em 1 Coríntios 10:7 (compare com Êxodo 32:1-6), as festas idólatras eram geralmente marcadas por excesso de comida e bebida, o que abria caminho para a imoralidade sexual (1 Coríntios 10:8). Ellen G. White afirma:\n\n\"É impossível para qualquer pessoa desfrutar da bênção da santificação enquanto for egoísta e glutona. [...] O poder da constituição humana de resistir aos abusos que lhe são infligidos é maravilhoso, mas hábitos errôneos persistentes, como comer e beber em excesso, enfraquecerão todas as funções do corpo. Na satisfação de apetites e paixões pervertidas, até mesmo os cristãos professos prejudicam a natureza em seu funcionamento e diminuem o poder físico, mental e moral.\" — Santificação, p. 16.\n\n\"Quando alguém se esvazia completamente de si mesmo, quando todo falso deus é expulso da alma, o vazio é preenchido pela entrada do Espírito de Cristo. Tal pessoa possui a fé que opera pelo amor e purifica a alma de toda impureza moral e espiritual.\" — Ellen G. White, Obreiros Evangélicos, p. 255.\n\n\"Deus busca nos exaltar ao Seu alto, puro e celestial padrão. Para esse propósito, Seu Espírito luta constantemente conosco. [...] Nossas tendências naturais, a menos que corrigidas pelo Espírito Santo de Deus, contêm as sementes da morte moral.\" — Ellen G. White, Manuscrito 12, 1888.\n\nQuestões para discussão:\n\n1. Em 1 Coríntios 5 e 1 Coríntios 6, há uma série de sete perguntas introduzidas pela fórmula \"Vocês não sabem?\" (1 Coríntios 5:6; 1 Coríntios 6:2, 3, 9, 15, 16, 19). Todas exigem uma resposta afirmativa e enfática – algo como: \"É claro que sim!\" Como essas perguntas demonstram as preocupações de Paulo com a igreja? Por que também devemos nos preocupar com esses temas hoje?\n\n2. O casamento vem de Deus (Gênesis 1:27, 28; Gênesis 2:18-24) e deve ser honrado (Hebreus 13:4). Em uma época em que muitos o consideram \"antiquado\", como mostrar que o casamento é um presente divino, vindo diretamente do Éden?",
      versiculoChave: { texto: "Será que vocês não sabem que o coração de você é santuário do Espírito Santo, que está em vocês e que vocês receberam de Deus, e que vocês não pertencem a vocês mesmos? Por que vocês foram comprados por preço. Agora, pois, glorifiquem a Deus no corpo de vocês", referencia: "1 Coríntios 6:19, 20" },
      perguntas: [
        { id: "d7q1", pergunta: "Quais pecados aparecem listados junto com a imoralidade sexual nos catálogos de vícios de 1 Coríntios 5 e 6, segundo o texto?", opcoes: ["Apenas o roubo", "Idolatria e embriaguez", "Apenas a preguiça", "Nenhum outro pecado é mencionado"], correta: 1, explicacao: "A resposta correta é: Idolatria e embriaguez." },
        { id: "d7q2", pergunta: "Segundo Ellen White, o que acontece quando alguém se esvazia completamente de si mesmo e todo falso deus é expulso da alma?", opcoes: ["Nada muda", "O vazio é preenchido pelo Espírito de Cristo", "A pessoa se torna mais legalista", "A pessoa perde a fé"], correta: 1, explicacao: "A resposta correta é: O vazio é preenchido pelo Espírito de Cristo." },
        { id: "d7q3", pergunta: "Segundo o texto, quantas perguntas com a fórmula \"Vocês não sabem?\" aparecem em 1 Coríntios 5 e 6?", opcoes: ["Três", "Sete", "Doze", "Uma"], correta: 1, explicacao: "A resposta correta é: Sete." },
        { id: "d7q4", pergunta: "Segundo o texto, de onde vem o casamento?", opcoes: ["De uma invenção humana tardia", "De Deus, desde o Éden", "De uma tradição romana", "Não é mencionado na Bíblia"], correta: 1, explicacao: "A resposta correta é: De Deus, desde o Éden." }
      ]
    }
  ]
};

export const LICAO_ADULT_5 = {
  titulo: "Lição 5 - Tudo para a glória de Deus (25 a 31 de julho)",
  semana: "2026-W30",
  trimestre: "1 e 2 Coríntios",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-07-25",
      titulo: "Tudo para a glória de Deus",
      conteudo: "Primeira Coríntios 8–10 conclui a discussão sobre sexualidade (nos capítulos 5–6) e, ao mesmo tempo, apresenta as respostas de Paulo a perguntas específicas feitas por meio de uma carta (1 Coríntios 7:1) dos coríntios. Essas respostas dominarão o restante de 1 Coríntios.\n\nA natureza transitória de 1 Coríntios 7 indica que a imoralidade sexual (capítulos 5–7) e a idolatria (capítulos 8–10) são temas relacionados. De fato, eles são frequentemente mencionados juntos no Novo Testamento (ver Atos 15:20, 29; Atos 21:25; 1 Coríntios 6:9; Efésios 5:5; Colossenses 3:5; Apocalipse 21:8; Apocalipse 22:15).\n\nEm geral, enquanto em 1 Coríntios 5–7 Paulo trata do problema da imoralidade sexual, em 1 Coríntios 8–10 sua principal preocupação é a questão da idolatria. Ele afirma que os cristãos devem fugir de ambas (1 Coríntios 6:18, 1 Coríntios 10:14).\n\nNa semana passada, vimos que, sendo um templo do Espírito Santo (1 Coríntios 6:19, 20), é possível fugir da imoralidade sexual. Esta semana, veremos que é possível fugir da idolatria fazendo \"tudo para a glória de Deus\" (1 Coríntios 10:31).\n\nEstude a lição desta semana para se preparar para o Sábado, 01 de Agosto.",
      versiculoChave: { texto: "Portanto, se vocês comem, ou bebem ou fazem qualquer outra coisa, façam tudo para a glória de Deus", referencia: "1 Coríntios 10:31" },
      perguntas: [
        { id: "d1q1", pergunta: "Segundo o texto, o que 1 Coríntios 8-10 conclui e apresenta ao mesmo tempo?", opcoes: ["A discussão sobre dons espirituais", "A discussão sobre sexualidade e respostas a perguntas específicas dos coríntios", "A defesa do apostolado de Paulo", "A questão da ressurreição"], correta: 1, explicacao: "A resposta correta é: A discussão sobre sexualidade e respostas a perguntas específicas dos coríntios." },
        { id: "d1q2", pergunta: "Enquanto 1 Coríntios 5-7 trata da imoralidade sexual, qual é o tema principal de 1 Coríntios 8-10?", opcoes: ["Idolatria", "Casamento", "Batismo", "Profecia"], correta: 0, explicacao: "A resposta correta é: Idolatria." },
        { id: "d1q3", pergunta: "Segundo o texto, de que os cristãos devem fugir, segundo 1 Coríntios 6:18 e 10:14?", opcoes: ["Apenas da pobreza", "Da imoralidade sexual e da idolatria", "Do trabalho manual", "Da sinagoga"], correta: 1, explicacao: "A resposta correta é: Da imoralidade sexual e da idolatria." },
        { id: "d1q4", pergunta: "Qual é o princípio-chave da lição, baseado em 1 Coríntios 10:31?", opcoes: ["\"Tudo é permitido\"", "\"Façam tudo para a glória de Deus\"", "\"Evitem toda decisão difícil\"", "\"Guardem silêncio sobre a fé\""], correta: 1, explicacao: "A resposta correta é: \"Façam tudo para a glória de Deus\"." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-07-26",
      titulo: "Conhecimento versus amor",
      conteudo: "1. Leia 1 Coríntios 8:1-13. Por que Paulo contrasta conhecimento com amor, e em que contexto? Qual verdade ele desejava enfatizar?\n\nPaulo usa o tema dos alimentos oferecidos a ídolos para abordar uma questão mais profunda: a falta de amor ao próximo (1 Coríntios 8). A questão dos alimentos oferecidos a ídolos dividiu a igreja de Corinto em dois grupos. Alguns acreditavam que seu conhecimento sobre a inexistência de outros deuses lhes dava o direito de comer qualquer coisa (1 Coríntios 8:4). Estes são chamados de \"fortes\" (1 Coríntios 4:10). Os que se opunham a esse comportamento são chamados de \"fracos\" (1 Coríntios 8:9-12). Paulo usa essa denominação porque eles não haviam superado algumas crenças supersticiosas que marcaram sua experiência pagã anterior. Ao verem os \"fortes\" comendo alimentos oferecidos a ídolos, poderiam concluir que o cristianismo e a idolatria eram compatíveis. Portanto, Paulo não queria que os \"fortes\" se tornassem um obstáculo para os fracos.\n\nA Bíblia vê o ato de comer alimentos oferecidos a ídolos de forma muito negativa (Atos 15:20, 29; Atos 21:25; compare com Apocalipse 2:14, 20). No entanto, Paulo não faz declarações tão radicais quanto as que se veem nessas passagens. Isso porque sua principal preocupação diz respeito à falta de unidade que o mau uso do conhecimento pode causar. Paulo não está criticando o conhecimento como algo mau em si mesmo; em vez disso, ele se opõe ao tipo de conhecimento que leva à arrogância e à divisão na igreja. Conhecimento sem amor não é verdadeiro conhecimento (1 Coríntios 8:2). O verdadeiro conhecimento surge somente quando alguém ama a Deus e é conhecido por Ele (1 Coríntios 8:3).\n\nCitando Deuteronômio 6:4, Paulo mostra que os crentes devem saber que existe apenas um Deus (1 Coríntios 8:4-6). Curiosamente, ele segue a mesma ideia encontrada em Deuteronômio 6:4, 5, onde a afirmação de que nosso Deus é um só é seguida pelo mandamento: \"Amarás o Senhor teu Deus\". Tanto para Paulo quanto para Moisés, o conhecimento sem amor é inútil.\n\nConfiantes em seu conhecimento, os \"fortes\" acreditavam que comer alimentos sacrificados a ídolos era inofensivo. Como veremos na quarta e quinta-feira, Paulo lhes concedeu esse direito sob certas condições. Contudo, se isso se tornasse um obstáculo para os \"fracos\" (1 Coríntios 8:9), deveria ser evitado. Os cristãos devem praticar a abnegação por amor a Cristo e ao próximo.\n\nPaulo argumenta que, sem amor, o conhecimento pode se tornar um mal (1 Coríntios 8:1-13). Em que situações conhecimento sem amor, de fato, faz mal?",
      versiculoChave: { texto: "Portanto, se vocês comem, ou bebem ou fazem qualquer outra coisa, façam tudo para a glória de Deus", referencia: "1 Coríntios 10:31" },
      perguntas: [
        { id: "d2q1", pergunta: "Qual questão dividiu a igreja de Corinto em \"fortes\" e \"fracos\"?", opcoes: ["O uso de línguas estranhas", "Comer alimentos oferecidos a ídolos", "A forma de batismo", "O uso de instrumentos musicais"], correta: 1, explicacao: "A resposta correta é: Comer alimentos oferecidos a ídolos." },
        { id: "d2q2", pergunta: "Por que os \"fracos\" se opunham a comer esses alimentos, segundo o texto?", opcoes: ["Por razões econômicas", "Por não terem superado crenças supersticiosas de sua experiência pagã anterior", "Por ordem direta de Roma", "Por não gostarem do sabor"], correta: 1, explicacao: "A resposta correta é: Por não terem superado crenças supersticiosas de sua experiência pagã anterior." },
        { id: "d2q3", pergunta: "Segundo Paulo, o que caracteriza o \"verdadeiro conhecimento\"?", opcoes: ["Conhecimento acadêmico avançado", "Conhecimento que surge de amar a Deus e ser conhecido por Ele", "Conhecimento sem nenhuma limitação", "Conhecimento restrito aos apóstolos"], correta: 1, explicacao: "A resposta correta é: Conhecimento que surge de amar a Deus e ser conhecido por Ele." },
        { id: "d2q4", pergunta: "Que texto do Antigo Testamento Paulo cita para mostrar que existe um só Deus?", opcoes: ["Gênesis 1:1", "Deuteronômio 6:4", "Êxodo 20:1", "Salmos 23:1"], correta: 1, explicacao: "A resposta correta é: Deuteronômio 6:4." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-07-27",
      titulo: "Amor abnegado",
      conteudo: "2. Leia 1 Coríntios 9:1-6. Como esse trecho oferece um exemplo prático do que significa negar a si mesmo por amor?\n\nÀ primeira vista, parece que a defesa do apostolado de Paulo, em 1 Coríntios 9, não tem relação com a discussão anterior sobre conhecimento versus amor. Contudo, não se pode esquecer que a Bíblia não foi originalmente escrita em capítulos. O que Paulo ensina em 1 Coríntios 9 não está desconectado do material precedente. De fato, 1 Coríntios 9 oferece um exemplo prático de amor altruísta por Cristo e pelos irmãos. Por amor, Paulo abre mão de alguns direitos.\n\n\"Comer e beber\" (1 Coríntios 9:4). Aqui, comida e bebida representam assistência financeira em geral. Como apóstolo, Paulo tinha o direito de receber apoio material daqueles a quem ministrava. Outros líderes religiosos de sua época costumavam fazer exatamente isso. Mas ele não; em vez disso, sustentava-se fazendo tendas (Atos 18:3).\n\n\"Levar consigo uma esposa crente\" (1 Coríntios 9:5). Um apóstolo casado tinha permissão para fazer uma viagem missionária com sua esposa, às custas da igreja. Exemplos de casais missionários incluem Priscila e Áquila (Romanos 16:3) e Andrônico e Júnia (Romanos 16:7). Mas Paulo era solteiro (1 Coríntios 7:8). Ele poderia se casar e então se beneficiar do direito de ser acompanhado por uma esposa, com apoio financeiro para ambos.\n\n\"Abster-se de trabalhar\" para ganhar a vida (1 Coríntios 9:6). Paulo e Barnabé tinham o direito de receber salário por seu trabalho missionário (1 Coríntios 9:4-6). Paulo fabricava tendas para se sustentar (Atos 18:3), mas não sabemos qual era a ocupação de Barnabé. Sabemos que ele era muito generoso (Atos 4:36, 37) e, portanto, estava disposto a se sustentar.\n\nEm 1 Coríntios 9:7-11, Paulo desenvolve a ideia de 1 Coríntios 9:6 para mostrar que é justo que ele e Barnabé ganhem a vida com o sustento da igreja (1 Coríntios 9:11, 12). O próprio Senhor ordenou: \"Quem prega o evangelho deve viver do evangelho\" (1 Coríntios 9:14; compare com 1 Timóteo 5:18). Contudo, Paulo afirma: \"Não temos nos aproveitado desse direito\" (1 Coríntios 9:12). Assim, Paulo se apresenta como um exemplo de abnegação (1 Coríntios 9:1-18) e argumenta que isso beneficia a pregação do evangelho em Corinto (1 Coríntios 9:19-23).\n\nHá coisas às quais você tem direito, mas das quais talvez seja melhor abrir mão para ser uma testemunha mais eficaz do Senhor?",
      versiculoChave: { texto: "Portanto, se vocês comem, ou bebem ou fazem qualquer outra coisa, façam tudo para a glória de Deus", referencia: "1 Coríntios 10:31" },
      perguntas: [
        { id: "d3q1", pergunta: "Segundo o texto, \"comer e beber\" em 1 Coríntios 9:4 representa o quê?", opcoes: ["Um ritual religioso", "Assistência financeira em geral", "A Ceia do Senhor", "Um jejum obrigatório"], correta: 1, explicacao: "A resposta correta é: Assistência financeira em geral." },
        { id: "d3q2", pergunta: "Por que Paulo abriu mão do direito de receber sustento financeiro da igreja?", opcoes: ["Porque a igreja era pobre", "Por amor, como exemplo de abnegação", "Porque era proibido por lei romana", "Porque não gostava de pregar"], correta: 1, explicacao: "A resposta correta é: Por amor, como exemplo de abnegação." },
        { id: "d3q3", pergunta: "Como Paulo se sustentava enquanto pregava, segundo o texto?", opcoes: ["Recebendo doações apenas", "Fabricando tendas", "Cobrando pelos ensinamentos", "Vivendo de heranças"], correta: 1, explicacao: "A resposta correta é: Fabricando tendas." },
        { id: "d3q4", pergunta: "Quem são os exemplos de casais missionários citados no texto?", opcoes: ["Adão e Eva", "Priscila e Áquila, Andrônico e Júnia", "Abraão e Sara", "Isaque e Rebeca"], correta: 1, explicacao: "A resposta correta é: Priscila e Áquila, Andrônico e Júnia." }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-07-28",
      titulo: "Aprendendo com o passado",
      conteudo: "Após apresentar um exemplo de abnegação baseado em sua própria experiência, Paulo se volta mais especificamente para a questão da idolatria. De certa forma, 1 Coríntios 10 desenvolve a ideia de 1 Coríntios 9:27, onde Paulo comenta que exerce autodisciplina para não ser reprovado. Ele deseja que os coríntios sigam seu exemplo, mas Jesus é o modelo por excelência (1 Coríntios 11:1).\n\n3. Leia 1 Coríntios 10:7-11. Que pecados Israel cometeu no deserto? E por que os privilégios concedidos ao povo tornavam esses pecados ainda mais graves?\n\nEm 1 Coríntios 10:1-5, Paulo alude à história do povo de Deus no deserto. A referência à nuvem e ao mar traz à mente a direção, a presença e a proteção de Deus. Por sua vez, a comida e a bebida representam a provisão de Deus. Paulo se refere à experiência de Israel na nuvem e no mar como um batismo, análogo ao batismo cristão. Da mesma forma, ao se referir à comida e à bebida, Paulo alude à Ceia do Senhor.\n\nEm outras palavras, 1 Coríntios 10 ensina que, em certo sentido, os cristãos estão vivendo as mesmas experiências que Israel viveu. No entanto, Paulo relembra a história de Israel porque não quer que essa história se repita. Apesar de todos os privilégios que Israel tinha, muitos do povo desejavam coisas más (1 Coríntios 10:6), como idolatria (1 Coríntios 10:7) e imoralidade sexual (1 Coríntios 10:8). Não é de admirar, portanto, que \"Deus não se agradou da maioria deles\" (1 Coríntios 10:5).\n\nÉ fácil apontar o dedo para o antigo Israel e dizer que eles cometeram pecados graves. No entanto, Paulo argumenta que os cristãos são suscetíveis a praticar pecados semelhantes, apesar do imenso privilégio de conhecerem a história de Cristo. Isso fica claro na advertência: \"Aquele que pensa estar em pé, veja que não caia\" (1 Coríntios 10:12). A expressão \"aquele que pensa\" sugere que alguns na igreja não percebiam que corriam o risco de cair nesses pecados. Corremos o mesmo risco hoje?\n\n\"Quem pensa que está de pé, cuide para que não caia.\" Quem de nós não experimentou a realidade dessa advertência? A Bíblia diz que Deus não permitirá que sejamos tentados além do que podemos suportar, mas \"juntamente com a tentação proverá livramento\" (1 Coríntios 10:13). Por que, então, ainda nos vemos cair com tanta facilidade?",
      versiculoChave: { texto: "Portanto, se vocês comem, ou bebem ou fazem qualquer outra coisa, façam tudo para a glória de Deus", referencia: "1 Coríntios 10:31" },
      perguntas: [
        { id: "d4q1", pergunta: "A que experiência do povo de Israel Paulo compara a passagem pela nuvem e pelo mar?", opcoes: ["Um sacrifício", "Um batismo", "Uma peregrinação sem sentido", "Um exílio"], correta: 1, explicacao: "A resposta correta é: Um batismo." },
        { id: "d4q2", pergunta: "Que pecados Israel cometeu no deserto, segundo 1 Coríntios 10:7,8?", opcoes: ["Apenas preguiça", "Idolatria e imoralidade sexual", "Apenas desobediência a Moisés", "Nenhum pecado grave"], correta: 1, explicacao: "A resposta correta é: Idolatria e imoralidade sexual." },
        { id: "d4q3", pergunta: "O que a expressão \"aquele que pensa estar em pé, veja que não caia\" sugere?", opcoes: ["Que ninguém corre risco de cair em pecado", "Que alguns não percebiam que corriam risco de cair em pecados semelhantes", "Que apenas os fracos podem cair", "Que a queda é impossível para cristãos maduros"], correta: 1, explicacao: "A resposta correta é: Que alguns não percebiam que corriam risco de cair em pecados semelhantes." },
        { id: "d4q4", pergunta: "Segundo 1 Coríntios 10:13, o que Deus promete junto com a tentação?", opcoes: ["Punição imediata", "Um caminho de escape/livramento", "Isolamento total", "Nada, a tentação é inevitável"], correta: 1, explicacao: "A resposta correta é: Um caminho de escape/livramento." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-07-29",
      titulo: "Advertência contra a idolatria",
      conteudo: "4. Leia 1 Coríntios 10:5-22. Por que devemos fugir da idolatria?\n\nEm 1 Coríntios 10:14-22, Paulo retoma a questão dos alimentos oferecidos a ídolos. Oferecer comida a ídolos pode parecer estranho em muitas culturas hoje em dia, mas era comum nos tempos bíblicos. Quando animais eram sacrificados aos deuses nos templos pagãos, parte do animal era entregue aos sacerdotes oficiantes, que vendiam a carne. Parte dessa carne chegava aos mercados públicos. Como essa carne não era mantida separada de outras carnes oferecidas à venda no mercado, um cristão poderia, sem saber, comprar carne que havia sido oferecida a ídolos. O conselho do apóstolo é que essa carne pode ser comprada livremente pelos cristãos.\n\nContudo, embora a carne previamente sacrificada em um templo pudesse ser consumida pelos cristãos em casa (1 Coríntios 8:1-13), a prática de entrar em templos pagãos e participar de suas festas era claramente proibida aos cristãos. O critério é claro: os cristãos podem comer essa carne em casa porque os ídolos não são nada (1 Coríntios 8:4); porém, os cristãos não devem participar de cerimônias pagãs porque isso corresponde à adoração de demônios (1 Coríntios 10:20, 21). Participar de rituais pagãos equivale a ter comunhão com demônios (1 Coríntios 10:20), assim como participar da Ceia do Senhor equivale a ter comunhão com Cristo (1 Coríntios 10:16).\n\nAssim, Paulo diz: \"Não podeis beber do cálice do Senhor e do cálice dos demônios; não podeis participar da mesa do Senhor e da mesa dos demônios\" (1 Coríntios 10:21). Como Jesus disse: \"Ninguém pode servir a dois senhores\" (Mateus 6:24).\n\nPaulo ensina que Deus exige lealdade incondicional. Ele sugere que a idolatria provoca \"o Senhor a ciúmes\" (1 Coríntios 10:22). Para que isso não aconteça, Paulo, em 1 Coríntios 8:4-6, apresenta uma regra infalível contra a idolatria, aludindo a Deuteronômio 6:4-5: \"Ouve, ó Israel: O Senhor nosso Deus é o único Senhor. Amarás, pois, o Senhor teu Deus de todo o teu coração, de toda a tua alma e de todas as tuas forças\". A essa ideia de amar a Deus acima de todas as coisas, em Deuteronômio 6:5, Jesus acrescentou: \"'Amarás o teu próximo como a ti mesmo'\" (Marcos 12:31; veja também Levítico 19:18).\n\nUm ídolo não precisa ser uma estátua de pedra; podemos fabricá-lo a partir de praticamente qualquer coisa. De que \"ídolos\", se houver, você precisa fugir em sua vida?",
      versiculoChave: { texto: "Portanto, se vocês comem, ou bebem ou fazem qualquer outra coisa, façam tudo para a glória de Deus", referencia: "1 Coríntios 10:31" },
      perguntas: [
        { id: "d5q1", pergunta: "Por que carne vendida no mercado poderia, sem que o comprador soubesse, ter sido oferecida a ídolos?", opcoes: ["Porque todo mercado era um templo", "Porque não era mantida separada de outras carnes à venda", "Porque só carne sacrificada era vendida", "Isso nunca acontecia"], correta: 1, explicacao: "A resposta correta é: Porque não era mantida separada de outras carnes à venda." },
        { id: "d5q2", pergunta: "O que Paulo permite quanto a comer carne previamente sacrificada, em casa?", opcoes: ["É proibido em qualquer circunstância", "Pode ser consumida, pois os ídolos não são nada", "Apenas sacerdotes podem comer", "Somente aos sábados"], correta: 1, explicacao: "A resposta correta é: Pode ser consumida, pois os ídolos não são nada." },
        { id: "d5q3", pergunta: "O que era claramente proibido aos cristãos, segundo o texto?", opcoes: ["Comprar qualquer carne no mercado", "Participar de festas e rituais em templos pagãos", "Comer carne de porco", "Trabalhar aos domingos"], correta: 1, explicacao: "A resposta correta é: Participar de festas e rituais em templos pagãos." },
        { id: "d5q4", pergunta: "Segundo o texto, participar de rituais pagãos equivale a quê?", opcoes: ["Um simples costume social", "Ter comunhão com demônios", "Nada de espiritualmente relevante", "Uma forma alternativa de adoração aceitável"], correta: 1, explicacao: "A resposta correta é: Ter comunhão com demônios." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-07-30",
      titulo: "Vencendo a idolatria",
      conteudo: "Em 1 Coríntios 8:1-3, Paulo argumenta que o amor a Deus nos protege da idolatria. Esse argumento é retomado e desenvolvido em 1 Coríntios 10:23-33; 11:1. Em 1 Coríntios 8:3, ele fala sobre o nosso amor a Deus. Ele diz: \"Ninguém busque os seus próprios interesses, mas o bem-estar dos outros\" (1 Coríntios 10:24). Isso é amor ao próximo.\n\n5. Leia Marcos 10:17-22; Marcos 12:28-31. O que esses dois textos têm em comum e como se aplicam à situação de 1 Coríntios 10?\n\nEm 1 Coríntios 10, Paulo faz exatamente o que Jesus fez em Marcos 12:28-31; ou seja, ele une os dois grandes mandamentos da lei: o amor a Deus acima de tudo e o amor ao próximo. Na parábola do jovem rico (Marcos 10:17-22), Jesus une esses dois tipos de amor, aludindo respectivamente a Deuteronômio 6:4 (ver Marcos 10:18) e à segunda tábua do Decálogo (ver Marcos 10:19).\n\nO problema daquele jovem rico era que ele amava mais seus bens do que a Deus e ao seu próximo (Marcos 10:22). Ele valorizava seus tesouros na terra acima dos tesouros no céu. Ele valorizava seu dinheiro acima dos pobres (Marcos 10:21). Ele era um idólatra.\n\nSeguindo os ensinamentos de Jesus, Paulo sugere que o princípio de amar a Deus acima de tudo e ao próximo como a si mesmo deve ser aplicado às situações hipotéticas que ele menciona em 1 Coríntios 10:27, 28. Isso significa que mesmo coisas lícitas podem não ser úteis ou edificantes, visto que podem ofender a consciência de alguém (1 Coríntios 10:23). Esse princípio é magistralmente sintetizado nas palavras \"Façam tudo para a glória de Deus\" (1 Coríntios 10:31).\n\nAo dizer que tudo deve ser feito para a glória de Deus, Paulo indica que a idolatria pode se manifestar nas mais variadas formas, pois tudo o que usurpa a glória que pertence somente a Deus é uma forma de idolatria (Isaías 42:8).\n\nAs palavras de Paulo em 1 Coríntios 10:31–33; 11:1 servem como conclusão dos capítulos 8–10. Ele deixa claro que não buscou o seu próprio benefício, \"mas o de muitos, para que sejam salvos\" (1 Coríntios 10:33). Foi assim que ele imitou a Cristo (1 Coríntios 11:1).\n\nComo você pode aprender a amar melhor o seu próximo como a si mesmo?",
      versiculoChave: { texto: "Portanto, se vocês comem, ou bebem ou fazem qualquer outra coisa, façam tudo para a glória de Deus", referencia: "1 Coríntios 10:31" },
      perguntas: [
        { id: "d6q1", pergunta: "Segundo o texto, o que protege o cristão da idolatria?", opcoes: ["Riqueza material", "O amor a Deus", "Isolamento social", "Conhecimento acadêmico"], correta: 1, explicacao: "A resposta correta é: O amor a Deus." },
        { id: "d6q2", pergunta: "Quais dois mandamentos Jesus uniu, segundo o texto, e que Paulo também aplica em 1 Coríntios 10?", opcoes: ["Guardar o sábado e jejuar", "Amar a Deus acima de tudo e amar ao próximo como a si mesmo", "Não matar e não roubar", "Orar e jejuar"], correta: 1, explicacao: "A resposta correta é: Amar a Deus acima de tudo e amar ao próximo como a si mesmo." },
        { id: "d6q3", pergunta: "Qual era o problema do jovem rico, segundo Marcos 10:17-22, citado no texto?", opcoes: ["Ele não conhecia a lei", "Ele amava seus bens mais do que a Deus e ao próximo", "Ele era muito religioso", "Ele não tinha família"], correta: 1, explicacao: "A resposta correta é: Ele amava seus bens mais do que a Deus e ao próximo." },
        { id: "d6q4", pergunta: "Segundo o texto, o que pode se tornar uma forma de idolatria?", opcoes: ["Apenas estátuas religiosas", "Qualquer coisa que usurpe a glória que pertence somente a Deus", "Apenas o dinheiro", "Nada além de imagens esculpidas"], correta: 1, explicacao: "A resposta correta é: Qualquer coisa que usurpe a glória que pertence somente a Deus." }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-07-31",
      titulo: "Estudo Adicional - Tudo para a glória de Deus",
      conteudo: "Leia Ellen G. White, Patriarcas e Profetas, \"O bezerro de ouro\", p. 266-279.\n\n\"Quanto bem poderíamos fazer se fizéssemos bom uso de nossas relações uns com os outros! Todo aquele que recebeu benefícios celestiais tem a obrigação de iluminar o caminho dos outros. [...] Então, todos aqueles que verdadeiramente amam a Deus cessarão sua idolatria.\" — Ellen G. White, em The Advent Review and Sabbath Herald, 18 de novembro de 1884.\n\nPaulo exortou seus irmãos a refletirem sobre a influência que suas palavras e ações teriam sobre os outros e a não fazerem nada, por mais inocente que fosse em si mesmo, que pudesse parecer sancionar a idolatria ou ofender os escrúpulos daqueles que fossem fracos na fé. \"Portanto, quer comais, quer bebais, ou façais qualquer outra coisa, fazei tudo para a glória de Deus.\"\n\n\"As palavras de advertência do apóstolo à igreja de Corinto são aplicáveis a todos os tempos e especialmente adequadas aos nossos dias. Por idolatria, ele não se referia apenas à adoração de ídolos, mas também ao egoísmo, ao amor ao conforto, à satisfação dos apetites e das paixões.\" — Ellen G. White, Atos dos Apóstolos, p. 201, 202.\n\n\"Se você perceber que, ao fazer certas coisas que você tem todo o direito de fazer, você impede o avanço da obra de Deus, abstenha-se de fazê-las. Não faça nada que possa fechar a mente de outras pessoas à verdade. [...] Todas as coisas podem ser lícitas, mas nem todas as coisas são convenientes.\" — Ellen G. White, Testemunhos para a Igreja, vol. 9, p. 167.\n\nQuestões para discussão:\n\n1. Segundo Paulo, o comportamento de um cristão maduro pode, às vezes, inibir o crescimento de um cristão imaturo. Por que o princípio de amar a Deus acima de todas as coisas e ao próximo como a si mesmo é o único caminho para lidar com esse desafio?\n\n2. Os cristãos podem acabar adorando ídolos, se não forem vigilantes? Que tipo de ídolos? Quais coisas boas podem se transformar em ídolos? Além disso, como perceber se algo de que gostamos muito acabou se tornando um ídolo?",
      versiculoChave: { texto: "Portanto, se vocês comem, ou bebem ou fazem qualquer outra coisa, façam tudo para a glória de Deus", referencia: "1 Coríntios 10:31" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo Ellen White, por idolatria Paulo não se referia apenas a quê?", opcoes: ["Adoração de ídolos apenas", "Também ao egoísmo, amor ao conforto e satisfação de apetites e paixões", "Apenas a rituais pagãos", "Nada além da adoração de estátuas"], correta: 1, explicacao: "A resposta correta é: Também ao egoísmo, amor ao conforto e satisfação de apetites e paixões." },
        { id: "d7q2", pergunta: "Segundo o texto de Ellen White, o que devemos fazer se perceber que algo lícito impede o avanço da obra de Deus?", opcoes: ["Continuar fazendo de qualquer forma", "Abster-se de fazê-lo", "Ignorar o impacto sobre os outros", "Pedir uma votação da igreja"], correta: 1, explicacao: "A resposta correta é: Abster-se de fazê-lo." },
        { id: "d7q3", pergunta: "Segundo o texto, \"todas as coisas podem ser lícitas\", mas o que mais é preciso considerar?", opcoes: ["Nem todas as coisas são convenientes/edificantes", "Todas devem ser praticadas igualmente", "Apenas o preço importa", "Só a opinião pessoal importa"], correta: 0, explicacao: "A resposta correta é: Nem todas as coisas são convenientes/edificantes." },
        { id: "d7q4", pergunta: "Segundo a pergunta de discussão, coisas boas podem se transformar em quê, se não formos vigilantes?", opcoes: ["Em pecados imperdoáveis", "Em ídolos", "Em rituais obrigatórios", "Em leis eclesiásticas"], correta: 1, explicacao: "A resposta correta é: Em ídolos." }
      ]
    }
  ]
};

export const LICAO_ADULT_6 = {
  titulo: "Lição 6 - Dons espirituais (1 a 7 de agosto)",
  semana: "2026-W31",
  trimestre: "1 e 2 Coríntios",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-08-01",
      titulo: "Dons espirituais",
      conteudo: "Assim como um corpo humano, a igreja é una, mas possui muitos membros, cada um com diferentes papéis, funções e dons. Praticados com amor, esses dons espirituais promovem um senso de unidade que reflete o caráter do Deus trino.\n\nEsta semana, examinaremos 1 Coríntios 12–14 e seu ensinamento sobre os dons espirituais. Esta seção faz parte de uma unidade um pouco maior, onde Paulo trata do comportamento cristão esperado em contextos religiosos (1 Coríntios 11–14). A principal preocupação de Paulo diz respeito ao problema das reuniões desordenadas. Sua resposta a esse problema é que a igreja é um corpo cujas partes têm funções diferentes que contribuem para \"a edificação do corpo de Cristo\" (Efésios 4:12). Em resumo, Deus deu dons espirituais à igreja para promover a unidade na diversidade.\n\nCertamente, Paulo ainda tinha em mente o problema das divisões abordado nos quatro primeiros capítulos de 1 Coríntios, onde a resposta para a falta de acordo entre os membros da igreja é a unidade em Cristo. Agora, ele desenvolve essa ideia apresentando sua compreensão do papel dos dons espirituais. Segundo Paulo, a unidade em Cristo e no Espírito é o único meio de evitar cismas.\n\nEstude a lição desta semana para se preparar para o Sábado, 08 de Agosto.",
      versiculoChave: { texto: "Sigam o amor e procurem com zelo os dons espirituais, principalmente o de profetizar", referencia: "1 Coríntios 14:1" },
      perguntas: [
        { id: "d1q1", pergunta: "A que a igreja é comparada no texto introdutório, quanto a ter muitos membros com diferentes dons?", opcoes: ["Um exército", "Um corpo humano", "Uma escola", "Um tribunal"], correta: 1, explicacao: "A resposta correta é: Um corpo humano." },
        { id: "d1q2", pergunta: "Segundo o texto, qual é a principal preocupação de Paulo em 1 Coríntios 11-14?", opcoes: ["A ressurreição", "As reuniões desordenadas no culto", "O casamento", "A idolatria"], correta: 1, explicacao: "A resposta correta é: As reuniões desordenadas no culto." },
        { id: "d1q3", pergunta: "Segundo o texto, para que Deus deu dons espirituais à igreja?", opcoes: ["Para criar hierarquias", "Para promover a unidade na diversidade", "Para dividir os membros por talento", "Para substituir a pregação"], correta: 1, explicacao: "A resposta correta é: Para promover a unidade na diversidade." },
        { id: "d1q4", pergunta: "Segundo Paulo, qual é o único meio de evitar cismas na igreja?", opcoes: ["Regras rígidas", "A unidade em Cristo e no Espírito", "Punições severas", "Isolamento dos membros problemáticos"], correta: 1, explicacao: "A resposta correta é: A unidade em Cristo e no Espírito." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-08-02",
      titulo: "Diversidade de dons",
      conteudo: "Em 1 Coríntios 12:1, Paulo introduz um novo tópico com a fórmula \"agora, quanto à\". Os estudiosos discutem se ele está falando sobre \"dons espirituais\" ou \"pessoas espirituais\", pois a expressão grega tōn pneumatikōn permite ambas as interpretações. \"Dons espirituais\" é preferível à luz de 1 Coríntios 12:4, onde Paulo se refere claramente a dons espirituais. Em 1 Coríntios 12:2, 3, Paulo destaca que o primeiro dom do Espírito é a ousada confissão de que Jesus é o Senhor. Nos tempos do Novo Testamento, dizer que Jesus é o Senhor era dizer que César não o era (Atos 17:7; também João 19:12, 15). Isso era visto como sedição contra o poder imperial e, portanto, era punível com a morte.\n\nJesus e Paulo enfatizaram que a fé em Deus — mesmo diante da perseguição e da ameaça de morte — é um dom do Espírito. Na verdade, a fé é o dom mais básico. Não surpreendentemente, a fé é o primeiro item da lista em 1 Coríntios 13:13. Que a fé é um dom espiritual fica claro pela declaração de Paulo em 1 Coríntios 12:9. No entanto, existem muitos outros dons. O fato de o Espírito Santo distribuir os diferentes tipos de dons \"a cada um individualmente, como Ele quer\" (1 Coríntios 12:11) prova que todos eles são necessários.\n\n1. Leia 1 Coríntios 12:1-6. Qual é a ênfase dessa passagem?\n\nA repetição de \"variedades\" enfatiza a multiplicidade de dons. O que Paulo chama de \"dons espirituais\" em 1 Coríntios 12:1 é desenvolvido nos versículos 4–6, sob três perspectivas diferentes: \"dons\" (carisma), \"serviços\" ou \"ministérios\" (diaconia) e \"atividades\" (energēma). Embora essas palavras tenham significados diferentes, é importante não fazer uma distinção rígida entre elas devido ao paralelismo da passagem. Deve-se notar também que os dons espirituais são designados para promover a unidade com base no caráter trino de Deus (veja também Efésios 4:8–11). Embora o Espírito Santo conceda dons aos crentes, é Deus quem os capacita a servir a Cristo na comunidade de crentes (1 Coríntios 12:5, 6). Cada crente recebe dons individualmente (1 Coríntios 12:11), mas todos eles devem beneficiar a comunidade de crentes como um todo.\n\nPerceba novamente a ênfase de Paulo na unidade. Por que ela é tão importante para a igreja?",
      versiculoChave: { texto: "Sigam o amor e procurem com zelo os dons espirituais, principalmente o de profetizar", referencia: "1 Coríntios 14:1" },
      perguntas: [
        { id: "d2q1", pergunta: "Qual é, segundo o texto, o primeiro e mais básico dom do Espírito mencionado?", opcoes: ["O dom de línguas", "A confissão de que Jesus é o Senhor / a fé", "O dom de cura", "O dom de profecia"], correta: 1, explicacao: "A resposta correta é: A confissão de que Jesus é o Senhor / a fé." },
        { id: "d2q2", pergunta: "Por que dizer \"Jesus é o Senhor\" era arriscado nos tempos do Novo Testamento?", opcoes: ["Não tinha nenhum risco", "Era visto como sedição contra o poder imperial, pois negava que César era senhor", "Era apenas uma expressão religiosa comum", "Só os romanos podiam dizer isso"], correta: 1, explicacao: "A resposta correta é: Era visto como sedição contra o poder imperial, pois negava que César era senhor." },
        { id: "d2q3", pergunta: "Segundo 1 Coríntios 12:11, como o Espírito distribui os dons?", opcoes: ["Igualmente a todos, sem distinção", "A cada um individualmente, como Ele quer", "Apenas aos apóstolos", "Por sorteio entre os membros"], correta: 1, explicacao: "A resposta correta é: A cada um individualmente, como Ele quer." },
        { id: "d2q4", pergunta: "Quais três palavras gregas Paulo usa para descrever os dons em 1 Coríntios 12:4-6?", opcoes: ["Charis, Eros, Philia", "Carisma (dons), diaconia (serviços) e energēma (atividades)", "Logos, Sophia, Gnosis", "Pistis, Elpis, Agape"], correta: 1, explicacao: "A resposta correta é: Carisma (dons), diaconia (serviços) e energēma (atividades)." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-08-03",
      titulo: "Unidade por meio da diversidade",
      conteudo: "A linguagem de unidade introduzida em 1 Coríntios 12:4-6 (\"o mesmo Espírito\", \"o mesmo Senhor\" e \"o mesmo Deus\") é desenvolvida no restante de 1 Coríntios 12. Isso é evidenciado pelo uso, por Paulo, de frases como \"um e o mesmo Espírito\" (1 Coríntios 12:11), \"o corpo é um\" (1 Coríntios 12:12), \"um só corpo\" (1 Coríntios 12:12, 13, 20), \"um só Espírito\" (1 Coríntios 12:13 [duas vezes]) e \"o mesmo cuidado uns pelos outros\" (1 Coríntios 12:25).\n\nJuntamente com o conceito de unidade, Paulo destaca a diversidade dos membros no corpo de Cristo por meio de expressões como \"muitos membros\" (1 Coríntios 12:12, 20), \"todos nós fomos batizados\" (1 Coríntios 12:13), \"não um só membro, mas muitos\" (1 Coríntios 12:14), \"todo o corpo\" (1 Coríntios 12:17), \"cada um deles\" (1 Coríntios 12:18), \"membros do corpo\" (1 Coríntios 12:22, 23) e \"todos os membros\" (1 Coríntios 12:26). Essa ênfase tanto na unidade quanto na diversidade indica que os dons espirituais visam promover a unidade por meio da diversidade.\n\nEssa unidade em meio à diversidade deve refletir o caráter de Deus. O Pai é uma pessoa, o Filho é outra pessoa e o Espírito Santo outra. Os três mantêm suas individualidades enquanto trabalham juntos para edificar a igreja e capacitá-la para a missão (1 Coríntios 12:4-6, Efésios 4:11-13).\n\n2. Leia 1 Coríntios 12:12-31. Por que a ilustração do corpo com suas muitas partes é adequada para representar a igreja e seus membros?\n\nUm pensamento central em 1 Coríntios 12 é que, embora os membros do corpo sejam individualmente tão diferentes uns dos outros (1 Coríntios 12:15-20), todos dependem uns dos outros (1 Coríntios 12:21-26). Os pés dependem dos olhos para ver por onde devem andar; por sua vez, os olhos não podem tocar em nada — somente as mãos podem. Além disso, a ideia de que alguns membros são mais fracos (1 Coríntios 12:22) ou menos honrosos (1 Coríntios 12:23) do que outros é apenas uma impressão, pois todos são necessários (1 Coríntios 12:22).\n\nInfelizmente, havia uma tendência entre os coríntios de valorizar alguns dons em detrimento de outros. Para corrigir esse erro, Paulo chamou a atenção dos coríntios para o amor, que é \"um caminho mais excelente\" (1 Coríntios 12:31). Em outras palavras, não importa qual seja o dom, se praticado com sabedoria e amor, é agradável a Deus.\n\nLeia as listas de dons em 1 Coríntios 12:8-10, 28; Romanos 12:6-8; e Efésios 4:11. Quais são os seus dons? Como você pode usá-los para edificar o corpo de Cristo?",
      versiculoChave: { texto: "Sigam o amor e procurem com zelo os dons espirituais, principalmente o de profetizar", referencia: "1 Coríntios 14:1" },
      perguntas: [
        { id: "d3q1", pergunta: "Qual metáfora Paulo usa para explicar a unidade na diversidade dos dons?", opcoes: ["Uma árvore", "O corpo humano com suas muitas partes", "Um exército organizado", "Uma orquestra"], correta: 1, explicacao: "A resposta correta é: O corpo humano com suas muitas partes." },
        { id: "d3q2", pergunta: "Segundo o texto, os membros do corpo, embora diferentes, o que fazem entre si?", opcoes: ["Competem por reconhecimento", "Dependem uns dos outros", "Funcionam de forma isolada", "Substituem-se mutuamente"], correta: 1, explicacao: "A resposta correta é: Dependem uns dos outros." },
        { id: "d3q3", pergunta: "Segundo o texto, alguns membros parecerem \"mais fracos\" ou \"menos honrosos\" é...", opcoes: ["Uma realidade absoluta", "Apenas uma impressão, pois todos são necessários", "Motivo para exclusão", "Sinal de pecado"], correta: 1, explicacao: "A resposta correta é: Apenas uma impressão, pois todos são necessários." },
        { id: "d3q4", pergunta: "Que atitude Paulo recomenda para corrigir a tendência de valorizar alguns dons mais que outros?", opcoes: ["Ignorar os dons menos populares", "Buscar o amor, \"um caminho mais excelente\"", "Criar um ranking de dons", "Abolir todos os dons"], correta: 1, explicacao: "A resposta correta é: Buscar o amor, \"um caminho mais excelente\"." }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-08-04",
      titulo: "Um caminho ainda mais excelente",
      conteudo: "\"O amor não é apenas mais um dom entre muitos. É o meio pelo qual todos os dons alcançam seu propósito final.\" — \"1 Coríntios\", Comentário Bíblico de Andrews: Romanos a Apocalipse, p. 195.\n\n3. Leia 1 Coríntios 13:1-7; 1 Pedro 4:8-11. Qual é o papel do amor em relação aos dons espirituais?\n\nPrimeira Coríntios 13 ensina que somente através do amor os dons espirituais podem ser usados apropriadamente. Paulo inicia 1 Coríntios 13 aludindo aos dons mencionados em 1 Coríntios 12, apenas para enfatizar a sua falta de valor se não forem motivados pelo amor. Assim, o conhecimento (1 Coríntios 12:8) e a fé (1 Coríntios 12:9), mesmo uma fé \"de maneira tal que possa remover montanhas\" (1 Coríntios 13:2), nada são sem amor (1 Coríntios 13:2). Sem amor, a capacidade de falar em línguas (1 Coríntios 12:10, 28, 30) se reduz meramente a \"um gongo ressonante ou um címbalo clangorante\" (1 Coríntios 13:1). Da mesma forma, mesmo o importante dom da profecia nada é sem amor (1 Coríntios 13:2).\n\nEm 1 Coríntios 13:4-7, Paulo se concentra no que é o amor e no que ele não é; mais especificamente, no que o amor faz e no que ele não faz. Os verbos que ele escolheu para caracterizar o amor indicam que o amor não é tanto algo que sentimos, mas sim algo que praticamos. Assim, Paulo menciona que o amor (1) demonstra paciência; (2) demonstra bondade; (3) se alegra com a verdade; (4) tudo sofre; (5) tudo crê; (6) tudo espera; e (7) tudo persevera. Por outro lado, o amor (1) não inveja; (2) não se vangloria; (3) não se ensoberbece; (4) não se comporta de maneira grosseira; (5) não busca os seus próprios interesses; (6) não se irrita facilmente; (7) não guarda rancor; e (8) não se alegra com a injustiça.\n\nEste total de 15 verbos fornece uma sólida orientação para o comportamento apropriado na prática dos dons. Notavelmente, esta discussão sobre a verdadeira natureza do amor encontra-se precisamente entre 1 Coríntios 12 e 14, onde Paulo aborda o conflito relativo aos dons espirituais. De fato, o amor é a chave para o uso sábio dos dons espirituais. O amor também é colocado lado a lado com a fé e a esperança, \"mas o maior deles é o amor\" (1 Coríntios 13:13).\n\nPor que o amor é essencial para a nossa fé? Que melhor forma há de experimentar a realidade do amor de Deus do que procurar, com oração, refletir esse amor aos outros?",
      versiculoChave: { texto: "Sigam o amor e procurem com zelo os dons espirituais, principalmente o de profetizar", referencia: "1 Coríntios 14:1" },
      perguntas: [
        { id: "d4q1", pergunta: "Segundo 1 Coríntios 13, o que acontece com os dons se não forem motivados pelo amor?", opcoes: ["Continuam igualmente eficazes", "Perdem seu valor, tornam-se \"nada\"", "Se tornam ainda mais poderosos", "Não há relação entre dons e amor"], correta: 1, explicacao: "A resposta correta é: Perdem seu valor, tornam-se \"nada\"." },
        { id: "d4q2", pergunta: "Quantos verbos Paulo usa em 1 Coríntios 13:4-7 para caracterizar o amor?", opcoes: ["Cinco", "Quinze", "Trinta", "Dois"], correta: 1, explicacao: "A resposta correta é: Quinze." },
        { id: "d4q3", pergunta: "Segundo o texto, o amor é mais bem descrito como...", opcoes: ["Um sentimento passageiro", "Algo que se pratica, não apenas se sente", "Um dom exclusivo de poucos", "Uma emoção incontrolável"], correta: 1, explicacao: "A resposta correta é: Algo que se pratica, não apenas se sente." },
        { id: "d4q4", pergunta: "Segundo 1 Coríntios 13:13, qual é o maior entre fé, esperança e amor?", opcoes: ["A fé", "O amor", "A esperança", "Todos são iguais"], correta: 1, explicacao: "A resposta correta é: O amor." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-08-05",
      titulo: "O dom de línguas",
      conteudo: "E quanto ao dom de línguas? Em consonância com a manifestação desse dom em outras partes da Bíblia (Marcos 16:17, Atos 2:1-13, Atos 10:44-48, Atos 19:6), o dom de línguas em 1 Coríntios é muito provavelmente a capacidade concedida pelo Espírito de falar em línguas estrangeiras.\n\nPaulo menciona o dom de línguas na lista de dons em 1 Coríntios 12:8-10 (veja também 1 Coríntios 12:28, 30; 1 Coríntios 13:1, 8). No entanto, ele se refere a ele repetidamente em 1 Coríntios 14. De fato, a palavra grega glōssa (\"língua\") aparece mais de vinte vezes em 1 Coríntios 12-14, com quinze ocorrências apenas em 1 Coríntios 14. Além dessas, a palavra grega heteroglōssos (\"outra língua\") também ocorre em 1 Coríntios 14:21. Esse grande número de referências ao dom de línguas sugere que esse assunto era de particular preocupação para Paulo. O mau uso e o abuso desse dom pela igreja em Corinto causavam desordem e confusão no culto público (1 Coríntios 14:23, 27, 33, 40).\n\n4. Leia 1 Coríntios 14:5, 13, 26, 27; 1 Coríntios 12:10, 30. Quais orientações específicas Paulo deu quanto ao dom de línguas?\n\nA razão pela qual o dom de falar em línguas deve andar de mãos dadas com o de interpretá-las é que as línguas precisam ser inteligíveis (1 Coríntios 14:9); caso contrário, não há benefício algum em usar o dom (1 Coríntios 14:6). Isso explica por que Paulo enfatizou tanto a interpretação e o entendimento. Obviamente, ele não está criticando o dom de línguas em si, mas, como veremos amanhã, a importância excessiva que os coríntios lhe atribuíam, o que levou à negligência do dom da profecia.\n\nNeste ponto, é importante observar que, embora Paulo desejasse que todos os coríntios pudessem falar línguas estrangeiras (1 Coríntios 14:5), ele não esperava que isso acontecesse (1 Coríntios 12:10). Portanto, a ideia de que \"todos devem falar em línguas antes de receber o batismo no Espírito Santo é uma perversão do ensinamento de Paulo em 1 Coríntios 12 e 14\". — (Tratado de Teologia Adventista do Sétimo Dia, [2011], p. 687).\n\nHá pessoas em sua igreja que falam outros idiomas? Como elas podem usar essa habilidade para alcançar mais pessoas para Cristo? De que modo esse fato nos ajuda a compreender a verdadeira natureza do dom de línguas tratado por Paulo?",
      versiculoChave: { texto: "Sigam o amor e procurem com zelo os dons espirituais, principalmente o de profetizar", referencia: "1 Coríntios 14:1" },
      perguntas: [
        { id: "d5q1", pergunta: "Segundo o texto, o dom de línguas em 1 Coríntios é muito provavelmente o quê?", opcoes: ["Uma linguagem angelical incompreensível", "A capacidade de falar em línguas estrangeiras reais", "Um transe emocional", "Um sinal de loucura"], correta: 1, explicacao: "A resposta correta é: A capacidade de falar em línguas estrangeiras reais." },
        { id: "d5q2", pergunta: "Por que o dom de línguas deve andar de mãos dadas com o de interpretação?", opcoes: ["Por exigência romana", "Porque as línguas precisam ser inteligíveis para haver benefício", "Porque interpretação é mais importante que qualquer outro dom", "Não há necessidade de interpretação"], correta: 1, explicacao: "A resposta correta é: Porque as línguas precisam ser inteligíveis para haver benefício." },
        { id: "d5q3", pergunta: "Segundo o texto, o que causava desordem no culto público em Corinto?", opcoes: ["A pregação da cruz", "O mau uso e abuso do dom de línguas", "A leitura das Escrituras", "A oração em grupo"], correta: 1, explicacao: "A resposta correta é: O mau uso e abuso do dom de línguas." },
        { id: "d5q4", pergunta: "Segundo o texto, é correto dizer que \"todos devem falar em línguas antes de receber o batismo no Espírito Santo\"?", opcoes: ["Sim, é o ensino de Paulo", "Não, isso é uma perversão do ensinamento de Paulo", "Sim, mas apenas para apóstolos", "O texto não aborda esse assunto"], correta: 1, explicacao: "A resposta correta é: Não, isso é uma perversão do ensinamento de Paulo." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-08-06",
      titulo: "O dom de profecia",
      conteudo: "O dom da profecia ocupa um lugar de destaque na discussão de Paulo sobre os dons espirituais. Curiosamente, o dom da profecia é geralmente mencionado antes do dom de línguas (1 Coríntios 12:10, 28; 1 Coríntios 13:8). Quando o dom de línguas é mencionado primeiro, isso serve apenas para enfatizar sua relativa insignificância em comparação com o dom da profecia (1 Coríntios 14:4, 5, 6, 22).\n\n5. Leia Efésios 4:11-13; 1 Coríntios 14:3, 4. O que esses textos dizem sobre o propósito dos dons espirituais em geral e do dom de profecia em particular?\n\nO dom da profecia visa edificação, exortação e consolo (1 Coríntios 14:3; compare com Atos 15:32). Isso sugere que a profecia não se trata tanto de predizer o futuro, mas sim de como viver no presente. O verbo grego prophēteuō pode significar tanto \"dizer algo antecipadamente\" quanto \"dizer algo em nome de outra pessoa\". Por exemplo, o primeiro sentido é visto em Atos 2:29-31 (compare com Amós 3:7), onde a ideia de que Davi era um profeta é explicada como \"prever\". O segundo sentido é visto em Atos 15:32, onde Judas e Silas são identificados como profetas. Sua \"profecia\", no entanto, consistia em encorajar e fortalecer \"os irmãos com muitas palavras\".\n\nEm Efésios 4:11-13, aprendemos que os dons espirituais não cessaram na era apostólica. Eles devem permanecer até o fim (Atos 2:39). Contudo, se alguém se declara profeta, deve ser avaliado com base nas Escrituras. De modo geral, quatro regras devem ser satisfeitas. Primeiro, as profecias incondicionais sempre se cumprem (Deuteronômio 18:22; Jeremias 28:8, 9). Segundo, a mensagem concorda com a dos profetas anteriores (Deuteronômio 13:1-3; Isaías 8:20). Terceiro, a vida diária demonstra um compromisso com Cristo (1 João 4:1-3). Quarto, Jesus disse que os falsos profetas seriam conhecidos pelos seus frutos (Mateus 7:15-20). Isso também se aplica aos verdadeiros profetas.\n\nO livro do Apocalipse indica que o dom da profecia é uma característica distintiva da igreja remanescente (Apocalipse 12:17, Ap 19:10). Como adventistas do sétimo dia, cremos que o dom da profecia foi concedido a Ellen G. White e se reflete em seus escritos.\n\nQuais são as razões pelas quais cremos no dom profético de Ellen White? Que perguntas você ainda tem quanto ao papel e autoridade dessa profecia?",
      versiculoChave: { texto: "Sigam o amor e procurem com zelo os dons espirituais, principalmente o de profetizar", referencia: "1 Coríntios 14:1" },
      perguntas: [
        { id: "d6q1", pergunta: "Segundo o texto, para que serve o dom da profecia, segundo 1 Coríntios 14:3?", opcoes: ["Apenas prever o futuro", "Edificação, exortação e consolo", "Impressionar os ouvintes", "Substituir a pregação do evangelho"], correta: 1, explicacao: "A resposta correta é: Edificação, exortação e consolo." },
        { id: "d6q2", pergunta: "Segundo o texto, os dons espirituais cessaram na era apostólica?", opcoes: ["Sim, terminaram com os apóstolos", "Não, devem permanecer até o fim", "Apenas o dom de línguas cessou", "O texto não trata disso"], correta: 1, explicacao: "A resposta correta é: Não, devem permanecer até o fim." },
        { id: "d6q3", pergunta: "Quantas regras o texto menciona para avaliar se alguém é um verdadeiro profeta?", opcoes: ["Duas", "Quatro", "Dez", "Nenhuma, é impossível avaliar"], correta: 1, explicacao: "A resposta correta é: Quatro." },
        { id: "d6q4", pergunta: "Segundo o texto, a quem os adventistas do sétimo dia creem que o dom da profecia foi concedido?", opcoes: ["Apenas aos apóstolos originais", "A Ellen G. White", "A todos os pastores atuais", "A nenhuma pessoa específica"], correta: 1, explicacao: "A resposta correta é: A Ellen G. White." }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-08-07",
      titulo: "Estudo Adicional - Dons espirituais",
      conteudo: "Leia Roswell F. Cottrell, capítulo 33, \"Introdução\", em Ellen G. White, Primeiros Escritos [2022], p. 134-142.\n\n\"Que os homens saiam para trabalhar, confiando no Senhor, e Ele irá com eles, convencendo e convertendo almas. Um trabalhador pode ser um orador eloquente, outro um escritor habilidoso, outro pode ter o dom da oração sincera, fervorosa e intensa, outro o dom do canto. Outro pode ter poder especial para explicar a palavra de Deus com clareza. E cada dom deve se tornar um poder para Deus, porque Ele coopera com o trabalhador. A um Deus dá a palavra da sabedoria, a outro o conhecimento, a outro a fé. Mas todos devem trabalhar sob a mesma liderança. A diversidade de dons leva a uma diversidade de operações, 'mas é o mesmo Deus que opera tudo em todos' (1 Coríntios 12:6).\"\n\n\"Que ninguém despreze os supostos dons menores. Que todos se dediquem ao trabalho. Que ninguém cruze os braços em incredulidade por achar que não pode realizar grandes obras. Deixem de olhar para si mesmos. Olhem para o seu Líder. Com mansidão, sinceridade e amor, façam o que puderem.\" — Ellen G. White, Este dia com Deus [1979], 18 de Janeiro.\n\n\"Cada um de nós precisa da ajuda que pode receber de outras mentes. Deus opera em mentes diferentes da nossa. Os diversos dons dados a diferentes pessoas devem se misturar para o 'aperfeiçoamento dos santos, para a obra do ministério, para a edificação do corpo de Cristo' (Efésios 4:12)... Sempre haverá obstáculos à nossa frente, mas devemos seguir nosso Líder e enfrentar nossas dificuldades unidos, de mãos dadas.\" — Ellen G. White, Olhando para o Alto [1982], 7 de maio.\n\nQuestões para discussão:\n\n1. Por que o dom de profecia é mais importante do que o dom de línguas quando não há interpretação? Se necessário, releia 1 Coríntios 14 para recapitular os argumentos de Paulo.\n\n2. Em classe, conversem sobre Ellen White e por que, como igreja, cremos que ela recebeu o dom de profecia. Que grandes bênçãos esse dom traz à igreja? Quais são os desafios para saber usá-lo da melhor maneira?\n\n3. Por mais importante que seja o amor, por que ele não pode ser o único critério para discernir se alguém está falando a verdade e merece ser ouvido?",
      versiculoChave: { texto: "Sigam o amor e procurem com zelo os dons espirituais, principalmente o de profetizar", referencia: "1 Coríntios 14:1" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo Ellen White, cada dom deve se tornar o quê, porque Deus coopera com o trabalhador?", opcoes: ["Um fardo", "Um poder para Deus", "Um motivo de orgulho pessoal", "Uma obrigação legal"], correta: 1, explicacao: "A resposta correta é: Um poder para Deus." },
        { id: "d7q2", pergunta: "Segundo o texto de Ellen White, o que ninguém deveria desprezar?", opcoes: ["Os dons considerados \"menores\"", "A pregação formal", "A liderança da igreja", "As Escrituras"], correta: 0, explicacao: "A resposta correta é: Os dons considerados \"menores\"." },
        { id: "d7q3", pergunta: "Segundo o texto, por que precisamos da ajuda de outras mentes?", opcoes: ["Porque não temos capacidade própria", "Porque Deus opera em mentes diferentes da nossa", "Porque é uma tradição da igreja", "Não precisamos, cada um deve agir sozinho"], correta: 1, explicacao: "A resposta correta é: Porque Deus opera em mentes diferentes da nossa." },
        { id: "d7q4", pergunta: "Segundo a pergunta de discussão, por que o amor sozinho não basta para discernir se alguém fala a verdade?", opcoes: ["Porque o amor é irrelevante", "Porque é preciso avaliar também pelas Escrituras e pelos frutos, não apenas pelo sentimento", "Porque o amor sempre engana", "Porque só profetas têm amor verdadeiro"], correta: 1, explicacao: "A resposta correta é: Porque é preciso avaliar também pelas Escrituras e pelos frutos, não apenas pelo sentimento." }
      ]
    }
  ]
};
