export const LICAO_ADULT_7 = {
  titulo: "Lição 7 - O retrato do amor (8 a 14 de agosto)",
  semana: "2026-W32",
  trimestre: "1 e 2 Coríntios",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-08-08",
      titulo: "O retrato do amor",
      conteudo: "O amor pode vencer tudo. É por isso que Paulo tinha tanto a dizer sobre ele. A família de palavras ágape — a palavra grega mais comum no Novo Testamento para expressar o conceito de amor — ocorre mais de 135 vezes em suas cartas. Isso representa quase metade de todas as ocorrências no Novo Testamento. Isso deve nos dizer algo sobre o tema central das cartas de Paulo à igreja de Corinto.\n\nExistem muitas passagens notáveis sobre o amor no Novo Testamento — Romanos 8:35-39, 1 Coríntios 2:9, 1 Coríntios 8:3, Gálatas 2:20, Colossenses 1:13, 1 Tessalonicenses 3:12 e mais — mas nada se compara a 1 Coríntios 13.\n\nNa semana passada, vimos que sem amor, todas as coisas, até mesmo os dons espirituais, são inúteis. Esta semana, vamos analisar mais profundamente 1 Coríntios 13 e seu maravilhoso retrato do amor.\n\nComo veremos, o amor não é tanto uma emoção, mas sim uma atitude, uma atitude que deve ser expressa na vida, em atos e em palavras; caso contrário, não significa nada.\n\nO que o amor realmente é e faz foi plenamente revelado na vida de Jesus.\n\nEstude a lição desta semana para se preparar para o Sábado, 15 de Agosto.",
      versiculoChave: { texto: "Agora, pois, permanecem a fé, a esperança e o amor, estes três; porém o maior deles é o amor", referencia: "1 Coríntios 13:13" },
      perguntas: [
        { id: "d1q1", pergunta: "Qual palavra grega para \"amor\" ocorre mais de 135 vezes nas cartas de Paulo?", opcoes: ["Eros", "Ágape", "Philia", "Storge"], correta: 1, explicacao: "A resposta correta é: Ágape." },
        { id: "d1q2", pergunta: "Segundo o texto, o que representa essa ocorrência de \"ágape\" nas cartas de Paulo?", opcoes: ["Quase metade de todas as ocorrências no Novo Testamento", "Uma ocorrência rara", "Menos de 10 vezes no total", "Não é significativo"], correta: 0, explicacao: "A resposta correta é: Quase metade de todas as ocorrências no Novo Testamento." },
        { id: "d1q3", pergunta: "Segundo o texto, o amor não é tanto uma emoção, mas sim...", opcoes: ["Um sentimento passageiro", "Uma atitude expressa em atos e palavras", "Um dom exclusivo dos apóstolos", "Algo impossível de definir"], correta: 1, explicacao: "A resposta correta é: Uma atitude expressa em atos e palavras." },
        { id: "d1q4", pergunta: "Onde o que o amor realmente é e faz foi plenamente revelado, segundo o texto?", opcoes: ["Nas leis do Antigo Testamento", "Na vida de Jesus", "Nos escritos de Platão", "Nas tradições da igreja"], correta: 1, explicacao: "A resposta correta é: Na vida de Jesus." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-08-09",
      titulo: "O caráter essencial do amor",
      conteudo: "Na semana passada, abordamos o tema do amor conforme visto em 1 Coríntios 13. Precisamos explorar as palavras de Paulo aqui com ainda mais profundidade.\n\n1. Leia 1 Coríntios 13. Resuma o que esse capítulo nos ensina sobre o amor.\n\nPaulo não está dizendo que línguas (1 Coríntios 13:1), profecia, entendimento, conhecimento, fé (1 Coríntios 13:2) e benevolência (1 Coríntios 13:3) são inúteis. Eles são inúteis apenas se não forem motivados pelo amor.\n\nO tipo de amor de que Paulo fala não se expressa em frases como \"Eu amo morangos\", \"Eu amo meus amigos\" ou mesmo \"Eu amo meu cônjuge e meus filhos\". Tampouco se refere ao tipo de amor que vemos nos filmes. E não, não é amor erótico, embora essa passagem seja comumente usada em sermões de casamento.\n\nEsse amor não pode ser reduzido a afeição, caridade, virtude ou benevolência. Contudo, todos esses termos o representam em maior ou menor grau. Esse amor é uma graça especial que nos é concedida pelo Espírito. De fato, o amor em 1 Coríntios 13 é a motivação dada pelo Espírito que nos leva a agir com afeição, caridade, virtude e benevolência. É um compromisso total de nossas ações, sentimentos e pensamentos para com Cristo e nosso próximo.\n\n2. Leia Mateus 24:12. Que alerta Jesus nos dá nesse verso?\n\nÉ por isso que o amor ágape é tão essencial e necessário. No poder de Cristo, não podemos deixar que o amor esfrie em nossos lares, igrejas e vizinhanças. Temos o exemplo de Cristo na cruz, morrendo por nós. Que expressão melhor e mais poderosa desse tipo de amor poderia haver? Embora, é claro, jamais possamos expressar esse amor da mesma forma, pela graça de Deus devemos nos esforçar para revelá-lo em nossas próprias vidas, na medida do possível.\n\nEm que momentos esse tipo de amor pode fazer diferença na vida de alguém?",
      versiculoChave: { texto: "Agora, pois, permanecem a fé, a esperança e o amor, estes três; porém o maior deles é o amor", referencia: "1 Coríntios 13:13" },
      perguntas: [
        { id: "d2q1", pergunta: "Segundo o texto, línguas, profecia, conhecimento e fé são inúteis quando...", opcoes: ["Praticados em público", "Não motivados pelo amor", "Usados por líderes", "Ensinados sem estudo"], correta: 1, explicacao: "A resposta correta é: Não motivados pelo amor." },
        { id: "d2q2", pergunta: "O amor de 1 Coríntios 13 se refere a que tipo de amor, segundo o texto?", opcoes: ["Amor erótico apenas", "Uma graça especial concedida pelo Espírito", "Apenas afeição familiar", "Um sentimento passageiro de simpatia"], correta: 1, explicacao: "A resposta correta é: Uma graça especial concedida pelo Espírito." },
        { id: "d2q3", pergunta: "Segundo Mateus 24:12, citado no texto, o que aconteceria com o amor de muitos?", opcoes: ["Aumentaria continuamente", "Esfriaria", "Permaneceria inalterado", "Se tornaria perfeito"], correta: 1, explicacao: "A resposta correta é: Esfriaria." },
        { id: "d2q4", pergunta: "Qual é o exemplo supremo desse tipo de amor, segundo o texto?", opcoes: ["O amor entre amigos", "Cristo na cruz, morrendo por nós", "O amor romântico", "O amor pelos animais"], correta: 1, explicacao: "A resposta correta é: Cristo na cruz, morrendo por nós." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-08-10",
      titulo: "O que o amor faz",
      conteudo: "Primeira Coríntios 13:4-7 é o cerne do capítulo. Paulo se concentra nas características do amor — mostrando o que o amor é e o que não é, ou o que o amor faz e o que não faz. Ele personifica o amor para que possamos vislumbrar como se comporta uma pessoa cheia do amor guiado pelo Espírito. Em sua descrição do amor, Paulo usa uma série de verbos. Para ele, o amor tem mais a ver com ações do que com sentimentos ou emoções.\n\nAfinal, o que faz o amor?\n\nDemonstra paciência (makrothymeō). Significa demonstrar paciência, mesmo em meio a circunstâncias desafiadoras. A paciência também destaca a capacidade de ser tolerante uns com os outros (Efésios 4:2).\n\nDemonstra bondade (chrēsteuomai). Ocorre apenas aqui no Novo Testamento, mas outras palavras da mesma raiz são comuns em outros lugares. Na Septuaginta, palavras dessa raiz ocorrem frequentemente nos Salmos para se referir à bondade de Deus associada à Sua misericórdia (Salmos 145:9). Ao dizer que o amor demonstra bondade, Paulo quis dizer que o amor de alguém pelos outros deve imitar a compaixão e a misericórdia de Deus para conosco.\n\nAlegra-se com a verdade (synchairō). Expressa a capacidade de experimentar alegria junto com outra pessoa (Lucas 1:58; Lucas 15:6, 9; 1 Coríntios 12:26; Filipenses 2:17, 18).\n\nTudo sofre (stegō). Os estudiosos debatem se stegō significa \"cobrir\", ou seja, manter algo confidencial, ou \"perseverar\", com um sentido de resiliência. O conceito de perseverança ocorre claramente em 1 Coríntios 9:12, levando a maioria dos intérpretes a considerar a segunda opção como mais provável.\n\nTudo crê (pisteuō). Vem da mesma raiz que o termo grego para fé (pistis). Acreditar em todas as coisas significa dar uns aos outros o benefício da dúvida.\n\nTudo espera (elpizō). No Novo Testamento, o verbo elpizō sempre se refere à crença ou expectativa de que algo bom acontecerá.\n\nTudo suporta (hypomenō). Provavelmente sinônimo de stegō, significando perseverança em meio às dificuldades. Ao repetir o mesmo conceito com uma palavra diferente, Paulo chama a atenção para a fé e a esperança como ponto central. Em outras palavras, o amor perdura pela fé e pela esperança.\n\nCompare 1 Coríntios 13:4-7 com Gálatas 5:22, 23. Que ideias em comum você percebe entre as duas passagens? Como manifestar esse amor em sua vida?",
      versiculoChave: { texto: "Agora, pois, permanecem a fé, a esperança e o amor, estes três; porém o maior deles é o amor", referencia: "1 Coríntios 13:13" },
      perguntas: [
        { id: "d3q1", pergunta: "Segundo o texto, os verbos que Paulo usa para descrever o amor mostram que ele tem mais a ver com...", opcoes: ["Sentimentos e emoções", "Ações", "Pensamentos apenas", "Palavras vazias"], correta: 1, explicacao: "A resposta correta é: Ações." },
        { id: "d3q2", pergunta: "O que significa o verbo grego \"makrothymeō\", traduzido como demonstrar paciência?", opcoes: ["Ser indiferente", "Demonstrar paciência mesmo em circunstâncias desafiadoras", "Evitar conflitos a qualquer custo", "Nunca se emocionar"], correta: 1, explicacao: "A resposta correta é: Demonstrar paciência mesmo em circunstâncias desafiadoras." },
        { id: "d3q3", pergunta: "Segundo o texto, \"alegra-se com a verdade\" (synchairō) expressa a capacidade de...", opcoes: ["Sentir inveja dos outros", "Experimentar alegria junto com outra pessoa", "Ignorar as conquistas alheias", "Competir por reconhecimento"], correta: 1, explicacao: "A resposta correta é: Experimentar alegria junto com outra pessoa." },
        { id: "d3q4", pergunta: "Segundo o texto, o verbo grego \"elpizō\" sempre se refere a quê no Novo Testamento?", opcoes: ["Um medo constante", "A crença ou expectativa de que algo bom acontecerá", "Uma dúvida permanente", "Uma indiferença ao futuro"], correta: 1, explicacao: "A resposta correta é: A crença ou expectativa de que algo bom acontecerá." }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-08-11",
      titulo: "O que o amor não faz",
      conteudo: "3. Leia novamente 1 Coríntios 13:4-7. Por que Paulo menciona características negativas do amor, e não apenas positivas?\n\nOntem, nos concentramos em sete coisas que o amor faz; hoje, vamos examinar oito coisas que ele não faz. O amor...\n\nNão arde em ciúmes (zeloō). Pode ser usado positivamente, como em \"desejar os dons superiores\" (1 Coríntios 12:31). Aqui, porém, como em Atos 7:9, é negativo. É correto desejar dons espirituais, mas não invejar pessoas dotadas. Isso causa divisão (1 Coríntios 3:3).\n\nNão se envaidece (perpereuomai). Transmite a ideia de arrogância e desejo de elogios alheios. O amor, porém, não é egocêntrico dessa forma.\n\nNão é orgulhoso (physioō). Aparece em 1 Coríntios 8:1 na notável declaração de Paulo: \"O conhecimento envaidece, mas o amor edifica\". Refere-se a uma pessoa inflada de auto-importância.\n\nNão se conduz de forma inconveniente (aschēmoneo). De modo geral, significa agir contrariamente aos padrões sociais e morais de maneira desonrosa ou imprópria. Paulo provavelmente está se referindo ao comportamento arrogante e rude do grupo \"forte\" em relação aos membros \"fracos\" em Corinto (1 Coríntios 4:10, 1 Coríntios 8).\n\nNão busca os seus interesses (zēteo). Semelhante a 1 Coríntios 10:24: \"Ninguém busque o seu próprio direito, mas sim o dos outros\". O amor abre mão de seus próprios direitos em prol dos outros.\n\nNão se irrita (paroxyno). Sugere um estado interior de excitação, indicando alguém que se irrita com facilidade. O amor não é impaciente nem se deixa levar facilmente.\n\nNão se ressente do mal (logizomai). Tem aqui um sentido contábil, significando que o amor não leva em conta os erros de alguém. Em outras palavras, amar também significa perdoar.\n\nNão se alegra com a injustiça (chairō). O amor não apenas não guarda rancor dos erros alheios, como também não sente prazer neles. Quando amamos verdadeiramente os outros, não nos regozijamos com seus erros, mas, ao contrário, buscamos ajudá-los.",
      versiculoChave: { texto: "Agora, pois, permanecem a fé, a esperança e o amor, estes três; porém o maior deles é o amor", referencia: "1 Coríntios 13:13" },
      perguntas: [
        { id: "d4q1", pergunta: "Segundo o texto, \"não arde em ciúmes\" (zeloō) significa que é errado...", opcoes: ["Desejar dons espirituais", "Invejar pessoas dotadas", "Buscar crescimento espiritual", "Orar por dons"], correta: 1, explicacao: "A resposta correta é: Invejar pessoas dotadas." },
        { id: "d4q2", pergunta: "O verbo \"physioō\" (\"não é orgulhoso\") aparece em qual outra passagem citada pelo texto?", opcoes: ["1 Coríntios 13:1", "1 Coríntios 8:1, sobre o conhecimento que envaidece", "Romanos 1:1", "Gálatas 5:1"], correta: 1, explicacao: "A resposta correta é: 1 Coríntios 8:1, sobre o conhecimento que envaidece." },
        { id: "d4q3", pergunta: "Segundo o texto, o amor \"não busca os seus interesses\", relacionando-se com qual outro texto de Paulo?", opcoes: ["1 Coríntios 10:24, sobre buscar o direito dos outros", "1 Coríntios 15:1", "2 Coríntios 1:1", "Romanos 8:1"], correta: 0, explicacao: "A resposta correta é: 1 Coríntios 10:24, sobre buscar o direito dos outros." },
        { id: "d4q4", pergunta: "O que significa \"não se ressente do mal\" (logizomai), segundo o texto?", opcoes: ["Esquecer tudo instantaneamente", "Não levar em conta os erros de alguém, ou seja, perdoar", "Ignorar completamente a justiça", "Vingar-se discretamente"], correta: 1, explicacao: "A resposta correta é: Não levar em conta os erros de alguém, ou seja, perdoar." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-08-12",
      titulo: "Retrato de Jesus",
      conteudo: "Ao lermos 1 Coríntios 13:4-7, podemos nos sentir frustrados ao percebermos que, em maior ou menor grau, não conseguimos demonstrar todas as características do amor. Provavelmente, Paulo tinha em mente a pessoa de Jesus ao escrever 1 Coríntios 13. De fato, somente Cristo revelou perfeitamente todas essas características do amor. Assim, em última análise, a descrição do amor feita por Paulo é um retrato de Jesus.\n\n4. Leia João 13:1, 34; João 15:9, 12, 1 Timóteo 1:14; 2 Timóteo 1:7, 13; 1 João 3:16; 1 João 4:7-12, 19-21. O que esses textos nos ensinam sobre o amor?\n\nDeus é amor (1 João 4:8). Ele nos ama tanto que deu Seu Filho unigênito (João 3:16). Jesus é a expressão plena desse amor (Hebreus 1:3). Se quisermos saber como o amor se manifesta, precisamos observar Jesus atentamente. Se prestarmos atenção à descrição de Jesus no Novo Testamento, perceberemos que todas as características positivas do amor mencionadas em 1 Coríntios 13 estão presentes Nele.\n\nJesus é paciente. \"Mas foi exatamente por isso que recebi misericórdia, para que em mim, o pior dos pecadores, Cristo Jesus demonstrasse toda a sua paciência [makrothymia]\" (1 Timóteo 1:16).\n\nJesus é bondoso. A Bíblia diz que \"o Senhor é bondoso\" (1 Pedro 2:3). O termo \"bondoso\" traduz a palavra grega chrēstos, que vem da mesma raiz do verbo chrēsteuomai (\"mostrar bondade\") em 1 Coríntios 13:4.\n\nJesus se alegra com a verdade. Jesus experimentou alegria ao seguir a vontade do Pai e sentir o Seu amor por Ele (João 15:9-11, João 17:12-14).\n\nJesus tudo sofre e tudo suporta. Hebreus 12:2, 3 diz que Jesus \"suportou a cruz... [Ele] suportou tamanha hostilidade dos pecadores contra si mesmo\". Ninguém suportou tanto quanto Jesus (Filipenses 2:8). Ele fez isso pela alegria que lhe foi proposta!\n\nJesus tudo crê. Quando Ananias questionou a autenticidade da conversão de Paulo (Atos 9:13, 14), Jesus respondeu: \"Ele é um instrumento escolhido por mim\" (Atos 9:15). Jesus vê as pessoas não apenas como elas são, mas como elas se tornarão por meio do Seu poder.\n\nDe que outras maneiras Jesus nos mostra o que é o amor verdadeiro?",
      versiculoChave: { texto: "Agora, pois, permanecem a fé, a esperança e o amor, estes três; porém o maior deles é o amor", referencia: "1 Coríntios 13:13" },
      perguntas: [
        { id: "d5q1", pergunta: "Segundo o texto, a descrição do amor em 1 Coríntios 13 é, em última análise, um retrato de quem?", opcoes: ["Paulo", "Jesus", "Timóteo", "Um cristão ideal genérico"], correta: 1, explicacao: "A resposta correta é: Jesus." },
        { id: "d5q2", pergunta: "Segundo 1 João 4:8, citado no texto, o que Deus é?", opcoes: ["Poder", "Amor", "Juiz", "Mistério"], correta: 1, explicacao: "A resposta correta é: Amor." },
        { id: "d5q3", pergunta: "Segundo o texto, como Jesus demonstrou ser paciente, conforme 1 Timóteo 1:16?", opcoes: ["Recusando-se a perdoar", "Demonstrando toda a Sua paciência até com \"o pior dos pecadores\"", "Evitando o contato com pecadores", "Punindo Paulo por sua conversão tardia"], correta: 1, explicacao: "A resposta correta é: Demonstrando toda a Sua paciência até com \"o pior dos pecadores\"." },
        { id: "d5q4", pergunta: "Segundo o texto, como Jesus respondeu quando Ananias questionou a conversão de Paulo (Atos 9)?", opcoes: ["Concordando com a dúvida", "Afirmando que Paulo era \"um instrumento escolhido\"", "Ignorando a pergunta", "Punindo Ananias"], correta: 1, explicacao: "A resposta correta é: Afirmando que Paulo era \"um instrumento escolhido\"." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-08-13",
      titulo: "Fé, esperança e amor",
      conteudo: "Até agora, aprendemos que o amor é paciente, bondoso, alegre, resiliente, crente, esperançoso e perseverante, porque Jesus é todas essas coisas. Uma vez que vemos essas qualidades em Jesus, o próximo passo é imitá-Lo. Esse era o desejo de Paulo para os coríntios. No entanto, se removermos o \"não\" das oito características negativas do amor, obtemos uma descrição bastante precisa da conduta dos coríntios em seu círculo religioso: invejosos, jactanciosos, arrogantes, rudes, egoístas, facilmente ofendidos e sempre procurando o que os outros estavam fazendo de errado. Paulo está adaptando os verbos que usa aqui à situação dos coríntios.\n\nOs coríntios tinham muito a aprender. Nós também. Depois de descrever o que o amor faz e o que não faz, Paulo conclui sua seção enfatizando a natureza eterna do amor, a fim de estimular a prática do amor genuíno.\n\nUm dia, as profecias não serão mais necessárias; falaremos apenas uma língua; e o conhecimento humano falho será substituído por um conhecimento totalmente novo de Deus (1 Coríntios 13:12). Os dons do Espírito cessarão somente quando o propósito para o qual existem tiver se cumprido (1 Coríntios 13:10). \"Mas o amor durará para sempre!\" (1 Coríntios 13:8).\n\nDa mesma forma, quando Cristo voltar, a fé dará lugar à visão (2 Coríntios 5:7), e aquilo que há muito esperamos se tornará realidade (Romanos 8:24). E, acima de tudo, o amor perdurará como um emblema do caráter do nosso Deus trino. Contudo, há um sentido em que a fé e a esperança também durarão para sempre. A fé como a experiência da salvação (Romanos 4:3) e a esperança como o desejo e a expectativa de novas alegrias e conhecimento na nova terra marcarão a experiência dos redimidos para sempre. Mas o amor, o amor de Deus, prevalecerá eternamente.\n\nMuito em breve, veremos nosso Senhor face a face (1 Coríntios 13:12). Até que esse dia chegue, devemos definir nossas vidas com base nessas três virtudes: fé, esperança e amor. Essa tríade representa a plenitude da vida cristã por meio do Espírito. É por isso que era frequentemente mencionada entre os cristãos (Romanos 5:1-5; Gálatas 5:5, 6; Efésios 1:15, 18; 4:1-5). O amor, porém, é a maior; afinal, é a única virtude usada para descrever a própria natureza de Deus (1 João 4:8).\n\nReflita sobre a afirmação \"Deus é amor\". Como compreender o que ela significa? E, ainda que só possamos entender isso em parte, por que essa verdade é uma notícia tão boa para nós?",
      versiculoChave: { texto: "Agora, pois, permanecem a fé, a esperança e o amor, estes três; porém o maior deles é o amor", referencia: "1 Coríntios 13:13" },
      perguntas: [
        { id: "d6q1", pergunta: "Segundo o texto, se removermos o \"não\" das características negativas do amor, obtemos uma descrição de quê?", opcoes: ["Do caráter de Jesus", "Da conduta dos coríntios em seu círculo religioso", "Da vida de Paulo", "Do comportamento ideal cristão"], correta: 1, explicacao: "A resposta correta é: Da conduta dos coríntios em seu círculo religioso." },
        { id: "d6q2", pergunta: "Segundo 1 Coríntios 13:8, o que durará para sempre, diferente das profecias e línguas?", opcoes: ["O conhecimento humano", "O amor", "Os dons espirituais", "As controvérsias religiosas"], correta: 1, explicacao: "A resposta correta é: O amor." },
        { id: "d6q3", pergunta: "Segundo o texto, quando Cristo voltar, o que substituirá a fé?", opcoes: ["O conhecimento humano falho", "A visão", "Nada, a fé permanece igual", "A dúvida"], correta: 1, explicacao: "A resposta correta é: A visão." },
        { id: "d6q4", pergunta: "Segundo o texto, por que o amor é considerado o maior entre fé, esperança e amor?", opcoes: ["Porque é o mais fácil de praticar", "Porque é a única virtude usada para descrever a própria natureza de Deus", "Porque substitui a fé completamente", "Porque não precisa ser praticado"], correta: 1, explicacao: "A resposta correta é: Porque é a única virtude usada para descrever a própria natureza de Deus." }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-08-14",
      titulo: "Estudo Adicional - O retrato do amor",
      conteudo: "Leia Ellen G. White, \"A Necessidade do Amor\", The Advent Review and Sabbath Herald, 28 de agosto de 1888, p. 545, 546.\n\n\"Não importa quão elevada seja a profissão de fé, aquele cujo coração não esteja repleto de amor por Deus e pelo próximo não é um verdadeiro discípulo de Cristo. Mesmo que possua grande fé e tenha poder até para realizar milagres, sem amor sua fé seria inútil. Ele poderia demonstrar grande liberalidade; mas se, por algum outro motivo que não o amor genuíno, distribuísse todos os seus bens para alimentar os pobres, o ato não o recomendaria ao favor de Deus. Em seu zelo, ele poderia até encontrar a morte como mártir, mas se não fosse movido pelo amor, seria considerado por Deus um entusiasta iludido ou um hipócrita ambicioso.\" — Ellen G. White, Atos dos Apóstolos [2021], p. 203.\n\n\"Temos sermões em abundância. O que mais precisamos... é de amor pelas almas que se perdem, aquele amor que flui abundantemente do trono de Deus. O verdadeiro cristianismo difunde o amor por todo o ser. Ele toca cada parte vital: o cérebro, o coração, as mãos que ajudam, os pés, capacitando os homens a permanecerem firmes onde Deus exige que permaneçam, para que não criem caminhos tortuosos para os seus pés, para que o coxo não seja desviado. O amor ardente e consumidor de Cristo pelas almas que se perdem é a essência de todo o sistema do cristianismo.\" — Ellen G. White, Exaltai-O [1988], 30 de abril.\n\n\"Somente o amor que flui do coração de Cristo pode curar. Somente aquele em quem esse amor flui, assim como a seiva na árvore ou o sangue no corpo, pode restaurar a alma ferida.\" — Ellen G. White, Educação [2021], p. 79.\n\nQuestões para discussão:\n\n1. O que Paulo quis dizer com a ordem: \"Sigam o amor\" (1 Coríntios 14:1)? Que relação isso tem com o que ele diz em 1 Coríntios 13:4-7?\n\n2. Qual característica do amor você mais precisa colocar em prática no dia a dia? Quais são mais necessárias em sua igreja local? E por que Paulo compara o amor a dons como profecia, línguas e conhecimento (1 Coríntios 13:8)?\n\n3. Paulo revela que o amor é a solução definitiva para a falta de unidade na igreja de Corinto. Por quê? Como isso se aplica às nossas igrejas hoje?",
      versiculoChave: { texto: "Agora, pois, permanecem a fé, a esperança e o amor, estes três; porém o maior deles é o amor", referencia: "1 Coríntios 13:13" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo Ellen White, o que aconteceria com uma fé capaz de realizar milagres, mas sem amor?", opcoes: ["Seria ainda mais poderosa", "Seria inútil", "Se tornaria perfeita", "Substituiria o amor"], correta: 1, explicacao: "A resposta correta é: Seria inútil." },
        { id: "d7q2", pergunta: "Segundo o texto de Ellen White, o que mais precisamos, além de sermões?", opcoes: ["Mais doutrina", "Amor pelas almas que se perdem", "Mais regras", "Mais rituais"], correta: 1, explicacao: "A resposta correta é: Amor pelas almas que se perdem." },
        { id: "d7q3", pergunta: "Segundo Ellen White, o que é capaz de curar a alma ferida?", opcoes: ["O conhecimento acadêmico", "O amor que flui do coração de Cristo", "A disciplina rígida", "O isolamento"], correta: 1, explicacao: "A resposta correta é: O amor que flui do coração de Cristo." },
        { id: "d7q4", pergunta: "Segundo a pergunta de discussão, por que Paulo compara o amor a dons como profecia, línguas e conhecimento?", opcoes: ["Para desvalorizar os dons", "Para mostrar que o amor é superior e permanente, enquanto os dons são temporários", "Para dizer que são idênticos", "Para incentivar apenas o dom de línguas"], correta: 1, explicacao: "A resposta correta é: Para mostrar que o amor é superior e permanente, enquanto os dons são temporários." }
      ]
    }
  ]
};

export const LICAO_ADULT_8 = {
  titulo: "Lição 8 - O poder da ressurreição de Cristo (15 a 21 de agosto)",
  semana: "2026-W33",
  trimestre: "1 e 2 Coríntios",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-08-15",
      titulo: "O poder da ressurreição de Cristo",
      conteudo: "Que fascinante que, mesmo em sua época, Paulo tenha tido que lidar com aqueles que negavam a ressurreição dos mortos. Afinal, as pessoas daquela época viam o que a morte fazia com o corpo humano. Sabiam como o cadáver se liquefazia, depois se desfazia em pó e, por fim, tornava-se quase nada. E também sabiam que as pessoas morriam há muito tempo. Aliás, a maioria das pessoas morria há muito mais tempo do que vivia.\n\nA ressurreição dos mortos não parecia mais plausível para eles naquela época do que parece para nós agora, pelo menos do ponto de vista humano. E essa deve ter sido uma questão que Paulo estava abordando.\n\nE isso era crucial. Se Jesus não tivesse ressuscitado, Ele não seria quem disse ser, a cruz não teria tido efeito e nossos pecados não teriam sido perdoados. O desespero seria tudo o que nos restaria. Mas nosso Senhor ressuscitou, ascendeu aos céus e voltará para nos levar para casa!\n\nEsta semana, vamos nos concentrar em 1 Coríntios 15 e seu ensinamento sobre a ressurreição de Cristo. Influenciados pela visão de mundo pagã da época, alguns em Corinto afirmavam que não havia ressurreição. Em resposta, Paulo afirma a ressurreição de Cristo como nossa única esperança de salvação.\n\nEstude a lição desta semana para se preparar para o Sábado, 22 de Agosto.",
      versiculoChave: { texto: "E, se Cristo não ressuscitou, é vã a nossa pregação, e é vã a fé que vocês têm. [...] E, se Cristo não ressuscitou, é vã a fé que vocês têm, e vocês ainda permanecem nos seus pecados", referencia: "1 Coríntios 15:14, 17" },
      perguntas: [
        { id: "d1q1", pergunta: "Segundo o texto, o que as pessoas da época de Paulo sabiam sobre a morte?", opcoes: ["Que era reversível facilmente", "Como o cadáver se liquefazia e se desfazia em pó", "Que ninguém realmente morria", "Que a ressurreição era óbvia"], correta: 1, explicacao: "A resposta correta é: Como o cadáver se liquefazia e se desfazia em pó." },
        { id: "d1q2", pergunta: "Segundo o texto, o que aconteceria se Jesus não tivesse ressuscitado?", opcoes: ["Nada mudaria", "Ele não seria quem disse ser, e nossos pecados não teriam sido perdoados", "A cruz teria ainda mais efeito", "Isso não teria relevância teológica"], correta: 1, explicacao: "A resposta correta é: Ele não seria quem disse ser, e nossos pecados não teriam sido perdoados." },
        { id: "d1q3", pergunta: "Segundo o texto, quem em Corinto afirmava que não havia ressurreição?", opcoes: ["Todos os membros, sem exceção", "Alguns, influenciados pela visão de mundo pagã", "Apenas Paulo", "Ninguém, era um consenso cristão"], correta: 1, explicacao: "A resposta correta é: Alguns, influenciados pela visão de mundo pagã." },
        { id: "d1q4", pergunta: "Qual capítulo de 1 Coríntios trata da ressurreição de Cristo, foco desta lição?", opcoes: ["1 Coríntios 10", "1 Coríntios 15", "1 Coríntios 5", "1 Coríntios 1"], correta: 1, explicacao: "A resposta correta é: 1 Coríntios 15." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-08-16",
      titulo: "Proclamação a ressurreição de Cristo",
      conteudo: "Paulo inicia 1 Coríntios 15 focando no evangelho. Ele fala sobre o evangelho: (1) que pregou aos coríntios; (2) que eles receberam; (3) no qual permaneceram firmes; e (4) pelo qual foram salvos (1 Coríntios 15:1, 2). Essa introdução prepara o leitor para o que vem a seguir no capítulo e mostra como a ressurreição de Cristo é essencial para a nossa salvação (veja também Romanos 10:9, 10). Sua ressurreição é uma parte tão vital da mensagem do evangelho que negá-la contradiz a fé em Cristo.\n\n1. Leia 1 Coríntios 15:1-4, Lucas 24:44-47, Romanos 1:1-4. O que esses textos têm em comum?\n\nEm 1 Coríntios 15:1-4, encontramos um resumo da mensagem de Paulo. Não importa se a expressão \"segundo as Escrituras\" se refere a passagens específicas do Antigo Testamento ou ao Antigo Testamento como um todo. A morte e ressurreição de Jesus cumprem as promessas de Deus encontradas no Antigo Testamento.\n\n2. Leia 1 Coríntios 15:2, 11. Por que esses versos colocam lado a lado crer e pregar? Que relação existe entre os dois conceitos?\n\nTodos os que proclamam a ressurreição de Cristo devem primeiro crer que a Sua ressurreição é um evento histórico. Nesse caso, 1 Coríntios 15:5-8 desempenha um papel crucial no Novo Testamento. Essa passagem fornece evidências bíblicas sólidas de que Cristo foi visto por inúmeras pessoas após a Sua ressurreição, muitas das quais ainda estavam vivas quando Paulo escreveu a carta (1 Coríntios 15:6).\n\nBasicamente, Paulo está dizendo: \"Vão e perguntem a eles mesmos o que viram\". Essa era a certeza que ele tinha da realidade da ressurreição de Cristo.\n\nEssas pessoas eram testemunhas oculares. Elas eram o que Jesus disse que seriam, ou seja, \"testemunhas destas coisas\" (Lucas 24:48).\n\nQue razões temos para crer na ressurreição de Cristo? Além disso, em que outras coisas – seculares ou sagradas – cremos, mesmo sem tê-las visto pessoalmente?",
      versiculoChave: { texto: "E, se Cristo não ressuscitou, é vã a nossa pregação, e é vã a fé que vocês têm. [...] E, se Cristo não ressuscitou, é vã a fé que vocês têm, e vocês ainda permanecem nos seus pecados", referencia: "1 Coríntios 15:14, 17" },
      perguntas: [
        { id: "d2q1", pergunta: "Segundo 1 Coríntios 15:1,2, Paulo fala do evangelho em quantos aspectos?", opcoes: ["Dois", "Quatro: pregou, receberam, permaneceram firmes, foram salvos", "Um só", "Dez"], correta: 1, explicacao: "A resposta correta é: Quatro: pregou, receberam, permaneceram firmes, foram salvos." },
        { id: "d2q2", pergunta: "Segundo o texto, por que a ressurreição de Cristo é essencial para a salvação?", opcoes: ["Porque é apenas um detalhe histórico", "Porque negá-la contradiz a fé em Cristo", "Porque não tem relação com o evangelho", "Porque é opcional"], correta: 1, explicacao: "A resposta correta é: Porque negá-la contradiz a fé em Cristo." },
        { id: "d2q3", pergunta: "Segundo 1 Coríntios 15:5-8, o que comprova que Cristo ressuscitou?", opcoes: ["Apenas a tradição oral", "Cristo foi visto por inúmeras testemunhas oculares, muitas ainda vivas", "Nenhuma evidência é dada", "Apenas os discípulos mais próximos o viram"], correta: 1, explicacao: "A resposta correta é: Cristo foi visto por inúmeras testemunhas oculares, muitas ainda vivas." },
        { id: "d2q4", pergunta: "Segundo Lucas 24:48, citado no texto, o que os discípulos eram chamados a ser?", opcoes: ["Sacerdotes", "Testemunhas dessas coisas", "Reis", "Escribas"], correta: 1, explicacao: "A resposta correta é: Testemunhas dessas coisas." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-08-17",
      titulo: "Cristo ressuscitado, nossa única esperança",
      conteudo: "Em 1 Coríntios 15:9-19, Paulo explica quão severas e terríveis são as consequências de negar a Ressurreição. Sem a Ressurreição, os crentes não têm esperança no presente, muito menos no futuro.\n\n3. Leia 1 Coríntios 15:9-19. Quais seriam as consequências se Cristo não tivesse ressuscitado?\n\nDe modo geral, os antigos pagãos não acreditavam na ressurreição, especialmente no mundo grego, com sua crença no dualismo corpo-alma (na morte, a alma ascende para onde quer que as almas dos mortos supostamente vão). Paulo inicia o parágrafo em 1 Coríntios 15:12-19 com uma pergunta retórica que demonstra sua profunda perplexidade: \"Como? Como podem alguns de vocês dizer que não existe ressurreição dos mortos?\" (1 Coríntios 15:12).\n\nPara Paulo, descrer na Ressurreição era inconcebível, especialmente porque havia tantas testemunhas oculares (1 Coríntios 15:5-8). Mas pior ainda, sem a Ressurreição, a esperança deles se baseava em uma mentira, e eles permaneciam em seus pecados.\n\nEle diz, de fato, que se não há ressurreição dos mortos, então (1) Cristo não ressuscitou (1 Coríntios 15:13, 16); (2) nossa pregação é vã (1 Coríntios 15:14); (3) nossa fé também é vã (1 Coríntios 15:14); (4) somos falsas testemunhas (1 Coríntios 15:15); (5) nossa fé é inútil (1 Coríntios 15:17); (6) ainda estamos em nossos pecados (1 Coríntios 15:17); e, obviamente, (7) aqueles que morreram não existem mais (1 Coríntios 15:18).\n\nSem a Ressurreição, tanto a pregação quanto a fé são vazias (1 Coríntios 15:14). O termo grego que traduz a palavra \"vazia\" é kenos. Esta é uma boa tradução, mas é muito ampla. Os intérpretes debatem se kenos significa \"vazia\" no sentido de falta de verdade (portanto, \"falsa\"), falta de resultados (portanto, \"sem resultado ou efeito\") ou falta de propósito (portanto, \"sem propósito\", \"em vão\").\n\nIndependentemente do significado específico, num cenário em que a ressurreição não existe, a fé é retratada como fútil, do grego mataios (1 Coríntios 15:17). Embora mataios não seja muito diferente de kenos, a ideia é que, se Jesus não está vivo, a fé é inútil, uma ilusão, porque os nossos pecados não foram perdoados (1 Coríntios 15:17). Seríamos falsas testemunhas, enganando e sendo enganados (1 Coríntios 15:15).\n\nSe, ao morrer, a pessoa vai imediatamente para o Céu ou para o inferno, que sentido tem 1 Coríntios 15? Por que a verdade bíblica do \"sono\" dos mortos é um ensino tão importante?",
      versiculoChave: { texto: "E, se Cristo não ressuscitou, é vã a nossa pregação, e é vã a fé que vocês têm. [...] E, se Cristo não ressuscitou, é vã a fé que vocês têm, e vocês ainda permanecem nos seus pecados", referencia: "1 Coríntios 15:14, 17" },
      perguntas: [
        { id: "d3q1", pergunta: "Segundo o texto, os antigos pagãos geralmente não acreditavam na ressurreição por causa de qual crença?", opcoes: ["O dualismo corpo-alma", "A reencarnação", "O politeísmo", "O ateísmo"], correta: 0, explicacao: "A resposta correta é: O dualismo corpo-alma." },
        { id: "d3q2", pergunta: "Segundo 1 Coríntios 15:14, se não há ressurreição, o que se torna vão?", opcoes: ["Apenas os rituais", "A pregação e a fé", "Nada muda", "Apenas o batismo"], correta: 1, explicacao: "A resposta correta é: A pregação e a fé." },
        { id: "d3q3", pergunta: "Segundo o texto, sem a ressurreição, o que se diria sobre aqueles que já morreram?", opcoes: ["Que estão no céu", "Que não existem mais", "Que se tornaram anjos", "Que retornarão como espíritos"], correta: 1, explicacao: "A resposta correta é: Que não existem mais." },
        { id: "d3q4", pergunta: "Segundo o texto, a palavra grega \"kenos\" pode significar o quê?", opcoes: ["Apenas alegria", "Vazio, sem resultado ou sem propósito", "Vitória", "Perfeição"], correta: 1, explicacao: "A resposta correta é: Vazio, sem resultado ou sem propósito." }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-08-18",
      titulo: "Cristo, as Primícias",
      conteudo: "Se Jesus não estivesse vivo, qualquer expectativa sobre o futuro seria mera ilusão (1 Coríntios 15:12-19). \"Mas, de fato, Cristo ressuscitou dentre os mortos\" (1 Coríntios 15:20). Sua ressurreição é um evento histórico. Consequentemente, podemos ter certeza de que todos os que morreram em Cristo ressuscitarão na Sua vinda (1 Coríntios 15:20-23).\n\n4. Leia 1 Coríntios 15:20-23. O que significa dizer que Jesus é as \"primícias\"?\n\nO fim desta era maligna será marcado pela ressurreição corporal daqueles que morreram em Cristo (1 Coríntios 15:22, 23; Apocalipse 20:5, 6). Como o último Adão, Cristo devolverá o reino ao Pai, trazendo de volta para Si o domínio deste mundo (1 Coríntios 15:25-28). A submissão de Cristo a Deus (1 Coríntios 15:28) deve ser compreendida em termos de como Adão e Cristo são retratados em relação um ao outro. Como o Adão definitivo no plano da redenção (1 Coríntios 15:45), Jesus submete-se inteiramente à vontade do Pai, algo que o primeiro Adão não conseguiu fazer.\n\nEm 1 Coríntios 15:29-34, Paulo retoma seu pensamento sobre a insensatez de negar a ressurreição de Cristo. Ele usa a ilustração do batismo porque este é, em si, um símbolo da união do crente com Cristo em Sua morte e ressurreição (Romanos 6:3, 4; Colossenses 2:12); não faz sentido negar a realidade da Ressurreição. O que é difícil de compreender, porém, é o que Paulo quis dizer com a expressão \"batizados pelos mortos\" (1 Coríntios 15:29).\n\n\"Foram apresentadas diversas sugestões, mas é melhor interpretar a expressão como referente à decisão de alguns de serem batizados para que pudessem se reunir com seus entes queridos falecidos na ressurreição. Também pode ser que a decisão de ser batizado tenha sido uma resposta à vida exemplar daqueles que morreram em Cristo. Nesse caso, as pessoas não seriam batizadas em lugar dos mortos, mas por causa dos mortos.\" — Comentário Bíblico Andrews, v. 4: \"Romanos a Apocalipse\" [2025], p. 206.\n\nEm segundo lugar, arriscar a morte seria inútil se não houvesse ressurreição (1 Coríntios 15:30-32). Seria melhor, em vez disso, deleitar-se nos prazeres deste mundo (1 Coríntios 15:32).\n\nReflita nas palavras de Paulo em 2 Timóteo 1:12. Como ele podia ter tanta certeza em relação ao futuro? E nós, como podemos tê-la?",
      versiculoChave: { texto: "E, se Cristo não ressuscitou, é vã a nossa pregação, e é vã a fé que vocês têm. [...] E, se Cristo não ressuscitou, é vã a fé que vocês têm, e vocês ainda permanecem nos seus pecados", referencia: "1 Coríntios 15:14, 17" },
      perguntas: [
        { id: "d4q1", pergunta: "Segundo 1 Coríntios 15:20-23, o que significa Jesus ser as \"primícias\"?", opcoes: ["Que Ele foi o único a ressuscitar, sem consequências para outros", "Que a ressurreição d'Ele garante a ressurreição de quem morreu Nele", "Que Ele era o primeiro pecador", "Que não há relação com a ressurreição futura"], correta: 1, explicacao: "A resposta correta é: Que a ressurreição d'Ele garante a ressurreição de quem morreu Nele." },
        { id: "d4q2", pergunta: "Segundo o texto, como Jesus é chamado em relação a Adão?", opcoes: ["O primeiro Adão", "O último Adão", "Um discípulo de Adão", "Não há comparação no texto"], correta: 1, explicacao: "A resposta correta é: O último Adão." },
        { id: "d4q3", pergunta: "Segundo o texto, o que Paulo quis dizer com \"batizados pelos mortos\" (1 Coríntios 15:29), segundo a interpretação sugerida?", opcoes: ["Um ritual mágico", "Possivelmente uma resposta à vida exemplar dos que morreram em Cristo, ou desejo de se reunir a entes queridos na ressurreição", "Uma prática proibida", "Não tem explicação alguma"], correta: 1, explicacao: "A resposta correta é: Possivelmente uma resposta à vida exemplar dos que morreram em Cristo, ou desejo de se reunir a entes queridos na ressurreição." },
        { id: "d4q4", pergunta: "Segundo o texto, se não houvesse ressurreição, o que seria mais sensato fazer, segundo 1 Coríntios 15:32?", opcoes: ["Arriscar a vida sem motivo", "Deleitar-se nos prazeres deste mundo", "Jejuar constantemente", "Isolar-se do mundo"], correta: 1, explicacao: "A resposta correta é: Deleitar-se nos prazeres deste mundo." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-08-19",
      titulo: "O corpo ressuscitado",
      conteudo: "Em 1 Coríntios 15:35-39, Paulo aborda brevemente o corpo ressuscitado. Ele inicia esta seção com duas perguntas: \"Como ressuscitam os mortos? E com que corpo vêm?\" (1 Coríntios 15:35). Essas perguntas são respondidas em 1 Coríntios 15:36-49.\n\n5. Leia 1 Coríntios 15:36-41. Como esse trecho responde às perguntas de 1 Coríntios 15:35?\n\nPaulo utiliza três analogias para ajudar seus leitores a compreender o que acontece na ressurreição. A primeira analogia (1 Coríntios 15:36-38) observa que o corpo é como uma semente que primeiro precisa morrer (ou deixar de ser semente) para milagrosamente se tornar uma planta. O ensinamento é claro: a ressurreição é um milagre de Deus.\n\nEm segundo lugar, a analogia dos corpos (1 Coríntios 15:39, 40) destaca que, neste mundo, Deus providenciou diferentes tipos de corpos para animais e para humanos, adequados ao ambiente presente. Da mesma forma, nossos corpos serão adequados às novas circunstâncias no mundo celestial. Essa ideia é aprofundada na terceira analogia de um corpo glorioso (1 Coríntios 15:40, 41), que enfatiza que a glória do corpo ressuscitado excede enormemente a do corpo que o precedeu, nossos corpos terrenos caídos.\n\nEssa ideia também pode ser vista através de quatro contrastes entre o nosso corpo terreno aqui e agora e o corpo ressuscitado. O primeiro é terrestre, perecível, frágil e natural. Por sua vez, o segundo é celestial, imperecível, poderoso e espiritual (1 Coríntios 15:40-44). Isso não significa que não haja continuidade entre os dois. O uso do termo grego sōma (\"corpo\") por Paulo, tanto para o corpo sepultado quanto para o corpo ressuscitado, demonstra continuidade. Por outro lado, os quatro contrastes acima também demonstram descontinuidade. Nossos novos corpos não serão iguais aos corpos em decomposição que temos agora (graças a Deus).\n\nPaulo não relaciona o termo \"espiritual\" a uma existência imaterial. Em outro lugar, ele diz que Jesus \"transformará o nosso corpo humilde, para ser semelhante ao seu corpo glorioso\" (Filipenses 3:21). Teremos corpos reais, mas eles não se desgastarão nem se deteriorarão. Como tudo o que conhecemos agora é decadência, doença e morte, é difícil imaginar a vida sem essas coisas, mas é isso que nos é prometido em Jesus.\n\nDe que maneira a certeza de que nosso corpo será transformado à perfeição nos ajuda a lidar, com resiliência, com as limitações físicas que enfrentamos hoje?",
      versiculoChave: { texto: "E, se Cristo não ressuscitou, é vã a nossa pregação, e é vã a fé que vocês têm. [...] E, se Cristo não ressuscitou, é vã a fé que vocês têm, e vocês ainda permanecem nos seus pecados", referencia: "1 Coríntios 15:14, 17" },
      perguntas: [
        { id: "d5q1", pergunta: "Que pergunta Paulo faz no início de 1 Coríntios 15:35, segundo o texto?", opcoes: ["\"Quem ressuscitará?\"", "\"Como ressuscitam os mortos? E com que corpo vêm?\"", "\"Quando será a ressurreição?\"", "\"Por que alguns não creem?\""], correta: 1, explicacao: "A resposta correta é: \"Como ressuscitam os mortos? E com que corpo vêm?\"." },
        { id: "d5q2", pergunta: "Qual é a primeira analogia usada por Paulo para explicar a ressurreição?", opcoes: ["Uma semente que morre para se tornar planta", "Um rio que nunca seca", "Uma estrela cadente", "Um edifício reconstruído"], correta: 0, explicacao: "A resposta correta é: Uma semente que morre para se tornar planta." },
        { id: "d5q3", pergunta: "Segundo o texto, quais são as quatro características do corpo terreno, em contraste com o corpo ressuscitado?", opcoes: ["Rico, pobre, forte, fraco", "Terrestre, perecível, frágil e natural", "Sábio, tolo, rápido, lento", "Jovem, velho, saudável, doente"], correta: 1, explicacao: "A resposta correta é: Terrestre, perecível, frágil e natural." },
        { id: "d5q4", pergunta: "Segundo o texto, o termo \"espiritual\" usado por Paulo para o corpo ressuscitado significa...", opcoes: ["Uma existência imaterial, sem corpo", "Um corpo real, mas que não se desgasta nem se deteriora", "Apenas um símbolo, sem realidade física", "Uma alma sem forma"], correta: 1, explicacao: "A resposta correta é: Um corpo real, mas que não se desgasta nem se deteriora." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-08-20",
      titulo: "Vitória final sobre a morte",
      conteudo: "6. Leia 1 Coríntios 15:54-57. O que esse trecho nos diz a respeito da nossa vitória definitiva sobre a morte?\n\nPaulo inicia o último parágrafo de 1 Coríntios 15 com uma afirmação intrigante: \"Carne e sangue não podem herdar o reino de Deus\" (1 Coríntios 15:50). Muitos leitores da Bíblia usam essa declaração para dizer que Paulo defende uma existência imaterial no céu. Mas o contexto indica o contrário. O paralelismo em 1 Coríntios 15:50 sugere que \"carne e sangue\" está em paralelo com \"corrupção\", assim como \"o reino de Deus\" está em paralelo com \"incorrupção\". Assim como ocorreu em 1 Coríntios 15:42-49, aqui também Paulo está contrastando o corpo atual (ou mesmo o cadáver) com o corpo ressuscitado. O corpo sepultado é marcado pela corrupção e mortalidade, enquanto o corpo ressuscitado é caracterizado pela incorrupção e imortalidade (1 Coríntios 15:50, 53, 54). Simplificando, Paulo está dizendo que nossos corpos precisam passar por uma transformação radical para herdar o céu.\n\nEm resumo, Paulo usa as ideias de corrupção e mortalidade para se referir à nossa natureza pecaminosa. Nos escritos judaicos, \"carne e sangue\" é uma expressão para a humanidade caída, razão pela qual nossos corpos devem ser transformados e purificados de toda imperfeição em Seu retorno.\n\nSomente quando nossa natureza pecaminosa for removida (1 Coríntios 15:54) e passarmos pela experiência da glorificação (1 Coríntios 15:51-53, 1 Tessalonicenses 4:13-17) é que a proclamação \"A morte foi tragada pela vitória\" (1 Coríntios 15:54) se cumprirá. Então, este hino ousado e desafiador será cantado: \"Onde está, ó morte, o teu aguilhão? Onde está, ó inferno, a tua vitória?\" (1 Coríntios 15:55). Tudo isso acontecerá na segunda vinda de Cristo (1 Coríntios 15:51, 52).\n\nPense nisso: fechamos os olhos na morte, e a próxima coisa que experimentaremos será a segunda vinda de Jesus, quando Ele nos ressuscitar dos mortos. Não importa quando um crente morreu, mesmo milhares de anos atrás, \"num instante, num abrir e fechar de olhos\", ele será vivificado \"ao som da última trombeta. Pois a trombeta soará, os mortos ressuscitarão incorruptíveis e nós seremos transformados\" (1 Coríntios 15:52).\n\nQuem nunca lamentou como a vida passa rapidamente? Do mesmo modo, a volta de Jesus nos parecerá rápida. Talvez, naquele dia, pensemos: \"Senhor, como Tua vinda foi rápida!\" Como essa perspectiva nos ajuda a lidar melhor com o que é visto como \"demora\"?",
      versiculoChave: { texto: "E, se Cristo não ressuscitou, é vã a nossa pregação, e é vã a fé que vocês têm. [...] E, se Cristo não ressuscitou, é vã a fé que vocês têm, e vocês ainda permanecem nos seus pecados", referencia: "1 Coríntios 15:14, 17" },
      perguntas: [
        { id: "d6q1", pergunta: "Segundo o texto, o que significa \"carne e sangue não podem herdar o reino de Deus\" (1 Coríntios 15:50)?", opcoes: ["Que o corpo atual, marcado pela corrupção, precisa ser transformado", "Que só almas sem corpo entram no céu", "Que ninguém pode ser salvo", "Que a ressurreição é impossível"], correta: 0, explicacao: "A resposta correta é: Que o corpo atual, marcado pela corrupção, precisa ser transformado." },
        { id: "d6q2", pergunta: "Segundo o texto, quando a proclamação \"a morte foi tragada pela vitória\" se cumprirá?", opcoes: ["Imediatamente após a morte de cada pessoa", "Na segunda vinda de Cristo", "Nunca se cumprirá", "No batismo"], correta: 1, explicacao: "A resposta correta é: Na segunda vinda de Cristo." },
        { id: "d6q3", pergunta: "Segundo 1 Coríntios 15:52, em quanto tempo os mortos ressuscitarão, ao som da última trombeta?", opcoes: ["Em muitos anos", "Num instante, num abrir e fechar de olhos", "Gradualmente, ao longo de séculos", "Não há tempo definido"], correta: 1, explicacao: "A resposta correta é: Num instante, num abrir e fechar de olhos." },
        { id: "d6q4", pergunta: "Segundo o texto, o que a pessoa experimentará logo após fechar os olhos na morte, do seu próprio ponto de vista?", opcoes: ["Uma longa espera consciente", "A segunda vinda de Jesus", "O julgamento imediato", "Uma jornada pelo espaço"], correta: 1, explicacao: "A resposta correta é: A segunda vinda de Jesus." }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-08-21",
      titulo: "Estudo Adicional - O poder da ressurreição de Cristo",
      conteudo: "Leia Ellen G. White, O Grande Conflito [2021], \"O grande resgate\" (p. 527-540).\n\n\"A divindade de Cristo é a garantia da vida eterna para o crente. 'Quem crê em mim', disse Jesus, 'ainda que esteja morto, viverá; e todo aquele que vive e crê em mim jamais morrerá. Crês tu nisso?' Cristo aqui antecipa o tempo de Sua segunda vinda. Então os justos mortos ressuscitarão incorruptíveis, e os justos vivos serão trasladados para o céu sem ver a morte. O milagre que Cristo estava prestes a realizar, ao ressuscitar Lázaro dentre os mortos, representaria a ressurreição de todos os justos mortos.\" — Ellen G. White, O Desejado de Todas as Nações [2021], p. 424.\n\n\"A terra tremeu poderosamente quando a voz do Filho de Deus chamou os santos adormecidos. Eles responderam ao chamado e saíram revestidos de gloriosa imortalidade, clamando: 'Vitória, vitória sobre a morte e a sepultura! Ó morte, onde está o teu aguilhão? Ó sepultura, onde está a tua vitória?' (Ver 1 Coríntios 15:55). Então, os santos vivos e os ressuscitados ergueram suas vozes num longo e arrebatador brado de vitória. Aqueles corpos que haviam descido à sepultura, carregando as marcas da doença e da morte, ressurgiram com saúde e vigor imortais. Os santos vivos são transformados num instante, num abrir e fechar de olhos, e arrebatados com os ressuscitados, e juntos encontram seu Senhor nos ares. Oh, que encontro glorioso! Amigos que a morte havia separado foram reunidos, para nunca mais se separarem.\" — Ellen G. White, História da Redenção [2021], p. 288, 289.\n\nQuestões para discussão:\n\n1. A ressurreição de Cristo é parte integrante da mensagem do evangelho (1 Coríntios 15:1-4). Sem a ressurreição, a proclamação da morte de Cristo perderia o sentido! (1 Coríntios 15:14). A própria morte de Cristo seria irrelevante. Por quê? O que sua resposta revela sobre o poder da ressurreição?\n\n2. Reflita na afirmação de Paulo: \"Se os mortos não ressuscitam, comamos e bebamos, porque amanhã morreremos\" (1 Coríntios 15:32). O que isso significa?\n\n3. Em classe, converse sobre o estado dos mortos. Por que 1 Coríntios 15 não faz sentido se, ao morrer, os salvos fossem levados imediatamente para o Céu?",
      versiculoChave: { texto: "E, se Cristo não ressuscitou, é vã a nossa pregação, e é vã a fé que vocês têm. [...] E, se Cristo não ressuscitou, é vã a fé que vocês têm, e vocês ainda permanecem nos seus pecados", referencia: "1 Coríntios 15:14, 17" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo Ellen White, o que Cristo antecipou ao dizer \"quem crê em mim, ainda que esteja morto, viverá\"?", opcoes: ["O tempo de Sua segunda vinda", "A destruição do mundo", "O fim do evangelho", "A ressurreição apenas dos ímpios"], correta: 0, explicacao: "A resposta correta é: O tempo de Sua segunda vinda." },
        { id: "d7q2", pergunta: "Segundo o relato de Ellen White sobre a ressurreição dos justos, como eles ressurgem?", opcoes: ["Fracos e doentes", "Com saúde e vigor imortais", "Sem reconhecer uns aos outros", "Apenas como espíritos"], correta: 1, explicacao: "A resposta correta é: Com saúde e vigor imortais." },
        { id: "d7q3", pergunta: "Segundo a pergunta de discussão, sem a ressurreição, o que aconteceria com a morte de Cristo?", opcoes: ["Continuaria tendo o mesmo significado", "Se tornaria irrelevante", "Se tornaria ainda mais importante", "Nada mudaria"], correta: 1, explicacao: "A resposta correta é: Se tornaria irrelevante." },
        { id: "d7q4", pergunta: "Segundo o texto, por que 1 Coríntios 15 não faz sentido se os salvos fossem levados imediatamente ao Céu ao morrer?", opcoes: ["Porque não haveria necessidade de ressurreição futura", "Porque o Céu não existe", "Porque contradiria apenas tradições humanas", "O texto não aborda essa questão"], correta: 0, explicacao: "A resposta correta é: Porque não haveria necessidade de ressurreição futura." }
      ]
    }
  ]
};

export const LICAO_ADULT_9 = {
  titulo: "Lição 9 - Ministério movido pelo amor (22 a 28 de agosto)",
  semana: "2026-W34",
  trimestre: "1 e 2 Coríntios",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-08-22",
      titulo: "Ministério movido pelo amor",
      conteudo: "O apóstolo Paulo nem sempre teve uma vida fácil. Além da prisão e das situações de risco de vida que enfrentou, Paulo também escreveu: \"Dos judeus recebi cinco vezes quarenta açoites menos um.\n\nTrês vezes fui açoitado com varas; uma vez fui apedrejado; três vezes sofri naufrágio; passei uma noite e um dia no alto-mar; em viagens muitas vezes, em perigos dos rios, em perigos de salteadores, em perigos dos meus compatriotas, em perigos dos gentios, em perigos na cidade, em perigos no deserto, em perigos no mar, em perigos entre falsos irmãos; em fadigas e trabalhos, em vigílias muitas vezes, em fome e sede, em jejuns muitas vezes, em frio e nudez; além de todas essas coisas, o que me aflige diariamente: a minha profunda preocupação com todas as igrejas\" (2 Coríntios 11:24-28).\n\nO que vemos em suas cartas aos Coríntios é parte da \"profunda preocupação\" que Paulo tinha por esta igreja. Contudo, em meio a tudo isso, seu amor por eles jamais falhou, assim como o amor de Cristo por nós jamais nos falha. De fato, foi de Jesus que Paulo aprendeu a amar as igrejas de uma maneira que reflete o amor que Jesus tem por nós (2 Coríntios 5:14; veja 1 Coríntios 11:1).\n\nEstude a lição desta semana para se preparar para o Sábado, 29 de Agosto.",
      versiculoChave: { texto: "Porque lhes escrevi no meio de muitos sofrimentos e angústia de coração, com muitas lágrimas, não para que vocês ficassem tristes, mas para que soubessem do amor que tenho por vocês", referencia: "2 Coríntios 2:4" },
      perguntas: [
        { id: "d1q1", pergunta: "Segundo 2 Coríntios 11:24-28, citado no texto, quantas vezes Paulo foi açoitado pelos judeus com \"quarenta menos um\"?", opcoes: ["Uma vez", "Cinco vezes", "Dez vezes", "Nunca"], correta: 1, explicacao: "A resposta correta é: Cinco vezes." },
        { id: "d1q2", pergunta: "Segundo o texto, apesar de todas as dificuldades, o que jamais falhou em Paulo?", opcoes: ["Sua saúde", "Seu amor pelas igrejas", "Sua riqueza", "Sua popularidade"], correta: 1, explicacao: "A resposta correta é: Seu amor pelas igrejas." },
        { id: "d1q3", pergunta: "De quem Paulo aprendeu a amar as igrejas dessa maneira, segundo o texto?", opcoes: ["De seus pais", "De Jesus", "De Barnabé", "De filósofos gregos"], correta: 1, explicacao: "A resposta correta é: De Jesus." },
        { id: "d1q4", pergunta: "Qual é a \"profunda preocupação\" diária de Paulo, mencionada em 2 Coríntios 11:28?", opcoes: ["Sua segurança pessoal", "Todas as igrejas", "Seu sustento financeiro", "Sua reputação"], correta: 1, explicacao: "A resposta correta é: Todas as igrejas." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-08-23",
      titulo: "Ação de graças",
      conteudo: "1. Leia 2 Coríntios 1:3-7. Por que Paulo manifesta gratidão nesse trecho?\n\nA gratidão de Paulo se concentra no consolo que Deus oferece àqueles que sofrem. Nesta passagem, o verbo parakaleō (consolar) e o substantivo paraklēsis (consolo) ocorrem juntos dez vezes. Isso representa um terço de todas as ocorrências dessas palavras em 2 Coríntios (29 vezes). Deus é retratado como o \"Pai das misericórdias e Deus de toda consolação, que nos consola em todas as nossas tribulações\" (2 Coríntios 1:3, 4).\n\nO consolo que recebemos de Deus não deve ser guardado para nós mesmos (2 Coríntios 1:4, 5). Somente o coração aflito que se tornou recipiente da consolação de Deus é capaz de transmitir consolo eficazmente àqueles que também sofrem.\n\nPaulo podia consolar os outros porque ele próprio, em seus sofrimentos, recebeu consolo de Deus. \"Se somos atribulados, é para vossa consolação e salvação... Ou, se somos consolados, é para vossa consolação e salvação\" (2 Coríntios 1:6). Isso é amor!\n\n2. Pelo que Paulo dá graças em 2 Coríntios 1:8-11?\n\nPaulo fala de problemas \"incomparáveis, que ultrapassavam todas as nossas forças\", que fizeram com que ele e seus companheiros de trabalho temessem que o fim estivesse próximo (2 Coríntios 1:8). Por um momento, eles pensaram que a ressurreição era sua única esperança. Contudo, Deus os livrou, e o cenário mudou (2 Coríntios 1:10). Do medo da morte (2 Coríntios 1:8), eles ascendem a uma esperança implícita de que Deus os livraria mais uma vez (2 Coríntios 1:10). As vitórias de Deus no passado nos dão a confiança de que Ele fará o mesmo no futuro. Deus usa as aflições para nos ensinar a confiar Nele. As dificuldades podem nos levar à maturidade espiritual, pelo menos na medida em que permitimos que elas nos aproximem de Deus. A ação de graças de Paulo também demonstra o poder da oração intercessora e a gratidão que experimentamos por causa da libertação de Deus (2 Coríntios 1:11).\n\nO que tem ajudado você a lidar com o sofrimento que, de uma forma ou outra, todos enfrentamos?",
      versiculoChave: { texto: "Porque lhes escrevi no meio de muitos sofrimentos e angústia de coração, com muitas lágrimas, não para que vocês ficassem tristes, mas para que soubessem do amor que tenho por vocês", referencia: "2 Coríntios 2:4" },
      perguntas: [
        { id: "d2q1", pergunta: "Segundo o texto, em que se concentra a gratidão de Paulo em 2 Coríntios 1:3-7?", opcoes: ["No sucesso financeiro", "No consolo que Deus oferece aos que sofrem", "Na fama do apóstolo", "Na vitória militar"], correta: 1, explicacao: "A resposta correta é: No consolo que Deus oferece aos que sofrem." },
        { id: "d2q2", pergunta: "Segundo o texto, quem é capaz de transmitir consolo eficazmente a quem sofre?", opcoes: ["Qualquer pessoa, independente da experiência", "Somente o coração aflito que recebeu a consolação de Deus", "Apenas os apóstolos", "Ninguém, o consolo não pode ser transmitido"], correta: 1, explicacao: "A resposta correta é: Somente o coração aflito que recebeu a consolação de Deus." },
        { id: "d2q3", pergunta: "Segundo 2 Coríntios 1:8, que tipo de problemas Paulo enfrentou que o fizeram temer pela vida?", opcoes: ["Problemas financeiros simples", "Problemas incomparáveis, que ultrapassavam suas forças", "Problemas triviais", "Nenhum problema sério"], correta: 1, explicacao: "A resposta correta é: Problemas incomparáveis, que ultrapassavam suas forças." },
        { id: "d2q4", pergunta: "Segundo o texto, o que as vitórias passadas de Deus nos dão?", opcoes: ["Motivo para orgulho", "Confiança de que Ele agirá novamente no futuro", "Nenhuma lição relevante", "Um sentimento de invencibilidade pessoal"], correta: 1, explicacao: "A resposta correta é: Confiança de que Ele agirá novamente no futuro." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-08-24",
      titulo: "Simplicidade e sinceridade",
      conteudo: "Ontem, aprendemos que o amor de Paulo pelos coríntios se manifestou no fato de ele os consolar em suas dificuldades, assim como ele próprio recebeu consolo de Deus nas suas (2 Coríntios 1:1-11). Hoje, veremos que seu amor por eles também se manifestou na integridade que ele e seus companheiros de trabalho demonstraram para com os membros da igreja em Corinto.\n\n3. Leia 2 Coríntios 1:12-14 à luz de 2 Coríntios 2:17; 2 Coríntios 4:2. Como a sinceridade de Paulo revela seu amor pelos coríntios?\n\nSegunda Coríntios 1:12-14 introduz a tese que Paulo desenvolverá no restante da carta. Sua integridade e apostolado foram questionados por alguns em Corinto. Eles achavam que Paulo tinha um caráter vacilante e indeciso, o que não era adequado para o ministério apostólico. Em resposta, Paulo enfatiza que ele e seus colegas se comportaram com a máxima integridade para com eles.\n\nDuas palavras descrevem a conduta de Paulo e seus companheiros: simplicidade e sinceridade (2 Coríntios 1:12). O termo \"simplicidade\" vem da palavra grega haplotēs. Aqui, ele é usado para expressar integridade pessoal na fala ou no comportamento; em resumo, revela a pureza das motivações (Efésios 6:5, Colossenses 3:22). Por sua vez, o termo \"sinceridade\" (do grego eilikrineia) também aponta para integridade e pureza de motivações.\n\nOs coríntios não deveriam ter duvidado da clareza das intenções de Paulo. Ele deixa claro que sua simplicidade e sinceridade têm origem em Deus. Essa ideia é bem capturada pela Bíblia na Nova Tradução Inglesa, que menciona \"motivos puros e sinceridade que vêm de Deus\" (2 Coríntios 1:12, grifo nosso). No mesmo versículo, Paulo afirma ainda que essas qualidades ministeriais nos são dadas \"pela graça de Deus\".\n\nParece que os oponentes de Paulo interpretaram mal suas palavras em comunicações escritas anteriores (2 Coríntios 1:13, 14). Paulo garante que suas intenções eram claras e compreensíveis. Ele tinha certeza de que a retidão de suas palavras, intenções e ações seria esclarecida \"no dia do Senhor Jesus\" (2 Coríntios 1:14).\n\nQue experiências você já teve ao ver suas motivações – por mais bem-intencionadas e sinceras – serem questionadas? O que isso nos ensina sobre o cuidado necessário ao avaliar as intenções de outras pessoas?",
      versiculoChave: { texto: "Porque lhes escrevi no meio de muitos sofrimentos e angústia de coração, com muitas lágrimas, não para que vocês ficassem tristes, mas para que soubessem do amor que tenho por vocês", referencia: "2 Coríntios 2:4" },
      perguntas: [
        { id: "d3q1", pergunta: "Segundo o texto, o que alguns coríntios pensavam sobre o caráter de Paulo?", opcoes: ["Que era exemplar em tudo", "Que era vacilante e indeciso", "Que era rico demais", "Que era ausente demais"], correta: 1, explicacao: "A resposta correta é: Que era vacilante e indeciso." },
        { id: "d3q2", pergunta: "Quais duas palavras descrevem a conduta de Paulo, segundo 2 Coríntios 1:12?", opcoes: ["Força e coragem", "Simplicidade e sinceridade", "Riqueza e poder", "Sabedoria e eloquência"], correta: 1, explicacao: "A resposta correta é: Simplicidade e sinceridade." },
        { id: "d3q3", pergunta: "Segundo o texto, de onde vêm a simplicidade e a sinceridade de Paulo?", opcoes: ["De sua educação", "De Deus, pela Sua graça", "De sua própria força de vontade", "Da cultura grega"], correta: 1, explicacao: "A resposta correta é: De Deus, pela Sua graça." },
        { id: "d3q4", pergunta: "Segundo o texto, quando a retidão das palavras, intenções e ações de Paulo seria esclarecida?", opcoes: ["Nunca", "No dia do Senhor Jesus", "Apenas após sua morte", "Imediatamente após escrever a carta"], correta: 1, explicacao: "A resposta correta é: No dia do Senhor Jesus." }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-08-25",
      titulo: "Mudando os planos por amor",
      conteudo: "Vimos que alguns em Corinto duvidavam das intenções e do amor de Paulo. Hoje, examinaremos um motivo específico: a mudança em seus planos de viagem (2 Coríntios 1:15–2:4).\n\n4. Leia 1 Coríntios 16:5-7. Qual era o plano original de viagem de Paulo?\n\nPaulo já havia estado em Corinto antes. De acordo com 1 Coríntios 16:5, 6, ele planejava passar pela Macedônia em seu caminho de volta para Corinto e, talvez, ficar em Corinto durante o inverno. De Corinto, ele iria para a Judeia com a oferta coletada para os pobres em Jerusalém, não apenas na Macedônia, mas também na Acaia, Galácia e Ásia. No entanto, ele mudou seus planos por causa de um relatório negativo trazido por Timóteo de Corinto (1 Coríntios 4:17, 1 Coríntios 16:10, 2 Coríntios 1:1).\n\nPaulo pretendia ir diretamente de Éfeso para Corinto e lá tratar das questões relatadas por Timóteo. O novo itinerário seria Éfeso—Corinto—Macedônia—Corinto—Judeia (2 Coríntios 1:15, 16). Ele foi de Éfeso para Corinto, mas depois retornou a Éfeso. Seus planos mudaram. Ele não voltou a Corinto como planejado, pelo menos não imediatamente, porque sua última visita não havia corrido bem. Então, ele retornou a Éfeso e escreveu-lhes. Ele preferiu enviar uma carta a arriscar piorar as coisas com outra visita (2 Coríntios 2:1, 3).\n\nAs intenções de Paulo na última visita foram mal interpretadas. Alguns em Corinto disseram que ele não era confiável e que não os amava o suficiente (2 Coríntios 1:17). Em sua resposta às acusações, ele direcionou os olhos dos coríntios para o evangelho de Cristo. Ele foi fiel à sua intenção de visitar os coríntios na melhor oportunidade, assim como Deus havia sido fiel em cumprir Suas promessas a eles por meio de Cristo (2 Coríntios 1:18-22).\n\n\"Pois todas as promessas de Deus são nele sim, e nele amém, para glória de Deus por nosso intermédio\" (2 Coríntios 1:20).\n\nAssim, sua resposta não foi uma mistura confusa de \"sim\" ou \"não\" dependendo das circunstâncias, como disseram, mas foi \"sempre sim\", assim como a obra de Deus em Cristo é \"sempre sim\" (2 Coríntios 1:19).\n\nPortanto, a razão pela qual Paulo escreveu uma carta aos coríntios em vez de visitá-los foi o seu sincero amor por eles, e não o contrário (2 Coríntios 2:4). Outra visita logo após a dolorosa apenas aumentaria ainda mais sofrimento, e não a alegria que ele pretendia causar com a sua presença (2 Coríntios 1:24, 2 Coríntios 2:3). Como suas boas intenções foram facilmente mal interpretadas!",
      versiculoChave: { texto: "Porque lhes escrevi no meio de muitos sofrimentos e angústia de coração, com muitas lágrimas, não para que vocês ficassem tristes, mas para que soubessem do amor que tenho por vocês", referencia: "2 Coríntios 2:4" },
      perguntas: [
        { id: "d4q1", pergunta: "Segundo 1 Coríntios 16:5-7, qual era o plano original de viagem de Paulo?", opcoes: ["Ficar permanentemente em Éfeso", "Passar pela Macedônia a caminho de Corinto", "Ir direto para Roma", "Nunca mais visitar Corinto"], correta: 1, explicacao: "A resposta correta é: Passar pela Macedônia a caminho de Corinto." },
        { id: "d4q2", pergunta: "Por que Paulo mudou seus planos de viagem, segundo o texto?", opcoes: ["Por falta de dinheiro", "Por causa de um relatório negativo trazido por Timóteo", "Por ordem do imperador", "Por uma doença"], correta: 1, explicacao: "A resposta correta é: Por causa de um relatório negativo trazido por Timóteo." },
        { id: "d4q3", pergunta: "Segundo o texto, por que Paulo preferiu enviar uma carta em vez de fazer outra visita?", opcoes: ["Por preguiça", "Para não arriscar piorar as coisas com outra visita difícil", "Porque não sabia escrever bem", "Porque a viagem era cara demais"], correta: 1, explicacao: "A resposta correta é: Para não arriscar piorar as coisas com outra visita difícil." },
        { id: "d4q4", pergunta: "Segundo 2 Coríntios 1:19,20, como é descrita a fidelidade de Deus e de Paulo?", opcoes: ["Inconsistente e variável", "\"Sempre sim\"", "Sempre condicional", "Apenas ocasional"], correta: 1, explicacao: "A resposta correta é: \"Sempre sim\"." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-08-26",
      titulo: "Perdão e reafirmação do amor",
      conteudo: "Em vez de visitar os coríntios uma segunda vez, Paulo, depois de retornar a Éfeso, enviou o que ficou conhecido como \"a carta severa\" (ver 2 Coríntios 2:3, 4; 2 Coríntios 7:8, 12).\n\n5. Leia 2 Coríntios 7:5-13. Que frutos trouxe o que Paulo escreveu, e como o apóstolo reagiu ao saber disso?\n\nPaulo e Tito se encontraram mais tarde na Macedônia, onde Paulo recebeu de Tito a excelente notícia de que suas palavras firmes haviam surtido efeito, o que trouxe muita alegria ao coração do apóstolo. Se antes alguns em Corinto se posicionavam contra Paulo, agora a igreja estava ao seu lado. Como é importante apoiar nossos líderes! Como membros da igreja, podemos facilitar muito o trabalho deles.\n\n6. Leia 2 Coríntios 2:5-11. Qual é a ideia central desse trecho?\n\nEsta passagem trata de um caso de disciplina eclesiástica. Os estudiosos debatem se o ofensor aqui é o homem incestuoso de 1 Coríntios 5:1-5 ou outra pessoa, alguém que influenciou outros membros da igreja a acusá-los de serem inconsistentes e desconsiderados em suas decisões de viagem. O contexto parece favorecer a segunda opção. Em todo caso, o ensinamento mais importante da passagem diz respeito a como a igreja deve lidar com uma pessoa em pecado.\n\nEsta passagem ensina que o propósito da disciplina na igreja é a restauração por meio do perdão e da reafirmação do amor pelo pecador (2 Coríntios 2:6-8, 10). A passagem também sugere que a disciplina na igreja pode ser dolorosa, mas é necessária. Ou seja, por mais bem-intencionadas que sejam e por mais que desejem ser orientadas pela graça, algumas igrejas podem nunca confrontar ou lidar com o pecado flagrante ou mesmo público. Por outro lado, outras podem ser muito rígidas, implacáveis e severas. O pecado precisa ser tratado, mas com amor. Assim, Paulo pôde exortar a igreja a reafirmar seu amor pelo transgressor (2 Coríntios 2:8) porque ele mesmo amava a igreja (2 Coríntios 2:4).\n\nA igreja de Corinto poderia amar o ofensor (2 Coríntios 2:8) porque ela própria havia sido alvo do amor de Deus, expresso no amor de Paulo por ela. O que isso nos ensina sobre o amor?",
      versiculoChave: { texto: "Porque lhes escrevi no meio de muitos sofrimentos e angústia de coração, com muitas lágrimas, não para que vocês ficassem tristes, mas para que soubessem do amor que tenho por vocês", referencia: "2 Coríntios 2:4" },
      perguntas: [
        { id: "d5q1", pergunta: "O que Paulo enviou aos coríntios depois de retornar a Éfeso, em vez de visitá-los novamente?", opcoes: ["Um presente", "A \"carta severa\"", "Um novo apóstolo", "Nenhuma comunicação"], correta: 1, explicacao: "A resposta correta é: A \"carta severa\"." },
        { id: "d5q2", pergunta: "Segundo o texto, que notícia Tito trouxe a Paulo na Macedônia?", opcoes: ["Que a igreja havia se dividido ainda mais", "Que as palavras firmes de Paulo haviam surtido efeito positivo", "Que ninguém leu a carta", "Que a igreja havia sido dissolvida"], correta: 1, explicacao: "A resposta correta é: Que as palavras firmes de Paulo haviam surtido efeito positivo." },
        { id: "d5q3", pergunta: "Segundo 2 Coríntios 2:5-11, qual é o propósito da disciplina na igreja?", opcoes: ["Humilhação pública permanente", "Restauração por meio do perdão e reafirmação do amor", "Expulsão definitiva sem possibilidade de retorno", "Punição severa sem misericórdia"], correta: 1, explicacao: "A resposta correta é: Restauração por meio do perdão e reafirmação do amor." },
        { id: "d5q4", pergunta: "Segundo o texto, por que a igreja de Corinto podia amar o ofensor?", opcoes: ["Porque não sabia da gravidade do pecado", "Porque ela própria havia sido alvo do amor de Deus, expresso no amor de Paulo", "Porque o pecado era irrelevante", "Porque não havia outra opção"], correta: 1, explicacao: "A resposta correta é: Porque ela própria havia sido alvo do amor de Deus, expresso no amor de Paulo." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-08-27",
      titulo: "Triunfo em Cristo",
      conteudo: "7. Leia 2 Coríntios 2:12, 13. Para onde Paulo foi depois de escrever a \"carta severa\" aos coríntios? O que ele fez lá?\n\nO coração de Paulo estava inquieto enquanto esperava por Tito (2 Coríntios 7:5, 6). Apesar dessa inquietação, ele não conseguia parar de falar de Jesus (2 Coríntios 2:12). Ele amava muito Jesus. Naquele momento, ele ainda não sabia o resultado de sua carta. Ele estava ansioso para ver Tito e ouvir a reação dos coríntios.\n\nO trabalho de Paulo em Trôade foi bem-sucedido, mas \"ele não pôde permanecer lá por muito tempo. 'O cuidado com todas as igrejas', e particularmente com a igreja de Corinto, pesava muito em seu coração. Ele esperava encontrar Tito em Trôade e saber dele como as palavras de conselho e repreensão enviadas aos irmãos coríntios haviam sido recebidas, mas ficou desapontado. 'Não tive paz de espírito', escreveu ele a respeito dessa experiência, 'porque não encontrei Tito, meu irmão'. Portanto, ele deixou Trôade e atravessou para a Macedônia, onde, em Filipos, encontrou Timóteo.\" — Ellen G. White, Atos dos Apóstolos [2021], p. 206.\n\n8. Leia 2 Coríntios 2:14-17. Qual foi a reação de Paulo ao encontrar Tito na Macedônia e ouvir sobre a resposta positiva dos coríntios?\n\nEm um acesso de alegria, Paulo afirma que Deus \"sempre nos conduz em triunfo em Cristo\" (2 Coríntios 2:14). Que declaração maravilhosa! Um coração cheio da presença de Cristo espalha \"a fragrância do seu conhecimento por todo lugar\" (2 Coríntios 2:14).\n\nPaulo se alegra em Cristo porque a carta dolorosa produziu o fruto que ele pretendia colher (2 Coríntios 7:5-9). Esta é uma grande vitória. Enquanto isso, em 2 Coríntios 2:17, Paulo reafirma sua sinceridade como apóstolo de Cristo (2 Coríntios 2:17, 2 Coríntios 1:12). De acordo com esta passagem, o que distingue um servo fiel de Cristo de um falso ministro é que, enquanto este último vende o evangelho por interesse próprio, aquele prega a Palavra de Deus com amor sincero por Cristo.\n\nO que motiva você em tudo o que faz, especialmente quando o faz em nome de Jesus?",
      versiculoChave: { texto: "Porque lhes escrevi no meio de muitos sofrimentos e angústia de coração, com muitas lágrimas, não para que vocês ficassem tristes, mas para que soubessem do amor que tenho por vocês", referencia: "2 Coríntios 2:4" },
      perguntas: [
        { id: "d6q1", pergunta: "Para onde Paulo foi depois de escrever a \"carta severa\"?", opcoes: ["Diretamente para Roma", "Para Trôade, e depois para a Macedônia", "De volta para Jerusalém", "Para o Egito"], correta: 1, explicacao: "A resposta correta é: Para Trôade, e depois para a Macedônia." },
        { id: "d6q2", pergunta: "Segundo o texto, por que Paulo não teve \"paz de espírito\" em Trôade?", opcoes: ["Por causa de perseguição local", "Porque não encontrou Tito lá", "Por causa de uma doença", "Por falta de recursos financeiros"], correta: 1, explicacao: "A resposta correta é: Porque não encontrou Tito lá." },
        { id: "d6q3", pergunta: "Segundo 2 Coríntios 2:14, o que Deus sempre faz por Paulo e seus companheiros?", opcoes: ["Os abandona nas dificuldades", "Os conduz em triunfo em Cristo", "Os isola dos problemas", "Os pune por seus erros"], correta: 1, explicacao: "A resposta correta é: Os conduz em triunfo em Cristo." },
        { id: "d6q4", pergunta: "Segundo o texto, o que distingue um servo fiel de Cristo de um falso ministro?", opcoes: ["A quantidade de seguidores", "Que o falso ministro vende o evangelho por interesse próprio, enquanto o fiel prega com amor sincero", "O nível de educação formal", "A riqueza material"], correta: 1, explicacao: "A resposta correta é: Que o falso ministro vende o evangelho por interesse próprio, enquanto o fiel prega com amor sincero." }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-08-28",
      titulo: "Estudo Adicional - Ministério movido pelo amor",
      conteudo: "Leia Ellen G. White, Atos dos Apóstolos [2021], \"A mensagem atendida\" (p. 206-113).\n\n\"Aqueles que suportaram as maiores tristezas são frequentemente os que levam o maior consolo aos outros, espalhando luz por onde passam. Tais pessoas foram disciplinadas e amadurecidas por suas aflições; não perderam a confiança em Deus quando as dificuldades os afligiram, mas se apegaram ainda mais ao Seu amor protetor. Essas pessoas são a prova viva do terno cuidado de Deus.\" — Ellen G. White, Mensagens Escolhidas [2023], v. 2, p. 228.\n\n\"Uma vida cristã consagrada irradia luz, conforto e paz. Caracteriza-se pela pureza, tato, simplicidade e utilidade. É guiada por aquele amor altruísta que santifica a sua influência. É repleta de Cristo e deixa um rastro de luz por onde quer que seu possuidor vá.\" — Ellen G. White, Patriarcas e Profetas [2022], p. 594.\n\n\"O apóstolo Paulo achou necessário repreender o erro na igreja, mas não perdeu o autocontrole ao fazê-lo. Ele explicou com ansiedade a razão de sua ação. Com que cuidado agiu para deixar a impressão de que era amigo dos que erravam! Fez com que entendessem que lhe custava dor causar-lhes dor. Deixou em suas mentes a impressão de que seus interesses se identificavam com os deles.\" — Ellen G. White, Comentário Bíblico Adventista, vol. 6, p. 1219.\n\nQuestões para discussão:\n\n1. Em 2 Coríntios 2:1-14, Paulo reafirma a integridade de seu ministério. Por que essa qualidade é tão essencial?\n\n2. Paulo mudou seus planos de viagem. Que lições esse fato traz sobre a necessidade de flexibilidade no ministério cristão? Por que é importante permanecer aberto a ajustes quando as circunstâncias exigem?\n\n3. Paulo enfrentou angústia e ansiedade no exercício do ministério, mostrando que líderes de igreja são tão humanos quanto qualquer um. O que os membros da igreja podem fazer para aliviar a carga deles?",
      versiculoChave: { texto: "Porque lhes escrevi no meio de muitos sofrimentos e angústia de coração, com muitas lágrimas, não para que vocês ficassem tristes, mas para que soubessem do amor que tenho por vocês", referencia: "2 Coríntios 2:4" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo Ellen White, quem frequentemente leva o maior consolo aos outros?", opcoes: ["Os que nunca sofreram", "Os que suportaram as maiores tristezas", "Apenas os líderes da igreja", "Ninguém pode consolar verdadeiramente"], correta: 1, explicacao: "A resposta correta é: Os que suportaram as maiores tristezas." },
        { id: "d7q2", pergunta: "Segundo o texto de Ellen White, uma vida cristã consagrada é caracterizada por quê?", opcoes: ["Riqueza e status", "Pureza, tato, simplicidade e utilidade", "Isolamento social", "Rigidez legalista"], correta: 1, explicacao: "A resposta correta é: Pureza, tato, simplicidade e utilidade." },
        { id: "d7q3", pergunta: "Segundo o texto, como Paulo agiu ao repreender o erro na igreja?", opcoes: ["Perdendo o autocontrole", "Com cuidado, deixando claro que era amigo dos que erravam", "Com indiferença total", "Delegando a repreensão a outros"], correta: 1, explicacao: "A resposta correta é: Com cuidado, deixando claro que era amigo dos que erravam." },
        { id: "d7q4", pergunta: "Segundo a pergunta de discussão, por que a integridade do ministério de Paulo era tão essencial?", opcoes: ["Porque não tinha relação com sua pregação", "Porque sustentava a credibilidade de sua mensagem e o amor genuíno pelos coríntios", "Porque era exigida por lei romana", "Porque não importava para os coríntios"], correta: 1, explicacao: "A resposta correta é: Porque sustentava a credibilidade de sua mensagem e o amor genuíno pelos coríntios." }
      ]
    }
  ]
};
