import { LICAO_ADULT_1 } from "./dataAdult1";
import { LICAO_ADULT_2, LICAO_ADULT_3 } from "./dataAdult2";
import { LICAO_ADULT_4, LICAO_ADULT_5, LICAO_ADULT_6 } from "./dataAdult3";
import { LICAO_ADULT_7, LICAO_ADULT_8, LICAO_ADULT_9 } from "./dataAdult4";
import { LICAO_ADULT_10, LICAO_ADULT_11, LICAO_ADULT_12, LICAO_ADULT_13 } from "./dataAdult5";

const LICOES_ADULT = [
  LICAO_ADULT_1, LICAO_ADULT_2, LICAO_ADULT_3, LICAO_ADULT_4, LICAO_ADULT_5, LICAO_ADULT_6,
  LICAO_ADULT_7, LICAO_ADULT_8, LICAO_ADULT_9, LICAO_ADULT_10, LICAO_ADULT_11, LICAO_ADULT_12, LICAO_ADULT_13
];

export default LICOES_ADULT;
