import { LICAO_ADULT_1 } from "./dataAdult1";
import { LICAO_ADULT_2, LICAO_ADULT_3 } from "./dataAdult2";
import { LICAO_ADULT_4, LICAO_ADULT_5, LICAO_ADULT_6 } from "./dataAdult3";
import { LICAO_ADULT_7, LICAO_ADULT_8, LICAO_ADULT_9 } from "./dataAdult4";
import { LICAO_ADULT_10, LICAO_ADULT_11, LICAO_ADULT_12, LICAO_ADULT_13 } from "./dataAdult5";
import { LICAO_PROF_1 } from "./dataAdult6";
import { LICAO_PROF_2, LICAO_PROF_3, LICAO_PROF_4 } from "./dataAdult7";
import { LICAO_PROF_5, LICAO_PROF_6, LICAO_PROF_7 } from "./dataAdult8";
import { LICAO_PROF_8, LICAO_PROF_9, LICAO_PROF_10 } from "./dataAdult9";
import { LICAO_PROF_11, LICAO_PROF_12, LICAO_PROF_13 } from "./dataAdult10";

const LICOES_ADULT = [
  LICAO_ADULT_1, LICAO_ADULT_2, LICAO_ADULT_3, LICAO_ADULT_4, LICAO_ADULT_5, LICAO_ADULT_6,
  LICAO_ADULT_7, LICAO_ADULT_8, LICAO_ADULT_9, LICAO_ADULT_10, LICAO_ADULT_11, LICAO_ADULT_12, LICAO_ADULT_13,
  LICAO_PROF_1, LICAO_PROF_2, LICAO_PROF_3, LICAO_PROF_4, LICAO_PROF_5, LICAO_PROF_6, LICAO_PROF_7,
  LICAO_PROF_8, LICAO_PROF_9, LICAO_PROF_10, LICAO_PROF_11, LICAO_PROF_12, LICAO_PROF_13
];

export default LICOES_ADULT;
